#ifndef __TEST_H__
#define __TEST_H__

#define DEVFILE "/dev/vpqutdev"
#define VPQUT_IOC_MAGIC 'P'

#define printk printf

typedef struct _VPQC_FILE_struct {
	unsigned int id;
	unsigned int index;
	unsigned int size;
	unsigned int crc;
	unsigned int array_index;
}VPQC_FILE_struct;

typedef enum {
	VPQUT_IOC_PQ_CMD_INIT = 0,
	VPQUT_IOC_PQ_CMD_REG = 1,
	VPQUT_IOC_PQ_CMD_REG_BIT = 2,
	VPQUT_IOC_PQ_CMD_GET_MEM_INFO = 3,
	VPQUT_IOC_PQ_CMD_SET_DI_MEM = 4,
	VPQUT_IOC_PQ_CMD_GET_DI_MEM = 5,
	VPQUT_IOC_PQ_CMD_GET_VD_MEM_INFO = 6,
	VPQUT_IOC_PQ_CMD_SET_VD_MEM = 7,
	VPQUT_IOC_PQ_CMD_GET_VD_MEM = 8,
	VPQUT_IOC_PQ_CMD_SET_TABLE_SIZE = 9,
	VPQUT_IOC_PQ_CMD_SET_Run_Setup_IMD = 10,

	VPQUT_IOC_PQ_CMD_SET_m_defaultYPbPrGainOffsetData = 50,
	VPQUT_IOC_PQ_CMD_SET_m_defaultVgaGainOffset = 51,
	VPQUT_IOC_PQ_CMD_SET_m_defaultColorDataTable = 52,
	VPQUT_IOC_PQ_CMD_SET_m_defaultColorFacTable = 53,
	VPQUT_IOC_PQ_CMD_SET_m_defaultPictureModeTable = 54,
	VPQUT_IOC_PQ_CMD_SET_m_defaultVipTable = 55,
	VPQUT_IOC_PQ_CMD_SET_m_defaultColorTempTable = 56,
	VPQUT_IOC_PQ_CMD_SET_m_customVipTable = 57,
	VPQUT_IOC_PQ_CMD_SET_m_customVipTable_demo_tv002 = 58,

	VPQUT_IOC_PQ_CMD_SET_S_RPC_AutoMA_Flag = 100,
	VPQUT_IOC_PQ_CMD_SET_tVipNewDcti_auto_adjust = 101,
	VPQUT_IOC_PQ_CMD_SET_gVipDNewDcti_Table = 102,
	VPQUT_IOC_PQ_CMD_SET_gVipINewDcti_Table = 103,
	VPQUT_IOC_PQ_CMD_SET_gVipVcti_Table = 104,
	VPQUT_IOC_PQ_CMD_SET_gVipVcti_lpf_Table = 105,
	VPQUT_IOC_PQ_CMD_SET_gVipUV_Delay_TOP_Table = 106,
	VPQUT_IOC_PQ_CMD_SET_g_Chroma_Compensation_Curve = 107,
	VPQUT_IOC_PQ_CMD_SET_Dnoise_Coef = 108,
	VPQUT_IOC_PQ_CMD_SET_Dnoise_Level = 109,
	VPQUT_IOC_PQ_CMD_SET_SUFIR256_CEC1x00_Hamm = 110,
	VPQUT_IOC_PQ_CMD_SET_SUFIR256_CEP0x75 = 111,
	VPQUT_IOC_PQ_CMD_SET_SUFIR256_PM41x5_32 = 112,
	VPQUT_IOC_PQ_CMD_SET_SUFIR256_PM46_32 = 113,
	VPQUT_IOC_PQ_CMD_SET_SUFIR256_PM56_32 = 114,
	VPQUT_IOC_PQ_CMD_SET_SUFIR256_CLS0x80 = 115,
	VPQUT_IOC_PQ_CMD_SET_SUFIR256_Sinc3z_Hamm = 116,
	VPQUT_IOC_PQ_CMD_SET_SUFIRcls256_96s2_45 = 117,
	VPQUT_IOC_PQ_CMD_SET_SU_table_8tap = 118,
	VPQUT_IOC_PQ_CMD_SET_SUFIR192_Sinc2x6_Hamm = 119,
	VPQUT_IOC_PQ_CMD_SET_SUFIR192_PM52_32 = 120,
	VPQUT_IOC_PQ_CMD_SET_SUFIR192_Sinc2x4_Hamm = 121,
	VPQUT_IOC_PQ_CMD_SET_SUFIR192_PM56_32 = 122,
	VPQUT_IOC_PQ_CMD_SET_SUFIR192_PM52_36 = 123,
	VPQUT_IOC_PQ_CMD_SET_SUFIR192_Sinc2x2_Hamm = 124,
	VPQUT_IOC_PQ_CMD_SET_SUFIR192_Hann0x70 = 125,
	VPQUT_IOC_PQ_CMD_SET_SUFIRcls192_84s2_55 = 126,
	VPQUT_IOC_PQ_CMD_SET_SU_table_6tap = 127,
	VPQUT_IOC_PQ_CMD_SET_gVipDirsu_Table = 128,
	VPQUT_IOC_PQ_CMD_SET_gSMDtable = 129,
	VPQUT_IOC_PQ_CMD_SET_gHMETable = 130,
	VPQUT_IOC_PQ_CMD_SET_gHMCTable = 131,
	VPQUT_IOC_PQ_CMD_SET_gPanTable = 132,
	VPQUT_IOC_PQ_CMD_SET_gFilmInitTable = 133,
	VPQUT_IOC_PQ_CMD_SET_gVipIntra_Set_Ver2_tab = 134,
	VPQUT_IOC_PQ_CMD_SET_gUVCTable = 135,
	VPQUT_IOC_PQ_CMD_SET_gBSTable = 136,
	VPQUT_IOC_PQ_CMD_SET_gVipSupk_Mask = 137,
	VPQUT_IOC_PQ_CMD_SET_gVipSkipir_Ring = 138,
	VPQUT_IOC_PQ_CMD_SET_gVipSkipir_Islet = 139,
	VPQUT_IOC_PQ_CMD_SET_gVipEmfMk2 = 140,
	VPQUT_IOC_PQ_CMD_SET_gVip2Dpk_Seg = 141,
	VPQUT_IOC_PQ_CMD_SET_gVip2Dpk_Tex_Detect = 142,
	VPQUT_IOC_PQ_CMD_SET_gVipOSD_sharp = 143,
	VPQUT_IOC_PQ_CMD_SET_D_DLTI_Table = 144,
	VPQUT_IOC_PQ_CMD_SET_gVipUn_Shp_Mask = 145,
	VPQUT_IOC_PQ_CMD_SET_gCMTable = 146,
	VPQUT_IOC_PQ_CMD_SET_Curve_boundary_table = 147,
	VPQUT_IOC_PQ_CMD_SET_Advance_control_table = 148,
	VPQUT_IOC_PQ_CMD_SET_sRGB_Hue_Mapping = 149,
	VPQUT_IOC_PQ_CMD_SET_sRGB_RGB_LUT = 150,
	VPQUT_IOC_PQ_CMD_SET_sRGB_YUV2RGB = 151,
	VPQUT_IOC_PQ_CMD_SET_sRGB_RGB2YUV = 152,
	VPQUT_IOC_PQ_CMD_SET_sRGB_APPLY = 153,
	VPQUT_IOC_PQ_CMD_SET_YUV2RGB_Matrix_COEF_601_YCbCr = 154,
	VPQUT_IOC_PQ_CMD_SET_tYUV2RGB_COEF_TVBOX_SD = 155,
	VPQUT_IOC_PQ_CMD_SET_tYUV2RGB_COEF_TVBOX_HD = 156,
	VPQUT_IOC_PQ_CMD_SET_tYUV2RGB_COEF_601_YCbCr_NOClampY = 157,
	VPQUT_IOC_PQ_CMD_SET_tYUV2RGB_COEF = 158,
	VPQUT_IOC_PQ_CMD_SET_ConBriMapping_Offset_Table = 159,
	VPQUT_IOC_PQ_CMD_SET_AVBlackLevelMapping_Table = 160,
	VPQUT_IOC_PQ_CMD_SET_ATVBlackLevelMapping_Table = 161,
	VPQUT_IOC_PQ_CMD_SET_tRGB2YUV_COEF_709_YUV_0_255 = 162,
	VPQUT_IOC_PQ_CMD_SET_tRGB2YUV_COEF_709_YUV_16_235 = 163,
	VPQUT_IOC_PQ_CMD_SET_tRGB2YUV_COEF_709_RGB_0_255 = 164,
	VPQUT_IOC_PQ_CMD_SET_tRGB2YUV_COEF_709_RGB_16_235 = 165,
	VPQUT_IOC_PQ_CMD_SET_tRGB2YUV_COEF_601_RGB_0_255 = 166,
	VPQUT_IOC_PQ_CMD_SET_tRGB2YUV_COEF_601_RGB_16_235 = 167,
	VPQUT_IOC_PQ_CMD_SET_tRGB2YUV_COEF_601_YCbCr_0_255 = 168,
	VPQUT_IOC_PQ_CMD_SET_tRGB2YUV_COEF_601_YCbCr_16_235 = 169,
	VPQUT_IOC_PQ_CMD_SET_tRGB2YUV_COEF_601_YCbCr_16_255 = 170,
	VPQUT_IOC_PQ_CMD_SET_tRGB2YUV_COEF_TVBOX_SD = 171,
	VPQUT_IOC_PQ_CMD_SET_tRGB2YUV_COEF_TVBOX_720 = 172,
	VPQUT_IOC_PQ_CMD_SET_tRGB2YUV_COEF_TVBOX_1080 = 173,
	VPQUT_IOC_PQ_CMD_SET_tRGB2YUV_COEF = 174,
	VPQUT_IOC_PQ_CMD_SET_Local_Dimming_Table = 175,
	VPQUT_IOC_PQ_CMD_SET_LD_Backlight_Profile_Interpolation_table = 176,
	VPQUT_IOC_PQ_CMD_SET_LD_Data_Compensation_NewMode_2DTable = 177,
	VPQUT_IOC_PQ_CMD_SET_Local_Contrast_Table = 178,
	VPQUT_IOC_PQ_CMD_SET_LC_Backlight_Profile_Interpolation_table = 179,
	VPQUT_IOC_PQ_CMD_SET_LC_ToneMappingSlopePoint_Table = 180,
	VPQUT_IOC_PQ_CMD_SET_DI_MA_Init_Table = 181,
	VPQUT_IOC_PQ_CMD_SET_DI_MA_Adjust_Table = 182,
	VPQUT_IOC_PQ_CMD_SET_di_TNR_XC_table = 183,
	VPQUT_IOC_PQ_CMD_SET_Scaler_DI_Coef_table = 184,
	VPQUT_IOC_PQ_CMD_SET_Adaptive_Gamma_Ctrl_Table = 185,
	VPQUT_IOC_PQ_CMD_SET_OD_table = 186,
	VPQUT_IOC_PQ_CMD_SET_OD_setting_table = 187,
	VPQUT_IOC_PQ_CMD_SET_FIR_Coef_Ctrl = 188,
	VPQUT_IOC_PQ_CMD_SET_TwoStepSU_Table = 189,
	VPQUT_IOC_PQ_CMD_SET_ScaleDown_COEF_TAB = 190,
	VPQUT_IOC_PQ_CMD_SET_PCID_table = 191,
	VPQUT_IOC_PQ_CMD_SET_PCID2_Table = 192,
	VPQUT_IOC_PQ_CMD_SET_PCID2_Pol_Table_R = 193,
	VPQUT_IOC_PQ_CMD_SET_PCID2_Pol_Table_G = 194,
	VPQUT_IOC_PQ_CMD_SET_PCID2_Pol_Table_B = 195,
	VPQUT_IOC_PQ_CMD_SET_pq_misc_MA_SNR_IESM_TBL = 196,
	VPQUT_IOC_PQ_CMD_SET_t_inv_GAMMA = 197,
	VPQUT_IOC_PQ_CMD_SET_t_gamma_curve_22 = 198,
	VPQUT_IOC_PQ_CMD_SET_Power1div22Gamma = 199,
	VPQUT_IOC_PQ_CMD_SET_Power22InvGamma = 200,
	VPQUT_IOC_PQ_CMD_SET_LinearInvGamma = 201,
	VPQUT_IOC_PQ_CMD_SET_LEDOutGamma = 202,
	VPQUT_IOC_PQ_CMD_SET_gVip_Profile_Table = 203,
	VPQUT_IOC_PQ_CMD_SET_PQ_ByPass_Struct = 204,
	VPQUT_IOC_PQ_CMD_SET_PQ_check_source_table = 205,
	VPQUT_IOC_PQ_CMD_SET_PQ_check_register_table = 206,
	VPQUT_IOC_PQ_CMD_SET_PQ_check_register_diff_table = 207,
	VPQUT_IOC_PQ_CMD_SET_I_De_XC_TBL = 208,
	VPQUT_IOC_PQ_CMD_SET_I_De_Contour_TBL = 209,
	VPQUT_IOC_PQ_CMD_SET_BOE_RGBW_TAB_160624 = 210,
	VPQUT_IOC_PQ_CMD_SET_BOE_RGBW_TAB_160713 = 211,
	VPQUT_IOC_PQ_CMD_SET_Output_InvOutput_Gamma = 212,
	VPQUT_IOC_PQ_CMD_SET_hdr_table = 213,
	VPQUT_IOC_PQ_CMD_SET_hdr_YUV2RGB = 214,
	VPQUT_IOC_PQ_CMD_SET_hdr_RGB2OPT = 215,
	VPQUT_IOC_PQ_CMD_SET_HDR10_3DLUT_17x17x17 = 216,
	VPQUT_IOC_PQ_CMD_SET_EOTF_LUT_HLG_DEFAULT = 217,
	VPQUT_IOC_PQ_CMD_SET_OETF_LUT_HLG_DEFAULT = 218,
	VPQUT_IOC_PQ_CMD_SET_EOTF_LUT_R = 219,
	VPQUT_IOC_PQ_CMD_SET_OETF_LUT_R = 220,
	VPQUT_IOC_PQ_CMD_SET_Tone_Mapping_LUT_R = 221,
	VPQUT_IOC_PQ_CMD_SET_HDR10_3DLUT_24x24x24 = 222,
	VPQUT_IOC_PQ_CMD_SET_HLG_3DLUT_24x24x24 = 223,
	VPQUT_IOC_PQ_CMD_SET_HLG_OETF_LUT_R = 224,
	VPQUT_IOC_PQ_CMD_SET_HLG_EOTF_LUT_R = 225,
	VPQUT_IOC_PQ_CMD_SET_TCHDR_Table = 226,
	VPQUT_IOC_PQ_CMD_SET_TCHDR_COEF_C_LUT_TBL = 227,
	VPQUT_IOC_PQ_CMD_SET_TCHDR_COEF_I_LUT_TBL = 228,
	VPQUT_IOC_PQ_CMD_SET_TCHDR_COEF_S_LUT_TBL = 229,
	VPQUT_IOC_PQ_CMD_SET_TCHDR_COEF_P_LUT_TBL = 230,
	VPQUT_IOC_PQ_CMD_SET_TCHDR_COEF_D_LUT_TBL = 231,
}VPQUT_IOC_pq_cmd;

typedef struct _VPQC_REG_struct {
	char type;
	unsigned int reg;
	unsigned int bit[2];
	unsigned int value;
}VPQC_REG_struct;

// Structure of memory tag
typedef enum {
	UNDEFINED = 0,
	ALLOCATED_FROM_LOW = 1,
	ALLOCATED_FROM_HIGH = 2,
	ALLOCATED_FROM_PLI = 3,
} MemBlockStatus;

typedef struct _MemoryBlock
{
	unsigned int Allocate_StartAddr;
	unsigned int Allocate_VirAddr;
	MemBlockStatus Status;		// 0: undefined, 1: allocated from low, 2: allocated from high
	unsigned int StartAddr;
	unsigned int Size;
}StructMemBlock;

unsigned int crc32(const void *buf, unsigned int size);

#endif
