/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SECURERPCBASEDS_H_RPCGEN
#define _SECURERPCBASEDS_H_RPCGEN

#include <rt/misc/RPCstruct.h>

#include "SecureRPCBaseDS_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#define printf(str)

#include <rpc_common.h>

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_RPC_RtkDrmCode (XDR *, RPC_RtkDrmCode*);

#else /* K&R C */
extern bool_t xdr_RPC_RtkDrmCode ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SECURERPCBASEDS_H_RPCGEN */
