#
# Makefile for the Realtek HDMI drivers.
#
obj-y := hdmi_reg.o hdmiFun.o hdmiHdmi.o hdmiPhy.o hdmiMS.o hdmiPlatform.o hdcp2p2.o hdmi_ddc.o 
obj-y += mhl_driver.o mhl_detect.o MHL_cbus.o
obj-y += hdmi_vfe.o hdmi_vfe_config.o 
obj-y += hdmi-sysfs.o
obj-y += hdmi_arc.o
obj-y += hdmi_edid.o cea_861.o
