#Copyright (C) 2007-2017 Realtek Semiconductor Corporation.
#
# Makefile for the linux kernel.
#

# DDC driver

KBUILD_CFLAGS += -Werror 

obj-$(CONFIG_RTK_KDRV_DDC)+= rtk_ddc_drv.o rtk_ddc_dev.o rtk_ddc_sysfs.o rtk_ddc_lib.o 


