#ifndef _RTK_MD_REG_H_
#define _RTK_MD_REG_H_

#include <rbus/md_reg.h>

//  MD Register Address
#define  MD_SMQ_CNTL                                            MD_MD_SMQ_CNTL
#define  MD_SMQ_CNTL_reg_addr                                   MD_MD_SMQ_CNTL_reg_addr
#define  MD_SMQ_CNTL_reg                                        MD_MD_SMQ_CNTL_reg
#define  MD_SMQ_CNTL_inst_addr                                  MD_MD_SMQ_CNTL_inst_addr
#define  set_MD_SMQ_CNTL_reg(data)                              set_MD_MD_SMQ_CNTL_reg(data)
#define  get_MD_SMQ_CNTL_reg                                    get_MD_MD_SMQ_CNTL_reg
#define  MD_SMQ_CNTL_smq_idle_shift                             MD_MD_SMQ_CNTL_smq_idle_shift
#define  MD_SMQ_CNTL_smq_cmd_swap_shift                         MD_MD_SMQ_CNTL_smq_cmd_swap_shift
#define  MD_SMQ_CNTL_smq_go_shift                               MD_MD_SMQ_CNTL_smq_go_shift
#define  MD_SMQ_CNTL_write_data_shift                           MD_MD_SMQ_CNTL_write_data_shift
#define  MD_SMQ_CNTL_smq_idle_mask                              MD_MD_SMQ_CNTL_smq_idle_mask
#define  MD_SMQ_CNTL_smq_cmd_swap_mask                          MD_MD_SMQ_CNTL_smq_cmd_swap_mask
#define  MD_SMQ_CNTL_smq_go_mask                                MD_MD_SMQ_CNTL_smq_go_mask
#define  MD_SMQ_CNTL_write_data_mask                            MD_MD_SMQ_CNTL_write_data_mask
#define  MD_SMQ_CNTL_smq_idle(data)                             MD_MD_SMQ_CNTL_smq_idle(data)
#define  MD_SMQ_CNTL_smq_cmd_swap(data)                         MD_MD_SMQ_CNTL_smq_cmd_swap(data)
#define  MD_SMQ_CNTL_smq_go(data)                               MD_MD_SMQ_CNTL_smq_go(data)
#define  MD_SMQ_CNTL_write_data(data)                           MD_MD_SMQ_CNTL_write_data(data)
#define  MD_SMQ_CNTL_get_smq_idle(data)                         MD_MD_SMQ_CNTL_get_smq_idle(data)
#define  MD_SMQ_CNTL_get_smq_cmd_swap(data)                     MD_MD_SMQ_CNTL_get_smq_cmd_swap(data)
#define  MD_SMQ_CNTL_get_smq_go(data)                           MD_MD_SMQ_CNTL_get_smq_go(data)
#define  MD_SMQ_CNTL_get_write_data(data)                       MD_MD_SMQ_CNTL_get_write_data(data)

#define  MD_SMQ_INT_STATUS                                      MD_MD_SMQ_INT_STATUS
#define  MD_SMQ_INT_STATUS_reg_addr                             MD_MD_SMQ_INT_STATUS_reg_addr
#define  MD_SMQ_INT_STATUS_reg                                  MD_MD_SMQ_INT_STATUS_reg
#define  MD_SMQ_INT_STATUS_inst_addr                            MD_MD_SMQ_INT_STATUS_inst_addr
#define  set_MD_SMQ_INT_STATUS_reg(data)                        set_MD_MD_SMQ_INT_STATUS_reg(data)
#define  get_MD_SMQ_INT_STATUS_reg                              get_MD_MD_SMQ_INT_STATUS_reg
#define  MD_SMQ_INT_STATUS_fdma_go_busy_shift                   MD_MD_SMQ_INT_STATUS_fdma_go_busy_shift
#define  MD_SMQ_INT_STATUS_ur_length_err_shift                  MD_MD_SMQ_INT_STATUS_ur_length_err_shift
#define  MD_SMQ_INT_STATUS_ur_rx_timeout_shift                  MD_MD_SMQ_INT_STATUS_ur_rx_timeout_shift
#define  MD_SMQ_INT_STATUS_ur_rx_thd_shift                      MD_MD_SMQ_INT_STATUS_ur_rx_thd_shift
#define  MD_SMQ_INT_STATUS_ur_tx_thd_shift                      MD_MD_SMQ_INT_STATUS_ur_tx_thd_shift
#define  MD_SMQ_INT_STATUS_smq_mode_2b4berr_shift               MD_MD_SMQ_INT_STATUS_smq_mode_2b4berr_shift
#define  MD_SMQ_INT_STATUS_fdma_done_shift                      MD_MD_SMQ_INT_STATUS_fdma_done_shift
#define  MD_SMQ_INT_STATUS_smq_empty_shift                      MD_MD_SMQ_INT_STATUS_smq_empty_shift
#define  MD_SMQ_INT_STATUS_smq_length_err_shift                 MD_MD_SMQ_INT_STATUS_smq_length_err_shift
#define  MD_SMQ_INT_STATUS_smq_inst_err_shift                   MD_MD_SMQ_INT_STATUS_smq_inst_err_shift
#define  MD_SMQ_INT_STATUS_write_data_shift                     MD_MD_SMQ_INT_STATUS_write_data_shift
#define  MD_SMQ_INT_STATUS_fdma_go_busy_mask                    MD_MD_SMQ_INT_STATUS_fdma_go_busy_mask
#define  MD_SMQ_INT_STATUS_ur_length_err_mask                   MD_MD_SMQ_INT_STATUS_ur_length_err_mask
#define  MD_SMQ_INT_STATUS_ur_rx_timeout_mask                   MD_MD_SMQ_INT_STATUS_ur_rx_timeout_mask
#define  MD_SMQ_INT_STATUS_ur_rx_thd_mask                       MD_MD_SMQ_INT_STATUS_ur_rx_thd_mask
#define  MD_SMQ_INT_STATUS_ur_tx_thd_mask                       MD_MD_SMQ_INT_STATUS_ur_tx_thd_mask
#define  MD_SMQ_INT_STATUS_smq_mode_2b4berr_mask                MD_MD_SMQ_INT_STATUS_smq_mode_2b4berr_mask
#define  MD_SMQ_INT_STATUS_fdma_done_mask                       MD_MD_SMQ_INT_STATUS_fdma_done_mask
#define  MD_SMQ_INT_STATUS_smq_empty_mask                       MD_MD_SMQ_INT_STATUS_smq_empty_mask
#define  MD_SMQ_INT_STATUS_smq_length_err_mask                  MD_MD_SMQ_INT_STATUS_smq_length_err_mask
#define  MD_SMQ_INT_STATUS_smq_inst_err_mask                    MD_MD_SMQ_INT_STATUS_smq_inst_err_mask
#define  MD_SMQ_INT_STATUS_write_data_mask                      MD_MD_SMQ_INT_STATUS_write_data_mask
#define  MD_SMQ_INT_STATUS_fdma_go_busy(data)                   MD_MD_SMQ_INT_STATUS_fdma_go_busy(data)
#define  MD_SMQ_INT_STATUS_ur_length_err(data)                  MD_MD_SMQ_INT_STATUS_ur_length_err(data)
#define  MD_SMQ_INT_STATUS_ur_rx_timeout(data)                  MD_MD_SMQ_INT_STATUS_ur_rx_timeout(data)
#define  MD_SMQ_INT_STATUS_ur_rx_thd(data)                      MD_MD_SMQ_INT_STATUS_ur_rx_thd(data)
#define  MD_SMQ_INT_STATUS_ur_tx_thd(data)                      MD_MD_SMQ_INT_STATUS_ur_tx_thd(data)
#define  MD_SMQ_INT_STATUS_smq_mode_2b4berr(data)               MD_MD_SMQ_INT_STATUS_smq_mode_2b4berr(data)
#define  MD_SMQ_INT_STATUS_fdma_done(data)                      MD_MD_SMQ_INT_STATUS_fdma_done(data)
#define  MD_SMQ_INT_STATUS_smq_empty(data)                      MD_MD_SMQ_INT_STATUS_smq_empty(data)
#define  MD_SMQ_INT_STATUS_smq_length_err(data)                 MD_MD_SMQ_INT_STATUS_smq_length_err(data)
#define  MD_SMQ_INT_STATUS_smq_inst_err(data)                   MD_MD_SMQ_INT_STATUS_smq_inst_err(data)
#define  MD_SMQ_INT_STATUS_write_data(data)                     MD_MD_SMQ_INT_STATUS_write_data(data)
#define  MD_SMQ_INT_STATUS_get_fdma_go_busy(data)               MD_MD_SMQ_INT_STATUS_get_fdma_go_busy(data)
#define  MD_SMQ_INT_STATUS_get_ur_length_err(data)              MD_MD_SMQ_INT_STATUS_get_ur_length_err(data)
#define  MD_SMQ_INT_STATUS_get_ur_rx_timeout(data)              MD_MD_SMQ_INT_STATUS_get_ur_rx_timeout(data)
#define  MD_SMQ_INT_STATUS_get_ur_rx_thd(data)                  MD_MD_SMQ_INT_STATUS_get_ur_rx_thd(data)
#define  MD_SMQ_INT_STATUS_get_ur_tx_thd(data)                  MD_MD_SMQ_INT_STATUS_get_ur_tx_thd(data)
#define  MD_SMQ_INT_STATUS_get_smq_mode_2b4berr(data)           MD_MD_SMQ_INT_STATUS_get_smq_mode_2b4berr(data)
#define  MD_SMQ_INT_STATUS_get_fdma_done(data)                  MD_MD_SMQ_INT_STATUS_get_fdma_done(data)
#define  MD_SMQ_INT_STATUS_get_smq_empty(data)                  MD_MD_SMQ_INT_STATUS_get_smq_empty(data)
#define  MD_SMQ_INT_STATUS_get_smq_length_err(data)             MD_MD_SMQ_INT_STATUS_get_smq_length_err(data)
#define  MD_SMQ_INT_STATUS_get_smq_inst_err(data)               MD_MD_SMQ_INT_STATUS_get_smq_inst_err(data)
#define  MD_SMQ_INT_STATUS_get_write_data(data)                 MD_MD_SMQ_INT_STATUS_get_write_data(data)

#define  MD_SMQ_INT_ENABLE                                      MD_MD_SMQ_INT_ENABLE
#define  MD_SMQ_INT_ENABLE_reg_addr                             MD_MD_SMQ_INT_ENABLE_reg_addr
#define  MD_SMQ_INT_ENABLE_reg                                  MD_MD_SMQ_INT_ENABLE_reg
#define  MD_SMQ_INT_ENABLE_inst_addr                            MD_MD_SMQ_INT_ENABLE_inst_addr
#define  set_MD_SMQ_INT_ENABLE_reg(data)                        set_MD_MD_SMQ_INT_ENABLE_reg(data)
#define  get_MD_SMQ_INT_ENABLE_reg                              get_MD_MD_SMQ_INT_ENABLE_reg
#define  MD_SMQ_INT_ENABLE_scpu_int_en_shift                    MD_MD_SMQ_INT_ENABLE_scpu_int_en_shift
#define  MD_SMQ_INT_ENABLE_ur_length_err_en_shift               MD_MD_SMQ_INT_ENABLE_ur_length_err_en_shift
#define  MD_SMQ_INT_ENABLE_ur_rx_timeout_en_shift               MD_MD_SMQ_INT_ENABLE_ur_rx_timeout_en_shift
#define  MD_SMQ_INT_ENABLE_ur_rx_thd_en_shift                   MD_MD_SMQ_INT_ENABLE_ur_rx_thd_en_shift
#define  MD_SMQ_INT_ENABLE_ur_tx_thd_en_shift                   MD_MD_SMQ_INT_ENABLE_ur_tx_thd_en_shift
#define  MD_SMQ_INT_ENABLE_smq_mode_2b4b_err_en_shift           MD_MD_SMQ_INT_ENABLE_smq_mode_2b4b_err_en_shift
#define  MD_SMQ_INT_ENABLE_fdma_done_en_shift                   MD_MD_SMQ_INT_ENABLE_fdma_done_en_shift
#define  MD_SMQ_INT_ENABLE_smq_empty_en_shift                   MD_MD_SMQ_INT_ENABLE_smq_empty_en_shift
#define  MD_SMQ_INT_ENABLE_smq_length_err_en_shift              MD_MD_SMQ_INT_ENABLE_smq_length_err_en_shift
#define  MD_SMQ_INT_ENABLE_smq_inst_err_en_shift                MD_MD_SMQ_INT_ENABLE_smq_inst_err_en_shift
#define  MD_SMQ_INT_ENABLE_write_data_shift                     MD_MD_SMQ_INT_ENABLE_write_data_shift
#define  MD_SMQ_INT_ENABLE_scpu_int_en_mask                     MD_MD_SMQ_INT_ENABLE_scpu_int_en_mask
#define  MD_SMQ_INT_ENABLE_ur_length_err_en_mask                MD_MD_SMQ_INT_ENABLE_ur_length_err_en_mask
#define  MD_SMQ_INT_ENABLE_ur_rx_timeout_en_mask                MD_MD_SMQ_INT_ENABLE_ur_rx_timeout_en_mask
#define  MD_SMQ_INT_ENABLE_ur_rx_thd_en_mask                    MD_MD_SMQ_INT_ENABLE_ur_rx_thd_en_mask
#define  MD_SMQ_INT_ENABLE_ur_tx_thd_en_mask                    MD_MD_SMQ_INT_ENABLE_ur_tx_thd_en_mask
#define  MD_SMQ_INT_ENABLE_smq_mode_2b4b_err_en_mask            MD_MD_SMQ_INT_ENABLE_smq_mode_2b4b_err_en_mask
#define  MD_SMQ_INT_ENABLE_fdma_done_en_mask                    MD_MD_SMQ_INT_ENABLE_fdma_done_en_mask
#define  MD_SMQ_INT_ENABLE_smq_empty_en_mask                    MD_MD_SMQ_INT_ENABLE_smq_empty_en_mask
#define  MD_SMQ_INT_ENABLE_smq_length_err_en_mask               MD_MD_SMQ_INT_ENABLE_smq_length_err_en_mask
#define  MD_SMQ_INT_ENABLE_smq_inst_err_en_mask                 MD_MD_SMQ_INT_ENABLE_smq_inst_err_en_mask
#define  MD_SMQ_INT_ENABLE_write_data_mask                      MD_MD_SMQ_INT_ENABLE_write_data_mask
#define  MD_SMQ_INT_ENABLE_scpu_int_en(data)                    MD_MD_SMQ_INT_ENABLE_scpu_int_en(data)
#define  MD_SMQ_INT_ENABLE_ur_length_err_en(data)               MD_MD_SMQ_INT_ENABLE_ur_length_err_en(data)
#define  MD_SMQ_INT_ENABLE_ur_rx_timeout_en(data)               MD_MD_SMQ_INT_ENABLE_ur_rx_timeout_en(data)
#define  MD_SMQ_INT_ENABLE_ur_rx_thd_en(data)                   MD_MD_SMQ_INT_ENABLE_ur_rx_thd_en(data)
#define  MD_SMQ_INT_ENABLE_ur_tx_thd_en(data)                   MD_MD_SMQ_INT_ENABLE_ur_tx_thd_en(data)
#define  MD_SMQ_INT_ENABLE_smq_mode_2b4b_err_en(data)           MD_MD_SMQ_INT_ENABLE_smq_mode_2b4b_err_en(data)
#define  MD_SMQ_INT_ENABLE_fdma_done_en(data)                   MD_MD_SMQ_INT_ENABLE_fdma_done_en(data)
#define  MD_SMQ_INT_ENABLE_smq_empty_en(data)                   MD_MD_SMQ_INT_ENABLE_smq_empty_en(data)
#define  MD_SMQ_INT_ENABLE_smq_length_err_en(data)              MD_MD_SMQ_INT_ENABLE_smq_length_err_en(data)
#define  MD_SMQ_INT_ENABLE_smq_inst_err_en(data)                MD_MD_SMQ_INT_ENABLE_smq_inst_err_en(data)
#define  MD_SMQ_INT_ENABLE_write_data(data)                     MD_MD_SMQ_INT_ENABLE_write_data(data)
#define  MD_SMQ_INT_ENABLE_get_scpu_int_en(data)                MD_MD_SMQ_INT_ENABLE_get_scpu_int_en(data)
#define  MD_SMQ_INT_ENABLE_get_ur_length_err_en(data)           MD_MD_SMQ_INT_ENABLE_get_ur_length_err_en(data)
#define  MD_SMQ_INT_ENABLE_get_ur_rx_timeout_en(data)           MD_MD_SMQ_INT_ENABLE_get_ur_rx_timeout_en(data)
#define  MD_SMQ_INT_ENABLE_get_ur_rx_thd_en(data)               MD_MD_SMQ_INT_ENABLE_get_ur_rx_thd_en(data)
#define  MD_SMQ_INT_ENABLE_get_ur_tx_thd_en(data)               MD_MD_SMQ_INT_ENABLE_get_ur_tx_thd_en(data)
#define  MD_SMQ_INT_ENABLE_get_smq_mode_2b4b_err_en(data)       MD_MD_SMQ_INT_ENABLE_get_smq_mode_2b4b_err_en(data)
#define  MD_SMQ_INT_ENABLE_get_fdma_done_en(data)               MD_MD_SMQ_INT_ENABLE_get_fdma_done_en(data)
#define  MD_SMQ_INT_ENABLE_get_smq_empty_en(data)               MD_MD_SMQ_INT_ENABLE_get_smq_empty_en(data)
#define  MD_SMQ_INT_ENABLE_get_smq_length_err_en(data)          MD_MD_SMQ_INT_ENABLE_get_smq_length_err_en(data)
#define  MD_SMQ_INT_ENABLE_get_smq_inst_err_en(data)            MD_MD_SMQ_INT_ENABLE_get_smq_inst_err_en(data)
#define  MD_SMQ_INT_ENABLE_get_write_data(data)                 MD_MD_SMQ_INT_ENABLE_get_write_data(data)

#define  MD_SMQBASE                                             MD_MD_SMQBase
#define  MD_SMQBASE_reg_addr                                    MD_MD_SMQBase_reg_addr
#define  MD_SMQBASE_reg                                         MD_MD_SMQBase_reg
#define  MD_SMQBASE_inst_addr                                   MD_MD_SMQBase_inst_addr
#define  set_MD_SMQBASE_reg(data)                               set_MD_MD_SMQBase_reg(data)
#define  get_MD_SMQBASE_reg                                     get_MD_MD_SMQBase_reg
#define  MD_SMQBASE_smq_base_shift                              MD_MD_SMQBase_smq_base_shift
#define  MD_SMQBASE_smq_base_mask                               MD_MD_SMQBase_smq_base_mask
#define  MD_SMQBASE_smq_base(data)                              MD_MD_SMQBase_smq_base(data)
#define  MD_SMQBASE_get_smq_base(data)                          MD_MD_SMQBase_get_smq_base(data)

#define  MD_SMQLIMIT                                            MD_MD_SMQLimit
#define  MD_SMQLIMIT_reg_addr                                   MD_MD_SMQLimit_reg_addr
#define  MD_SMQLIMIT_reg                                        MD_MD_SMQLimit_reg
#define  MD_SMQLIMIT_inst_addr                                  MD_MD_SMQLimit_inst_addr
#define  set_MD_SMQLIMIT_reg(data)                              set_MD_MD_SMQLimit_reg(data)
#define  get_MD_SMQLIMIT_reg                                    get_MD_MD_SMQLimit_reg
#define  MD_SMQLIMIT_smq_limit_shift                            MD_MD_SMQLimit_smq_limit_shift
#define  MD_SMQLIMIT_smq_limit_mask                             MD_MD_SMQLimit_smq_limit_mask
#define  MD_SMQLIMIT_smq_limit(data)                            MD_MD_SMQLimit_smq_limit(data)
#define  MD_SMQLIMIT_get_smq_limit(data)                        MD_MD_SMQLimit_get_smq_limit(data)

#define  MD_SMQRDPTR                                            MD_MD_SMQRdptr
#define  MD_SMQRDPTR_reg_addr                                   MD_MD_SMQRdptr_reg_addr
#define  MD_SMQRDPTR_reg                                        MD_MD_SMQRdptr_reg
#define  MD_SMQRDPTRr_inst_addr                                  MD_MD_SMQRdptr_inst_addr
#define  set_MD_SMQRDPTR_reg(data)                              set_MD_MD_SMQRdptr_reg(data)
#define  get_MD_SMQRDPTR_reg                                    get_MD_MD_SMQRdptr_reg
#define  MD_SMQRDPTR_smq_rdptr_shift                            MD_MD_SMQRdptr_smq_rdptr_shift
#define  MD_SMQRDPTR_smq_rdptr_mask                             MD_MD_SMQRdptr_smq_rdptr_mask
#define  MD_SMQRDPTR_smq_rdptr(data)                            MD_MD_SMQRdptr_smq_rdptr(data)
#define  MD_SMQRDPTR_get_smq_rdptr(data)                        MD_MD_SMQRdptr_get_smq_rdptr(data)

#define  MD_SMQWRPTR                                            MD_MD_SMQWrptr
#define  MD_SMQWRPTR_reg_addr                                   MD_MD_SMQWrptr_reg_addr
#define  MD_SMQWRPTR_reg                                        MD_MD_SMQWrptr_reg
#define  MD_SMQWRPTR_inst_addr                                  MD_MD_SMQWrptr_inst_addr
#define  set_MD_SMQWRPTR_reg(data)                              set_MD_MD_SMQWrptr_reg(data)
#define  get_MD_SMQWRPTR_reg                                    get_MD_MD_SMQWrptr_reg
#define  MD_SMQWRPTR_smq_wrptr_shift                            MD_MD_SMQWrptr_smq_wrptr_shift
#define  MD_SMQWRPTR_smq_wrptr_mask                             MD_MD_SMQWrptr_smq_wrptr_mask
#define  MD_SMQWRPTR_smq_wrptr(data)                            MD_MD_SMQWrptr_smq_wrptr(data)
#define  MD_SMQWRPTR_get_smq_wrptr(data)                        MD_MD_SMQWrptr_get_smq_wrptr(data)

#define  MD_SMQFIFOSTATE                                        MD_MD_SMQFifoState
#define  MD_SMQFIFOSTATE_reg_addr                               MD_MD_SMQFifoState_reg_addr
#define  MD_SMQFIFOSTATE_reg                                    MD_MD_SMQFifoState_reg
#define  MD_SMQFIFOSTATE_inst_addr                              MD_MD_SMQFifoState_inst_addr
#define  set_MD_SMQFIFOSTATE_reg(data)                          set_MD_MD_SMQFifoState_reg(data)
#define  get_MD_SMQFIFOSTATE_reg                                get_MD_MD_SMQFifoState_reg
#define  MD_SMQFIFOSTATE_smq_inst_remain_shift                  MD_MD_SMQFifoState_smq_inst_remain_shift
#define  MD_SMQFIFOSTATE_smq_inst_remain_mask                   MD_MD_SMQFifoState_smq_inst_remain_mask
#define  MD_SMQFIFOSTATE_smq_inst_remain(data)                  MD_MD_SMQFifoState_smq_inst_remain(data)
#define  MD_SMQFIFOSTATE_get_smq_inst_remain(data)              MD_MD_SMQFifoState_get_smq_inst_remain(data)

#define  MD_SMQ_INSTCNT                                         MD_MD_SMQ_INSTCNT
#define  MD_SMQ_INSTCNT_reg_addr                                MD_MD_SMQ_INSTCNT_reg_addr
#define  MD_SMQ_INSTCNT_reg                                     MD_MD_SMQ_INSTCNT_reg
#define  MD_SMQ_INSTCNT_inst_addr                               MD_MD_SMQ_INSTCNT_inst_addr
#define  set_MD_SMQ_INSTCNT_reg(data)                           set_MD_MD_SMQ_INSTCNT_reg(data)
#define  get_MD_SMQ_INSTCNT_reg                                 get_MD_MD_SMQ_INSTCNT_reg
#define  MD_SMQ_INSTCNT_smq_inst_cnt_shift                      MD_MD_SMQ_INSTCNT_smq_inst_cnt_shift
#define  MD_SMQ_INSTCNT_smq_inst_cnt_mask                       MD_MD_SMQ_INSTCNT_smq_inst_cnt_mask
#define  MD_SMQ_INSTCNT_smq_inst_cnt(data)                      MD_MD_SMQ_INSTCNT_smq_inst_cnt(data)
#define  MD_SMQ_INSTCNT_get_smq_inst_cnt(data)                  MD_MD_SMQ_INSTCNT_get_smq_inst_cnt(data)

#define  MD_VMQ_CNTL                                            MD_MD_VMQ_CNTL
#define  MD_VMQ_CNTL_reg_addr                                   MD_MD_VMQ_CNTL_reg_addr
#define  MD_VMQ_CNTL_reg                                        MD_MD_VMQ_CNTL_reg
#define  MD_VMQ_CNTL_inst_addr                                  MD_MD_VMQ_CNTL_inst_addr
#define  set_MD_VMQ_CNTL_reg(data)                              set_MD_MD_VMQ_CNTL_reg(data)
#define  get_MD_VMQ_CNTL_reg                                    get_MD_MD_VMQ_CNTL_reg
#define  MD_VMQ_CNTL_vmq_idle_shift                             MD_MD_VMQ_CNTL_vmq_idle_shift
#define  MD_VMQ_CNTL_vmq_cmd_swap_shift                         MD_MD_VMQ_CNTL_vmq_cmd_swap_shift
#define  MD_VMQ_CNTL_vmq_go_shift                               MD_MD_VMQ_CNTL_vmq_go_shift
#define  MD_VMQ_CNTL_write_data_shift                           MD_MD_VMQ_CNTL_write_data_shift
#define  MD_VMQ_CNTL_vmq_idle_mask                              MD_MD_VMQ_CNTL_vmq_idle_mask
#define  MD_VMQ_CNTL_vmq_cmd_swap_mask                          MD_MD_VMQ_CNTL_vmq_cmd_swap_mask
#define  MD_VMQ_CNTL_vmq_go_mask                                MD_MD_VMQ_CNTL_vmq_go_mask
#define  MD_VMQ_CNTL_write_data_mask                            MD_MD_VMQ_CNTL_write_data_mask
#define  MD_VMQ_CNTL_vmq_idle(data)                             MD_MD_VMQ_CNTL_vmq_idle(data)
#define  MD_VMQ_CNTL_vmq_cmd_swap(data)                         MD_MD_VMQ_CNTL_vmq_cmd_swap(data)
#define  MD_VMQ_CNTL_vmq_go(data)                               MD_MD_VMQ_CNTL_vmq_go(data)
#define  MD_VMQ_CNTL_write_data(data)                           MD_MD_VMQ_CNTL_write_data(data)
#define  MD_VMQ_CNTL_get_vmq_idle(data)                         MD_MD_VMQ_CNTL_get_vmq_idle(data)
#define  MD_VMQ_CNTL_get_vmq_cmd_swap(data)                     MD_MD_VMQ_CNTL_get_vmq_cmd_swap(data)
#define  MD_VMQ_CNTL_get_vmq_go(data)                           MD_MD_VMQ_CNTL_get_vmq_go(data)
#define  MD_VMQ_CNTL_get_write_data(data)                       MD_MD_VMQ_CNTL_get_write_data(data)

#define  MD_VMQ_INT_STATUS                                      MD_MD_VMQ_INT_STATUS
#define  MD_VMQ_INT_STATUS_reg_addr                             MD_MD_VMQ_INT_STATUS_reg_addr
#define  MD_VMQ_INT_STATUS_reg                                  MD_MD_VMQ_INT_STATUS_reg
#define  MD_VMQ_INT_STATUS_inst_addr                            MD_MD_VMQ_INT_STATUS_inst_addr
#define  set_MD_VMQ_INT_STATUS_reg(data)                        set_MD_MD_VMQ_INT_STATUS_reg(data)
#define  get_MD_VMQ_INT_STATUS_reg                              get_MD_MD_VMQ_INT_STATUS_reg
#define  MD_VMQ_INT_STATUS_vmq_mode_2b4berr_shift               MD_MD_VMQ_INT_STATUS_vmq_mode_2b4berr_shift
#define  MD_VMQ_INT_STATUS_vmq_empty_shift                      MD_MD_VMQ_INT_STATUS_vmq_empty_shift
#define  MD_VMQ_INT_STATUS_vmq_length_err_shift                 MD_MD_VMQ_INT_STATUS_vmq_length_err_shift
#define  MD_VMQ_INT_STATUS_vmq_inst_err_shift                   MD_MD_VMQ_INT_STATUS_vmq_inst_err_shift
#define  MD_VMQ_INT_STATUS_write_data_shift                     MD_MD_VMQ_INT_STATUS_write_data_shift
#define  MD_VMQ_INT_STATUS_vmq_mode_2b4berr_mask                MD_MD_VMQ_INT_STATUS_vmq_mode_2b4berr_mask
#define  MD_VMQ_INT_STATUS_vmq_empty_mask                       MD_MD_VMQ_INT_STATUS_vmq_empty_mask
#define  MD_VMQ_INT_STATUS_vmq_length_err_mask                  MD_MD_VMQ_INT_STATUS_vmq_length_err_mask
#define  MD_VMQ_INT_STATUS_vmq_inst_err_mask                    MD_MD_VMQ_INT_STATUS_vmq_inst_err_mask
#define  MD_VMQ_INT_STATUS_write_data_mask                      MD_MD_VMQ_INT_STATUS_write_data_mask
#define  MD_VMQ_INT_STATUS_vmq_mode_2b4berr(data)               MD_MD_VMQ_INT_STATUS_vmq_mode_2b4berr(data)
#define  MD_VMQ_INT_STATUS_vmq_empty(data)                      MD_MD_VMQ_INT_STATUS_vmq_empty(data)
#define  MD_VMQ_INT_STATUS_vmq_length_err(data)                 MD_MD_VMQ_INT_STATUS_vmq_length_err(data)
#define  MD_VMQ_INT_STATUS_vmq_inst_err(data)                   MD_MD_VMQ_INT_STATUS_vmq_inst_err(data)
#define  MD_VMQ_INT_STATUS_write_data(data)                     MD_MD_VMQ_INT_STATUS_write_data(data)
#define  MD_VMQ_INT_STATUS_get_vmq_mode_2b4berr(data)           MD_MD_VMQ_INT_STATUS_get_vmq_mode_2b4berr(data)
#define  MD_VMQ_INT_STATUS_get_vmq_empty(data)                  MD_MD_VMQ_INT_STATUS_get_vmq_empty(data)
#define  MD_VMQ_INT_STATUS_get_vmq_length_err(data)             MD_MD_VMQ_INT_STATUS_get_vmq_length_err(data)
#define  MD_VMQ_INT_STATUS_get_vmq_inst_err(data)               MD_MD_VMQ_INT_STATUS_get_vmq_inst_err(data)
#define  MD_VMQ_INT_STATUS_get_write_data(data)                 MD_MD_VMQ_INT_STATUS_get_write_data(data)

#define  MD_VMQ_INT_ENABLE                                      MD_MD_VMQ_INT_ENABLE
#define  MD_VMQ_INT_ENABLE_reg_addr                             MD_MD_VMQ_INT_ENABLE_reg_addr
#define  MD_VMQ_INT_ENABLE_reg                                  MD_MD_VMQ_INT_ENABLE_reg
#define  MD_VMQ_INT_ENABLE_inst_addr                            MD_MD_VMQ_INT_ENABLE_inst_addr
#define  set_MD_VMQ_INT_ENABLE_reg(data)                        set_MD_MD_VMQ_INT_ENABLE_reg(data)
#define  get_MD_VMQ_INT_ENABLE_reg                              get_MD_MD_VMQ_INT_ENABLE_reg
#define  MD_VMQ_INT_ENABLE_vcpu_int_en_shift                    MD_MD_VMQ_INT_ENABLE_vcpu_int_en_shift
#define  MD_VMQ_INT_ENABLE_vmq_mode_2b4b_err_en_shift           MD_MD_VMQ_INT_ENABLE_vmq_mode_2b4b_err_en_shift
#define  MD_VMQ_INT_ENABLE_vmq_empty_en_shift                   MD_MD_VMQ_INT_ENABLE_vmq_empty_en_shift
#define  MD_VMQ_INT_ENABLE_vmq_length_err_en_shift              MD_MD_VMQ_INT_ENABLE_vmq_length_err_en_shift
#define  MD_VMQ_INT_ENABLE_vmq_inst_err_en_shift                MD_MD_VMQ_INT_ENABLE_vmq_inst_err_en_shift
#define  MD_VMQ_INT_ENABLE_write_data_shift                     MD_MD_VMQ_INT_ENABLE_write_data_shift
#define  MD_VMQ_INT_ENABLE_vcpu_int_en_mask                     MD_MD_VMQ_INT_ENABLE_vcpu_int_en_mask
#define  MD_VMQ_INT_ENABLE_vmq_mode_2b4b_err_en_mask            MD_MD_VMQ_INT_ENABLE_vmq_mode_2b4b_err_en_mask
#define  MD_VMQ_INT_ENABLE_vmq_empty_en_mask                    MD_MD_VMQ_INT_ENABLE_vmq_empty_en_mask
#define  MD_VMQ_INT_ENABLE_vmq_length_err_en_mask               MD_MD_VMQ_INT_ENABLE_vmq_length_err_en_mask
#define  MD_VMQ_INT_ENABLE_vmq_inst_err_en_mask                 MD_MD_VMQ_INT_ENABLE_vmq_inst_err_en_mask
#define  MD_VMQ_INT_ENABLE_write_data_mask                      MD_MD_VMQ_INT_ENABLE_write_data_mask
#define  MD_VMQ_INT_ENABLE_vcpu_int_en(data)                    MD_MD_VMQ_INT_ENABLE_vcpu_int_en(data)
#define  MD_VMQ_INT_ENABLE_vmq_mode_2b4b_err_en(data)           MD_MD_VMQ_INT_ENABLE_vmq_mode_2b4b_err_en(data)
#define  MD_VMQ_INT_ENABLE_vmq_empty_en(data)                   MD_MD_VMQ_INT_ENABLE_vmq_empty_en(data)
#define  MD_VMQ_INT_ENABLE_vmq_length_err_en(data)              MD_MD_VMQ_INT_ENABLE_vmq_length_err_en(data)
#define  MD_VMQ_INT_ENABLE_vmq_inst_err_en(data)                MD_MD_VMQ_INT_ENABLE_vmq_inst_err_en(data)
#define  MD_VMQ_INT_ENABLE_write_data(data)                     MD_MD_VMQ_INT_ENABLE_write_data(data)
#define  MD_VMQ_INT_ENABLE_get_vcpu_int_en(data)                MD_MD_VMQ_INT_ENABLE_get_vcpu_int_en(data)
#define  MD_VMQ_INT_ENABLE_get_vmq_mode_2b4b_err_en(data)       MD_MD_VMQ_INT_ENABLE_get_vmq_mode_2b4b_err_en(data)
#define  MD_VMQ_INT_ENABLE_get_vmq_empty_en(data)               MD_MD_VMQ_INT_ENABLE_get_vmq_empty_en(data)
#define  MD_VMQ_INT_ENABLE_get_vmq_length_err_en(data)          MD_MD_VMQ_INT_ENABLE_get_vmq_length_err_en(data)
#define  MD_VMQ_INT_ENABLE_get_vmq_inst_err_en(data)            MD_MD_VMQ_INT_ENABLE_get_vmq_inst_err_en(data)
#define  MD_VMQ_INT_ENABLE_get_write_data(data)                 MD_MD_VMQ_INT_ENABLE_get_write_data(data)

#define  MD_VMQBASE                                             MD_MD_VMQBase
#define  MD_VMQBASE_reg_addr                                    MD_MD_VMQBase_reg_addr
#define  MD_VMQBASE_reg                                         MD_MD_VMQBase_reg
#define  MD_VMQBASE_inst_addr                                   MD_MD_VMQBase_inst_addr
#define  set_MD_VMQBASE_reg(data)                               set_MD_MD_VMQBase_reg(data)
#define  get_MD_VMQBASE_reg                                     get_MD_MD_VMQBase_reg
#define  MD_VMQBASE_vmq_base_shift                              MD_MD_VMQBase_vmq_base_shift
#define  MD_VMQBASE_vmq_base_mask                               MD_MD_VMQBase_vmq_base_mask
#define  MD_VMQBASE_vmq_base(data)                              MD_MD_VMQBase_vmq_base(data)
#define  MD_VMQBASE_get_vmq_base(data)                          MD_MD_VMQBase_get_vmq_base(data)

#define  MD_VMQLIMIT                                            MD_MD_VMQLimit
#define  MD_VMQLIMIT_reg_addr                                   MD_MD_VMQLimit_reg_addr
#define  MD_VMQLIMIT_reg                                        MD_MD_VMQLimit_reg
#define  MD_VMQLIMIT_inst_addr                                  MD_MD_VMQLimit_inst_addr
#define  set_MD_VMQLIMIT_reg(data)                              set_MD_MD_VMQLimit_reg(data)
#define  get_MD_VMQLIMIT_reg                                    get_MD_MD_VMQLimit_reg
#define  MD_VMQLIMIT_vmq_limit_shift                            MD_MD_VMQLimit_vmq_limit_shift
#define  MD_VMQLIMIT_vmq_limit_mask                             MD_MD_VMQLimit_vmq_limit_mask
#define  MD_VMQLIMIT_vmq_limit(data)                            MD_MD_VMQLimit_vmq_limit(data)
#define  MD_VMQLIMIT_get_vmq_limit(data)                        MD_MD_VMQLimit_get_vmq_limit(data)

#define  MD_VMQRDPTR                                            MD_MD_VMQRdptr
#define  MD_VMQRDPTR_reg_addr                                   MD_MD_VMQRdptr_reg_addr
#define  MD_VMQRDPTR_reg                                        MD_MD_VMQRdptr_reg
#define  MD_VMQRDPTR_inst_addr                                  MD_MD_VMQRdptr_inst_addr
#define  set_MD_VMQRDPTR_reg(data)                              set_MD_MD_VMQRdptr_reg(data)
#define  get_MD_VMQRDPTR_reg                                    get_MD_MD_VMQRdptr_reg
#define  MD_VMQRDPTR_vmq_rdptr_shift                            MD_MD_VMQRdptr_vmq_rdptr_shift
#define  MD_VMQRDPTR_vmq_rdptr_mask                             MD_MD_VMQRdptr_vmq_rdptr_mask
#define  MD_VMQRDPTR_vmq_rdptr(data)                            MD_MD_VMQRdptr_vmq_rdptr(data)
#define  MD_VMQRDPTR_get_vmq_rdptr(data)                        MD_MD_VMQRdptr_get_vmq_rdptr(data)

#define  MD_VMQWRPTR                                            MD_MD_VMQWrptr
#define  MD_VMQWRPTR_reg_addr                                   MD_MD_VMQWrptr_reg_addr
#define  MD_VMQWRPTR_reg                                        MD_MD_VMQWrptr_reg
#define  MD_VMQWRPTR_inst_addr                                  MD_MD_VMQWrptr_inst_addr
#define  set_MD_VMQWRPTR_reg(data)                              set_MD_MD_VMQWrptr_reg(data)
#define  get_MD_VMQWRPTR_reg                                    get_MD_MD_VMQWrptr_reg
#define  MD_VMQWRPTR_vmq_wrptr_shift                            MD_MD_VMQWrptr_vmq_wrptr_shift
#define  MD_VMQWRPTR_vmq_wrptr_mask                             MD_MD_VMQWrptr_vmq_wrptr_mask
#define  MD_VMQWRPTR_vmq_wrptr(data)                            MD_MD_VMQWrptr_vmq_wrptr(data)
#define  MD_VMQWRPTR_get_vmq_wrptr(data)                        MD_MD_VMQWrptr_get_vmq_wrptr(data)

#define  MD_VMQFifoState                                        MD_MD_VMQFifoState
#define  MD_VMQFifoState_reg_addr                               MD_MD_VMQFifoState_reg_addr
#define  MD_VMQFifoState_reg                                    MD_MD_VMQFifoState_reg
#define  MD_VMQFifoState_inst_addr                              MD_MD_VMQFifoState_inst_addr
#define  set_MD_VMQFifoState_reg(data)                          set_MD_MD_VMQFifoState_reg(data)
#define  get_MD_VMQFifoState_reg                                get_MD_MD_VMQFifoState_reg
#define  MD_VMQFifoState_vmq_inst_remain_shift                  MD_MD_VMQFifoState_vmq_inst_remain_shift
#define  MD_VMQFifoState_vmq_inst_remain_mask                   MD_MD_VMQFifoState_vmq_inst_remain_mask
#define  MD_VMQFifoState_vmq_inst_remain(data)                  MD_MD_VMQFifoState_vmq_inst_remain(data)
#define  MD_VMQFifoState_get_vmq_inst_remain(data)              MD_MD_VMQFifoState_get_vmq_inst_remain(data)

#define  MD_VMQ_INSTCNT                                         MD_MD_VMQ_INSTCNT
#define  MD_VMQ_INSTCNT_reg_addr                                MD_MD_VMQ_INSTCNT_reg_addr
#define  MD_VMQ_INSTCNT_reg                                     MD_MD_VMQ_INSTCNT_reg
#define  MD_VMQ_INSTCNT_inst_addr                               MD_MD_VMQ_INSTCNT_inst_addr
#define  set_MD_VMQ_INSTCNT_reg(data)                           set_MD_MD_VMQ_INSTCNT_reg(data)
#define  get_MD_VMQ_INSTCNT_reg                                 get_MD_MD_VMQ_INSTCNT_reg
#define  MD_VMQ_INSTCNT_vmq_inst_cnt_shift                      MD_MD_VMQ_INSTCNT_vmq_inst_cnt_shift
#define  MD_VMQ_INSTCNT_vmq_inst_cnt_mask                       MD_MD_VMQ_INSTCNT_vmq_inst_cnt_mask
#define  MD_VMQ_INSTCNT_vmq_inst_cnt(data)                      MD_MD_VMQ_INSTCNT_vmq_inst_cnt(data)
#define  MD_VMQ_INSTCNT_get_vmq_inst_cnt(data)                  MD_MD_VMQ_INSTCNT_get_vmq_inst_cnt(data)

#define  MD_KMQ_CNTL                                            MD_MD_KMQ_CNTL
#define  MD_KMQ_CNTL_reg_addr                                   MD_MD_KMQ_CNTL_reg_addr
#define  MD_KMQ_CNTL_reg                                        MD_MD_KMQ_CNTL_reg
#define  MD_KMQ_CNTL_inst_addr                                  MD_MD_KMQ_CNTL_inst_addr
#define  set_MD_KMQ_CNTL_reg(data)                              set_MD_MD_KMQ_CNTL_reg(data)
#define  get_MD_KMQ_CNTL_reg                                    get_MD_MD_KMQ_CNTL_reg
#define  MD_KMQ_CNTL_kmq_idle_shift                             MD_MD_KMQ_CNTL_kmq_idle_shift
#define  MD_KMQ_CNTL_kmq_cmd_swap_shift                         MD_MD_KMQ_CNTL_kmq_cmd_swap_shift
#define  MD_KMQ_CNTL_kmq_go_shift                               MD_MD_KMQ_CNTL_kmq_go_shift
#define  MD_KMQ_CNTL_write_data_shift                           MD_MD_KMQ_CNTL_write_data_shift
#define  MD_KMQ_CNTL_kmq_idle_mask                              MD_MD_KMQ_CNTL_kmq_idle_mask
#define  MD_KMQ_CNTL_kmq_cmd_swap_mask                          MD_MD_KMQ_CNTL_kmq_cmd_swap_mask
#define  MD_KMQ_CNTL_kmq_go_mask                                MD_MD_KMQ_CNTL_kmq_go_mask
#define  MD_KMQ_CNTL_write_data_mask                            MD_MD_KMQ_CNTL_write_data_mask
#define  MD_KMQ_CNTL_kmq_idle(data)                             MD_MD_KMQ_CNTL_kmq_idle(data)
#define  MD_KMQ_CNTL_kmq_cmd_swap(data)                         MD_MD_KMQ_CNTL_kmq_cmd_swap(data)
#define  MD_KMQ_CNTL_kmq_go(data)                               MD_MD_KMQ_CNTL_kmq_go(data)
#define  MD_KMQ_CNTL_write_data(data)                           MD_MD_KMQ_CNTL_write_data(data)
#define  MD_KMQ_CNTL_get_kmq_idle(data)                         MD_MD_KMQ_CNTL_get_kmq_idle(data)
#define  MD_KMQ_CNTL_get_kmq_cmd_swap(data)                     MD_MD_KMQ_CNTL_get_kmq_cmd_swap(data)
#define  MD_KMQ_CNTL_get_kmq_go(data)                           MD_MD_KMQ_CNTL_get_kmq_go(data)
#define  MD_KMQ_CNTL_get_write_data(data)                       MD_MD_KMQ_CNTL_get_write_data(data)

#define  MD_KMQ_INT_STATUS                                      MD_MD_KMQ_INT_STATUS
#define  MD_KMQ_INT_STATUS_reg_addr                             MD_MD_KMQ_INT_STATUS_reg_addr
#define  MD_KMQ_INT_STATUS_reg                                  MD_MD_KMQ_INT_STATUS_reg
#define  MD_KMQ_INT_STATUS_inst_addr                            MD_MD_KMQ_INT_STATUS_inst_addr
#define  set_MD_KMQ_INT_STATUS_reg(data)                        set_MD_MD_KMQ_INT_STATUS_reg(data)
#define  get_MD_KMQ_INT_STATUS_reg                              get_MD_MD_KMQ_INT_STATUS_reg
#define  MD_KMQ_INT_STATUS_kmq_mode_2b4berr_shift               MD_MD_KMQ_INT_STATUS_kmq_mode_2b4berr_shift
#define  MD_KMQ_INT_STATUS_kmq_empty_shift                      MD_MD_KMQ_INT_STATUS_kmq_empty_shift
#define  MD_KMQ_INT_STATUS_kmq_length_err_shift                 MD_MD_KMQ_INT_STATUS_kmq_length_err_shift
#define  MD_KMQ_INT_STATUS_kmq_inst_err_shift                   MD_MD_KMQ_INT_STATUS_kmq_inst_err_shift
#define  MD_KMQ_INT_STATUS_write_data_shift                     MD_MD_KMQ_INT_STATUS_write_data_shift
#define  MD_KMQ_INT_STATUS_kmq_mode_2b4berr_mask                MD_MD_KMQ_INT_STATUS_kmq_mode_2b4berr_mask
#define  MD_KMQ_INT_STATUS_kmq_empty_mask                       MD_MD_KMQ_INT_STATUS_kmq_empty_mask
#define  MD_KMQ_INT_STATUS_kmq_length_err_mask                  MD_MD_KMQ_INT_STATUS_kmq_length_err_mask
#define  MD_KMQ_INT_STATUS_kmq_inst_err_mask                    MD_MD_KMQ_INT_STATUS_kmq_inst_err_mask
#define  MD_KMQ_INT_STATUS_write_data_mask                      MD_MD_KMQ_INT_STATUS_write_data_mask
#define  MD_KMQ_INT_STATUS_kmq_mode_2b4berr(data)               MD_MD_KMQ_INT_STATUS_kmq_mode_2b4berr(data)
#define  MD_KMQ_INT_STATUS_kmq_empty(data)                      MD_MD_KMQ_INT_STATUS_kmq_empty(data)
#define  MD_KMQ_INT_STATUS_kmq_length_err(data)                 MD_MD_KMQ_INT_STATUS_kmq_length_err(data)
#define  MD_KMQ_INT_STATUS_kmq_inst_err(data)                   MD_MD_KMQ_INT_STATUS_kmq_inst_err(data)
#define  MD_KMQ_INT_STATUS_write_data(data)                     MD_MD_KMQ_INT_STATUS_write_data(data)
#define  MD_KMQ_INT_STATUS_get_kmq_mode_2b4berr(data)           MD_MD_KMQ_INT_STATUS_get_kmq_mode_2b4berr(data)
#define  MD_KMQ_INT_STATUS_get_kmq_empty(data)                  MD_MD_KMQ_INT_STATUS_get_kmq_empty(data)
#define  MD_KMQ_INT_STATUS_get_kmq_length_err(data)             MD_MD_KMQ_INT_STATUS_get_kmq_length_err(data)
#define  MD_KMQ_INT_STATUS_get_kmq_inst_err(data)               MD_MD_KMQ_INT_STATUS_get_kmq_inst_err(data)
#define  MD_KMQ_INT_STATUS_get_write_data(data)                 MD_MD_KMQ_INT_STATUS_get_write_data(data)

#define  MD_KMQ_INT_ENABLE                                      MD_MD_KMQ_INT_ENABLE
#define  MD_KMQ_INT_ENABLE_reg_addr                             MD_MD_KMQ_INT_ENABLE_reg_addr
#define  MD_KMQ_INT_ENABLE_reg                                  MD_MD_KMQ_INT_ENABLE_reg
#define  MD_KMQ_INT_ENABLE_inst_addr                            MD_MD_KMQ_INT_ENABLE_inst_addr
#define  set_MD_KMQ_INT_ENABLE_reg(data)                        set_MD_MD_KMQ_INT_ENABLE_reg(data)
#define  get_MD_KMQ_INT_ENABLE_reg                              get_MD_MD_KMQ_INT_ENABLE_reg
#define  MD_KMQ_INT_ENABLE_kcpu_int_en_shift                    MD_MD_KMQ_INT_ENABLE_kcpu_int_en_shift
#define  MD_KMQ_INT_ENABLE_kmq_mode_2b4b_err_en_shift           MD_MD_KMQ_INT_ENABLE_kmq_mode_2b4b_err_en_shift
#define  MD_KMQ_INT_ENABLE_kmq_empty_en_shift                   MD_MD_KMQ_INT_ENABLE_kmq_empty_en_shift
#define  MD_KMQ_INT_ENABLE_kmq_length_err_en_shift              MD_MD_KMQ_INT_ENABLE_kmq_length_err_en_shift
#define  MD_KMQ_INT_ENABLE_kmq_inst_err_en_shift                MD_MD_KMQ_INT_ENABLE_kmq_inst_err_en_shift
#define  MD_KMQ_INT_ENABLE_write_data_shift                     MD_MD_KMQ_INT_ENABLE_write_data_shift
#define  MD_KMQ_INT_ENABLE_kcpu_int_en_mask                     MD_MD_KMQ_INT_ENABLE_kcpu_int_en_mask
#define  MD_KMQ_INT_ENABLE_kmq_mode_2b4b_err_en_mask            MD_MD_KMQ_INT_ENABLE_kmq_mode_2b4b_err_en_mask
#define  MD_KMQ_INT_ENABLE_kmq_empty_en_mask                    MD_MD_KMQ_INT_ENABLE_kmq_empty_en_mask
#define  MD_KMQ_INT_ENABLE_kmq_length_err_en_mask               MD_MD_KMQ_INT_ENABLE_kmq_length_err_en_mask
#define  MD_KMQ_INT_ENABLE_kmq_inst_err_en_mask                 MD_MD_KMQ_INT_ENABLE_kmq_inst_err_en_mask
#define  MD_KMQ_INT_ENABLE_write_data_mask                      MD_MD_KMQ_INT_ENABLE_write_data_mask
#define  MD_KMQ_INT_ENABLE_kcpu_int_en(data)                    MD_MD_KMQ_INT_ENABLE_kcpu_int_en(data)
#define  MD_KMQ_INT_ENABLE_kmq_mode_2b4b_err_en(data)           MD_MD_KMQ_INT_ENABLE_kmq_mode_2b4b_err_en(data)
#define  MD_KMQ_INT_ENABLE_kmq_empty_en(data)                   MD_MD_KMQ_INT_ENABLE_kmq_empty_en(data)
#define  MD_KMQ_INT_ENABLE_kmq_length_err_en(data)              MD_MD_KMQ_INT_ENABLE_kmq_length_err_en(data)
#define  MD_KMQ_INT_ENABLE_kmq_inst_err_en(data)                MD_MD_KMQ_INT_ENABLE_kmq_inst_err_en(data)
#define  MD_KMQ_INT_ENABLE_write_data(data)                     MD_MD_KMQ_INT_ENABLE_write_data(data)
#define  MD_KMQ_INT_ENABLE_get_kcpu_int_en(data)                MD_MD_KMQ_INT_ENABLE_get_kcpu_int_en(data)
#define  MD_KMQ_INT_ENABLE_get_kmq_mode_2b4b_err_en(data)       MD_MD_KMQ_INT_ENABLE_get_kmq_mode_2b4b_err_en(data)
#define  MD_KMQ_INT_ENABLE_get_kmq_empty_en(data)               MD_MD_KMQ_INT_ENABLE_get_kmq_empty_en(data)
#define  MD_KMQ_INT_ENABLE_get_kmq_length_err_en(data)          MD_MD_KMQ_INT_ENABLE_get_kmq_length_err_en(data)
#define  MD_KMQ_INT_ENABLE_get_kmq_inst_err_en(data)            MD_MD_KMQ_INT_ENABLE_get_kmq_inst_err_en(data)
#define  MD_KMQ_INT_ENABLE_get_write_data(data)                 MD_MD_KMQ_INT_ENABLE_get_write_data(data)

#define  MD_KMQBase                                             MD_MD_KMQBase
#define  MD_KMQBase_reg_addr                                    MD_MD_KMQBase_reg_addr
#define  MD_KMQBase_reg                                         MD_MD_KMQBase_reg
#define  MD_KMQBase_inst_addr                                   MD_MD_KMQBase_inst_addr
#define  set_MD_KMQBase_reg(data)                               set_MD_MD_KMQBase_reg(data)
#define  get_MD_KMQBase_reg                                     get_MD_MD_KMQBase_reg
#define  MD_KMQBase_kmq_base_shift                              MD_MD_KMQBase_kmq_base_shift
#define  MD_KMQBase_kmq_base_mask                               MD_MD_KMQBase_kmq_base_mask
#define  MD_KMQBase_kmq_base(data)                              MD_MD_KMQBase_kmq_base(data)
#define  MD_KMQBase_get_kmq_base(data)                          MD_MD_KMQBase_get_kmq_base(data)

#define  MD_KMQLimit                                            MD_MD_KMQLimit
#define  MD_KMQLimit_reg_addr                                   MD_MD_KMQLimit_reg_addr
#define  MD_KMQLimit_reg                                        MD_MD_KMQLimit_reg
#define  MD_KMQLimit_inst_addr                                  MD_MD_KMQLimit_inst_addr
#define  set_MD_KMQLimit_reg(data)                              set_MD_MD_KMQLimit_reg(data)
#define  get_MD_KMQLimit_reg                                    get_MD_MD_KMQLimit_reg
#define  MD_KMQLimit_kmq_limit_shift                            MD_MD_KMQLimit_kmq_limit_shift
#define  MD_KMQLimit_kmq_limit_mask                             MD_MD_KMQLimit_kmq_limit_mask
#define  MD_KMQLimit_kmq_limit(data)                            MD_MD_KMQLimit_kmq_limit(data)
#define  MD_KMQLimit_get_kmq_limit(data)                        MD_MD_KMQLimit_get_kmq_limit(data)

#define  MD_KMQRdptr                                            MD_MD_KMQRdptr
#define  MD_KMQRdptr_reg_addr                                   MD_MD_KMQRdptr_reg_addr
#define  MD_KMQRdptr_reg                                        MD_MD_KMQRdptr_reg
#define  MD_KMQRdptr_inst_addr                                  MD_MD_KMQRdptr_inst_addr
#define  set_MD_KMQRdptr_reg(data)                              set_MD_MD_KMQRdptr_reg(data)
#define  get_MD_KMQRdptr_reg                                    get_MD_MD_KMQRdptr_reg
#define  MD_KMQRdptr_kmq_rdptr_shift                            MD_MD_KMQRdptr_kmq_rdptr_shift
#define  MD_KMQRdptr_kmq_rdptr_mask                             MD_MD_KMQRdptr_kmq_rdptr_mask
#define  MD_KMQRdptr_kmq_rdptr(data)                            MD_MD_KMQRdptr_kmq_rdptr(data)
#define  MD_KMQRdptr_get_kmq_rdptr(data)                        MD_MD_KMQRdptr_get_kmq_rdptr(data)

#define  MD_KMQWrptr                                            MD_MD_KMQWrptr
#define  MD_KMQWrptr_reg_addr                                   MD_MD_KMQWrptr_reg_addr
#define  MD_KMQWrptr_reg                                        MD_MD_KMQWrptr_reg
#define  MD_KMQWrptr_inst_addr                                  MD_MD_KMQWrptr_inst_addr
#define  set_MD_KMQWrptr_reg(data)                              set_MD_MD_KMQWrptr_reg(data)
#define  get_MD_KMQWrptr_reg                                    get_MD_MD_KMQWrptr_reg
#define  MD_KMQWrptr_kmq_wrptr_shift                            MD_MD_KMQWrptr_kmq_wrptr_shift
#define  MD_KMQWrptr_kmq_wrptr_mask                             MD_MD_KMQWrptr_kmq_wrptr_mask
#define  MD_KMQWrptr_kmq_wrptr(data)                            MD_MD_KMQWrptr_kmq_wrptr(data)
#define  MD_KMQWrptr_get_kmq_wrptr(data)                        MD_MD_KMQWrptr_get_kmq_wrptr(data)

#define  MD_KMQFifoState                                        MD_MD_KMQFifoState
#define  MD_KMQFifoState_reg_addr                               MD_MD_KMQFifoState_reg_addr
#define  MD_KMQFifoState_reg                                    MD_MD_KMQFifoState_reg
#define  MD_KMQFifoState_inst_addr                              MD_MD_KMQFifoState_inst_addr
#define  set_MD_KMQFifoState_reg(data)                          set_MD_MD_KMQFifoState_reg(data)
#define  get_MD_KMQFifoState_reg                                get_MD_MD_KMQFifoState_reg
#define  MD_KMQFifoState_kmq_inst_remain_shift                  MD_MD_KMQFifoState_kmq_inst_remain_shift
#define  MD_KMQFifoState_kmq_inst_remain_mask                   MD_MD_KMQFifoState_kmq_inst_remain_mask
#define  MD_KMQFifoState_kmq_inst_remain(data)                  MD_MD_KMQFifoState_kmq_inst_remain(data)
#define  MD_KMQFifoState_get_kmq_inst_remain(data)              MD_MD_KMQFifoState_get_kmq_inst_remain(data)

#define  MD_KMQ_INSTCNT                                         MD_MD_KMQ_INSTCNT
#define  MD_KMQ_INSTCNT_reg_addr                                MD_MD_KMQ_INSTCNT_reg_addr
#define  MD_KMQ_INSTCNT_reg                                     MD_MD_KMQ_INSTCNT_reg
#define  MD_KMQ_INSTCNT_inst_addr                               MD_MD_KMQ_INSTCNT_inst_addr
#define  set_MD_KMQ_INSTCNT_reg(data)                           set_MD_MD_KMQ_INSTCNT_reg(data)
#define  get_MD_KMQ_INSTCNT_reg                                 get_MD_MD_KMQ_INSTCNT_reg
#define  MD_KMQ_INSTCNT_kmq_inst_cnt_shift                      MD_MD_KMQ_INSTCNT_kmq_inst_cnt_shift
#define  MD_KMQ_INSTCNT_kmq_inst_cnt_mask                       MD_MD_KMQ_INSTCNT_kmq_inst_cnt_mask
#define  MD_KMQ_INSTCNT_kmq_inst_cnt(data)                      MD_MD_KMQ_INSTCNT_kmq_inst_cnt(data)
#define  MD_KMQ_INSTCNT_get_kmq_inst_cnt(data)                  MD_MD_KMQ_INSTCNT_get_kmq_inst_cnt(data)

#define  MD_DBG                                                 MD_MD_DBG
#define  MD_DBG_reg_addr                                        MD_MD_DBG_reg_addr
#define  MD_DBG_reg                                             MD_MD_DBG_reg
#define  MD_DBG_inst_addr                                       MD_MD_DBG_inst_addr
#define  set_MD_DBG_reg(data)                                   set_MD_MD_DBG_reg(data)
#define  get_MD_DBG_reg                                         get_MD_MD_DBG_reg
#define  MD_DBG_md_dbg_sel1_shift                               MD_MD_DBG_md_dbg_sel1_shift
#define  MD_DBG_md_dbg_sel0_shift                               MD_MD_DBG_md_dbg_sel0_shift
#define  MD_DBG_md_dbg_enable_shift                             MD_MD_DBG_md_dbg_enable_shift
#define  MD_DBG_md_dbg_sel1_mask                                MD_MD_DBG_md_dbg_sel1_mask
#define  MD_DBG_md_dbg_sel0_mask                                MD_MD_DBG_md_dbg_sel0_mask
#define  MD_DBG_md_dbg_enable_mask                              MD_MD_DBG_md_dbg_enable_mask
#define  MD_DBG_md_dbg_sel1(data)                               MD_MD_DBG_md_dbg_sel1(data)
#define  MD_DBG_md_dbg_sel0(data)                               MD_MD_DBG_md_dbg_sel0(data)
#define  MD_DBG_md_dbg_enable(data)                             MD_MD_DBG_md_dbg_enable(data)
#define  MD_DBG_get_md_dbg_sel1(data)                           MD_MD_DBG_get_md_dbg_sel1(data)
#define  MD_DBG_get_md_dbg_sel0(data)                           MD_MD_DBG_get_md_dbg_sel0(data)
#define  MD_DBG_get_md_dbg_enable(data)                         MD_MD_DBG_get_md_dbg_enable(data)

#define  MD_FDMA_DDR_SADDR                                      MD_MD_FDMA_DDR_SADDR
#define  MD_FDMA_DDR_SADDR_reg_addr                             MD_MD_FDMA_DDR_SADDR_reg_addr
#define  MD_FDMA_DDR_SADDR_reg                                  MD_MD_FDMA_DDR_SADDR_reg
#define  MD_FDMA_DDR_SADDR_inst_addr                            MD_MD_FDMA_DDR_SADDR_inst_addr
#define  set_MD_FDMA_DDR_SADDR_reg(data)                        set_MD_MD_FDMA_DDR_SADDR_reg(data)
#define  get_MD_FDMA_DDR_SADDR_reg                              get_MD_MD_FDMA_DDR_SADDR_reg
#define  MD_FDMA_DDR_SADDR_fdma_ddr_saddr_shift                 MD_MD_FDMA_DDR_SADDR_fdma_ddr_saddr_shift
#define  MD_FDMA_DDR_SADDR_fdma_ddr_saddr_mask                  MD_MD_FDMA_DDR_SADDR_fdma_ddr_saddr_mask
#define  MD_FDMA_DDR_SADDR_fdma_ddr_saddr(data)                 MD_MD_FDMA_DDR_SADDR_fdma_ddr_saddr(data)
#define  MD_FDMA_DDR_SADDR_get_fdma_ddr_saddr(data)             MD_MD_FDMA_DDR_SADDR_get_fdma_ddr_saddr(data)

#define  MD_FDMA_FL_SADDR                                       MD_MD_FDMA_FL_SADDR
#define  MD_FDMA_FL_SADDR_reg_addr                              MD_MD_FDMA_FL_SADDR_reg_addr
#define  MD_FDMA_FL_SADDR_reg                                   MD_MD_FDMA_FL_SADDR_reg
#define  MD_FDMA_FL_SADDR_inst_addr                             MD_MD_FDMA_FL_SADDR_inst_addr
#define  set_MD_FDMA_FL_SADDR_reg(data)                         set_MD_MD_FDMA_FL_SADDR_reg(data)
#define  get_MD_FDMA_FL_SADDR_reg                               get_MD_MD_FDMA_FL_SADDR_reg
#define  MD_FDMA_FL_SADDR_fdma_fl_saddr_shift                   MD_MD_FDMA_FL_SADDR_fdma_fl_saddr_shift
#define  MD_FDMA_FL_SADDR_fdma_fl_saddr_mask                    MD_MD_FDMA_FL_SADDR_fdma_fl_saddr_mask
#define  MD_FDMA_FL_SADDR_fdma_fl_saddr(data)                   MD_MD_FDMA_FL_SADDR_fdma_fl_saddr(data)
#define  MD_FDMA_FL_SADDR_get_fdma_fl_saddr(data)               MD_MD_FDMA_FL_SADDR_get_fdma_fl_saddr(data)

#define  MD_FDMA_CTRL2                                          MD_MD_FDMA_CTRL2
#define  MD_FDMA_CTRL2_reg_addr                                 MD_MD_FDMA_CTRL2_reg_addr
#define  MD_FDMA_CTRL2_reg                                      MD_MD_FDMA_CTRL2_reg
#define  MD_FDMA_CTRL2_inst_addr                                MD_MD_FDMA_CTRL2_inst_addr
#define  set_MD_FDMA_CTRL2_reg(data)                            set_MD_MD_FDMA_CTRL2_reg(data)
#define  get_MD_FDMA_CTRL2_reg                                  get_MD_MD_FDMA_CTRL2_reg
#define  MD_FDMA_CTRL2_fl_cp_en_shift                           MD_MD_FDMA_CTRL2_fl_cp_en_shift
#define  MD_FDMA_CTRL2_fl_mapping_mode_shift                    MD_MD_FDMA_CTRL2_fl_mapping_mode_shift
#define  MD_FDMA_CTRL2_fdma_swap_shift                          MD_MD_FDMA_CTRL2_fdma_swap_shift
#define  MD_FDMA_CTRL2_fdma_max_xfer_shift                      MD_MD_FDMA_CTRL2_fdma_max_xfer_shift
#define  MD_FDMA_CTRL2_fdma_dir_shift                           MD_MD_FDMA_CTRL2_fdma_dir_shift
#define  MD_FDMA_CTRL2_fdma_length_shift                        MD_MD_FDMA_CTRL2_fdma_length_shift
#define  MD_FDMA_CTRL2_fl_cp_en_mask                            MD_MD_FDMA_CTRL2_fl_cp_en_mask
#define  MD_FDMA_CTRL2_fl_mapping_mode_mask                     MD_MD_FDMA_CTRL2_fl_mapping_mode_mask
#define  MD_FDMA_CTRL2_fdma_swap_mask                           MD_MD_FDMA_CTRL2_fdma_swap_mask
#define  MD_FDMA_CTRL2_fdma_max_xfer_mask                       MD_MD_FDMA_CTRL2_fdma_max_xfer_mask
#define  MD_FDMA_CTRL2_fdma_dir_mask                            MD_MD_FDMA_CTRL2_fdma_dir_mask
#define  MD_FDMA_CTRL2_fdma_length_mask                         MD_MD_FDMA_CTRL2_fdma_length_mask
#define  MD_FDMA_CTRL2_fl_cp_en(data)                           MD_MD_FDMA_CTRL2_fl_cp_en(data)
#define  MD_FDMA_CTRL2_fl_mapping_mode(data)                    MD_MD_FDMA_CTRL2_fl_mapping_mode(data)
#define  MD_FDMA_CTRL2_fdma_swap(data)                          MD_MD_FDMA_CTRL2_fdma_swap(data)
#define  MD_FDMA_CTRL2_fdma_max_xfer(data)                      MD_MD_FDMA_CTRL2_fdma_max_xfer(data)
#define  MD_FDMA_CTRL2_fdma_dir(data)                           MD_MD_FDMA_CTRL2_fdma_dir(data)
#define  MD_FDMA_CTRL2_fdma_length(data)                        MD_MD_FDMA_CTRL2_fdma_length(data)
#define  MD_FDMA_CTRL2_get_fl_cp_en(data)                       MD_MD_FDMA_CTRL2_get_fl_cp_en(data)
#define  MD_FDMA_CTRL2_get_fl_mapping_mode(data)                MD_MD_FDMA_CTRL2_get_fl_mapping_mode(data)
#define  MD_FDMA_CTRL2_get_fdma_swap(data)                      MD_MD_FDMA_CTRL2_get_fdma_swap(data)
#define  MD_FDMA_CTRL2_get_fdma_max_xfer(data)                  MD_MD_FDMA_CTRL2_get_fdma_max_xfer(data)
#define  MD_FDMA_CTRL2_get_fdma_dir(data)                       MD_MD_FDMA_CTRL2_get_fdma_dir(data)
#define  MD_FDMA_CTRL2_get_fdma_length(data)                    MD_MD_FDMA_CTRL2_get_fdma_length(data)

#define  MD_FDMA_CTRL1                                          MD_MD_FDMA_CTRL1
#define  MD_FDMA_CTRL1_reg_addr                                 MD_MD_FDMA_CTRL1_reg_addr
#define  MD_FDMA_CTRL1_reg                                      MD_MD_FDMA_CTRL1_reg
#define  MD_FDMA_CTRL1_inst_addr                                MD_MD_FDMA_CTRL1_inst_addr
#define  set_MD_FDMA_CTRL1_reg(data)                            set_MD_MD_FDMA_CTRL1_reg(data)
#define  get_MD_FDMA_CTRL1_reg                                  get_MD_MD_FDMA_CTRL1_reg
#define  MD_FDMA_CTRL1_write_en2_shift                          MD_MD_FDMA_CTRL1_write_en2_shift
#define  MD_FDMA_CTRL1_fdma_stop_shift                          MD_MD_FDMA_CTRL1_fdma_stop_shift
#define  MD_FDMA_CTRL1_write_en1_shift                          MD_MD_FDMA_CTRL1_write_en1_shift
#define  MD_FDMA_CTRL1_fdma_go_shift                            MD_MD_FDMA_CTRL1_fdma_go_shift
#define  MD_FDMA_CTRL1_write_en2_mask                           MD_MD_FDMA_CTRL1_write_en2_mask
#define  MD_FDMA_CTRL1_fdma_stop_mask                           MD_MD_FDMA_CTRL1_fdma_stop_mask
#define  MD_FDMA_CTRL1_write_en1_mask                           MD_MD_FDMA_CTRL1_write_en1_mask
#define  MD_FDMA_CTRL1_fdma_go_mask                             MD_MD_FDMA_CTRL1_fdma_go_mask
#define  MD_FDMA_CTRL1_write_en2(data)                          MD_MD_FDMA_CTRL1_write_en2(data)
#define  MD_FDMA_CTRL1_fdma_stop(data)                          MD_MD_FDMA_CTRL1_fdma_stop(data)
#define  MD_FDMA_CTRL1_write_en1(data)                          MD_MD_FDMA_CTRL1_write_en1(data)
#define  MD_FDMA_CTRL1_fdma_go(data)                            MD_MD_FDMA_CTRL1_fdma_go(data)
#define  MD_FDMA_CTRL1_get_write_en2(data)                      MD_MD_FDMA_CTRL1_get_write_en2(data)
#define  MD_FDMA_CTRL1_get_fdma_stop(data)                      MD_MD_FDMA_CTRL1_get_fdma_stop(data)
#define  MD_FDMA_CTRL1_get_write_en1(data)                      MD_MD_FDMA_CTRL1_get_write_en1(data)
#define  MD_FDMA_CTRL1_get_fdma_go(data)                        MD_MD_FDMA_CTRL1_get_fdma_go(data)

#define  MD_FDMA_DDR_SADDR_K                                    MD_MD_FDMA_DDR_SADDR_K
#define  MD_FDMA_DDR_SADDR_K_reg_addr                           MD_MD_FDMA_DDR_SADDR_K_reg_addr
#define  MD_FDMA_DDR_SADDR_K_reg                                MD_MD_FDMA_DDR_SADDR_K_reg
#define  MD_FDMA_DDR_SADDR_K_inst_addr                          MD_MD_FDMA_DDR_SADDR_K_inst_addr
#define  set_MD_FDMA_DDR_SADDR_K_reg(data)                      set_MD_MD_FDMA_DDR_SADDR_K_reg(data)
#define  get_MD_FDMA_DDR_SADDR_K_reg                            get_MD_MD_FDMA_DDR_SADDR_K_reg
#define  MD_FDMA_DDR_SADDR_K_fdma_ddr_saddr_k_shift             MD_MD_FDMA_DDR_SADDR_K_fdma_ddr_saddr_k_shift
#define  MD_FDMA_DDR_SADDR_K_fdma_ddr_saddr_k_mask              MD_MD_FDMA_DDR_SADDR_K_fdma_ddr_saddr_k_mask
#define  MD_FDMA_DDR_SADDR_K_fdma_ddr_saddr_k(data)             MD_MD_FDMA_DDR_SADDR_K_fdma_ddr_saddr_k(data)
#define  MD_FDMA_DDR_SADDR_K_get_fdma_ddr_saddr_k(data)         MD_MD_FDMA_DDR_SADDR_K_get_fdma_ddr_saddr_k(data)

#define  MD_FDMA_FL_SADDR_K                                     MD_MD_FDMA_FL_SADDR_K
#define  MD_FDMA_FL_SADDR_K_reg_addr                            MD_MD_FDMA_FL_SADDR_K_reg_addr
#define  MD_FDMA_FL_SADDR_K_reg                                 MD_MD_FDMA_FL_SADDR_K_reg
#define  MD_FDMA_FL_SADDR_K_inst_addr                           MD_MD_FDMA_FL_SADDR_K_inst_addr
#define  set_MD_FDMA_FL_SADDR_K_reg(data)                       set_MD_MD_FDMA_FL_SADDR_K_reg(data)
#define  get_MD_FDMA_FL_SADDR_K_reg                             get_MD_MD_FDMA_FL_SADDR_K_reg
#define  MD_FDMA_FL_SADDR_K_fdma_fl_saddr_k_shift               MD_MD_FDMA_FL_SADDR_K_fdma_fl_saddr_k_shift
#define  MD_FDMA_FL_SADDR_K_fdma_fl_saddr_k_mask                MD_MD_FDMA_FL_SADDR_K_fdma_fl_saddr_k_mask
#define  MD_FDMA_FL_SADDR_K_fdma_fl_saddr_k(data)               MD_MD_FDMA_FL_SADDR_K_fdma_fl_saddr_k(data)
#define  MD_FDMA_FL_SADDR_K_get_fdma_fl_saddr_k(data)           MD_MD_FDMA_FL_SADDR_K_get_fdma_fl_saddr_k(data)

#define  MD_FDMA_CTRL2_K                                        MD_MD_FDMA_CTRL2_K
#define  MD_FDMA_CTRL2_K_reg_addr                               MD_MD_FDMA_CTRL2_K_reg_addr
#define  MD_FDMA_CTRL2_K_reg                                    MD_MD_FDMA_CTRL2_K_reg
#define  MD_FDMA_CTRL2_K_inst_addr                              MD_MD_FDMA_CTRL2_K_inst_addr
#define  set_MD_FDMA_CTRL2_K_reg(data)                          set_MD_MD_FDMA_CTRL2_K_reg(data)
#define  get_MD_FDMA_CTRL2_K_reg                                get_MD_MD_FDMA_CTRL2_K_reg
#define  MD_FDMA_CTRL2_K_fl_cp_en_k_shift                       MD_MD_FDMA_CTRL2_K_fl_cp_en_k_shift
#define  MD_FDMA_CTRL2_K_fl_mapping_mode_k_shift                MD_MD_FDMA_CTRL2_K_fl_mapping_mode_k_shift
#define  MD_FDMA_CTRL2_K_fdma_swap_k_shift                      MD_MD_FDMA_CTRL2_K_fdma_swap_k_shift
#define  MD_FDMA_CTRL2_K_fdma_max_xfer_k_shift                  MD_MD_FDMA_CTRL2_K_fdma_max_xfer_k_shift
#define  MD_FDMA_CTRL2_K_fdma_dir_k_shift                       MD_MD_FDMA_CTRL2_K_fdma_dir_k_shift
#define  MD_FDMA_CTRL2_K_fdma_length_k_shift                    MD_MD_FDMA_CTRL2_K_fdma_length_k_shift
#define  MD_FDMA_CTRL2_K_fl_cp_en_k_mask                        MD_MD_FDMA_CTRL2_K_fl_cp_en_k_mask
#define  MD_FDMA_CTRL2_K_fl_mapping_mode_k_mask                 MD_MD_FDMA_CTRL2_K_fl_mapping_mode_k_mask
#define  MD_FDMA_CTRL2_K_fdma_swap_k_mask                       MD_MD_FDMA_CTRL2_K_fdma_swap_k_mask
#define  MD_FDMA_CTRL2_K_fdma_max_xfer_k_mask                   MD_MD_FDMA_CTRL2_K_fdma_max_xfer_k_mask
#define  MD_FDMA_CTRL2_K_fdma_dir_k_mask                        MD_MD_FDMA_CTRL2_K_fdma_dir_k_mask
#define  MD_FDMA_CTRL2_K_fdma_length_k_mask                     MD_MD_FDMA_CTRL2_K_fdma_length_k_mask
#define  MD_FDMA_CTRL2_K_fl_cp_en_k(data)                       MD_MD_FDMA_CTRL2_K_fl_cp_en_k(data)
#define  MD_FDMA_CTRL2_K_fl_mapping_mode_k(data)                MD_MD_FDMA_CTRL2_K_fl_mapping_mode_k(data)
#define  MD_FDMA_CTRL2_K_fdma_swap_k(data)                      MD_MD_FDMA_CTRL2_K_fdma_swap_k(data)
#define  MD_FDMA_CTRL2_K_fdma_max_xfer_k(data)                  MD_MD_FDMA_CTRL2_K_fdma_max_xfer_k(data)
#define  MD_FDMA_CTRL2_K_fdma_dir_k(data)                       MD_MD_FDMA_CTRL2_K_fdma_dir_k(data)
#define  MD_FDMA_CTRL2_K_fdma_length_k(data)                    MD_MD_FDMA_CTRL2_K_fdma_length_k(data)
#define  MD_FDMA_CTRL2_K_get_fl_cp_en_k(data)                   MD_MD_FDMA_CTRL2_K_get_fl_cp_en_k(data)
#define  MD_FDMA_CTRL2_K_get_fl_mapping_mode_k(data)            MD_MD_FDMA_CTRL2_K_get_fl_mapping_mode_k(data)
#define  MD_FDMA_CTRL2_K_get_fdma_swap_k(data)                  MD_MD_FDMA_CTRL2_K_get_fdma_swap_k(data)
#define  MD_FDMA_CTRL2_K_get_fdma_max_xfer_k(data)              MD_MD_FDMA_CTRL2_K_get_fdma_max_xfer_k(data)
#define  MD_FDMA_CTRL2_K_get_fdma_dir_k(data)                   MD_MD_FDMA_CTRL2_K_get_fdma_dir_k(data)
#define  MD_FDMA_CTRL2_K_get_fdma_length_k(data)                MD_MD_FDMA_CTRL2_K_get_fdma_length_k(data)

#define  MD_FDMA_CTRL1_K                                        MD_MD_FDMA_CTRL1_K
#define  MD_FDMA_CTRL1_K_reg_addr                               MD_MD_FDMA_CTRL1_K_reg_addr
#define  MD_FDMA_CTRL1_K_reg                                    MD_MD_FDMA_CTRL1_K_reg
#define  MD_FDMA_CTRL1_K_inst_addr                              MD_MD_FDMA_CTRL1_K_inst_addr
#define  set_MD_FDMA_CTRL1_K_reg(data)                          set_MD_MD_FDMA_CTRL1_K_reg(data)
#define  get_MD_FDMA_CTRL1_K_reg                                get_MD_MD_FDMA_CTRL1_K_reg
#define  MD_FDMA_CTRL1_K_write_en2_k_shift                      MD_MD_FDMA_CTRL1_K_write_en2_k_shift
#define  MD_FDMA_CTRL1_K_fdma_stop_k_shift                      MD_MD_FDMA_CTRL1_K_fdma_stop_k_shift
#define  MD_FDMA_CTRL1_K_write_en1_k_shift                      MD_MD_FDMA_CTRL1_K_write_en1_k_shift
#define  MD_FDMA_CTRL1_K_fdma_go_k_shift                        MD_MD_FDMA_CTRL1_K_fdma_go_k_shift
#define  MD_FDMA_CTRL1_K_write_en2_k_mask                       MD_MD_FDMA_CTRL1_K_write_en2_k_mask
#define  MD_FDMA_CTRL1_K_fdma_stop_k_mask                       MD_MD_FDMA_CTRL1_K_fdma_stop_k_mask
#define  MD_FDMA_CTRL1_K_write_en1_k_mask                       MD_MD_FDMA_CTRL1_K_write_en1_k_mask
#define  MD_FDMA_CTRL1_K_fdma_go_k_mask                         MD_MD_FDMA_CTRL1_K_fdma_go_k_mask
#define  MD_FDMA_CTRL1_K_write_en2_k(data)                      MD_MD_FDMA_CTRL1_K_write_en2_k(data)
#define  MD_FDMA_CTRL1_K_fdma_stop_k(data)                      MD_MD_FDMA_CTRL1_K_fdma_stop_k(data)
#define  MD_FDMA_CTRL1_K_write_en1_k(data)                      MD_MD_FDMA_CTRL1_K_write_en1_k(data)
#define  MD_FDMA_CTRL1_K_fdma_go_k(data)                        MD_MD_FDMA_CTRL1_K_fdma_go_k(data)
#define  MD_FDMA_CTRL1_K_get_write_en2_k(data)                  MD_MD_FDMA_CTRL1_K_get_write_en2_k(data)
#define  MD_FDMA_CTRL1_K_get_fdma_stop_k(data)                  MD_MD_FDMA_CTRL1_K_get_fdma_stop_k(data)
#define  MD_FDMA_CTRL1_K_get_write_en1_k(data)                  MD_MD_FDMA_CTRL1_K_get_write_en1_k(data)
#define  MD_FDMA_CTRL1_K_get_fdma_go_k(data)                    MD_MD_FDMA_CTRL1_K_get_fdma_go_k(data)

#define  MD_POWER                                               MD_MD_POWER
#define  MD_POWER_reg_addr                                      MD_MD_POWER_reg_addr
#define  MD_POWER_reg                                           MD_MD_POWER_reg
#define  MD_POWER_inst_addr                                     MD_MD_POWER_inst_addr
#define  set_MD_POWER_reg(data)                                 set_MD_MD_POWER_reg(data)
#define  get_MD_POWER_reg                                       get_MD_MD_POWER_reg
#define  MD_POWER_gating_en_shift                               MD_MD_POWER_gating_en_shift
#define  MD_POWER_gating_en_mask                                MD_MD_POWER_gating_en_mask
#define  MD_POWER_gating_en(data)                               MD_MD_POWER_gating_en(data)
#define  MD_POWER_get_gating_en(data)                           MD_MD_POWER_get_gating_en(data)

#define  MD_DUMMY1                                              MD_MD_DUMMY1
#define  MD_DUMMY1_reg_addr                                     MD_MD_DUMMY1_reg_addr
#define  MD_DUMMY1_reg                                          MD_MD_DUMMY1_reg
#define  MD_DUMMY1_inst_addr                                    MD_MD_DUMMY1_inst_addr
#define  set_MD_DUMMY1_reg(data)                                set_MD_MD_DUMMY1_reg(data)
#define  get_MD_DUMMY1_reg                                      get_MD_MD_DUMMY1_reg
#define  MD_DUMMY1_dummy1_shift                                 MD_MD_DUMMY1_dummy1_shift
#define  MD_DUMMY1_dummy1_mask                                  MD_MD_DUMMY1_dummy1_mask
#define  MD_DUMMY1_dummy1(data)                                 MD_MD_DUMMY1_dummy1(data)
#define  MD_DUMMY1_get_dummy1(data)                             MD_MD_DUMMY1_get_dummy1(data)

#define  MD_DUMMY2                                              MD_MD_DUMMY2
#define  MD_DUMMY2_reg_addr                                     MD_MD_DUMMY2_reg_addr
#define  MD_DUMMY2_reg                                          MD_MD_DUMMY2_reg
#define  MD_DUMMY2_inst_addr                                    MD_MD_DUMMY2_inst_addr
#define  set_MD_DUMMY2_reg(data)                                set_MD_MD_DUMMY2_reg(data)
#define  get_MD_DUMMY2_reg                                      get_MD_MD_DUMMY2_reg
#define  MD_DUMMY2_dummy2_shift                                 MD_MD_DUMMY2_dummy2_shift
#define  MD_DUMMY2_dummy2_mask                                  MD_MD_DUMMY2_dummy2_mask
#define  MD_DUMMY2_dummy2(data)                                 MD_MD_DUMMY2_dummy2(data)
#define  MD_DUMMY2_get_dummy2(data)                             MD_MD_DUMMY2_get_dummy2(data)

#define  md_BIST_MODE                                           MD_md_BIST_MODE
#define  md_BIST_MODE_reg_addr                                  MD_md_BIST_MODE_reg_addr
#define  md_BIST_MODE_reg                                       MD_md_BIST_MODE_reg
#define  md_BIST_MODE_inst_addr                                 MD_md_BIST_MODE_inst_addr
#define  set_md_BIST_MODE_reg(data)                             set_MD_md_BIST_MODE_reg(data)
#define  get_md_BIST_MODE_reg                                   get_MD_md_BIST_MODE_reg
#define  md_BIST_MODE_md_bist_mode_a_2p_shift                   MD_md_BIST_MODE_md_bist_mode_a_2p_shift
#define  md_BIST_MODE_md_bist_mode_a_shift                      MD_md_BIST_MODE_md_bist_mode_a_shift
#define  md_BIST_MODE_md_bist_mode_a_2p_mask                    MD_md_BIST_MODE_md_bist_mode_a_2p_mask
#define  md_BIST_MODE_md_bist_mode_a_mask                       MD_md_BIST_MODE_md_bist_mode_a_mask
#define  md_BIST_MODE_md_bist_mode_a_2p(data)                   MD_md_BIST_MODE_md_bist_mode_a_2p(data)
#define  md_BIST_MODE_md_bist_mode_a(data)                      MD_md_BIST_MODE_md_bist_mode_a(data)
#define  md_BIST_MODE_get_md_bist_mode_a_2p(data)               MD_md_BIST_MODE_get_md_bist_mode_a_2p(data)
#define  md_BIST_MODE_get_md_bist_mode_a(data)                  MD_md_BIST_MODE_get_md_bist_mode_a(data)

#define  md_BIST_DONE                                           MD_md_BIST_DONE
#define  md_BIST_DONE_reg_addr                                  MD_md_BIST_DONE_reg_addr
#define  md_BIST_DONE_reg                                       MD_md_BIST_DONE_reg
#define  md_BIST_DONE_inst_addr                                 MD_md_BIST_DONE_inst_addr
#define  set_md_BIST_DONE_reg(data)                             set_MD_md_BIST_DONE_reg(data)
#define  get_md_BIST_DONE_reg                                   get_MD_md_BIST_DONE_reg
#define  md_BIST_DONE_md_bist_done_a_2p_shift                   MD_md_BIST_DONE_md_bist_done_a_2p_shift
#define  md_BIST_DONE_md_bist_done_a_shift                      MD_md_BIST_DONE_md_bist_done_a_shift
#define  md_BIST_DONE_md_bist_done_a_2p_mask                    MD_md_BIST_DONE_md_bist_done_a_2p_mask
#define  md_BIST_DONE_md_bist_done_a_mask                       MD_md_BIST_DONE_md_bist_done_a_mask
#define  md_BIST_DONE_md_bist_done_a_2p(data)                   MD_md_BIST_DONE_md_bist_done_a_2p(data)
#define  md_BIST_DONE_md_bist_done_a(data)                      MD_md_BIST_DONE_md_bist_done_a(data)
#define  md_BIST_DONE_get_md_bist_done_a_2p(data)               MD_md_BIST_DONE_get_md_bist_done_a_2p(data)
#define  md_BIST_DONE_get_md_bist_done_a(data)                  MD_md_BIST_DONE_get_md_bist_done_a(data)

#define  md_BIST_A_FAIL                                         MD_md_BIST_A_FAIL
#define  md_BIST_A_FAIL_reg_addr                                MD_md_BIST_A_FAIL_reg_addr
#define  md_BIST_A_FAIL_reg                                     MD_md_BIST_A_FAIL_reg
#define  md_BIST_A_FAIL_inst_addr                               MD_md_BIST_A_FAIL_inst_addr
#define  set_md_BIST_A_FAIL_reg(data)                           set_MD_md_BIST_A_FAIL_reg(data)
#define  get_md_BIST_A_FAIL_reg                                 get_MD_md_BIST_A_FAIL_reg
#define  md_BIST_A_FAIL_md_bist_a_fail_1_shift                  MD_md_BIST_A_FAIL_md_bist_a_fail_1_shift
#define  md_BIST_A_FAIL_md_bist_a_fail_0_shift                  MD_md_BIST_A_FAIL_md_bist_a_fail_0_shift
#define  md_BIST_A_FAIL_md_bist_a_fail_1_mask                   MD_md_BIST_A_FAIL_md_bist_a_fail_1_mask
#define  md_BIST_A_FAIL_md_bist_a_fail_0_mask                   MD_md_BIST_A_FAIL_md_bist_a_fail_0_mask
#define  md_BIST_A_FAIL_md_bist_a_fail_1(data)                  MD_md_BIST_A_FAIL_md_bist_a_fail_1(data)
#define  md_BIST_A_FAIL_md_bist_a_fail_0(data)                  MD_md_BIST_A_FAIL_md_bist_a_fail_0(data)
#define  md_BIST_A_FAIL_get_md_bist_a_fail_1(data)              MD_md_BIST_A_FAIL_get_md_bist_a_fail_1(data)
#define  md_BIST_A_FAIL_get_md_bist_a_fail_0(data)              MD_md_BIST_A_FAIL_get_md_bist_a_fail_0(data)

#define  md_DRF_MODE                                            MD_md_DRF_MODE
#define  md_DRF_MODE_reg_addr                                   MD_md_DRF_MODE_reg_addr
#define  md_DRF_MODE_reg                                        MD_md_DRF_MODE_reg
#define  md_DRF_MODE_inst_addr                                  MD_md_DRF_MODE_inst_addr
#define  set_md_DRF_MODE_reg(data)                              set_MD_md_DRF_MODE_reg(data)
#define  get_md_DRF_MODE_reg                                    get_MD_md_DRF_MODE_reg
#define  md_DRF_MODE_md_drf_mode_a_2p_shift                     MD_md_DRF_MODE_md_drf_mode_a_2p_shift
#define  md_DRF_MODE_md_drf_mode_a_shift                        MD_md_DRF_MODE_md_drf_mode_a_shift
#define  md_DRF_MODE_md_drf_mode_a_2p_mask                      MD_md_DRF_MODE_md_drf_mode_a_2p_mask
#define  md_DRF_MODE_md_drf_mode_a_mask                         MD_md_DRF_MODE_md_drf_mode_a_mask
#define  md_DRF_MODE_md_drf_mode_a_2p(data)                     MD_md_DRF_MODE_md_drf_mode_a_2p(data)
#define  md_DRF_MODE_md_drf_mode_a(data)                        MD_md_DRF_MODE_md_drf_mode_a(data)
#define  md_DRF_MODE_get_md_drf_mode_a_2p(data)                 MD_md_DRF_MODE_get_md_drf_mode_a_2p(data)
#define  md_DRF_MODE_get_md_drf_mode_a(data)                    MD_md_DRF_MODE_get_md_drf_mode_a(data)

#define  md_DRF_RESUME                                          MD_md_DRF_RESUME
#define  md_DRF_RESUME_reg_addr                                 MD_md_DRF_RESUME_reg_addr
#define  md_DRF_RESUME_reg                                      MD_md_DRF_RESUME_reg
#define  md_DRF_RESUME_inst_addr                                MD_md_DRF_RESUME_inst_addr
#define  set_md_DRF_RESUME_reg(data)                            set_MD_md_DRF_RESUME_reg(data)
#define  get_md_DRF_RESUME_reg                                  get_MD_md_DRF_RESUME_reg
#define  md_DRF_RESUME_md_drf_resume_a_2p_shift                 MD_md_DRF_RESUME_md_drf_resume_a_2p_shift
#define  md_DRF_RESUME_md_drf_resume_a_shift                    MD_md_DRF_RESUME_md_drf_resume_a_shift
#define  md_DRF_RESUME_md_drf_resume_a_2p_mask                  MD_md_DRF_RESUME_md_drf_resume_a_2p_mask
#define  md_DRF_RESUME_md_drf_resume_a_mask                     MD_md_DRF_RESUME_md_drf_resume_a_mask
#define  md_DRF_RESUME_md_drf_resume_a_2p(data)                 MD_md_DRF_RESUME_md_drf_resume_a_2p(data)
#define  md_DRF_RESUME_md_drf_resume_a(data)                    MD_md_DRF_RESUME_md_drf_resume_a(data)
#define  md_DRF_RESUME_get_md_drf_resume_a_2p(data)             MD_md_DRF_RESUME_get_md_drf_resume_a_2p(data)
#define  md_DRF_RESUME_get_md_drf_resume_a(data)                MD_md_DRF_RESUME_get_md_drf_resume_a(data)

#define  md_DRF_DONE                                            MD_md_DRF_DONE
#define  md_DRF_DONE_reg_addr                                   MD_md_DRF_DONE_reg_addr
#define  md_DRF_DONE_reg                                        MD_md_DRF_DONE_reg
#define  md_DRF_DONE_inst_addr                                  MD_md_DRF_DONE_inst_addr
#define  set_md_DRF_DONE_reg(data)                              set_MD_md_DRF_DONE_reg(data)
#define  get_md_DRF_DONE_reg                                    get_MD_md_DRF_DONE_reg
#define  md_DRF_DONE_md_drf_done_a_2p_shift                     MD_md_DRF_DONE_md_drf_done_a_2p_shift
#define  md_DRF_DONE_md_drf_done_a_shift                        MD_md_DRF_DONE_md_drf_done_a_shift
#define  md_DRF_DONE_md_drf_done_a_2p_mask                      MD_md_DRF_DONE_md_drf_done_a_2p_mask
#define  md_DRF_DONE_md_drf_done_a_mask                         MD_md_DRF_DONE_md_drf_done_a_mask
#define  md_DRF_DONE_md_drf_done_a_2p(data)                     MD_md_DRF_DONE_md_drf_done_a_2p(data)
#define  md_DRF_DONE_md_drf_done_a(data)                        MD_md_DRF_DONE_md_drf_done_a(data)
#define  md_DRF_DONE_get_md_drf_done_a_2p(data)                 MD_md_DRF_DONE_get_md_drf_done_a_2p(data)
#define  md_DRF_DONE_get_md_drf_done_a(data)                    MD_md_DRF_DONE_get_md_drf_done_a(data)

#define  md_DRF_PAUSE                                           MD_md_DRF_PAUSE
#define  md_DRF_PAUSE_reg_addr                                  MD_md_DRF_PAUSE_reg_addr
#define  md_DRF_PAUSE_reg                                       MD_md_DRF_PAUSE_reg
#define  md_DRF_PAUSE_inst_addr                                 MD_md_DRF_PAUSE_inst_addr
#define  set_md_DRF_PAUSE_reg(data)                             set_MD_md_DRF_PAUSE_reg(data)
#define  get_md_DRF_PAUSE_reg                                   get_MD_md_DRF_PAUSE_reg
#define  md_DRF_PAUSE_md_drf_pause_a_2p_shift                   MD_md_DRF_PAUSE_md_drf_pause_a_2p_shift
#define  md_DRF_PAUSE_md_drf_pause_a_shift                      MD_md_DRF_PAUSE_md_drf_pause_a_shift
#define  md_DRF_PAUSE_md_drf_pause_a_2p_mask                    MD_md_DRF_PAUSE_md_drf_pause_a_2p_mask
#define  md_DRF_PAUSE_md_drf_pause_a_mask                       MD_md_DRF_PAUSE_md_drf_pause_a_mask
#define  md_DRF_PAUSE_md_drf_pause_a_2p(data)                   MD_md_DRF_PAUSE_md_drf_pause_a_2p(data)
#define  md_DRF_PAUSE_md_drf_pause_a(data)                      MD_md_DRF_PAUSE_md_drf_pause_a(data)
#define  md_DRF_PAUSE_get_md_drf_pause_a_2p(data)               MD_md_DRF_PAUSE_get_md_drf_pause_a_2p(data)
#define  md_DRF_PAUSE_get_md_drf_pause_a(data)                  MD_md_DRF_PAUSE_get_md_drf_pause_a(data)

#define  md_DRF_A_FAIL                                          MD_md_DRF_A_FAIL
#define  md_DRF_A_FAIL_reg_addr                                 MD_md_DRF_A_FAIL_reg_addr
#define  md_DRF_A_FAIL_reg                                      MD_md_DRF_A_FAIL_reg
#define  md_DRF_A_FAIL_inst_addr                                MD_md_DRF_A_FAIL_inst_addr
#define  set_md_DRF_A_FAIL_reg(data)                            set_MD_md_DRF_A_FAIL_reg(data)
#define  get_md_DRF_A_FAIL_reg                                  get_MD_md_DRF_A_FAIL_reg
#define  md_DRF_A_FAIL_md_drf_a_fail_1_shift                    MD_md_DRF_A_FAIL_md_drf_a_fail_1_shift
#define  md_DRF_A_FAIL_md_drf_a_fail_0_shift                    MD_md_DRF_A_FAIL_md_drf_a_fail_0_shift
#define  md_DRF_A_FAIL_md_drf_a_fail_1_mask                     MD_md_DRF_A_FAIL_md_drf_a_fail_1_mask
#define  md_DRF_A_FAIL_md_drf_a_fail_0_mask                     MD_md_DRF_A_FAIL_md_drf_a_fail_0_mask
#define  md_DRF_A_FAIL_md_drf_a_fail_1(data)                    MD_md_DRF_A_FAIL_md_drf_a_fail_1(data)
#define  md_DRF_A_FAIL_md_drf_a_fail_0(data)                    MD_md_DRF_A_FAIL_md_drf_a_fail_0(data)
#define  md_DRF_A_FAIL_get_md_drf_a_fail_1(data)                MD_md_DRF_A_FAIL_get_md_drf_a_fail_1(data)
#define  md_DRF_A_FAIL_get_md_drf_a_fail_0(data)                MD_md_DRF_A_FAIL_get_md_drf_a_fail_0(data)

#define  bist_dvs                                               MD_bist_dvs
#define  bist_dvs_reg_addr                                      MD_bist_dvs_reg_addr
#define  bist_dvs_reg                                           MD_bist_dvs_reg
#define  bist_dvs_inst_addr                                     MD_bist_dvs_inst_addr
#define  set_bist_dvs_reg(data)                                 set_MD_bist_dvs_reg(data)
#define  get_bist_dvs_reg                                       get_MD_bist_dvs_reg
#define  bist_dvs_testrwm_0_shift                               MD_bist_dvs_testrwm_0_shift
#define  bist_dvs_dvse_1_shift                                  MD_bist_dvs_dvse_1_shift
#define  bist_dvs_dvs_1_shift                                   MD_bist_dvs_dvs_1_shift
#define  bist_dvs_dvse_0_shift                                  MD_bist_dvs_dvse_0_shift
#define  bist_dvs_dvs_0_shift                                   MD_bist_dvs_dvs_0_shift
#define  bist_dvs_testrwm_0_mask                                MD_bist_dvs_testrwm_0_mask
#define  bist_dvs_dvse_1_mask                                   MD_bist_dvs_dvse_1_mask
#define  bist_dvs_dvs_1_mask                                    MD_bist_dvs_dvs_1_mask
#define  bist_dvs_dvse_0_mask                                   MD_bist_dvs_dvse_0_mask
#define  bist_dvs_dvs_0_mask                                    MD_bist_dvs_dvs_0_mask
#define  bist_dvs_testrwm_0(data)                               MD_bist_dvs_testrwm_0(data)
#define  bist_dvs_dvse_1(data)                                  MD_bist_dvs_dvse_1(data)
#define  bist_dvs_dvs_1(data)                                   MD_bist_dvs_dvs_1(data)
#define  bist_dvs_dvse_0(data)                                  MD_bist_dvs_dvse_0(data)
#define  bist_dvs_dvs_0(data)                                   MD_bist_dvs_dvs_0(data)
#define  bist_dvs_get_testrwm_0(data)                           MD_bist_dvs_get_testrwm_0(data)
#define  bist_dvs_get_dvse_1(data)                              MD_bist_dvs_get_dvse_1(data)
#define  bist_dvs_get_dvs_1(data)                               MD_bist_dvs_get_dvs_1(data)
#define  bist_dvs_get_dvse_0(data)                              MD_bist_dvs_get_dvse_0(data)
#define  bist_dvs_get_dvs_0(data)                               MD_bist_dvs_get_dvs_0(data)

#define  MD_REG_MODE                                            MD_MD_REG_MODE
#define  MD_REG_MODE_reg_addr                                   MD_MD_REG_MODE_reg_addr
#define  MD_REG_MODE_reg                                        MD_MD_REG_MODE_reg
#define  MD_REG_MODE_inst_addr                                  MD_MD_REG_MODE_inst_addr
#define  set_MD_REG_MODE_reg(data)                              set_MD_MD_REG_MODE_reg(data)
#define  get_MD_REG_MODE_reg                                    get_MD_MD_REG_MODE_reg
#define  MD_REG_MODE_reg_mode_shift                             MD_MD_REG_MODE_reg_mode_shift
#define  MD_REG_MODE_reg_mode_mask                              MD_MD_REG_MODE_reg_mode_mask
#define  MD_REG_MODE_reg_mode(data)                             MD_MD_REG_MODE_reg_mode(data)
#define  MD_REG_MODE_get_reg_mode(data)                         MD_MD_REG_MODE_get_reg_mode(data)

#define  MD_REG_CTRL                                            MD_MD_REG_CTRL
#define  MD_REG_CTRL_reg_addr                                   MD_MD_REG_CTRL_reg_addr
#define  MD_REG_CTRL_reg                                        MD_MD_REG_CTRL_reg
#define  MD_REG_CTRL_inst_addr                                  MD_MD_REG_CTRL_inst_addr
#define  set_MD_REG_CTRL_reg(data)                              set_MD_MD_REG_CTRL_reg(data)
#define  get_MD_REG_CTRL_reg                                    get_MD_MD_REG_CTRL_reg
#define  MD_REG_CTRL_reg_poll_shift                             MD_MD_REG_CTRL_reg_poll_shift
#define  MD_REG_CTRL_loop_shift                                 MD_MD_REG_CTRL_loop_shift
#define  MD_REG_CTRL_reg_poll_mask                              MD_MD_REG_CTRL_reg_poll_mask
#define  MD_REG_CTRL_loop_mask                                  MD_MD_REG_CTRL_loop_mask
#define  MD_REG_CTRL_reg_poll(data)                             MD_MD_REG_CTRL_reg_poll(data)
#define  MD_REG_CTRL_loop(data)                                 MD_MD_REG_CTRL_loop(data)
#define  MD_REG_CTRL_get_reg_poll(data)                         MD_MD_REG_CTRL_get_reg_poll(data)
#define  MD_REG_CTRL_get_loop(data)                             MD_MD_REG_CTRL_get_loop(data)

#define  MD_REG_CMD1                                            MD_MD_REG_CMD1
#define  MD_REG_CMD1_reg_addr                                   MD_MD_REG_CMD1_reg_addr
#define  MD_REG_CMD1_reg                                        MD_MD_REG_CMD1_reg
#define  MD_REG_CMD1_inst_addr                                  MD_MD_REG_CMD1_inst_addr
#define  set_MD_REG_CMD1_reg(data)                              set_MD_MD_REG_CMD1_reg(data)
#define  get_MD_REG_CMD1_reg                                    get_MD_MD_REG_CMD1_reg
#define  MD_REG_CMD1_cmd_word1_shift                            MD_MD_REG_CMD1_cmd_word1_shift
#define  MD_REG_CMD1_cmd_word1_mask                             MD_MD_REG_CMD1_cmd_word1_mask
#define  MD_REG_CMD1_cmd_word1(data)                            MD_MD_REG_CMD1_cmd_word1(data)
#define  MD_REG_CMD1_get_cmd_word1(data)                        MD_MD_REG_CMD1_get_cmd_word1(data)

#define  MD_REG_CMD2                                            MD_MD_REG_CMD2
#define  MD_REG_CMD2_reg_addr                                   MD_MD_REG_CMD2_reg_addr
#define  MD_REG_CMD2_reg                                        MD_MD_REG_CMD2_reg
#define  MD_REG_CMD2_inst_addr                                  MD_MD_REG_CMD2_inst_addr
#define  set_MD_REG_CMD2_reg(data)                              set_MD_MD_REG_CMD2_reg(data)
#define  get_MD_REG_CMD2_reg                                    get_MD_MD_REG_CMD2_reg
#define  MD_REG_CMD2_cmd_word2_shift                            MD_MD_REG_CMD2_cmd_word2_shift
#define  MD_REG_CMD2_cmd_word2_mask                             MD_MD_REG_CMD2_cmd_word2_mask
#define  MD_REG_CMD2_cmd_word2(data)                            MD_MD_REG_CMD2_cmd_word2(data)
#define  MD_REG_CMD2_get_cmd_word2(data)                        MD_MD_REG_CMD2_get_cmd_word2(data)

#define  MD_REG_CMD3                                            MD_MD_REG_CMD3
#define  MD_REG_CMD3_reg_addr                                   MD_MD_REG_CMD3_reg_addr
#define  MD_REG_CMD3_reg                                        MD_MD_REG_CMD3_reg
#define  MD_REG_CMD3_inst_addr                                  MD_MD_REG_CMD3_inst_addr
#define  set_MD_REG_CMD3_reg(data)                              set_MD_MD_REG_CMD3_reg(data)
#define  get_MD_REG_CMD3_reg                                    get_MD_MD_REG_CMD3_reg
#define  MD_REG_CMD3_cmd_word3_shift                            MD_MD_REG_CMD3_cmd_word3_shift
#define  MD_REG_CMD3_cmd_word3_mask                             MD_MD_REG_CMD3_cmd_word3_mask
#define  MD_REG_CMD3_cmd_word3(data)                            MD_MD_REG_CMD3_cmd_word3(data)
#define  MD_REG_CMD3_get_cmd_word3(data)                        MD_MD_REG_CMD3_get_cmd_word3(data)

#define  MD_REG_CMD4                                            MD_MD_REG_CMD4
#define  MD_REG_CMD4_reg_addr                                   MD_MD_REG_CMD4_reg_addr
#define  MD_REG_CMD4_reg                                        MD_MD_REG_CMD4_reg
#define  MD_REG_CMD4_inst_addr                                  MD_MD_REG_CMD4_inst_addr
#define  set_MD_REG_CMD4_reg(data)                              set_MD_MD_REG_CMD4_reg(data)
#define  get_MD_REG_CMD4_reg                                    get_MD_MD_REG_CMD4_reg
#define  MD_REG_CMD4_cmd_word4_shift                            MD_MD_REG_CMD4_cmd_word4_shift
#define  MD_REG_CMD4_cmd_word4_mask                             MD_MD_REG_CMD4_cmd_word4_mask
#define  MD_REG_CMD4_cmd_word4(data)                            MD_MD_REG_CMD4_cmd_word4(data)
#define  MD_REG_CMD4_get_cmd_word4(data)                        MD_MD_REG_CMD4_get_cmd_word4(data)

#define  MD_W_CRC_CTRL                                          MD_MD_W_CRC_CTRL
#define  MD_W_CRC_CTRL_reg_addr                                 MD_MD_W_CRC_CTRL_reg_addr
#define  MD_W_CRC_CTRL_reg                                      MD_MD_W_CRC_CTRL_reg
#define  MD_W_CRC_CTRL_inst_addr                                MD_MD_W_CRC_CTRL_inst_addr
#define  set_MD_W_CRC_CTRL_reg(data)                            set_MD_MD_W_CRC_CTRL_reg(data)
#define  get_MD_W_CRC_CTRL_reg                                  get_MD_MD_W_CRC_CTRL_reg
#define  MD_W_CRC_CTRL_auto_trigger_shift                       MD_MD_W_CRC_CTRL_auto_trigger_shift
#define  MD_W_CRC_CTRL_const_ascending_value_shift              MD_MD_W_CRC_CTRL_const_ascending_value_shift
#define  MD_W_CRC_CTRL_const_ascending_byte_shift               MD_MD_W_CRC_CTRL_const_ascending_byte_shift
#define  MD_W_CRC_CTRL_crc_const_ascending_mode_shift           MD_MD_W_CRC_CTRL_crc_const_ascending_mode_shift
#define  MD_W_CRC_CTRL_crc_data_ctrl_shift                      MD_MD_W_CRC_CTRL_crc_data_ctrl_shift
#define  MD_W_CRC_CTRL_w_crc_start_shift                        MD_MD_W_CRC_CTRL_w_crc_start_shift
#define  MD_W_CRC_CTRL_w_crc_conti_shift                        MD_MD_W_CRC_CTRL_w_crc_conti_shift
#define  MD_W_CRC_CTRL_auto_trigger_mask                        MD_MD_W_CRC_CTRL_auto_trigger_mask
#define  MD_W_CRC_CTRL_const_ascending_value_mask               MD_MD_W_CRC_CTRL_const_ascending_value_mask
#define  MD_W_CRC_CTRL_const_ascending_byte_mask                MD_MD_W_CRC_CTRL_const_ascending_byte_mask
#define  MD_W_CRC_CTRL_crc_const_ascending_mode_mask            MD_MD_W_CRC_CTRL_crc_const_ascending_mode_mask
#define  MD_W_CRC_CTRL_crc_data_ctrl_mask                       MD_MD_W_CRC_CTRL_crc_data_ctrl_mask
#define  MD_W_CRC_CTRL_w_crc_start_mask                         MD_MD_W_CRC_CTRL_w_crc_start_mask
#define  MD_W_CRC_CTRL_w_crc_conti_mask                         MD_MD_W_CRC_CTRL_w_crc_conti_mask
#define  MD_W_CRC_CTRL_auto_trigger(data)                       MD_MD_W_CRC_CTRL_auto_trigger(data)
#define  MD_W_CRC_CTRL_const_ascending_value(data)              MD_MD_W_CRC_CTRL_const_ascending_value(data)
#define  MD_W_CRC_CTRL_const_ascending_byte(data)               MD_MD_W_CRC_CTRL_const_ascending_byte(data)
#define  MD_W_CRC_CTRL_crc_const_ascending_mode(data)           MD_MD_W_CRC_CTRL_crc_const_ascending_mode(data)
#define  MD_W_CRC_CTRL_crc_data_ctrl(data)                      MD_MD_W_CRC_CTRL_crc_data_ctrl(data)
#define  MD_W_CRC_CTRL_w_crc_start(data)                        MD_MD_W_CRC_CTRL_w_crc_start(data)
#define  MD_W_CRC_CTRL_w_crc_conti(data)                        MD_MD_W_CRC_CTRL_w_crc_conti(data)
#define  MD_W_CRC_CTRL_get_auto_trigger(data)                   MD_MD_W_CRC_CTRL_get_auto_trigger(data)
#define  MD_W_CRC_CTRL_get_const_ascending_value(data)          MD_MD_W_CRC_CTRL_get_const_ascending_value(data)
#define  MD_W_CRC_CTRL_get_const_ascending_byte(data)           MD_MD_W_CRC_CTRL_get_const_ascending_byte(data)
#define  MD_W_CRC_CTRL_get_crc_const_ascending_mode(data)       MD_MD_W_CRC_CTRL_get_crc_const_ascending_mode(data)
#define  MD_W_CRC_CTRL_get_crc_data_ctrl(data)                  MD_MD_W_CRC_CTRL_get_crc_data_ctrl(data)
#define  MD_W_CRC_CTRL_get_w_crc_start(data)                    MD_MD_W_CRC_CTRL_get_w_crc_start(data)
#define  MD_W_CRC_CTRL_get_w_crc_conti(data)                    MD_MD_W_CRC_CTRL_get_w_crc_conti(data)

#define  MD_W_CRC_MASK1                                         MD_MD_W_CRC_MASK1
#define  MD_W_CRC_MASK1_reg_addr                                MD_MD_W_CRC_MASK1_reg_addr
#define  MD_W_CRC_MASK1_reg                                     MD_MD_W_CRC_MASK1_reg
#define  MD_W_CRC_MASK1_inst_addr                               MD_MD_W_CRC_MASK1_inst_addr
#define  set_MD_W_CRC_MASK1_reg(data)                           set_MD_MD_W_CRC_MASK1_reg(data)
#define  get_MD_W_CRC_MASK1_reg                                 get_MD_MD_W_CRC_MASK1_reg
#define  MD_W_CRC_MASK1_w_crc_mask1_shift                       MD_MD_W_CRC_MASK1_w_crc_mask1_shift
#define  MD_W_CRC_MASK1_w_crc_mask1_mask                        MD_MD_W_CRC_MASK1_w_crc_mask1_mask
#define  MD_W_CRC_MASK1_w_crc_mask1(data)                       MD_MD_W_CRC_MASK1_w_crc_mask1(data)
#define  MD_W_CRC_MASK1_get_w_crc_mask1(data)                   MD_MD_W_CRC_MASK1_get_w_crc_mask1(data)

#define  MD_W_CRC_MASK2                                         MD_MD_W_CRC_MASK2
#define  MD_W_CRC_MASK2_reg_addr                                MD_MD_W_CRC_MASK2_reg_addr
#define  MD_W_CRC_MASK2_reg                                     MD_MD_W_CRC_MASK2_reg
#define  MD_W_CRC_MASK2_inst_addr                               MD_MD_W_CRC_MASK2_inst_addr
#define  set_MD_W_CRC_MASK2_reg(data)                           set_MD_MD_W_CRC_MASK2_reg(data)
#define  get_MD_W_CRC_MASK2_reg                                 get_MD_MD_W_CRC_MASK2_reg
#define  MD_W_CRC_MASK2_w_crc_mask2_shift                       MD_MD_W_CRC_MASK2_w_crc_mask2_shift
#define  MD_W_CRC_MASK2_w_crc_mask2_mask                        MD_MD_W_CRC_MASK2_w_crc_mask2_mask
#define  MD_W_CRC_MASK2_w_crc_mask2(data)                       MD_MD_W_CRC_MASK2_w_crc_mask2(data)
#define  MD_W_CRC_MASK2_get_w_crc_mask2(data)                   MD_MD_W_CRC_MASK2_get_w_crc_mask2(data)

#define  MD_W_CRC_RESULT                                        MD_MD_W_CRC_RESULT
#define  MD_W_CRC_RESULT_reg_addr                               MD_MD_W_CRC_RESULT_reg_addr
#define  MD_W_CRC_RESULT_reg                                    MD_MD_W_CRC_RESULT_reg
#define  MD_W_CRC_RESULT_inst_addr                              MD_MD_W_CRC_RESULT_inst_addr
#define  set_MD_W_CRC_RESULT_reg(data)                          set_MD_MD_W_CRC_RESULT_reg(data)
#define  get_MD_W_CRC_RESULT_reg                                get_MD_MD_W_CRC_RESULT_reg
#define  MD_W_CRC_RESULT_w_crc_result_shift                     MD_MD_W_CRC_RESULT_w_crc_result_shift
#define  MD_W_CRC_RESULT_w_crc_result_mask                      MD_MD_W_CRC_RESULT_w_crc_result_mask
#define  MD_W_CRC_RESULT_w_crc_result(data)                     MD_MD_W_CRC_RESULT_w_crc_result(data)
#define  MD_W_CRC_RESULT_get_w_crc_result(data)                 MD_MD_W_CRC_RESULT_get_w_crc_result(data)

#define  MD_R_CRC_CTRL                                          MD_MD_R_CRC_CTRL
#define  MD_R_CRC_CTRL_reg_addr                                 MD_MD_R_CRC_CTRL_reg_addr
#define  MD_R_CRC_CTRL_reg                                      MD_MD_R_CRC_CTRL_reg
#define  MD_R_CRC_CTRL_inst_addr                                MD_MD_R_CRC_CTRL_inst_addr
#define  set_MD_R_CRC_CTRL_reg(data)                            set_MD_MD_R_CRC_CTRL_reg(data)
#define  get_MD_R_CRC_CTRL_reg                                  get_MD_MD_R_CRC_CTRL_reg
#define  MD_R_CRC_CTRL_auto_cmp_en_shift                        MD_MD_R_CRC_CTRL_auto_cmp_en_shift
#define  MD_R_CRC_CTRL_r_crc_start_shift                        MD_MD_R_CRC_CTRL_r_crc_start_shift
#define  MD_R_CRC_CTRL_r_crc_conti_shift                        MD_MD_R_CRC_CTRL_r_crc_conti_shift
#define  MD_R_CRC_CTRL_auto_cmp_en_mask                         MD_MD_R_CRC_CTRL_auto_cmp_en_mask
#define  MD_R_CRC_CTRL_r_crc_start_mask                         MD_MD_R_CRC_CTRL_r_crc_start_mask
#define  MD_R_CRC_CTRL_r_crc_conti_mask                         MD_MD_R_CRC_CTRL_r_crc_conti_mask
#define  MD_R_CRC_CTRL_auto_cmp_en(data)                        MD_MD_R_CRC_CTRL_auto_cmp_en(data)
#define  MD_R_CRC_CTRL_r_crc_start(data)                        MD_MD_R_CRC_CTRL_r_crc_start(data)
#define  MD_R_CRC_CTRL_r_crc_conti(data)                        MD_MD_R_CRC_CTRL_r_crc_conti(data)
#define  MD_R_CRC_CTRL_get_auto_cmp_en(data)                    MD_MD_R_CRC_CTRL_get_auto_cmp_en(data)
#define  MD_R_CRC_CTRL_get_r_crc_start(data)                    MD_MD_R_CRC_CTRL_get_r_crc_start(data)
#define  MD_R_CRC_CTRL_get_r_crc_conti(data)                    MD_MD_R_CRC_CTRL_get_r_crc_conti(data)

#define  MD_R_CRC_MASK1                                         MD_MD_R_CRC_MASK1
#define  MD_R_CRC_MASK1_reg_addr                                MD_MD_R_CRC_MASK1_reg_addr
#define  MD_R_CRC_MASK1_reg                                     MD_MD_R_CRC_MASK1_reg
#define  MD_R_CRC_MASK1_inst_addr                               MD_MD_R_CRC_MASK1_inst_addr
#define  set_MD_R_CRC_MASK1_reg(data)                           set_MD_MD_R_CRC_MASK1_reg(data)
#define  get_MD_R_CRC_MASK1_reg                                 get_MD_MD_R_CRC_MASK1_reg
#define  MD_R_CRC_MASK1_r_crc_mask1_shift                       MD_MD_R_CRC_MASK1_r_crc_mask1_shift
#define  MD_R_CRC_MASK1_r_crc_mask1_mask                        MD_MD_R_CRC_MASK1_r_crc_mask1_mask
#define  MD_R_CRC_MASK1_r_crc_mask1(data)                       MD_MD_R_CRC_MASK1_r_crc_mask1(data)
#define  MD_R_CRC_MASK1_get_r_crc_mask1(data)                   MD_MD_R_CRC_MASK1_get_r_crc_mask1(data)

#define  MD_R_CRC_MASK2                                         MD_MD_R_CRC_MASK2
#define  MD_R_CRC_MASK2_reg_addr                                MD_MD_R_CRC_MASK2_reg_addr
#define  MD_R_CRC_MASK2_reg                                     MD_MD_R_CRC_MASK2_reg
#define  MD_R_CRC_MASK2_inst_addr                               MD_MD_R_CRC_MASK2_inst_addr
#define  set_MD_R_CRC_MASK2_reg(data)                           set_MD_MD_R_CRC_MASK2_reg(data)
#define  get_MD_R_CRC_MASK2_reg                                 get_MD_MD_R_CRC_MASK2_reg
#define  MD_R_CRC_MASK2_r_crc_mask2_shift                       MD_MD_R_CRC_MASK2_r_crc_mask2_shift
#define  MD_R_CRC_MASK2_r_crc_mask2_mask                        MD_MD_R_CRC_MASK2_r_crc_mask2_mask
#define  MD_R_CRC_MASK2_r_crc_mask2(data)                       MD_MD_R_CRC_MASK2_r_crc_mask2(data)
#define  MD_R_CRC_MASK2_get_r_crc_mask2(data)                   MD_MD_R_CRC_MASK2_get_r_crc_mask2(data)

#define  MD_DES_CRC                                             MD_MD_DES_CRC
#define  MD_DES_CRC_reg_addr                                    MD_MD_DES_CRC_reg_addr
#define  MD_DES_CRC_reg                                         MD_MD_DES_CRC_reg
#define  MD_DES_CRC_inst_addr                                   MD_MD_DES_CRC_inst_addr
#define  set_MD_DES_CRC_reg(data)                               set_MD_MD_DES_CRC_reg(data)
#define  get_MD_DES_CRC_reg                                     get_MD_MD_DES_CRC_reg
#define  MD_DES_CRC_des_crc_result_shift                        MD_MD_DES_CRC_des_crc_result_shift
#define  MD_DES_CRC_des_crc_result_mask                         MD_MD_DES_CRC_des_crc_result_mask
#define  MD_DES_CRC_des_crc_result(data)                        MD_MD_DES_CRC_des_crc_result(data)
#define  MD_DES_CRC_get_des_crc_result(data)                    MD_MD_DES_CRC_get_des_crc_result(data)

#define  MD_R_CRC_RESULT                                        MD_MD_R_CRC_RESULT
#define  MD_R_CRC_RESULT_reg_addr                               MD_MD_R_CRC_RESULT_reg_addr
#define  MD_R_CRC_RESULT_reg                                    MD_MD_R_CRC_RESULT_reg
#define  MD_R_CRC_RESULT_inst_addr                              MD_MD_R_CRC_RESULT_inst_addr
#define  set_MD_R_CRC_RESULT_reg(data)                          set_MD_MD_R_CRC_RESULT_reg(data)
#define  get_MD_R_CRC_RESULT_reg                                get_MD_MD_R_CRC_RESULT_reg
#define  MD_R_CRC_RESULT_r_crc_result_shift                     MD_MD_R_CRC_RESULT_r_crc_result_shift
#define  MD_R_CRC_RESULT_r_crc_result_mask                      MD_MD_R_CRC_RESULT_r_crc_result_mask
#define  MD_R_CRC_RESULT_r_crc_result(data)                     MD_MD_R_CRC_RESULT_r_crc_result(data)
#define  MD_R_CRC_RESULT_get_r_crc_result(data)                 MD_MD_R_CRC_RESULT_get_r_crc_result(data)

#define  MD_CRC_STATUS                                          MD_MD_CRC_STATUS
#define  MD_CRC_STATUS_reg_addr                                 MD_MD_CRC_STATUS_reg_addr
#define  MD_CRC_STATUS_reg                                      MD_MD_CRC_STATUS_reg
#define  MD_CRC_STATUS_inst_addr                                MD_MD_CRC_STATUS_inst_addr
#define  set_MD_CRC_STATUS_reg(data)                            set_MD_MD_CRC_STATUS_reg(data)
#define  get_MD_CRC_STATUS_reg                                  get_MD_MD_CRC_STATUS_reg
#define  MD_CRC_STATUS_cmd_addr_err_shift                       MD_MD_CRC_STATUS_cmd_addr_err_shift
#define  MD_CRC_STATUS_crc_err_cnt_shift                        MD_MD_CRC_STATUS_crc_err_cnt_shift
#define  MD_CRC_STATUS_cmd_addr_err_mask                        MD_MD_CRC_STATUS_cmd_addr_err_mask
#define  MD_CRC_STATUS_crc_err_cnt_mask                         MD_MD_CRC_STATUS_crc_err_cnt_mask
#define  MD_CRC_STATUS_cmd_addr_err(data)                       MD_MD_CRC_STATUS_cmd_addr_err(data)
#define  MD_CRC_STATUS_crc_err_cnt(data)                        MD_MD_CRC_STATUS_crc_err_cnt(data)
#define  MD_CRC_STATUS_get_cmd_addr_err(data)                   MD_MD_CRC_STATUS_get_cmd_addr_err(data)
#define  MD_CRC_STATUS_get_crc_err_cnt(data)                    MD_MD_CRC_STATUS_get_crc_err_cnt(data)

#define  MD_REG_CMD5                                            MD_MD_REG_CMD5
#define  MD_REG_CMD5_reg_addr                                   MD_MD_REG_CMD5_reg_addr
#define  MD_REG_CMD5_reg                                        MD_MD_REG_CMD5_reg
#define  MD_REG_CMD5_inst_addr                                  MD_MD_REG_CMD5_inst_addr
#define  set_MD_REG_CMD5_reg(data)                              set_MD_MD_REG_CMD5_reg(data)
#define  get_MD_REG_CMD5_reg                                    get_MD_MD_REG_CMD5_reg
#define  MD_REG_CMD5_cmd_word5_shift                            MD_MD_REG_CMD5_cmd_word5_shift
#define  MD_REG_CMD5_cmd_word5_mask                             MD_MD_REG_CMD5_cmd_word5_mask
#define  MD_REG_CMD5_cmd_word5(data)                            MD_MD_REG_CMD5_cmd_word5(data)
#define  MD_REG_CMD5_get_cmd_word5(data)                        MD_MD_REG_CMD5_get_cmd_word5(data)

#define  MD_MULTI_REQ                                           MD_MD_MULTI_REQ
#define  MD_MULTI_REQ_reg_addr                                  MD_MD_MULTI_REQ_reg_addr
#define  MD_MULTI_REQ_reg                                       MD_MD_MULTI_REQ_reg
#define  MD_MULTI_REQ_inst_addr                                 MD_MD_MULTI_REQ_inst_addr
#define  set_MD_MULTI_REQ_reg(data)                             set_MD_MD_MULTI_REQ_reg(data)
#define  get_MD_MULTI_REQ_reg                                   get_MD_MD_MULTI_REQ_reg
#define  MD_MULTI_REQ_cmd_wrap_en_shift                         MD_MD_MULTI_REQ_cmd_wrap_en_shift
#define  MD_MULTI_REQ_multi_req_en_shift                        MD_MD_MULTI_REQ_multi_req_en_shift
#define  MD_MULTI_REQ_cmd_wrap_en_mask                          MD_MD_MULTI_REQ_cmd_wrap_en_mask
#define  MD_MULTI_REQ_multi_req_en_mask                         MD_MD_MULTI_REQ_multi_req_en_mask
#define  MD_MULTI_REQ_cmd_wrap_en(data)                         MD_MD_MULTI_REQ_cmd_wrap_en(data)
#define  MD_MULTI_REQ_multi_req_en(data)                        MD_MD_MULTI_REQ_multi_req_en(data)
#define  MD_MULTI_REQ_get_cmd_wrap_en(data)                     MD_MD_MULTI_REQ_get_cmd_wrap_en(data)
#define  MD_MULTI_REQ_get_multi_req_en(data)                    MD_MD_MULTI_REQ_get_multi_req_en(data)

#define  MD_DBG_PORT                                            MD_MD_DBG_PORT
#define  MD_DBG_PORT_reg_addr                                   MD_MD_DBG_PORT_reg_addr
#define  MD_DBG_PORT_reg                                        MD_MD_DBG_PORT_reg
#define  MD_DBG_PORT_inst_addr                                  MD_MD_DBG_PORT_inst_addr
#define  set_MD_DBG_PORT_reg(data)                              set_MD_MD_DBG_PORT_reg(data)
#define  get_MD_DBG_PORT_reg                                    get_MD_MD_DBG_PORT_reg
#define  MD_DBG_PORT_md_dbg_out1_shift                          MD_MD_DBG_PORT_md_dbg_out1_shift
#define  MD_DBG_PORT_md_dbg_out0_shift                          MD_MD_DBG_PORT_md_dbg_out0_shift
#define  MD_DBG_PORT_md_dbg_out1_mask                           MD_MD_DBG_PORT_md_dbg_out1_mask
#define  MD_DBG_PORT_md_dbg_out0_mask                           MD_MD_DBG_PORT_md_dbg_out0_mask
#define  MD_DBG_PORT_md_dbg_out1(data)                          MD_MD_DBG_PORT_md_dbg_out1(data)
#define  MD_DBG_PORT_md_dbg_out0(data)                          MD_MD_DBG_PORT_md_dbg_out0(data)
#define  MD_DBG_PORT_get_md_dbg_out1(data)                      MD_MD_DBG_PORT_get_md_dbg_out1(data)
#define  MD_DBG_PORT_get_md_dbg_out0(data)                      MD_MD_DBG_PORT_get_md_dbg_out0(data)

#endif /* _RTK_MD_REG_H_ */
