#define D_CHANNEL_MAIN		0
#define D_CHANNEL_SUB		1

#define UZUPTG_VER_DISABLE	0
#define UZUPTG_VER_MAIN		1
#define UZUPTG_VER_SUB		2

#define UZUPTG_VER_RANDOM_DEFAULTSEED	0
#define UZUPTG_VER_RANDOM_CUSTOMSEED	1
#define UZUPTG_VER_COLORBAR_DEFAULT4	2
#define UZUPTG_VER_COLORBAR_DEFAULT8	3
#define UZUPTG_VER_COLORBAR_CUSTOM2		4
#define UZUPTG_VER_COLORBAR_CUSTOM4		5

#define COLOR_SHARP_SHP_CRC_RESULT_VADDR           (0xb802ae44)

