obj-$(CONFIG_RTK_KDRV_RTICE_SYSTEM_TOOL) += rtk_ice-system.o
obj-$(CONFIG_RTK_KDRV_RTICE_IOMEM_TOOL) += rtk_ice-iomem.o
obj-$(CONFIG_RTK_KDRV_RTICE_I2C_TOOL)   += rtk_ice-i2c.o
obj-$(CONFIG_RTK_KDRV_RTICE_ICM_TOOL)   += rtk_ice-icm.o
obj-$(CONFIG_RTK_KDRV_RTICE_AP_TOOL)   += rtk_ice-ap.o rtk_ice_ap_driver.o
obj-$(CONFIG_RTK_KDRV_RTICE_BW_CHECK) += rtk_ice-bw.o
obj-$(CONFIG_RTK_KDRV_RTICE_MC_MEASURE) += rtk_ice_mc_measure.o
obj-$(CONFIG_RTK_KDRV_RTICE_DMA_STATUS) += rtk_ice-dma.o