#ifndef __RTICE_IOMEM_H__
#define __RTICE_IOMEM_H__

#include "../core/rtk_ice.h"


#define RTICE_IOMEM_CMD(x) \
	RTICE_OP_CODE(RTICE_CMD_GROUP_ID_IOMEM, x)
#define RTICE_IOMEM_CMD_NORMAL_READ \
	RTICE_OP_CODE(RTICE_CMD_GROUP_ID_IOMEM, 0)
#define RTICE_IOMEM_CMD_NORMAL_WRITE \
	RTICE_OP_CODE(RTICE_CMD_GROUP_ID_IOMEM, 1)
#define RTICE_IOMEM_CMD_DATA_PORT_READ \
	RTICE_OP_CODE(RTICE_CMD_GROUP_ID_IOMEM, 2)
#define RTICE_IOMEM_CMD_DATA_PORT_WRITE \
	RTICE_OP_CODE(RTICE_CMD_GROUP_ID_IOMEM, 3)
#define RTICE_IOMEM_CMD_MULTI_READ \
	RTICE_OP_CODE(RTICE_CMD_GROUP_ID_IOMEM, 4)
#define RTICE_IOMEM_CMD_MULTI_WRITE \
	RTICE_OP_CODE(RTICE_CMD_GROUP_ID_IOMEM, 5)
#define RTICE_IOMEM_CMD_START_BUS_MONITOR \
	RTICE_OP_CODE(RTICE_CMD_GROUP_ID_IOMEM, 6)
#define RTICE_IOMEM_CMD_STOP_BUS_MONITOR \
	RTICE_OP_CODE(RTICE_CMD_GROUP_ID_IOMEM, 7)

#define RTICE_IOMEM_ERR_INVALID_ADDRESS		RTICE_FUNC_ERR(0)
#define RTICE_IOMEM_ERR_INVALID_LENGTH		RTICE_FUNC_ERR(1)
#define RTICE_IOMEM_ERR_BUS_MONITOR_IS_RUNNING	RTICE_FUNC_ERR(2)
#define RTICE_IOMEM_ERR_CREATE_BUS_MONITOR_THREAD_FAILED \
						RTICE_FUNC_ERR(3)
#define RTICE_IOMEM_ERR_CREATE_BUS_MONITOR_REGISTER_TABLE_FAILED \
							RTICE_FUNC_ERR(4)
#define RTICE_IOMEM_ERR_CREATE_BUS_MONITOR_TIMEOUT RTICE_FUNC_ERR(5)
#define RTICE_IOMEM_ERR_BUS_MONITOR_FAILED	RTICE_FUNC_ERR(6)

#ifdef DEBUG_RTICE_IOMEM
#define RTICE_IOMEM_DEBUG(fmt, args...)   printk(KERN_DEBUG fmt, ##args)
#else	/*  */
#define RTICE_IOMEM_DEBUG(args...)
#endif	/*  */

#endif
