#ifndef __RTICE_ICM_H__
#define __RTICE_ICM_H__

#include "../core/rtk_ice.h"


#define RTICE_ICM_CMD(x) \
	RTICE_OP_CODE(RTICE_CMD_GROUP_ID_ICM, x)
#define RTICE_ICM_READ_TABLE \
	RTICE_OP_CODE(RTICE_CMD_GROUP_ID_ICM, 0)
#define RTICE_ICM_READ_DATA_PACK_NUM \
	RTICE_OP_CODE(RTICE_CMD_GROUP_ID_ICM, 1)
#define RTICE_ICM_READ_DATA_FINISHED \
	RTICE_OP_CODE(RTICE_CMD_GROUP_ID_ICM, 2)
#define RTICE_ICM_WRITE_TABLE \
	RTICE_OP_CODE(RTICE_CMD_GROUP_ID_ICM, 3)
#define RTICE_ICM_WRITE_DATA_PACK_NUM \
	RTICE_OP_CODE(RTICE_CMD_GROUP_ID_ICM, 4)
#define RTICE_ICM_WRITE_DATA_STATUS \
	RTICE_OP_CODE(RTICE_CMD_GROUP_ID_ICM, 5)


#define RTICE_ICM_ERR_ABORT		RTICE_FUNC_ERR(0)
#define RTICE_ICM_ERR_INVALID_CM_TYPE	RTICE_FUNC_ERR(1)
#define RTICE_ICM_ERR_INVALID_CM_ADDR	RTICE_FUNC_ERR(2)
#define RTICE_ICM_ERR_READ_CM_TIMEOUT	RTICE_FUNC_ERR(3)
#define RTICE_ICM_ERR_INVALID_CM_DATA_LENGTH	RTICE_FUNC_ERR(4)

#ifdef DEBUG_RTICE_ICM
#define RTICE_ICM_DEBUG(fmt, args...)   printk(KERN_DEBUG fmt, ##args)
#else	/*  */
#define RTICE_ICM_DEBUG(args...)
#endif	/*  */

#endif
