/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AUDIORPC_SYSTEM_DATA_H_RPCGEN
#define _AUDIORPC_SYSTEM_DATA_H_RPCGEN

#include <RPCBaseDS.h>
#include <AudioRPCBaseDS.h>

#endif /* !_AUDIORPC_SYSTEM_DATA_H_RPCGEN */
