/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SECURERPC_AGENT_H_RPCGEN
#define _SECURERPC_AGENT_H_RPCGEN

#include <RPCstruct.h>

#include "SecureRPC_Agent_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <RPCBaseDS.h>
#include <SecureRPCBaseDS.h>

#define SECURE_AGENT 502
#define VERSION 0

struct REG_STRUCT * SECURE_AGENT_0_register(struct REG_STRUCT *rnode);

#if defined(__STDC__) || defined(__cplusplus)
#define SECURE_RPC_ToSystem_PlayReady_Result 2
extern  HRESULT * SECURE_RPC_ToSystem_PlayReady_Result_0(RPC_tee_rpc_result_t *, CLNT_STRUCT *);
extern  HRESULT * SECURE_RPC_ToSystem_PlayReady_Result_0_svc(RPC_tee_rpc_result_t *, RPC_STRUCT *, HRESULT *);
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
extern  HRESULT * (*p_SECURE_RPC_ToSystem_PlayReady_Result_0_svc)(RPC_tee_rpc_result_t *, RPC_STRUCT *, HRESULT *);
#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
#define SECURE_RPC_ToSystem_GetSetupParameter 4
extern  RPCRES_LONG * SECURE_RPC_ToSystem_GetSetupParameter_0(SECURE_RPC_TOSYSTEM_GET_SETUP_PARAM *, CLNT_STRUCT *);
extern  RPCRES_LONG * SECURE_RPC_ToSystem_GetSetupParameter_0_svc(SECURE_RPC_TOSYSTEM_GET_SETUP_PARAM *, RPC_STRUCT *, RPCRES_LONG *);
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
extern  RPCRES_LONG * (*p_SECURE_RPC_ToSystem_GetSetupParameter_0_svc)(SECURE_RPC_TOSYSTEM_GET_SETUP_PARAM *, RPC_STRUCT *, RPCRES_LONG *);
#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
#define SECURE_RPC_ToSystem_SetParameter 6
extern  HRESULT * SECURE_RPC_ToSystem_SetParameter_0(SECURE_RPC_TOSYSTEM_SET_PARAM *, CLNT_STRUCT *);
extern  HRESULT * SECURE_RPC_ToSystem_SetParameter_0_svc(SECURE_RPC_TOSYSTEM_SET_PARAM *, RPC_STRUCT *, HRESULT *);
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
extern  HRESULT * (*p_SECURE_RPC_ToSystem_SetParameter_0_svc)(SECURE_RPC_TOSYSTEM_SET_PARAM *, RPC_STRUCT *, HRESULT *);
#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
#define SECURE_RPC_ToSystem_SendReadCommand 8
extern  RPCRES_K_S * SECURE_RPC_ToSystem_SendReadCommand_0(SECURE_RPC_TOSYSTEM_SEND_RW *, CLNT_STRUCT *);
extern  RPCRES_K_S * SECURE_RPC_ToSystem_SendReadCommand_0_svc(SECURE_RPC_TOSYSTEM_SEND_RW *, RPC_STRUCT *, RPCRES_K_S *);
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
extern  RPCRES_K_S * (*p_SECURE_RPC_ToSystem_SendReadCommand_0_svc)(SECURE_RPC_TOSYSTEM_SEND_RW *, RPC_STRUCT *, RPCRES_K_S *);
#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
#define SECURE_RPC_ToSystem_SendWriteCommand 10
extern  HRESULT * SECURE_RPC_ToSystem_SendWriteCommand_0(SECURE_RPC_TOSYSTEM_SEND_RW *, CLNT_STRUCT *);
extern  HRESULT * SECURE_RPC_ToSystem_SendWriteCommand_0_svc(SECURE_RPC_TOSYSTEM_SEND_RW *, RPC_STRUCT *, HRESULT *);
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
extern  HRESULT * (*p_SECURE_RPC_ToSystem_SendWriteCommand_0_svc)(SECURE_RPC_TOSYSTEM_SEND_RW *, RPC_STRUCT *, HRESULT *);
#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
#define SECURE_RPC_ToSystem_TvServerControl 12
extern  HRESULT * SECURE_RPC_ToSystem_TvServerControl_0(SECURE_RPC_TOSYSTEM_TVSERVER_CTRL *, CLNT_STRUCT *);
extern  HRESULT * SECURE_RPC_ToSystem_TvServerControl_0_svc(SECURE_RPC_TOSYSTEM_TVSERVER_CTRL *, RPC_STRUCT *, HRESULT *);
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
extern  HRESULT * (*p_SECURE_RPC_ToSystem_TvServerControl_0_svc)(SECURE_RPC_TOSYSTEM_TVSERVER_CTRL *, RPC_STRUCT *, HRESULT *);
#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
#define SECURE_RPC_ToSystem_OsdMsg 14
extern  HRESULT * SECURE_RPC_ToSystem_OsdMsg_0(SECURE_RPC_TOSYSTEM_OSD_MSG *, CLNT_STRUCT *);
extern  HRESULT * SECURE_RPC_ToSystem_OsdMsg_0_svc(SECURE_RPC_TOSYSTEM_OSD_MSG *, RPC_STRUCT *, HRESULT *);
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
extern  HRESULT * (*p_SECURE_RPC_ToSystem_OsdMsg_0_svc)(SECURE_RPC_TOSYSTEM_OSD_MSG *, RPC_STRUCT *, HRESULT *);
#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
#define SECURE_RPC_ToSystem_GetData 16
extern  RPCRES_K_S * SECURE_RPC_ToSystem_GetData_0(SECURE_RPC_TOSYSTEM_SET_PARAM *, CLNT_STRUCT *);
extern  RPCRES_K_S * SECURE_RPC_ToSystem_GetData_0_svc(SECURE_RPC_TOSYSTEM_SET_PARAM *, RPC_STRUCT *, RPCRES_K_S *);
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
extern  RPCRES_K_S * (*p_SECURE_RPC_ToSystem_GetData_0_svc)(SECURE_RPC_TOSYSTEM_SET_PARAM *, RPC_STRUCT *, RPCRES_K_S *);
#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON

#else /* K&R C */
#define SECURE_RPC_ToSystem_PlayReady_Result 2
extern  HRESULT * SECURE_RPC_ToSystem_PlayReady_Result_0();
extern  HRESULT * SECURE_RPC_ToSystem_PlayReady_Result_0_svc();
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
extern  HRESULT * (*p_SECURE_RPC_ToSystem_PlayReady_Result_0_svc)();
#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
#define SECURE_RPC_ToSystem_GetSetupParameter 4
extern  RPCRES_LONG * SECURE_RPC_ToSystem_GetSetupParameter_0();
extern  RPCRES_LONG * SECURE_RPC_ToSystem_GetSetupParameter_0_svc();
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
extern  RPCRES_LONG * (*p_SECURE_RPC_ToSystem_GetSetupParameter_0_svc)();
#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
#define SECURE_RPC_ToSystem_SetParameter 6
extern  HRESULT * SECURE_RPC_ToSystem_SetParameter_0();
extern  HRESULT * SECURE_RPC_ToSystem_SetParameter_0_svc();
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
extern  HRESULT * (*p_SECURE_RPC_ToSystem_SetParameter_0_svc)();
#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
#define SECURE_RPC_ToSystem_SendReadCommand 8
extern  RPCRES_K_S * SECURE_RPC_ToSystem_SendReadCommand_0();
extern  RPCRES_K_S * SECURE_RPC_ToSystem_SendReadCommand_0_svc();
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
extern  RPCRES_K_S * (*p_SECURE_RPC_ToSystem_SendReadCommand_0_svc)();
#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
#define SECURE_RPC_ToSystem_SendWriteCommand 10
extern  HRESULT * SECURE_RPC_ToSystem_SendWriteCommand_0();
extern  HRESULT * SECURE_RPC_ToSystem_SendWriteCommand_0_svc();
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
extern  HRESULT * (*p_SECURE_RPC_ToSystem_SendWriteCommand_0_svc)();
#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
#define SECURE_RPC_ToSystem_TvServerControl 12
extern  HRESULT * SECURE_RPC_ToSystem_TvServerControl_0();
extern  HRESULT * SECURE_RPC_ToSystem_TvServerControl_0_svc();
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
extern  HRESULT * (*p_SECURE_RPC_ToSystem_TvServerControl_0_svc)();
#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
#define SECURE_RPC_ToSystem_OsdMsg 14
extern  HRESULT * SECURE_RPC_ToSystem_OsdMsg_0();
extern  HRESULT * SECURE_RPC_ToSystem_OsdMsg_0_svc();
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
extern  HRESULT * (*p_SECURE_RPC_ToSystem_OsdMsg_0_svc)();
#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
#define SECURE_RPC_ToSystem_GetData 16
extern  RPCRES_K_S * SECURE_RPC_ToSystem_GetData_0();
extern  RPCRES_K_S * SECURE_RPC_ToSystem_GetData_0_svc();
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
extern  RPCRES_K_S * (*p_SECURE_RPC_ToSystem_GetData_0_svc)();
#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_RPC_tee_rpc_result_t (XDR *, RPC_tee_rpc_result_t*);
extern  bool_t xdr_SECURE_RPC_TOSYSTEM_GET_SETUP_PARAM (XDR *, SECURE_RPC_TOSYSTEM_GET_SETUP_PARAM*);
extern  bool_t xdr_SECURE_RPC_TOSYSTEM_SET_PARAM (XDR *, SECURE_RPC_TOSYSTEM_SET_PARAM*);
extern  bool_t xdr_RPCRES_K_S (XDR *, RPCRES_K_S*);
extern  bool_t xdr_SECURE_RPC_TOSYSTEM_SEND_RW (XDR *, SECURE_RPC_TOSYSTEM_SEND_RW*);
extern  bool_t xdr_SECURE_RPC_TOSYSTEM_TVSERVER_CTRL (XDR *, SECURE_RPC_TOSYSTEM_TVSERVER_CTRL*);
extern  bool_t xdr_SECURE_RPC_TOSYSTEM_OSD_MSG (XDR *, SECURE_RPC_TOSYSTEM_OSD_MSG*);

#else /* K&R C */
extern bool_t xdr_RPC_tee_rpc_result_t ();
extern bool_t xdr_SECURE_RPC_TOSYSTEM_GET_SETUP_PARAM ();
extern bool_t xdr_SECURE_RPC_TOSYSTEM_SET_PARAM ();
extern bool_t xdr_RPCRES_K_S ();
extern bool_t xdr_SECURE_RPC_TOSYSTEM_SEND_RW ();
extern bool_t xdr_SECURE_RPC_TOSYSTEM_TVSERVER_CTRL ();
extern bool_t xdr_SECURE_RPC_TOSYSTEM_OSD_MSG ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SECURERPC_AGENT_H_RPCGEN */
