KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/demodcomm

demodcore-objs := foundation.o \
					math_mpi.o \
					self_sec_load_array.o \
					message_func_rtk.o \
					atsc_demod_base.o \
					atsc_demod_rtk.o \
					isdbt_demod_base.o \
					isdbt_demod_rtk.o \
					isdbt_ldr_array.o \
					qam_demod_base.o \
					qam_demod_rtk.o \
					qam_ldr_array.o \
					dvbc_demod_base.o \
					dvbc_demod_rtk.o \
					dvbc_ldr_array.o \
					dvbt_ldr_array.o \
					dvbt2_demod_base.o \
					dvbt2_demod_rtk.o \
					dvbt2_ldr_array.o \
					dvbs_ldr_array.o \
					dvbs2_demod_base.o \
					dvbs2_demod_rtk.o \
					dvbs2_ldr_array.o \
					dvbs2x_ldr_array.o \
					diseqc_rtk.o \
					spec_an_ldr_array.o \
					dtmb_demod_base.o \
					dtmb_demod_rtk.o \
					dtmb_demod_rtk_user.o \
					ifd_new.o \
					ifd_agc.o \
					ifd_cr.o \
					ifd_video.o \
					ifd_table.o \
					ifd_analog.o \

obj-y += demodcore.o 



