/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <AudioRPCBaseDS.h>
#include <rpc_common.h>

bool_t
xdr_AUDIO_DEC_TYPE (XDR *xdrs, AUDIO_DEC_TYPE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_CHANNEL_OUT_INDEX (XDR *xdrs, AUDIO_CHANNEL_OUT_INDEX *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_MODULE_TYPE (XDR *xdrs, AUDIO_MODULE_TYPE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_IO_PIN (XDR *xdrs, AUDIO_IO_PIN *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_BILINGUAL_TYPE (XDR *xdrs, ENUM_AUDIO_BILINGUAL_TYPE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_NIGHTMODE_CFG (XDR *xdrs, ENUM_AUDIO_NIGHTMODE_CFG *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_NIGHTMODE (XDR *xdrs, AUDIO_RPC_NIGHTMODE *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->cfg))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_PP_AGC (XDR *xdrs, AUDIO_RPC_PP_AGC *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->enable))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->gain_max))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->gain_min))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->gain_prev))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->gain_rise))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->gain_drop))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->gain_abrupt_drop))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->judge_sample))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_AGC_TYPE (XDR *xdrs, ENUM_AUDIO_AGC_TYPE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_DAC_SWITCH_CFG (XDR *xdrs, ENUM_AUDIO_DAC_SWITCH_CFG *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_TRUEHD_LOSSLESSMODE_CFG (XDR *xdrs, ENUM_AUDIO_TRUEHD_LOSSLESSMODE_CFG *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_TRUEHD_LOSSLESSMODE (XDR *xdrs, AUDIO_RPC_TRUEHD_LOSSLESSMODE *objp)
{
	 if (!xdr_long (xdrs, &objp->cfg))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_DELAY_DAC_SWITCH_CFG (XDR *xdrs, ENUM_AUDIO_DELAY_DAC_SWITCH_CFG *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_IPT_SRC (XDR *xdrs, ENUM_AUDIO_IPT_SRC *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_BBADC_SRC (XDR *xdrs, ENUM_AUDIO_BBADC_SRC *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_SPDIFI_SRC (XDR *xdrs, ENUM_AUDIO_SPDIFI_SRC *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_I2SI_SRC (XDR *xdrs, ENUM_AUDIO_I2SI_SRC *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_I2SI_ID (XDR *xdrs, ENUM_AUDIO_I2SI_ID *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_I2SI_MODE (XDR *xdrs, ENUM_AUDIO_I2SI_MODE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_I2SI_SYNC (XDR *xdrs, ENUM_AUDIO_I2SI_SYNC *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_BBADC_CLK (XDR *xdrs, ENUM_AUDIO_BBADC_CLK *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_IPT_SRC (XDR *xdrs, AUDIO_IPT_SRC *objp)
{
	 if (!xdr_vector (xdrs, (char *)objp->focus, 4,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mux_in))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_DEC_BITSTREAM_BUFFER (XDR *xdrs, AUDIO_RPC_DEC_BITSTREAM_BUFFER *objp)
{
	 if (!xdr_long (xdrs, &objp->bsBase))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->bsSize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_FORMAT_INFO (XDR *xdrs, AUDIO_RPC_FORMAT_INFO *objp)
{
	 if (!xdr_u_char (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_AUDIO_DEC_TYPE (xdrs, &objp->Type))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->VariableBitRateFlag))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->BitRate))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->copyright))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->rsv_data, 4,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_PCM_FORMAT (XDR *xdrs, AUDIO_PCM_FORMAT *objp)
{
	 if (!xdr_int (xdrs, &objp->chnum))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->samplebit))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->samplerate))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dynamicRange))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->emphasis))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->mute))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_EXT_BS (XDR *xdrs, AUDIO_EXT_BS *objp)
{
	 if (!xdr_int (xdrs, &objp->exist))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_DEC_CFG (XDR *xdrs, AUDIO_DEC_CFG *objp)
{
	 if (!xdr_long (xdrs, &objp->scalehi))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->scalelo))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->scalehi_2ch))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->scalelo_2ch))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->LFEMode))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->dualmono))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->comprMode))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->comprMode_2ch))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->stereoMode))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->sub_dec_mode))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->substream_id))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->dialnorm))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->prog_ref_level))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENCODE_MODE (XDR *xdrs, ENCODE_MODE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_ENC_CFG (XDR *xdrs, AUDIO_ENC_CFG *objp)
{
	 if (!xdr_int (xdrs, &objp->inputmode))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->outputmode))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->DRC1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->DRC2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->datarate))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->samprate))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->LorR))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_INSTANCE (XDR *xdrs, AUDIO_RPC_INSTANCE *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->type))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_HASH (XDR *xdrs, AUDIO_RPC_HASH *objp)
{
	 if (!xdr_long (xdrs, &objp->rand_value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_FRAME_BOUNDARY (XDR *xdrs, AUDIO_FRAME_BOUNDARY *objp)
{
	 if (!xdr_long (xdrs, &objp->frameBeginPtr))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->writeBeginPtr))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->writeSize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_SEND_LONG (XDR *xdrs, AUDIO_RPC_SEND_LONG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->data))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_SENDPIN_LONG (XDR *xdrs, AUDIO_RPC_SENDPIN_LONG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->pinID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->data))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_SEEK (XDR *xdrs, AUDIO_RPC_SEEK *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->speed))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->skip))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_PRIVATEINFO (XDR *xdrs, AUDIO_RPC_PRIVATEINFO *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->pData))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->length))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_RINGBUFFER (XDR *xdrs, AUDIO_RPC_RINGBUFFER *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->in_beginPAddrList, 8,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->in_listSize))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->in_bufSize))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->in_pinID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->extin_beginPAddrList, 8,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->extin_listSize))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->extin_bufSize))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->extin_pinID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->out_beginPAddrList, 8,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->out_listSize))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->out_bufSize))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->out_pinID))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_IOBUFFER (XDR *xdrs, AUDIO_RPC_IOBUFFER *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->in_ptrList, 8,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->in_bufSize))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->in_listSize))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->out_ptrList, 8,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->out_bufSize))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->out_listSize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_BUFFER (XDR *xdrs, AUDIO_RPC_BUFFER *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ptrList, 8,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->bufSize))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->listSize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_SYSTEM_PROCESS_TYPE (XDR *xdrs, ENUM_SYSTEM_PROCESS_TYPE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SYSTEM_PROCESS_INFO (XDR *xdrs, SYSTEM_PROCESS_INFO *objp)
{
	 if (!xdr_ENUM_SYSTEM_PROCESS_TYPE (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 16,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SYSTEM_PROCESS_RES (XDR *xdrs, SYSTEM_PROCESS_RES *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->data))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->packetBufHeader, 2,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_WRITEPACK (XDR *xdrs, AUDIO_RPC_WRITEPACK *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->pinID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->writePtr, 8,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->listSize))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->writeSize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_READPACK (XDR *xdrs, AUDIO_RPC_READPACK *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->pinID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->readPtr, 8,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->listSize))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->readSize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_SENDIO (XDR *xdrs, AUDIO_RPC_SENDIO *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pinID))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_SWITCHAGENT (XDR *xdrs, AUDIO_RPC_SWITCHAGENT *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID1))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->instanceID2))
		 return FALSE;
	 if (!xdr_AUDIO_PCM_FORMAT (xdrs, &objp->pcmFormat))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_PCMFORMAT (XDR *xdrs, AUDIO_RPC_PCMFORMAT *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->pinID))
		 return FALSE;
	 if (!xdr_AUDIO_PCM_FORMAT (xdrs, &objp->pcmFormat))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_FRAME_BOUNDARY (XDR *xdrs, AUDIO_RPC_FRAME_BOUNDARY *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_FRAME_BOUNDARY (xdrs, &objp->frameBoundary))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_DECCFG (XDR *xdrs, AUDIO_RPC_DECCFG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_DEC_CFG (xdrs, &objp->cfg))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_EXTBS_EXIST (XDR *xdrs, AUDIO_RPC_EXTBS_EXIST *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->extbsExist))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_CONNECTION (XDR *xdrs, AUDIO_RPC_CONNECTION *objp)
{
	 if (!xdr_long (xdrs, &objp->srcInstanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->srcPinID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->desInstanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->desPinID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->mediaType))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_REFCLOCK (XDR *xdrs, AUDIO_RPC_REFCLOCK *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->pRefClockID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->pRefClock))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_PTS_INFO (XDR *xdrs, AUDIO_RPC_PTS_INFO *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->pinID))
		 return FALSE;
	 if (!xdr_int64_t (xdrs, &objp->pts))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->pWritePointer))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->length))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_RINGBUFFER_HEADER (XDR *xdrs, AUDIO_RPC_RINGBUFFER_HEADER *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->pinID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->pRingBufferHeaderList, 8,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->readIdx))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->listSize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_FOCUS (XDR *xdrs, AUDIO_RPC_FOCUS *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->focusID))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_SUBCHANNEL (XDR *xdrs, AUDIO_RPC_SUBCHANNEL *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->SubChannelPinID))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_CHANNEL_IDX (XDR *xdrs, ENUM_AUDIO_CHANNEL_IDX *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_AO_FOCUS (XDR *xdrs, AUDIO_RPC_AO_FOCUS *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->focusID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->PTS_length))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_CHANNEL_IN (XDR *xdrs, ENUM_AUDIO_CHANNEL_IN *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_CHANNEL_OUT (XDR *xdrs, ENUM_AUDIO_CHANNEL_OUT *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_GENERAL_CONFIG (XDR *xdrs, AUDIO_GENERAL_CONFIG *objp)
{
	 if (!xdr_char (xdrs, &objp->interface_en))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->channel_in))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->count_down_rec_en))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count_down_rec_cyc))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_SAMPLE_INFO (XDR *xdrs, AUDIO_SAMPLE_INFO *objp)
{
	 if (!xdr_int (xdrs, &objp->sampling_rate))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->PCM_bitnum))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_BBADC_CONFIG (XDR *xdrs, AUDIO_BBADC_CONFIG *objp)
{
	 if (!xdr_AUDIO_GENERAL_CONFIG (xdrs, &objp->audioGeneralConfig))
		 return FALSE;
	 if (!xdr_AUDIO_SAMPLE_INFO (xdrs, &objp->sampleInfo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->clk_sel))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->src_sel))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_I2SI_CONFIG (XDR *xdrs, AUDIO_I2SI_CONFIG *objp)
{
	 if (!xdr_AUDIO_GENERAL_CONFIG (xdrs, &objp->audioGeneralConfig))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->src_sel))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->sync_type))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->mode_sel))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_SPDIFI_CONFIG (XDR *xdrs, AUDIO_SPDIFI_CONFIG *objp)
{
	 if (!xdr_AUDIO_GENERAL_CONFIG (xdrs, &objp->audioGeneralConfig))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->src_sel))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->req_after_lock))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_IPT_SRC (XDR *xdrs, AUDIO_RPC_IPT_SRC *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->focus_in, 4,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mux_in))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_SET_ATV_CLOCK (XDR *xdrs, AUDIO_RPC_SET_ATV_CLOCK *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->atv_type))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_INOUT_CH_SELECT (XDR *xdrs, AUDIO_RPC_INOUT_CH_SELECT *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->valid_setting))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ch_select_pb))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ch_select_ts))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_SET_FS_CLOCKSRC (XDR *xdrs, AUDIO_RPC_SET_FS_CLOCKSRC *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->set_fs))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->set_clock_src))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->set_i2s_mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_SET_PATH_DATA_OUT (XDR *xdrs, AUDIO_RPC_SET_PATH_DATA_OUT *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->data_out_path_pb))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->data_out_path_ts))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_AI_SET_OUT_FMT (XDR *xdrs, AUDIO_RPC_AI_SET_OUT_FMT *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->out_fmt_pb))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->out_fmt_ts))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_SET_INTERLEAVE_OUT (XDR *xdrs, AUDIO_RPC_SET_INTERLEAVE_OUT *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->enable_interleave_out_pb))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->enable_interleave_out_ts))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_SET_SIF_ADC_INIT (XDR *xdrs, AUDIO_RPC_SET_SIF_ADC_INIT *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->sif_adc_init_enable))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_SPDIF_ERROR (XDR *xdrs, AUDIO_SPDIF_ERROR *objp)
{
	 if (!xdr_u_char (xdrs, &objp->err_threshold))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->errorReportEnable))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_ADC_CONFIG (XDR *xdrs, AUDIO_ADC_CONFIG *objp)
{
	 if (!xdr_AUDIO_GENERAL_CONFIG (xdrs, &objp->audioGeneralConfig))
		 return FALSE;
	 if (!xdr_AUDIO_SAMPLE_INFO (xdrs, &objp->sampleInfo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_SPDIF_CONFIG (XDR *xdrs, AUDIO_SPDIF_CONFIG *objp)
{
	 if (!xdr_AUDIO_GENERAL_CONFIG (xdrs, &objp->audioGeneralConfig))
		 return FALSE;
	 if (!xdr_AUDIO_SPDIF_ERROR (xdrs, &objp->audioSPDIFError))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_IN_SOURCE (XDR *xdrs, AUDIO_IN_SOURCE *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->focus_in))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_IN_DATA_MEASURE (XDR *xdrs, AUDIO_IN_DATA_MEASURE *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_IN_MUTE_INFO (XDR *xdrs, AUDIO_IN_MUTE_INFO *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->mute_en))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_OUT_COPY_SOURCE (XDR *xdrs, AUDIO_OUT_COPY_SOURCE *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->src_channel))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_OUT_SPDIF_SOURCE (XDR *xdrs, AUDIO_OUT_SPDIF_SOURCE *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->l_channel))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->r_channel))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_KARAOKE_CONTROL_INFO (XDR *xdrs, AUDIO_KARAOKE_CONTROL_INFO *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->speaker_mode))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->vocal_mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_LINK_BUFFER (XDR *xdrs, LINK_BUFFER *objp)
{
	 if (!xdr_u_long (xdrs, &objp->magicNumber))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->Reserved))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->Next))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->Size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->Data, 1,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_SOUND_EVENT (XDR *xdrs, AUDIO_SOUND_EVENT *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_PCM_FORMAT (xdrs, &objp->pcmFormat))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->endianType))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->pBitstreamRB))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->iteration))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_HDMI_SET (XDR *xdrs, AUDIO_HDMI_SET *objp)
{
	 if (!xdr_u_int (xdrs, &objp->HDMI_Frequency))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_HDMI_MUTE_INFO (XDR *xdrs, AUDIO_HDMI_MUTE_INFO *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->hdmi_mute))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_OUT_MUTE_INFO (XDR *xdrs, AUDIO_OUT_MUTE_INFO *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->mute_flag))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_BBADC_CONFIG (XDR *xdrs, AUDIO_RPC_BBADC_CONFIG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_BBADC_CONFIG (xdrs, &objp->config))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_I2SI_CONFIG (XDR *xdrs, AUDIO_RPC_I2SI_CONFIG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_I2SI_CONFIG (xdrs, &objp->config))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_CONFIG_ADC (XDR *xdrs, AUDIO_CONFIG_ADC *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_ADC_CONFIG (xdrs, &objp->adcConfig))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_CONFIG_AFC (XDR *xdrs, AUDIO_CONFIG_AFC *objp)
{
	 if (!xdr_char (xdrs, &objp->afc_flag))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_DROP_SAMPLE (XDR *xdrs, AUDIO_DROP_SAMPLE *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->drop_pts))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_P_W_NOISE_CFG (XDR *xdrs, AUDIO_P_W_NOISE_CFG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->pink_white_noise_en))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->pink_white_noise_out_channel, 6,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_SPECTRUM_BANDNUM (XDR *xdrs, ENUM_AUDIO_SPECTRUM_BANDNUM *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_SPECTRUM_CFG (XDR *xdrs, AUDIO_SPECTRUM_CFG *objp)
{
	 if (!xdr_long (xdrs, &objp->enable))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->bandnum))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->data_addr))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->upper_bandlimit_addr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_VOLUME_CONTROL (XDR *xdrs, AUDIO_VOLUME_CONTROL *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->level))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_SPDIFI_CONFIG (XDR *xdrs, AUDIO_RPC_SPDIFI_CONFIG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_SPDIFI_CONFIG (xdrs, &objp->config))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_CONFIG_SPDIF (XDR *xdrs, AUDIO_CONFIG_SPDIF *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_SPDIF_CONFIG (xdrs, &objp->spdifConfig))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_CONFIG_SPDIF_ERR (XDR *xdrs, AUDIO_CONFIG_SPDIF_ERR *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_SPDIF_ERROR (xdrs, &objp->audioSPDIFError))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_BACKDOOR_AI_INIT (XDR *xdrs, AUDIO_BACKDOOR_AI_INIT *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->PTSStamp1))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->PTSStamp2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_OUT_GENERAL_CONFIG (XDR *xdrs, AUDIO_OUT_GENERAL_CONFIG *objp)
{
	 if (!xdr_char (xdrs, &objp->interface_en))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->channel_out))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->count_down_play_en))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count_down_play_cyc))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_OUT_CS_INFO (XDR *xdrs, AUDIO_OUT_CS_INFO *objp)
{
	 if (!xdr_char (xdrs, &objp->non_pcm_valid))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->non_pcm_format))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->audio_format))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->spdif_consumer_use))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->copy_right))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->pre_emphasis))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->stereo_channel))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_DAC_CONFIG (XDR *xdrs, AUDIO_DAC_CONFIG *objp)
{
	 if (!xdr_AUDIO_OUT_GENERAL_CONFIG (xdrs, &objp->audioGeneralConfig))
		 return FALSE;
	 if (!xdr_AUDIO_SAMPLE_INFO (xdrs, &objp->sampleInfo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_OUT_SPDIF_CONFIG (XDR *xdrs, AUDIO_OUT_SPDIF_CONFIG *objp)
{
	 if (!xdr_AUDIO_OUT_GENERAL_CONFIG (xdrs, &objp->audioGeneralConfig))
		 return FALSE;
	 if (!xdr_AUDIO_SAMPLE_INFO (xdrs, &objp->sampleInfo))
		 return FALSE;
	 if (!xdr_AUDIO_OUT_CS_INFO (xdrs, &objp->out_cs_info))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_CONFIG_DAC_I2S (XDR *xdrs, AUDIO_CONFIG_DAC_I2S *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_DAC_CONFIG (xdrs, &objp->dacConfig))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_CONFIG_DAC_SPDIF (XDR *xdrs, AUDIO_CONFIG_DAC_SPDIF *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_OUT_SPDIF_CONFIG (xdrs, &objp->spdifConfig))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_SPDIF_CHANNEL_STATUS (XDR *xdrs, AUDIO_RPC_SPDIF_CHANNEL_STATUS *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ChannelStatus, 6,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_DVD_AUDIO_ENCODER_OUTPUT_INFO_TYPE (XDR *xdrs, ENUM_DVD_AUDIO_ENCODER_OUTPUT_INFO_TYPE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_ENC_ELEM_GENERAL_INFO (XDR *xdrs, AUDIO_RPC_ENC_ELEM_GENERAL_INFO *objp)
{
	 if (!xdr_ENUM_DVD_AUDIO_ENCODER_OUTPUT_INFO_TYPE (xdrs, &objp->infoType))
		 return FALSE;
	 if (!xdr_AUDIO_MODULE_TYPE (xdrs, &objp->audioEncoderType))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->bitRate))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->samplingRate))
		 return FALSE;
	 if (!xdr_ENCODE_MODE (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_ENC_ELEM_FRAME_INFO (XDR *xdrs, AUDIO_RPC_ENC_ELEM_FRAME_INFO *objp)
{
	 if (!xdr_ENUM_DVD_AUDIO_ENCODER_OUTPUT_INFO_TYPE (xdrs, &objp->infoType))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->frameNumber))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->PTSH))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->PTSL))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->frameSize))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->NumberOfFrame))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_AIN_INFO_TYPE (XDR *xdrs, ENUM_AUDIO_AIN_INFO_TYPE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_AIN_ELEM_FRAME_INFO (XDR *xdrs, AUDIO_RPC_AIN_ELEM_FRAME_INFO *objp)
{
	 if (!xdr_ENUM_AUDIO_AIN_INFO_TYPE (xdrs, &objp->infoType))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->PTSH))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->PTSL))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->ptr))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->leng))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_DEC_GENERAL_INFO (XDR *xdrs, AUDIO_RPC_DEC_GENERAL_INFO *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->samplingRate))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->bitRate))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->bitWidth))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_DEC_FRAME_INFO (XDR *xdrs, AUDIO_RPC_DEC_FRAME_INFO *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->frameSize))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->NumberOfFrame))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->EOS))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_ERROR (XDR *xdrs, AUDIO_RPC_ERROR *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->audioError))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_MASTERSHIP (XDR *xdrs, AUDIO_RPC_MASTERSHIP *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->MasterShip))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_ENC_SOURCEFILE (XDR *xdrs, AUDIO_RPC_ENC_SOURCEFILE *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fileName, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->length))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_PP_FUNCTION (XDR *xdrs, AUDIO_PP_FUNCTION *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_PP_FUNCTION_MODE (XDR *xdrs, AUDIO_PP_FUNCTION_MODE *objp)
{
	 if (!xdr_char (xdrs, &objp->AUDIO_PP_FUNCTION_ENA))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->AUDIO_DEEMPHASIZE_ENA))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->AUDIO_PINKNOISE_ENA))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->AUDIO_DD_VIRTUAL_SURROUND_ENA))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->AUDIO_DD_VIRTUAL_SPEAKER_ENA))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->AUDIO_DD_EX_ENA))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->AUDIO_EQUALIZER_ENA))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->AUDIO_PROLOGIC2_ENA))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->AUDIO_SRS_ENA))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->AUDIO_BASS_MANAGER_ENA))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->AUDIO_DTS_NEO_ENA))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->AUDIO_DOWN_MIX_ENA))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->AUDIO_SRC_ENA))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->AUDIO_VOCAL_REMOVER_ENA, 4,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->AUDIO_REVERB_ENA, 4,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->AUDIO_KEY_SHIFT_ENA, 4,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_PP_CONFIG (XDR *xdrs, AUDIO_PP_CONFIG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_PP_FUNCTION_MODE (xdrs, &objp->app_config))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_PROLOGIC2_MODE (XDR *xdrs, AUDIO_PROLOGIC2_MODE *objp)
{
	 if (!xdr_char (xdrs, &objp->abaldisable_config_flag))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->chanconfig_config_flag))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->dimset_config_flag))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->surfiltenable_config_flag))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->modeselect_config_flag))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->panoramaenable_config_flag))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->fix_pcmscalefac_config_flag))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->rsinvenable_config_flag))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->samprateid_config_flag))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->cwidthset_config_flag))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->abaldisable))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->chanconfig))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->dimset))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->surfiltenable))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->modeselect))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->panoramaenable))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->fix_pcmscalefac))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->rsinvenable))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->samprateid))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->cwidthset))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_PROLOGIC2_ENA (XDR *xdrs, ENUM_PROLOGIC2_ENA *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AI_PATH (XDR *xdrs, ENUM_AI_PATH *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_PROLOGIC2_CONFIG (XDR *xdrs, AUDIO_PROLOGIC2_CONFIG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->ena))
		 return FALSE;
	 if (!xdr_AUDIO_PROLOGIC2_MODE (xdrs, &objp->app_pl2_config))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_SRC_MODE (XDR *xdrs, ENUM_SRC_MODE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_SRC_CONFIG (XDR *xdrs, AUDIO_SRC_CONFIG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_MIXER_MODE (XDR *xdrs, AUDIO_RPC_MIXER_MODE *objp)
{
	 if (!xdr_long (xdrs, &objp->simpleMix))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->exclusiveMode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_MIXER_CONFIG (XDR *xdrs, AUDIO_MIXER_CONFIG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_MIXER_MODE (xdrs, &objp->app_mixer_config))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_PTS_MIXER (XDR *xdrs, AUDIO_PTS_MIXER *objp)
{
	 if (!xdr_long (xdrs, &objp->pinID))
		 return FALSE;
	 if (!xdr_int64_t (xdrs, &objp->mixer_in_change_PTS))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->mixer_in_ena))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->mixer_gain, 8,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_PTS_MIXER_CONFIG (XDR *xdrs, AUDIO_RPC_PTS_MIXER_CONFIG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_PTS_MIXER (xdrs, &objp->config))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_EQUALIZER_GAIN (XDR *xdrs, ENUM_EQUALIZER_GAIN *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_EQUALIZER_MODE (XDR *xdrs, ENUM_EQUALIZER_MODE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_EQUALIZER_MODE (XDR *xdrs, AUDIO_RPC_EQUALIZER_MODE *objp)
{
	 if (!xdr_long (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->gain, 10,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_EQUALIZER_ENA (XDR *xdrs, ENUM_EQUALIZER_ENA *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_GBL_VAR_EQUALIZER_ID (XDR *xdrs, ENUM_GBL_VAR_EQUALIZER_ID *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_EQUALIZER_CONFIG (XDR *xdrs, AUDIO_EQUALIZER_CONFIG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->gbl_var_eq_ID))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->ena))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_EQUALIZER_MODE (xdrs, &objp->app_eq_config))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_BASS_MANAGEMENT_CUTOFFFREQ (XDR *xdrs, ENUM_BASS_MANAGEMENT_CUTOFFFREQ *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_BASS_MANAGEMENT_MODE (XDR *xdrs, ENUM_BASS_MANAGEMENT_MODE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_BASS_MANAGEMENT_SUBWOOFER_ENA (XDR *xdrs, ENUM_BASS_MANAGEMENT_SUBWOOFER_ENA *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_BASS_MANAGEMENT_MODE (XDR *xdrs, AUDIO_RPC_BASS_MANAGEMENT_MODE *objp)
{
	 if (!xdr_long (xdrs, &objp->cutoffFreq))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->config_mode))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->subwoofer_ena))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_BASS_MANAGEMENT_ENA (XDR *xdrs, ENUM_BASS_MANAGEMENT_ENA *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_BASS_MANAGEMENT_CONFIG (XDR *xdrs, AUDIO_BASS_MANAGEMENT_CONFIG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->ena))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_BASS_MANAGEMENT_MODE (xdrs, &objp->app_bassmng_config))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_DVS_MODE (XDR *xdrs, AUDIO_RPC_DVS_MODE *objp)
{
	 if (!xdr_long (xdrs, &objp->wide_mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_DVS_ENA (XDR *xdrs, ENUM_DVS_ENA *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_DVS_CONFIG (XDR *xdrs, AUDIO_DVS_CONFIG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->ena))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_DVS_MODE (xdrs, &objp->app_dvs_config))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_KEY_SHIFT_ENA (XDR *xdrs, ENUM_KEY_SHIFT_ENA *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_KEY_SHIFT_STONE (XDR *xdrs, ENUM_KEY_SHIFT_STONE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_KEY_SHIFT_CONFIG (XDR *xdrs, AUDIO_KEY_SHIFT_CONFIG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->ena))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->pinID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->semitone))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_REVERB_ENA (XDR *xdrs, ENUM_REVERB_ENA *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_REVERB_MODE (XDR *xdrs, ENUM_REVERB_MODE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_REVERB_CONFIG (XDR *xdrs, AUDIO_REVERB_CONFIG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->ena))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->pinID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->reverb_mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_VOCAL_REMOVER_ENA (XDR *xdrs, ENUM_VOCAL_REMOVER_ENA *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_VOCAL_REMOVER_MODE (XDR *xdrs, ENUM_VOCAL_REMOVER_MODE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_VOCAL_REMOVER_CONFIG (XDR *xdrs, AUDIO_VOCAL_REMOVER_CONFIG *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->ena))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->vr_mode))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->pinID))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_DEC_INIT (XDR *xdrs, AUDIO_RPC_DEC_INIT *objp)
{
	 if (!xdr_long (xdrs, &objp->temp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_ENC_INIT (XDR *xdrs, AUDIO_RPC_ENC_INIT *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->temp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_ENC_SET_BITRATE (XDR *xdrs, AUDIO_RPC_ENC_SET_BITRATE *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->bitrate))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_ENC_COMMAND (XDR *xdrs, AUDIO_RPC_ENC_COMMAND *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_ENC_CFG (xdrs, &objp->enc_config))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_DEBUG_MEMORY (XDR *xdrs, AUDIO_RPC_DEBUG_MEMORY *objp)
{
	 if (!xdr_int (xdrs, &objp->AudioFWVersionNumber))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->audioVersionNumber, 12,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int64_t (xdrs, &objp->AudioDemuxPTS))
		 return FALSE;
	 if (!xdr_int64_t (xdrs, &objp->AudioOutPTS))
		 return FALSE;
	 if (!xdr_int64_t (xdrs, &objp->DecoderPTS))
		 return FALSE;
	 if (!xdr_int64_t (xdrs, &objp->FreeRun))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->contextSwitchTimes))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->taskNumber))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ISRNumber))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->DSRNumber))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->EPC))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->exceptionCause))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->RPC_Status))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->Reserve, 8,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_ENC_INFO (XDR *xdrs, AUDIO_RPC_ENC_INFO *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->encode_type))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_ENC_DV_MIXER (XDR *xdrs, AUDIO_RPC_ENC_DV_MIXER *objp)
{
	 if (!xdr_long (xdrs, &objp->temp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_AO_INIT (XDR *xdrs, AUDIO_RPC_AO_INIT *objp)
{
	 if (!xdr_long (xdrs, &objp->temp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_AO_SET_EQUALIZER (XDR *xdrs, AUDIO_RPC_AO_SET_EQUALIZER *objp)
{
	 if (!xdr_long (xdrs, &objp->temp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_AO_RPC_CONFIG_DELAY_CONTROL (XDR *xdrs, AUDIO_AO_RPC_CONFIG_DELAY_CONTROL *objp)
{
	 if (!xdr_long (xdrs, &objp->temp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_AO_CONFIG_KARAOKE (XDR *xdrs, AUDIO_RPC_AO_CONFIG_KARAOKE *objp)
{
	 if (!xdr_long (xdrs, &objp->temp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_AO_MIXER (XDR *xdrs, AUDIO_RPC_AO_MIXER *objp)
{
	 if (!xdr_long (xdrs, &objp->temp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_PP_CFG (XDR *xdrs, AUDIO_RPC_PP_CFG *objp)
{
	 if (!xdr_long (xdrs, &objp->temp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_PP_MUTE (XDR *xdrs, AUDIO_RPC_PP_MUTE *objp)
{
	 if (!xdr_long (xdrs, &objp->temp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_AO_DAC (XDR *xdrs, AUDIO_RPC_AO_DAC *objp)
{
	 if (!xdr_long (xdrs, &objp->temp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_PP_PROLOGIC (XDR *xdrs, AUDIO_RPC_PP_PROLOGIC *objp)
{
	 if (!xdr_long (xdrs, &objp->temp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_AGC_MODE (XDR *xdrs, AUDIO_AGC_MODE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_KARAOKE_MODE (XDR *xdrs, AUDIO_KARAOKE_MODE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_EASE_TYPE (XDR *xdrs, AUDIO_EASE_TYPE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_CONFIG_CMD_MSG (XDR *xdrs, AUDIO_CONFIG_CMD_MSG *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_DTS_DEC_PARAM_TYPE (XDR *xdrs, AUDIO_DTS_DEC_PARAM_TYPE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_DBX_DEBUG_CMD (XDR *xdrs, AUDIO_DBX_DEBUG_CMD *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_DBXTV_PARAM_TYPE (XDR *xdrs, AUDIO_DBXTV_PARAM_TYPE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_DBXTV_TABLE (XDR *xdrs, AUDIO_DBXTV_TABLE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_DBXTV_TotSonMode (XDR *xdrs, AUDIO_DBXTV_TotSonMode *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_DBXTV_TotVolMode (XDR *xdrs, AUDIO_DBXTV_TotVolMode *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_DBXTV_TotSurMode (XDR *xdrs, AUDIO_DBXTV_TotSurMode *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_DBXTV_SAMPLE_RATE (XDR *xdrs, AUDIO_DBXTV_SAMPLE_RATE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_DBXTV_TABLE_INFO (XDR *xdrs, AUDIO_DBXTV_TABLE_INFO *objp)
{
	 if (!xdr_u_char (xdrs, &objp->dbxTotSonConfigsNum))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->dbxTotVolConfigsNum))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->dbxTotSurConfigsNum))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->tblAddr, AUDIO_DBXTV_TABLE_CNT,
		sizeof (u_int), (xdrproc_t) xdr_u_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_CONFIG_LGSE (XDR *xdrs, AUDIO_CONFIG_LGSE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_CONFIG_DEVICE (XDR *xdrs, AUDIO_CONFIG_DEVICE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_CONFIG_AIO (XDR *xdrs, AUDIO_CONFIG_AIO *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_CUSTOMIZE_REQUEST (XDR *xdrs, AUDIO_CUSTOMIZE_REQUEST *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_CONFIG_COMMAND (XDR *xdrs, AUDIO_CONFIG_COMMAND *objp)
{
	 if (!xdr_AUDIO_CONFIG_CMD_MSG (xdrs, &objp->msgID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->value, 15,
		sizeof (u_int), (xdrproc_t) xdr_u_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDISTRY_FEATURE_CMD_MSG (XDR *xdrs, AUDISTRY_FEATURE_CMD_MSG *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDISTRY_TWOUP_PARAMETER (XDR *xdrs, AUDISTRY_TWOUP_PARAMETER *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDISTRY_HEADSPACE_PARAMETER (XDR *xdrs, AUDISTRY_HEADSPACE_PARAMETER *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDISTRY_STEREOWRAPPER_PARAMETER (XDR *xdrs, AUDISTRY_STEREOWRAPPER_PARAMETER *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDISTRY_LATENIGHT_PARAMETER (XDR *xdrs, AUDISTRY_LATENIGHT_PARAMETER *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDISTRY_VOLUME_PARAMETER (XDR *xdrs, AUDISTRY_VOLUME_PARAMETER *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDISTRY_RUMBLER_PARAMETER (XDR *xdrs, AUDISTRY_RUMBLER_PARAMETER *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDISTRY_CONFIG_COMMAND (XDR *xdrs, AUDISTRY_CONFIG_COMMAND *objp)
{
	 if (!xdr_AUDISTRY_FEATURE_CMD_MSG (xdrs, &objp->feature))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->parameter))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_AO_MIC_CONFIG (XDR *xdrs, AUDIO_AO_MIC_CONFIG *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_AO_AUX_CONFIG (XDR *xdrs, AUDIO_AO_AUX_CONFIG *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_AO_ECHO_REVERB_CONFIG (XDR *xdrs, AUDIO_AO_ECHO_REVERB_CONFIG *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_ECHO_MODE (XDR *xdrs, AUDIO_RPC_ECHO_MODE *objp)
{
	 if (!xdr_long (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->delay))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->fdbk_gain))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_AO_ECHO_DELAY_MODE (XDR *xdrs, AUDIO_AO_ECHO_DELAY_MODE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_HDMI_CODING_TYPE (XDR *xdrs, AUDIO_HDMI_CODING_TYPE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_HDMI_CHANNEL_COUNT (XDR *xdrs, AUDIO_HDMI_CHANNEL_COUNT *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_HDMI_SAMPLING_FREQ (XDR *xdrs, AUDIO_HDMI_SAMPLING_FREQ *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_HDMI_SAMPLE_SIZE (XDR *xdrs, AUDIO_HDMI_SAMPLE_SIZE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_HDMI_SETTING_INFO (XDR *xdrs, AUDIO_HDMI_SETTING_INFO *objp)
{
	 if (!xdr_AUDIO_HDMI_CODING_TYPE (xdrs, &objp->coding_type))
		 return FALSE;
	 if (!xdr_AUDIO_HDMI_CHANNEL_COUNT (xdrs, &objp->channel_count))
		 return FALSE;
	 if (!xdr_AUDIO_HDMI_SAMPLING_FREQ (xdrs, &objp->sample_freq))
		 return FALSE;
	 if (!xdr_AUDIO_HDMI_SAMPLE_SIZE (xdrs, &objp->sample_size))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->max_bit_rate_divided_by_8KHz))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->lpcm_speaker_allocation, 3,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->lpcm_level_shift_value))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->mute))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ENUM_AUDIO_HDMI_EDID_ENABLE (XDR *xdrs, ENUM_AUDIO_HDMI_EDID_ENABLE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_HDMI_OUT_EDID_DATA (XDR *xdrs, AUDIO_HDMI_OUT_EDID_DATA *objp)
{
	 if (!xdr_long (xdrs, &objp->HDMI_output_enable))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->EDID_DATA_addr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_HDMI_OUT_EDID_DATA2 (XDR *xdrs, AUDIO_HDMI_OUT_EDID_DATA2 *objp)
{
	 if (!xdr_long (xdrs, &objp->Version))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->HDMI_output_enable))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->EDID_DATA_addr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_HDMI_OUT_VSDB_DATA (XDR *xdrs, AUDIO_HDMI_OUT_VSDB_DATA *objp)
{
	 if (!xdr_long (xdrs, &objp->HDMI_VSDB_delay))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_HDMI_VIDEO_TYPE (XDR *xdrs, HDMI_VIDEO_TYPE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_HDMI_INFO (XDR *xdrs, HDMI_INFO *objp)
{
	 if (!xdr_long (xdrs, &objp->video_type))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_MIC_DELAY_SLOT (XDR *xdrs, AUDIO_MIC_DELAY_SLOT *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_VOLUME_LEVEL (XDR *xdrs, AUDIO_VOLUME_LEVEL *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_DVOL_LEVEL (XDR *xdrs, AUDIO_DVOL_LEVEL *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_LICENSE_CONTROL_MASK (XDR *xdrs, AUDIO_LICENSE_CONTROL_MASK *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_DEC_FORMAT_INFO (XDR *xdrs, AUDIO_RPC_DEC_FORMAT_INFO *objp)
{
	 if (!xdr_AUDIO_DEC_TYPE (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->nChannels))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->wBitsPerSample))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->nSamplesPerSec))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->nAvgBytesPerSec))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->reserved, 4,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_AIN_FORMAT_INFO (XDR *xdrs, AUDIO_RPC_AIN_FORMAT_INFO *objp)
{
	 if (!xdr_AUDIO_DEC_TYPE (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->reserved, 4,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_LICENSE_STATUS_CONFIG (XDR *xdrs, AUDIO_LICENSE_STATUS_CONFIG *objp)
{
	 if (!xdr_long (xdrs, &objp->HighWord))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->LowWord))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AudioCodecControlBit (XDR *xdrs, AudioCodecControlBit *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_ENUM_PRIVAETINFO_TO_SYS (XDR *xdrs, AUDIO_ENUM_PRIVAETINFO_TO_SYS *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_PRIVATEINFO_TO_SYS (XDR *xdrs, AUDIO_RPC_PRIVATEINFO_TO_SYS *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_ENUM_PRIVAETINFO_TO_SYS (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->privateInfo, 16,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_ENUM_PRIVAETINFO (XDR *xdrs, AUDIO_ENUM_PRIVAETINFO *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_ENUM_AUDIO_FIRMWARE_CAPABILITY_BIT (XDR *xdrs, AUDIO_ENUM_AUDIO_FIRMWARE_CAPABILITY_BIT *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_PRIVATEINFO_PARAMETERS (XDR *xdrs, AUDIO_RPC_PRIVATEINFO_PARAMETERS *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_ENUM_PRIVAETINFO (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->privateInfo, 16,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_PRIVATEINFO_RETURNVAL (XDR *xdrs, AUDIO_RPC_PRIVATEINFO_RETURNVAL *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->privateInfo, 16,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_ENUM_MAX_OUTPUT_SAMPLERATE (XDR *xdrs, AUDIO_ENUM_MAX_OUTPUT_SAMPLERATE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_PASSTHROUGH_INFO (XDR *xdrs, AUDIO_PASSTHROUGH_INFO *objp)
{
	 if (!xdr_u_long (xdrs, &objp->audioPassThroughType))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->audioPassThroughFlag))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_SAMPLERATE (XDR *xdrs, AUDIO_SAMPLERATE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_USB_AUDIO_IN_CMD (XDR *xdrs, USB_AUDIO_IN_CMD *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_USB_AUDIO_IN_FORMAT (XDR *xdrs, USB_AUDIO_IN_FORMAT *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_USB_AUDIO_IN_INFO (XDR *xdrs, USB_AUDIO_IN_INFO *objp)
{
	 if (!xdr_u_long (xdrs, &objp->command))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->usb_ai_ringbuf_addr))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->usb_ai_samplerate))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->usb_ai_format))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->usb_ai_max_chnum))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_USB_AUDIO_IN_TYPE (XDR *xdrs, USB_AUDIO_IN_TYPE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_AI_DEVICE_USB_INFO (XDR *xdrs, AUDIO_AI_DEVICE_USB_INFO *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_USB_AUDIO_IN_INFO (xdrs, &objp->info))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_DUMMY_DATA (XDR *xdrs, AUDIO_DUMMY_DATA *objp)
{
	 if (!xdr_vector (xdrs, (char *)objp->parameter, 8,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_LPCM_ENDIANESS (XDR *xdrs, LPCM_ENDIANESS *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_TSXT (XDR *xdrs, AUDIO_RPC_TSXT *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->pp_Tsxt_Enable))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->ModeType))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->TruBassGain))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->TruBassSize))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->FocusGain))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->InputGain))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->IsTSXTEnable))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->IsHeadphoneMode))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->IsTruBassEnable))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->IsFocusEnable))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->DefinitionGain))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->IsDefEnable))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_TSHD_INFO (XDR *xdrs, AUDIO_RPC_TSHD_INFO *objp)
{
	 if (!xdr_short (xdrs, &objp->Enable))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->InGain))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->OutGain))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->BypassGain))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->InMode))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->OutMode))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->SurEnabled))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->SurLevel))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->SubWooferCxOverFc))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->FrontTBEn))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->FrontTBLevel))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->FrontTBSplitAnalysisEn))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->FrontTBCompLevel))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->FrontTBSpkSize))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->FrontTBMode))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->SubTBEn))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->SubTBLevel))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->SubTBSplitAnalysisEn))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->SubTBCompLevel))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->SubTBSpkSize))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->FrontDefEn))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->FrontDefLevel))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->CenterDefEn))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->CenterDefLevel))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->DiaClarityEn))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->DiaClarityLevel))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->WowhdSrs3dMode))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->WowhdSpaceLevel))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->WowhdCenterLevel))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->WowhdFocusEn))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->WowhdFocusLevel))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->WowhdLimiterEn))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->WowhdHighBitEn))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->WowhdLimiterMinimalGain))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_TSHD (XDR *xdrs, AUDIO_RPC_TSHD *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->Enable))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->Test_case_Enable))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->Type))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_TSHD_INFO (xdrs, &objp->TSHD_info))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_RETURNVAL (XDR *xdrs, AUDIO_RPC_LGSE_RETURNVAL *objp)
{
	 if (!xdr_long (xdrs, &objp->ret))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->value, 16,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_GETDATA (XDR *xdrs, AUDIO_RPC_LGSE_GETDATA *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->function_list))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->rw))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETMODE (XDR *xdrs, AUDIO_RPC_LGSE_SETMODE *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->flag))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00861 (XDR *xdrs, AUDIO_RPC_LGSE00861 *objp)
{
	 if (!xdr_u_int (xdrs, &objp->_LGSE01668))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->_LGSE01669))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->_LGSE02409))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->_LGSE01665))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->_LGSE01673))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->_LGSE01667))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->_LGSE01658))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->_LGSE01662))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->_LGSE01661))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->_LGSE01670))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00876 (XDR *xdrs, AUDIO_RPC_LGSE00876 *objp)
{
	 if (!xdr_u_int (xdrs, &objp->_LGSE00585))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->_LGSE00584))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->_LGSE00586))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETMAIN (XDR *xdrs, AUDIO_RPC_LGSE_SETMAIN *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_LGSE00861 (xdrs, &objp->dataInit))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_LGSE00876 (xdrs, &objp->dataVar))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00855 (XDR *xdrs, AUDIO_RPC_LGSE00855 *objp)
{
	 if (!xdr_int (xdrs, &objp->_LGSE00742))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00744))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00743))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00745))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00746))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00755))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00738))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00756))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00757))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00748))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00741))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00747))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00740))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00739))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00753))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00759, 140,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00758, 140,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00870 (XDR *xdrs, AUDIO_RPC_LGSE00870 *objp)
{
	 if (!xdr_int (xdrs, &objp->_LGSE00754))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN000 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN000 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->rpc_LGSE00855_set_address))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_LGSE00870 (xdrs, &objp->dataVar))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00854 (XDR *xdrs, AUDIO_RPC_LGSE00854 *objp)
{
	 if (!xdr_int (xdrs, &objp->_LGSE00784))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00823, 20,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00869 (XDR *xdrs, AUDIO_RPC_LGSE00869 *objp)
{
	 if (!xdr_int (xdrs, &objp->_LGSE00794))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00795))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00582))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00610))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00580))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00067))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00068))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00075))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00716))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00348))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00076))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00717))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00349))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00077))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00718))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00191))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00192))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00190))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00189))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00687))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00690))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00689))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00688))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00692))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00691))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00538))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00534))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00537))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00536))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00542, 101,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN001 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN001 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_LGSE00854 (xdrs, &objp->dataInit))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->rpc_LGSE00869_set_address))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00857 (XDR *xdrs, AUDIO_RPC_LGSE00857 *objp)
{
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00762, 2,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00343))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00693))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00545))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00543))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00539))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00544))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00540))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00541))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00872 (XDR *xdrs, AUDIO_RPC_LGSE00872 *objp)
{
	 if (!xdr_int (xdrs, &objp->_LGSE00132))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->VALUE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN009 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN009 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_LGSE00857 (xdrs, &objp->dataInit))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_LGSE00872 (xdrs, &objp->dataVar))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00859 (XDR *xdrs, AUDIO_RPC_LGSE00859 *objp)
{
	 if (!xdr_vector (xdrs, (char *)objp->_Left, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_Right, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00874 (XDR *xdrs, AUDIO_RPC_LGSE00874 *objp)
{
	 if (!xdr_int (xdrs, &objp->_LGSE00588))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN010 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN010 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_LGSE00859 (xdrs, &objp->dataInit))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_LGSE00874 (xdrs, &objp->dataVar))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN004 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN004 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 25,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN005 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN005 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 15,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00858 (XDR *xdrs, AUDIO_RPC_LGSE00858 *objp)
{
	 if (!xdr_int (xdrs, &objp->_LGSE00319))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00330))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00331))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00327))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00303))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00332))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00304))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00333))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00326))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00341))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00342))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00324))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00305))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00334))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00306))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00335))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00320, 20,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00322, 4,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00329, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00338, 20,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00337))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00328, 4,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00321, 20,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00317, 2,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00318, 3,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00315, 2,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00316, 3,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00313, 2,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00314, 3,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00309))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00323))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00336))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00873 (XDR *xdrs, AUDIO_RPC_LGSE00873 *objp)
{
	 if (!xdr_int (xdrs, &objp->_LGSE00843))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00340))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00841))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00308))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00842))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00312))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00311))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00307))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00325))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00339))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00310))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN008 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN008 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->rpc_LGSE00858_set_address))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_LGSE00873 (xdrs, &objp->dataVar))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00853 (XDR *xdrs, AUDIO_RPC_LGSE00853 *objp)
{
	 if (!xdr_int (xdrs, &objp->_LGSE00013))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00003))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00006))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00005, 3,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00015))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00016, 105,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00009, 24,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00868 (XDR *xdrs, AUDIO_RPC_LGSE00868 *objp)
{
	 if (!xdr_int (xdrs, &objp->_LGSE00008))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN014 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN014 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->rpc_LGSE00853_set_address))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_LGSE00868 (xdrs, &objp->dataVar))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00879 (XDR *xdrs, AUDIO_RPC_LGSE00879 *objp)
{
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00804, 80,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00803, 80,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00667))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00666))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN017 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN017 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->rpc_LGSE00879_set_address))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00856 (XDR *xdrs, AUDIO_RPC_LGSE00856 *objp)
{
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00799, 20,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00074, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->RELEASE, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00827, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00828, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00831, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00837, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00838, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00839, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00710, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00711, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00712, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE02471))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00764))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00763))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00079, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00720, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00078, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00719, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00871 (XDR *xdrs, AUDIO_RPC_LGSE00871 *objp)
{
	 if (!xdr_int (xdrs, &objp->_LGSE00018))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE02468))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE02469))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00298))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN019 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN019 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->rpc_LGSE00856_set_address))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_LGSE00871 (xdrs, &objp->dataVar))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00863 (XDR *xdrs, AUDIO_RPC_LGSE00863 *objp)
{
	 if (!xdr_u_int (xdrs, &objp->_LGSE00285))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00071))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00086))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->_LGSE00284))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00070))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00085))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00878 (XDR *xdrs, AUDIO_RPC_LGSE00878 *objp)
{
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00789, 240,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00788, 240,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN022 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN022 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_LGSE00863 (xdrs, &objp->dataInit))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->rpc_LGSE00878_set_address))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00862 (XDR *xdrs, AUDIO_RPC_LGSE00862 *objp)
{
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE02719, 2,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE02761, 20,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE02810, 20,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE00877 (XDR *xdrs, AUDIO_RPC_LGSE00877 *objp)
{
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE02720, 20,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN018 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN018 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->rpc_LGSE00862_set_address))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_LGSE00877 (xdrs, &objp->dataVar))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE02624 (XDR *xdrs, AUDIO_RPC_LGSE02624 *objp)
{
	 if (!xdr_long (xdrs, &objp->_LGSE02582))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->_LGSE02590))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE02591, 2,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE02592, 3,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE02605, 2,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE02606, 3,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN024 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN024 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_LGSE02624 (xdrs, &objp->dataInit))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_DATA026 (XDR *xdrs, AUDIO_RPC_LGSE_DATA026 *objp)
{
	 if (!xdr_vector (xdrs, (char *)objp->data, 200,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN026 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN026 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->rpc_data026_set_address))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_DATA027 (XDR *xdrs, AUDIO_RPC_LGSE_DATA027 *objp)
{
	 if (!xdr_vector (xdrs, (char *)objp->data, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN027 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN027 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->rpc_data027_set_address))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE02871 (XDR *xdrs, AUDIO_RPC_LGSE02871 *objp)
{
	 if (!xdr_int (xdrs, &objp->_LGSE02797))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE02798))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN028 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN028 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_LGSE02871 (xdrs, &objp->dataVar))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE02869 (XDR *xdrs, AUDIO_RPC_LGSE02869 *objp)
{
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00799, 20,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00074, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->RELEASE, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00827, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00828, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00831, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE02856, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00837, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00838, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00839, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE02861, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00710, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00711, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00712, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE02791, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE02471))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00764))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00763))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00079, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00720, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00078, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE00719, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE00018))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE02723, 20,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE02795))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE02717, 20,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE02718, 20,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE02729))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_LGSE02730))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_LGSE02767, 23,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_LGSE_SETFN029 (XDR *xdrs, AUDIO_RPC_LGSE_SETFN029 *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataOption))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->rpc_LGSE02869_set_address))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_TRUVOL_MODE (XDR *xdrs, AUDIO_RPC_TRUVOL_MODE *objp)
{
	 if (!xdr_int (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->enable))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->InputGain))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->OutputGain))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_FREQ_EQ_MODE (XDR *xdrs, AUDIO_FREQ_EQ_MODE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_FREQ_EQ (XDR *xdrs, AUDIO_RPC_FREQ_EQ *objp)
{
	 if (!xdr_int (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->bw, 15,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fc, 15,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->gain, 15,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->type, 15,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->valid_mask))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_TRUVOLUME (XDR *xdrs, AUDIO_RPC_TRUVOLUME *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->pp_TruVol_Enable))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_TRUVOL_MODE (xdrs, &objp->pp_TruVol_Info))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_SAMPLERATE_TOLERANCE (XDR *xdrs, AUDIO_SAMPLERATE_TOLERANCE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_BASSBACK_TV_MODE (XDR *xdrs, AUDIO_BASSBACK_TV_MODE *objp)
{
	 if (!xdr_int (xdrs, &objp->Enable_Sys))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->StopBandFreq_Sys))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->HarmonicGain))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->vb_enable))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Sys_EnhanceFreq))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Tru_StopbandFreq))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Set_BassGain))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_BASSBACK_PCBU_MODE (XDR *xdrs, AUDIO_BASSBACK_PCBU_MODE *objp)
{
	 if (!xdr_int (xdrs, &objp->Enable_Sys))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->StopBandFreq_Sys))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->HarmonicGain))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->SubHarmonicGain))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->TreHarmonicGain))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->vb_enable))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Sys_EnhanceFreq))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Tru_StopbandFreq))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Set_BassGain))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Enable_HPF))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->StopBandFreq_HPF))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Enable_PF))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Gain_PF))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->CenterFreq_PF))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->BandWidth_PF))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_PCBU_BASSBACK (XDR *xdrs, AUDIO_RPC_PCBU_BASSBACK *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->pp_bassback_Enable))
		 return FALSE;
	 if (!xdr_AUDIO_BASSBACK_PCBU_MODE (xdrs, &objp->pp_bassback_mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_TV_BASSBACK (XDR *xdrs, AUDIO_RPC_TV_BASSBACK *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->pp_bassback_Enable))
		 return FALSE;
	 if (!xdr_AUDIO_BASSBACK_TV_MODE (xdrs, &objp->pp_bassback_mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_TV_BASSBACK_CHANGE_BASS_GAIN (XDR *xdrs, AUDIO_RPC_TV_BASSBACK_CHANGE_BASS_GAIN *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->pp_bassback_bassgain))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_AO_CHANNEL_OUT_SWAP (XDR *xdrs, AUDIO_AO_CHANNEL_OUT_SWAP *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_AO_CHANNEL_OPT_SWAP (XDR *xdrs, AUDIO_RPC_AO_CHANNEL_OPT_SWAP *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->channelSwapIndex))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_CHANNEL_OUT_MODE (XDR *xdrs, AUDIO_CHANNEL_OUT_MODE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_CHANNEL_OUT_MODE (XDR *xdrs, AUDIO_RPC_CHANNEL_OUT_MODE *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_CHANNEL_OUT_MODE (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_GET_PTS_INFO (XDR *xdrs, AUDIO_RPC_GET_PTS_INFO *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_RPC_PTS_INFO (xdrs, &objp->pts_info))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_SPDIFO_SOURCE (XDR *xdrs, AUDIO_SPDIFO_SOURCE *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_SPDIFO_SOURCE (XDR *xdrs, AUDIO_RPC_SPDIFO_SOURCE *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_SPDIFO_SOURCE (xdrs, &objp->source))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_PP_ASF_ON_OFF (XDR *xdrs, AUDIO_RPC_PP_ASF_ON_OFF *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->on_off_flag))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_PP_ASF_BALANCE (XDR *xdrs, AUDIO_RPC_PP_ASF_BALANCE *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->asf_balance))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_PP_ASF_MASTER_VOLUME (XDR *xdrs, AUDIO_RPC_PP_ASF_MASTER_VOLUME *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->asf_volume))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_SPDIF_CS (XDR *xdrs, AUDIO_SPDIF_CS *objp)
{
	 if (!xdr_long (xdrs, &objp->module_type))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->professional))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->data_type))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->copyright))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->pre_emphasis))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->category_code))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->source_number))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->channel_number))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->sampling_freq))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->clock_accuracy))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->word_length))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->original_sampling_freq))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->cgms_a))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_RESAMPLE_INFO (XDR *xdrs, AUDIO_RPC_RESAMPLE_INFO *objp)
{
	 if (!xdr_int (xdrs, &objp->Taps))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->SrcSamples))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->DstSamples))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Coefs))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_TO_KERNEL_PARAMETER (XDR *xdrs, AUDIO_RPC_TO_KERNEL_PARAMETER *objp)
{
	 if (!xdr_u_int (xdrs, &objp->command))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->param1))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->param2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_DEC_SEEKING_CAP (XDR *xdrs, AUDIO_RPC_DEC_SEEKING_CAP *objp)
{
	 if (!xdr_long (xdrs, &objp->MaxSpeed))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->MaxReverseSpeed))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->MinSkip))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->MaxSkip))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->MinReverseSkip))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->MaxReverseSkip))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AUDIO_RPC_GET_DEC_SEEK_CAP (XDR *xdrs, AUDIO_RPC_GET_DEC_SEEK_CAP *objp)
{
	 if (!xdr_long (xdrs, &objp->instanceID))
		 return FALSE;
	 if (!xdr_AUDIO_DEC_TYPE (xdrs, &objp->dec_type))
		 return FALSE;
	return TRUE;
}
