/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <AudioRPC_Agent.h>
#include <SVCFunc.h>
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <RPCBaseDS.h>
#include <AudioRPCBaseDS.h>

static void
AUDIO_AGENT_0(RPC_STRUCT * rpc, int opt, pthread_mutex_t *pMutex)
{
	union {
		AUDIO_RPC_ERROR AUDIO_RPC_ToSystem_ErrorStatus_0_arg;
		AUDIO_RPC_SENDIO AUDIO_RPC_ToSystem_DeliverFlush_0_arg;
		AUDIO_RPC_SENDPIN_LONG AUDIO_RPC_ToSystem_EndOfStream_0_arg;
		long AUDIO_RPC_ToSystem_ENC_GeneralInfo_0_arg;
		long AUDIO_RPC_ToSystem_ENC_FrameInfo_0_arg;
		long AUDIO_RPC_ToSystem_ENC_EndOfStream_0_arg;
		AUDIO_RPC_DEC_GENERAL_INFO AUDIO_RPC_ToSystem_DEC_GeneralInfo_0_arg;
		AUDIO_RPC_DEC_GENERAL_INFO AUDIO_RPC_ToSystem_DEC_FrameInfo_0_arg;
		long AUDIO_RPC_ToSystem_AIN_FrameInfo_0_arg;
		long AUDIO_RPC_ToSystem_AO_KaraokeModeIndicate_0_arg;
		AUDIO_RPC_SPDIF_CHANNEL_STATUS AUDIO_RPC_ToSystem_AO_ReportSPDIFStatus_0_arg;
		AUDIO_RPC_MASTERSHIP AUDIO_RPC_ToSystem_AO_PostMastership_0_arg;
		long AUDIO_RPC_ToSystem_AO_ConfigDACDone_0_arg;
		long AUDIO_RPC_ToSystem_DAC_HardwareMute_0_arg;
		long AUDIO_RPC_ToSystem_ADC_HardwareMute_0_arg;
		AUDIO_RPC_HASH AUDIO_RPC_ToSystem_HashCheck_0_arg;
		long AUDIO_RPC_ToSystem_CreateIOBuf_0_arg;
		long AUDIO_RPC_ToSystem_FreeIOBuf_0_arg;
		long AUDIO_RPC_ToSystem_CreateBuf_0_arg;
		long AUDIO_RPC_ToSystem_FreeBuf_0_arg;
		SYSTEM_PROCESS_INFO AUDIO_RPC_ToSystem_Process_Open_0_arg;
		SYSTEM_PROCESS_INFO AUDIO_RPC_ToSystem_Process_Close_0_arg;
		long AUDIO_RPC_ToSystem_HDMI_Mute_0_arg;
		struct AUDIO_HDMI_SETTING_INFO AUDIO_RPC_ToSystem_HDMI_Setting_0_arg;
		long AUDIO_RPC_ToSystem_AudioHaltDone_0_arg;
		AUDIO_RPC_PRIVATEINFO_TO_SYS AUDIO_RPC_ToSystem_PrivateInfo_0_arg;
		AUDIO_RPC_TO_KERNEL_PARAMETER AUDIO_RPC_ToKernel_SimpleCommand_0_arg;
	} argument;

	union {
		HRESULT AUDIO_RPC_ToSystem_ErrorStatus_0_ret;
		HRESULT AUDIO_RPC_ToSystem_DeliverFlush_0_ret;
		HRESULT AUDIO_RPC_ToSystem_EndOfStream_0_ret;
		HRESULT AUDIO_RPC_ToSystem_ENC_GeneralInfo_0_ret;
		HRESULT AUDIO_RPC_ToSystem_ENC_FrameInfo_0_ret;
		HRESULT AUDIO_RPC_ToSystem_ENC_EndOfStream_0_ret;
		HRESULT AUDIO_RPC_ToSystem_DEC_GeneralInfo_0_ret;
		HRESULT AUDIO_RPC_ToSystem_DEC_FrameInfo_0_ret;
		HRESULT AUDIO_RPC_ToSystem_AIN_FrameInfo_0_ret;
		HRESULT AUDIO_RPC_ToSystem_AO_KaraokeModeIndicate_0_ret;
		HRESULT AUDIO_RPC_ToSystem_AO_ReportSPDIFStatus_0_ret;
		HRESULT AUDIO_RPC_ToSystem_AO_PostMastership_0_ret;
		HRESULT AUDIO_RPC_ToSystem_AO_ConfigDACDone_0_ret;
		HRESULT AUDIO_RPC_ToSystem_DAC_HardwareMute_0_ret;
		HRESULT AUDIO_RPC_ToSystem_ADC_HardwareMute_0_ret;
		RPCRES_LONG AUDIO_RPC_ToSystem_HashCheck_0_ret;
		AUDIO_RPC_IOBUFFER AUDIO_RPC_ToSystem_CreateIOBuf_0_ret;
		HRESULT AUDIO_RPC_ToSystem_FreeIOBuf_0_ret;
		AUDIO_RPC_BUFFER AUDIO_RPC_ToSystem_CreateBuf_0_ret;
		HRESULT AUDIO_RPC_ToSystem_FreeBuf_0_ret;
		SYSTEM_PROCESS_RES AUDIO_RPC_ToSystem_Process_Open_0_ret;
		HRESULT AUDIO_RPC_ToSystem_Process_Close_0_ret;
		HRESULT AUDIO_RPC_ToSystem_HDMI_Mute_0_ret;
		HRESULT AUDIO_RPC_ToSystem_HDMI_Setting_0_ret;
		HRESULT AUDIO_RPC_ToSystem_AudioHaltDone_0_ret;
		HRESULT AUDIO_RPC_ToSystem_PrivateInfo_0_ret;
		HRESULT AUDIO_RPC_ToKernel_SimpleCommand_0_ret;
	} retval;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct RPC_STRUCT *, char *);
	int ReplyParaSize;


	switch (rpc->procedureID) {
	case AUDIO_RPC_ToSystem_ErrorStatus:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_ERROR;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_ErrorStatus_0_svc;
		break;

	case AUDIO_RPC_ToSystem_DeliverFlush:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SENDIO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_DeliverFlush_0_svc;
		break;

	case AUDIO_RPC_ToSystem_EndOfStream:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SENDPIN_LONG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_EndOfStream_0_svc;
		break;

	case AUDIO_RPC_ToSystem_ENC_GeneralInfo:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_ENC_GeneralInfo_0_svc;
		break;

	case AUDIO_RPC_ToSystem_ENC_FrameInfo:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_ENC_FrameInfo_0_svc;
		break;

	case AUDIO_RPC_ToSystem_ENC_EndOfStream:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_ENC_EndOfStream_0_svc;
		break;

	case AUDIO_RPC_ToSystem_DEC_GeneralInfo:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_DEC_GENERAL_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_DEC_GeneralInfo_0_svc;
		break;

	case AUDIO_RPC_ToSystem_DEC_FrameInfo:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_DEC_GENERAL_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_DEC_FrameInfo_0_svc;
		break;

	case AUDIO_RPC_ToSystem_AIN_FrameInfo:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_AIN_FrameInfo_0_svc;
		break;

	case AUDIO_RPC_ToSystem_AO_KaraokeModeIndicate:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_AO_KaraokeModeIndicate_0_svc;
		break;

	case AUDIO_RPC_ToSystem_AO_ReportSPDIFStatus:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SPDIF_CHANNEL_STATUS;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_AO_ReportSPDIFStatus_0_svc;
		break;

	case AUDIO_RPC_ToSystem_AO_PostMastership:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_MASTERSHIP;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_AO_PostMastership_0_svc;
		break;

	case AUDIO_RPC_ToSystem_AO_ConfigDACDone:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_AO_ConfigDACDone_0_svc;
		break;

	case AUDIO_RPC_ToSystem_DAC_HardwareMute:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_DAC_HardwareMute_0_svc;
		break;

	case AUDIO_RPC_ToSystem_ADC_HardwareMute:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_ADC_HardwareMute_0_svc;
		break;

	case AUDIO_RPC_ToSystem_HashCheck:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_HASH;
		_xdr_result = (xdrproc_t) xdr_RPCRES_LONG;
		ReplyParaSize = sizeof(RPCRES_LONG);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_HashCheck_0_svc;
		break;

	case AUDIO_RPC_ToSystem_CreateIOBuf:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_AUDIO_RPC_IOBUFFER;
		ReplyParaSize = sizeof(AUDIO_RPC_IOBUFFER);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_CreateIOBuf_0_svc;
		break;

	case AUDIO_RPC_ToSystem_FreeIOBuf:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_FreeIOBuf_0_svc;
		break;

	case AUDIO_RPC_ToSystem_CreateBuf:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_AUDIO_RPC_BUFFER;
		ReplyParaSize = sizeof(AUDIO_RPC_BUFFER);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_CreateBuf_0_svc;
		break;

	case AUDIO_RPC_ToSystem_FreeBuf:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_FreeBuf_0_svc;
		break;

	case AUDIO_RPC_ToSystem_Process_Open:
		_xdr_argument = (xdrproc_t) xdr_SYSTEM_PROCESS_INFO;
		_xdr_result = (xdrproc_t) xdr_SYSTEM_PROCESS_RES;
		ReplyParaSize = sizeof(SYSTEM_PROCESS_RES);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_Process_Open_0_svc;
		break;

	case AUDIO_RPC_ToSystem_Process_Close:
		_xdr_argument = (xdrproc_t) xdr_SYSTEM_PROCESS_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_Process_Close_0_svc;
		break;

	case AUDIO_RPC_ToSystem_HDMI_Mute:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_HDMI_Mute_0_svc;
		break;

	case AUDIO_RPC_ToSystem_HDMI_Setting:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_HDMI_SETTING_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_HDMI_Setting_0_svc;
		break;

	case AUDIO_RPC_ToSystem_AudioHaltDone:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_AudioHaltDone_0_svc;
		break;

	case AUDIO_RPC_ToSystem_PrivateInfo:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_PRIVATEINFO_TO_SYS;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToSystem_PrivateInfo_0_svc;
		break;

	case AUDIO_RPC_ToKernel_SimpleCommand:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_TO_KERNEL_PARAMETER;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToKernel_SimpleCommand_0_svc;
		break;

	default:
#ifdef IS_SCPU
		RPC_EMERG("unknown procedure:pid = %d, procedureID = %d\n", (int)gettid(), (int)rpc->procedureID);
#endif
		return;
	}


	memset ((char *)&argument, 0, sizeof (argument));


	if (!rpc_getargs (rpc, (xdrproc_t) _xdr_argument, (caddr_t) &argument, opt)) {
		printf("get args error\n");
#ifdef IS_SCPU
		RPC_EMERG("rpc_getargs error:pid = %d, procedureID = %d\n", (int)gettid(), (int)rpc->procedureID);
#endif
		return;
	}

#ifdef IS_SCPU
	Q9527_DEBUG()

#endif
	pthread_mutex_unlock(pMutex);

	(*local)((char *)&argument, rpc, (char *)&retval);


	// When source msg is BLOCK_MODE,
	// we must help it reply
	// ps: reply mode is NON_BLOCK and use request's ringbuf type
	if (rpc->taskID != 0) {
	    SendReply(rpc->taskID, rpc->context, (char *)&retval, ReplyParaSize,
			 (xdrproc_t) _xdr_result, opt);
	}

	return;
}
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_ErrorStatus_0_svc)(AUDIO_RPC_ERROR *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_ErrorStatus_0_svc(AUDIO_RPC_ERROR *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_ErrorStatus_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_ErrorStatus_0_svc:%p\n", p_AUDIO_RPC_ToSystem_ErrorStatus_0_svc);
    if (p_AUDIO_RPC_ToSystem_ErrorStatus_0_svc)
    {
        p_AUDIO_RPC_ToSystem_ErrorStatus_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_DeliverFlush_0_svc)(AUDIO_RPC_SENDIO *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_DeliverFlush_0_svc(AUDIO_RPC_SENDIO *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_DeliverFlush_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_DeliverFlush_0_svc:%p\n", p_AUDIO_RPC_ToSystem_DeliverFlush_0_svc);
    if (p_AUDIO_RPC_ToSystem_DeliverFlush_0_svc)
    {
        p_AUDIO_RPC_ToSystem_DeliverFlush_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_EndOfStream_0_svc)(AUDIO_RPC_SENDPIN_LONG *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_EndOfStream_0_svc(AUDIO_RPC_SENDPIN_LONG *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_EndOfStream_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_EndOfStream_0_svc:%p\n", p_AUDIO_RPC_ToSystem_EndOfStream_0_svc);
    if (p_AUDIO_RPC_ToSystem_EndOfStream_0_svc)
    {
        p_AUDIO_RPC_ToSystem_EndOfStream_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_ENC_GeneralInfo_0_svc)(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_ENC_GeneralInfo_0_svc(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_ENC_GeneralInfo_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_ENC_GeneralInfo_0_svc:%p\n", p_AUDIO_RPC_ToSystem_ENC_GeneralInfo_0_svc);
    if (p_AUDIO_RPC_ToSystem_ENC_GeneralInfo_0_svc)
    {
        p_AUDIO_RPC_ToSystem_ENC_GeneralInfo_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_ENC_FrameInfo_0_svc)(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_ENC_FrameInfo_0_svc(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_ENC_FrameInfo_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_ENC_FrameInfo_0_svc:%p\n", p_AUDIO_RPC_ToSystem_ENC_FrameInfo_0_svc);
    if (p_AUDIO_RPC_ToSystem_ENC_FrameInfo_0_svc)
    {
        p_AUDIO_RPC_ToSystem_ENC_FrameInfo_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_ENC_EndOfStream_0_svc)(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_ENC_EndOfStream_0_svc(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_ENC_EndOfStream_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_ENC_EndOfStream_0_svc:%p\n", p_AUDIO_RPC_ToSystem_ENC_EndOfStream_0_svc);
    if (p_AUDIO_RPC_ToSystem_ENC_EndOfStream_0_svc)
    {
        p_AUDIO_RPC_ToSystem_ENC_EndOfStream_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_DEC_GeneralInfo_0_svc)(AUDIO_RPC_DEC_GENERAL_INFO *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_DEC_GeneralInfo_0_svc(AUDIO_RPC_DEC_GENERAL_INFO *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_DEC_GeneralInfo_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_DEC_GeneralInfo_0_svc:%p\n", p_AUDIO_RPC_ToSystem_DEC_GeneralInfo_0_svc);
    if (p_AUDIO_RPC_ToSystem_DEC_GeneralInfo_0_svc)
    {
        p_AUDIO_RPC_ToSystem_DEC_GeneralInfo_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_DEC_FrameInfo_0_svc)(AUDIO_RPC_DEC_GENERAL_INFO *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_DEC_FrameInfo_0_svc(AUDIO_RPC_DEC_GENERAL_INFO *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_DEC_FrameInfo_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_DEC_FrameInfo_0_svc:%p\n", p_AUDIO_RPC_ToSystem_DEC_FrameInfo_0_svc);
    if (p_AUDIO_RPC_ToSystem_DEC_FrameInfo_0_svc)
    {
        p_AUDIO_RPC_ToSystem_DEC_FrameInfo_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_AIN_FrameInfo_0_svc)(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_AIN_FrameInfo_0_svc(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_AIN_FrameInfo_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_AIN_FrameInfo_0_svc:%p\n", p_AUDIO_RPC_ToSystem_AIN_FrameInfo_0_svc);
    if (p_AUDIO_RPC_ToSystem_AIN_FrameInfo_0_svc)
    {
        p_AUDIO_RPC_ToSystem_AIN_FrameInfo_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_AO_KaraokeModeIndicate_0_svc)(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_AO_KaraokeModeIndicate_0_svc(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_AO_KaraokeModeIndicate_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_AO_KaraokeModeIndicate_0_svc:%p\n", p_AUDIO_RPC_ToSystem_AO_KaraokeModeIndicate_0_svc);
    if (p_AUDIO_RPC_ToSystem_AO_KaraokeModeIndicate_0_svc)
    {
        p_AUDIO_RPC_ToSystem_AO_KaraokeModeIndicate_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_AO_ReportSPDIFStatus_0_svc)(AUDIO_RPC_SPDIF_CHANNEL_STATUS *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_AO_ReportSPDIFStatus_0_svc(AUDIO_RPC_SPDIF_CHANNEL_STATUS *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_AO_ReportSPDIFStatus_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_AO_ReportSPDIFStatus_0_svc:%p\n", p_AUDIO_RPC_ToSystem_AO_ReportSPDIFStatus_0_svc);
    if (p_AUDIO_RPC_ToSystem_AO_ReportSPDIFStatus_0_svc)
    {
        p_AUDIO_RPC_ToSystem_AO_ReportSPDIFStatus_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_AO_PostMastership_0_svc)(AUDIO_RPC_MASTERSHIP *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_AO_PostMastership_0_svc(AUDIO_RPC_MASTERSHIP *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_AO_PostMastership_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_AO_PostMastership_0_svc:%p\n", p_AUDIO_RPC_ToSystem_AO_PostMastership_0_svc);
    if (p_AUDIO_RPC_ToSystem_AO_PostMastership_0_svc)
    {
        p_AUDIO_RPC_ToSystem_AO_PostMastership_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_AO_ConfigDACDone_0_svc)(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_AO_ConfigDACDone_0_svc(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_AO_ConfigDACDone_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_AO_ConfigDACDone_0_svc:%p\n", p_AUDIO_RPC_ToSystem_AO_ConfigDACDone_0_svc);
    if (p_AUDIO_RPC_ToSystem_AO_ConfigDACDone_0_svc)
    {
        p_AUDIO_RPC_ToSystem_AO_ConfigDACDone_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_DAC_HardwareMute_0_svc)(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_DAC_HardwareMute_0_svc(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_DAC_HardwareMute_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_DAC_HardwareMute_0_svc:%p\n", p_AUDIO_RPC_ToSystem_DAC_HardwareMute_0_svc);
    if (p_AUDIO_RPC_ToSystem_DAC_HardwareMute_0_svc)
    {
        p_AUDIO_RPC_ToSystem_DAC_HardwareMute_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_ADC_HardwareMute_0_svc)(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_ADC_HardwareMute_0_svc(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_ADC_HardwareMute_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_ADC_HardwareMute_0_svc:%p\n", p_AUDIO_RPC_ToSystem_ADC_HardwareMute_0_svc);
    if (p_AUDIO_RPC_ToSystem_ADC_HardwareMute_0_svc)
    {
        p_AUDIO_RPC_ToSystem_ADC_HardwareMute_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) RPCRES_LONG *  (*p_AUDIO_RPC_ToSystem_HashCheck_0_svc)(AUDIO_RPC_HASH *pParam, RPC_STRUCT *pRpcStruct, RPCRES_LONG *pRes) = 0;

__attribute__((weak)) RPCRES_LONG * AUDIO_RPC_ToSystem_HashCheck_0_svc(AUDIO_RPC_HASH *pParam, RPC_STRUCT *pRpcStruct, RPCRES_LONG *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_HashCheck_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_HashCheck_0_svc:%p\n", p_AUDIO_RPC_ToSystem_HashCheck_0_svc);
    if (p_AUDIO_RPC_ToSystem_HashCheck_0_svc)
    {
        p_AUDIO_RPC_ToSystem_HashCheck_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) AUDIO_RPC_IOBUFFER *  (*p_AUDIO_RPC_ToSystem_CreateIOBuf_0_svc)(long *pParam, RPC_STRUCT *pRpcStruct, AUDIO_RPC_IOBUFFER *pRes) = 0;

__attribute__((weak)) AUDIO_RPC_IOBUFFER * AUDIO_RPC_ToSystem_CreateIOBuf_0_svc(long *pParam, RPC_STRUCT *pRpcStruct, AUDIO_RPC_IOBUFFER *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_CreateIOBuf_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_CreateIOBuf_0_svc:%p\n", p_AUDIO_RPC_ToSystem_CreateIOBuf_0_svc);
    if (p_AUDIO_RPC_ToSystem_CreateIOBuf_0_svc)
    {
        p_AUDIO_RPC_ToSystem_CreateIOBuf_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_FreeIOBuf_0_svc)(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_FreeIOBuf_0_svc(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_FreeIOBuf_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_FreeIOBuf_0_svc:%p\n", p_AUDIO_RPC_ToSystem_FreeIOBuf_0_svc);
    if (p_AUDIO_RPC_ToSystem_FreeIOBuf_0_svc)
    {
        p_AUDIO_RPC_ToSystem_FreeIOBuf_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) AUDIO_RPC_BUFFER *  (*p_AUDIO_RPC_ToSystem_CreateBuf_0_svc)(long *pParam, RPC_STRUCT *pRpcStruct, AUDIO_RPC_BUFFER *pRes) = 0;

__attribute__((weak)) AUDIO_RPC_BUFFER * AUDIO_RPC_ToSystem_CreateBuf_0_svc(long *pParam, RPC_STRUCT *pRpcStruct, AUDIO_RPC_BUFFER *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_CreateBuf_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_CreateBuf_0_svc:%p\n", p_AUDIO_RPC_ToSystem_CreateBuf_0_svc);
    if (p_AUDIO_RPC_ToSystem_CreateBuf_0_svc)
    {
        p_AUDIO_RPC_ToSystem_CreateBuf_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_FreeBuf_0_svc)(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_FreeBuf_0_svc(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_FreeBuf_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_FreeBuf_0_svc:%p\n", p_AUDIO_RPC_ToSystem_FreeBuf_0_svc);
    if (p_AUDIO_RPC_ToSystem_FreeBuf_0_svc)
    {
        p_AUDIO_RPC_ToSystem_FreeBuf_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) SYSTEM_PROCESS_RES *  (*p_AUDIO_RPC_ToSystem_Process_Open_0_svc)(SYSTEM_PROCESS_INFO *pParam, RPC_STRUCT *pRpcStruct, SYSTEM_PROCESS_RES *pRes) = 0;

__attribute__((weak)) SYSTEM_PROCESS_RES * AUDIO_RPC_ToSystem_Process_Open_0_svc(SYSTEM_PROCESS_INFO *pParam, RPC_STRUCT *pRpcStruct, SYSTEM_PROCESS_RES *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_Process_Open_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_Process_Open_0_svc:%p\n", p_AUDIO_RPC_ToSystem_Process_Open_0_svc);
    if (p_AUDIO_RPC_ToSystem_Process_Open_0_svc)
    {
        p_AUDIO_RPC_ToSystem_Process_Open_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_Process_Close_0_svc)(SYSTEM_PROCESS_INFO *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_Process_Close_0_svc(SYSTEM_PROCESS_INFO *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_Process_Close_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_Process_Close_0_svc:%p\n", p_AUDIO_RPC_ToSystem_Process_Close_0_svc);
    if (p_AUDIO_RPC_ToSystem_Process_Close_0_svc)
    {
        p_AUDIO_RPC_ToSystem_Process_Close_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_HDMI_Mute_0_svc)(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_HDMI_Mute_0_svc(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_HDMI_Mute_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_HDMI_Mute_0_svc:%p\n", p_AUDIO_RPC_ToSystem_HDMI_Mute_0_svc);
    if (p_AUDIO_RPC_ToSystem_HDMI_Mute_0_svc)
    {
        p_AUDIO_RPC_ToSystem_HDMI_Mute_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_HDMI_Setting_0_svc)(struct AUDIO_HDMI_SETTING_INFO *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_HDMI_Setting_0_svc(struct AUDIO_HDMI_SETTING_INFO *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_HDMI_Setting_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_HDMI_Setting_0_svc:%p\n", p_AUDIO_RPC_ToSystem_HDMI_Setting_0_svc);
    if (p_AUDIO_RPC_ToSystem_HDMI_Setting_0_svc)
    {
        p_AUDIO_RPC_ToSystem_HDMI_Setting_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_AudioHaltDone_0_svc)(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_AudioHaltDone_0_svc(long *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_AudioHaltDone_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_AudioHaltDone_0_svc:%p\n", p_AUDIO_RPC_ToSystem_AudioHaltDone_0_svc);
    if (p_AUDIO_RPC_ToSystem_AudioHaltDone_0_svc)
    {
        p_AUDIO_RPC_ToSystem_AudioHaltDone_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToSystem_PrivateInfo_0_svc)(AUDIO_RPC_PRIVATEINFO_TO_SYS *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToSystem_PrivateInfo_0_svc(AUDIO_RPC_PRIVATEINFO_TO_SYS *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToSystem_PrivateInfo_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToSystem_PrivateInfo_0_svc:%p\n", p_AUDIO_RPC_ToSystem_PrivateInfo_0_svc);
    if (p_AUDIO_RPC_ToSystem_PrivateInfo_0_svc)
    {
        p_AUDIO_RPC_ToSystem_PrivateInfo_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_AUDIO_RPC_ToKernel_SimpleCommand_0_svc)(AUDIO_RPC_TO_KERNEL_PARAMETER *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * AUDIO_RPC_ToKernel_SimpleCommand_0_svc(AUDIO_RPC_TO_KERNEL_PARAMETER *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: AUDIO_RPC_ToKernel_SimpleCommand_0_svc() is called!\n");
    printf ("RPC HOOK: p_AUDIO_RPC_ToKernel_SimpleCommand_0_svc:%p\n", p_AUDIO_RPC_ToKernel_SimpleCommand_0_svc);
    if (p_AUDIO_RPC_ToKernel_SimpleCommand_0_svc)
    {
        p_AUDIO_RPC_ToKernel_SimpleCommand_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON


struct REG_STRUCT * AUDIO_AGENT_0_register(struct REG_STRUCT *rnode) {

	return (struct REG_STRUCT *)ipc_register(rnode, AUDIO_AGENT, 0,
		(void (*)(struct RPC_STRUCT *, int, pthread_mutex_t*))AUDIO_AGENT_0);

}
