KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/demodcomm
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/ademod/ademodcomm
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/ademod/ademodcore


rtkademod-objs := ADemodMgr.o \
                                     ademod.o \
                                     demod_rtk_atv.o \
                                     					
obj-y += rtkademod.o 
obj-y +=ademodcore/
#obj-y +=ademodcomm/
