/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <SecureRPC_Agent.h>
#include <SVCFunc.h>
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <RPCBaseDS.h>
#include <SecureRPCBaseDS.h>

static void
SECURE_AGENT_0(RPC_STRUCT * rpc, int opt, pthread_mutex_t *pMutex)
{
	union {
		RPC_tee_rpc_result_t SECURE_RPC_ToSystem_PlayReady_Result_0_arg;
		SECURE_RPC_TOSYSTEM_GET_SETUP_PARAM SECURE_RPC_ToSystem_GetSetupParameter_0_arg;
		SECURE_RPC_TOSYSTEM_SET_PARAM SECURE_RPC_ToSystem_SetParameter_0_arg;
		SECURE_RPC_TOSYSTEM_SEND_RW SECURE_RPC_ToSystem_SendReadCommand_0_arg;
		SECURE_RPC_TOSYSTEM_SEND_RW SECURE_RPC_ToSystem_SendWriteCommand_0_arg;
		SECURE_RPC_TOSYSTEM_TVSERVER_CTRL SECURE_RPC_ToSystem_TvServerControl_0_arg;
		SECURE_RPC_TOSYSTEM_OSD_MSG SECURE_RPC_ToSystem_OsdMsg_0_arg;
		SECURE_RPC_TOSYSTEM_SET_PARAM SECURE_RPC_ToSystem_GetData_0_arg;
	} argument;

	union {
		HRESULT SECURE_RPC_ToSystem_PlayReady_Result_0_ret;
		RPCRES_LONG SECURE_RPC_ToSystem_GetSetupParameter_0_ret;
		HRESULT SECURE_RPC_ToSystem_SetParameter_0_ret;
		RPCRES_K_S SECURE_RPC_ToSystem_SendReadCommand_0_ret;
		HRESULT SECURE_RPC_ToSystem_SendWriteCommand_0_ret;
		HRESULT SECURE_RPC_ToSystem_TvServerControl_0_ret;
		HRESULT SECURE_RPC_ToSystem_OsdMsg_0_ret;
		RPCRES_K_S SECURE_RPC_ToSystem_GetData_0_ret;
	} retval;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct RPC_STRUCT *, char *);
	int ReplyParaSize;


	switch (rpc->procedureID) {
	case SECURE_RPC_ToSystem_PlayReady_Result:
		_xdr_argument = (xdrproc_t) xdr_RPC_tee_rpc_result_t;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToSystem_PlayReady_Result_0_svc;
		break;

	case SECURE_RPC_ToSystem_GetSetupParameter:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_TOSYSTEM_GET_SETUP_PARAM;
		_xdr_result = (xdrproc_t) xdr_RPCRES_LONG;
		ReplyParaSize = sizeof(RPCRES_LONG);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToSystem_GetSetupParameter_0_svc;
		break;

	case SECURE_RPC_ToSystem_SetParameter:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_TOSYSTEM_SET_PARAM;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToSystem_SetParameter_0_svc;
		break;

	case SECURE_RPC_ToSystem_SendReadCommand:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_TOSYSTEM_SEND_RW;
		_xdr_result = (xdrproc_t) xdr_RPCRES_K_S;
		ReplyParaSize = sizeof(RPCRES_K_S);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToSystem_SendReadCommand_0_svc;
		break;

	case SECURE_RPC_ToSystem_SendWriteCommand:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_TOSYSTEM_SEND_RW;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToSystem_SendWriteCommand_0_svc;
		break;

	case SECURE_RPC_ToSystem_TvServerControl:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_TOSYSTEM_TVSERVER_CTRL;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToSystem_TvServerControl_0_svc;
		break;

	case SECURE_RPC_ToSystem_OsdMsg:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_TOSYSTEM_OSD_MSG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToSystem_OsdMsg_0_svc;
		break;

	case SECURE_RPC_ToSystem_GetData:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_TOSYSTEM_SET_PARAM;
		_xdr_result = (xdrproc_t) xdr_RPCRES_K_S;
		ReplyParaSize = sizeof(RPCRES_K_S);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToSystem_GetData_0_svc;
		break;

	default:
#ifdef IS_SCPU
		RPC_EMERG("unknown procedure:pid = %d, procedureID = %d\n", (int)gettid(), (int)rpc->procedureID);
#endif
		return;
	}


	memset ((char *)&argument, 0, sizeof (argument));


	if (!rpc_getargs (rpc, (xdrproc_t) _xdr_argument, (caddr_t) &argument, opt)) {
		printf("get args error\n");
#ifdef IS_SCPU
		RPC_EMERG("rpc_getargs error:pid = %d, procedureID = %d\n", (int)gettid(), (int)rpc->procedureID);
#endif
		return;
	}

#ifdef IS_SCPU
	Q9527_DEBUG()

#endif
	pthread_mutex_unlock(pMutex);

	(*local)((char *)&argument, rpc, (char *)&retval);


	// When source msg is BLOCK_MODE,
	// we must help it reply
	// ps: reply mode is NON_BLOCK and use request's ringbuf type
	if (rpc->taskID != 0) {
	    SendReply(rpc->taskID, rpc->context, (char *)&retval, ReplyParaSize,
			 (xdrproc_t) _xdr_result, opt);
	}

	return;
}
#ifdef ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON
__attribute__((weak)) HRESULT *  (*p_SECURE_RPC_ToSystem_PlayReady_Result_0_svc)(RPC_tee_rpc_result_t *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * SECURE_RPC_ToSystem_PlayReady_Result_0_svc(RPC_tee_rpc_result_t *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: SECURE_RPC_ToSystem_PlayReady_Result_0_svc() is called!\n");
    printf ("RPC HOOK: p_SECURE_RPC_ToSystem_PlayReady_Result_0_svc:%p\n", p_SECURE_RPC_ToSystem_PlayReady_Result_0_svc);
    if (p_SECURE_RPC_ToSystem_PlayReady_Result_0_svc)
    {
        p_SECURE_RPC_ToSystem_PlayReady_Result_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) RPCRES_LONG *  (*p_SECURE_RPC_ToSystem_GetSetupParameter_0_svc)(SECURE_RPC_TOSYSTEM_GET_SETUP_PARAM *pParam, RPC_STRUCT *pRpcStruct, RPCRES_LONG *pRes) = 0;

__attribute__((weak)) RPCRES_LONG * SECURE_RPC_ToSystem_GetSetupParameter_0_svc(SECURE_RPC_TOSYSTEM_GET_SETUP_PARAM *pParam, RPC_STRUCT *pRpcStruct, RPCRES_LONG *pRes)
{
    printf ("RPC HOOK: SECURE_RPC_ToSystem_GetSetupParameter_0_svc() is called!\n");
    printf ("RPC HOOK: p_SECURE_RPC_ToSystem_GetSetupParameter_0_svc:%p\n", p_SECURE_RPC_ToSystem_GetSetupParameter_0_svc);
    if (p_SECURE_RPC_ToSystem_GetSetupParameter_0_svc)
    {
        p_SECURE_RPC_ToSystem_GetSetupParameter_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_SECURE_RPC_ToSystem_SetParameter_0_svc)(SECURE_RPC_TOSYSTEM_SET_PARAM *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * SECURE_RPC_ToSystem_SetParameter_0_svc(SECURE_RPC_TOSYSTEM_SET_PARAM *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: SECURE_RPC_ToSystem_SetParameter_0_svc() is called!\n");
    printf ("RPC HOOK: p_SECURE_RPC_ToSystem_SetParameter_0_svc:%p\n", p_SECURE_RPC_ToSystem_SetParameter_0_svc);
    if (p_SECURE_RPC_ToSystem_SetParameter_0_svc)
    {
        p_SECURE_RPC_ToSystem_SetParameter_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) RPCRES_K_S *  (*p_SECURE_RPC_ToSystem_SendReadCommand_0_svc)(SECURE_RPC_TOSYSTEM_SEND_RW *pParam, RPC_STRUCT *pRpcStruct, RPCRES_K_S *pRes) = 0;

__attribute__((weak)) RPCRES_K_S * SECURE_RPC_ToSystem_SendReadCommand_0_svc(SECURE_RPC_TOSYSTEM_SEND_RW *pParam, RPC_STRUCT *pRpcStruct, RPCRES_K_S *pRes)
{
    printf ("RPC HOOK: SECURE_RPC_ToSystem_SendReadCommand_0_svc() is called!\n");
    printf ("RPC HOOK: p_SECURE_RPC_ToSystem_SendReadCommand_0_svc:%p\n", p_SECURE_RPC_ToSystem_SendReadCommand_0_svc);
    if (p_SECURE_RPC_ToSystem_SendReadCommand_0_svc)
    {
        p_SECURE_RPC_ToSystem_SendReadCommand_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_SECURE_RPC_ToSystem_SendWriteCommand_0_svc)(SECURE_RPC_TOSYSTEM_SEND_RW *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * SECURE_RPC_ToSystem_SendWriteCommand_0_svc(SECURE_RPC_TOSYSTEM_SEND_RW *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: SECURE_RPC_ToSystem_SendWriteCommand_0_svc() is called!\n");
    printf ("RPC HOOK: p_SECURE_RPC_ToSystem_SendWriteCommand_0_svc:%p\n", p_SECURE_RPC_ToSystem_SendWriteCommand_0_svc);
    if (p_SECURE_RPC_ToSystem_SendWriteCommand_0_svc)
    {
        p_SECURE_RPC_ToSystem_SendWriteCommand_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_SECURE_RPC_ToSystem_TvServerControl_0_svc)(SECURE_RPC_TOSYSTEM_TVSERVER_CTRL *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * SECURE_RPC_ToSystem_TvServerControl_0_svc(SECURE_RPC_TOSYSTEM_TVSERVER_CTRL *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: SECURE_RPC_ToSystem_TvServerControl_0_svc() is called!\n");
    printf ("RPC HOOK: p_SECURE_RPC_ToSystem_TvServerControl_0_svc:%p\n", p_SECURE_RPC_ToSystem_TvServerControl_0_svc);
    if (p_SECURE_RPC_ToSystem_TvServerControl_0_svc)
    {
        p_SECURE_RPC_ToSystem_TvServerControl_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) HRESULT *  (*p_SECURE_RPC_ToSystem_OsdMsg_0_svc)(SECURE_RPC_TOSYSTEM_OSD_MSG *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes) = 0;

__attribute__((weak)) HRESULT * SECURE_RPC_ToSystem_OsdMsg_0_svc(SECURE_RPC_TOSYSTEM_OSD_MSG *pParam, RPC_STRUCT *pRpcStruct, HRESULT *pRes)
{
    printf ("RPC HOOK: SECURE_RPC_ToSystem_OsdMsg_0_svc() is called!\n");
    printf ("RPC HOOK: p_SECURE_RPC_ToSystem_OsdMsg_0_svc:%p\n", p_SECURE_RPC_ToSystem_OsdMsg_0_svc);
    if (p_SECURE_RPC_ToSystem_OsdMsg_0_svc)
    {
        p_SECURE_RPC_ToSystem_OsdMsg_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

__attribute__((weak)) RPCRES_K_S *  (*p_SECURE_RPC_ToSystem_GetData_0_svc)(SECURE_RPC_TOSYSTEM_SET_PARAM *pParam, RPC_STRUCT *pRpcStruct, RPCRES_K_S *pRes) = 0;

__attribute__((weak)) RPCRES_K_S * SECURE_RPC_ToSystem_GetData_0_svc(SECURE_RPC_TOSYSTEM_SET_PARAM *pParam, RPC_STRUCT *pRpcStruct, RPCRES_K_S *pRes)
{
    printf ("RPC HOOK: SECURE_RPC_ToSystem_GetData_0_svc() is called!\n");
    printf ("RPC HOOK: p_SECURE_RPC_ToSystem_GetData_0_svc:%p\n", p_SECURE_RPC_ToSystem_GetData_0_svc);
    if (p_SECURE_RPC_ToSystem_GetData_0_svc)
    {
        p_SECURE_RPC_ToSystem_GetData_0_svc(pParam, pRpcStruct, pRes);
        return pRes;
    }
    else
    {
        return pRes;
    }
}

#endif //ENABLE_FW2SYSTEM_RPC_HOOK_FUNCTION_IN_COMMON


struct REG_STRUCT * SECURE_AGENT_0_register(struct REG_STRUCT *rnode) {

	return (struct REG_STRUCT *)ipc_register(rnode, SECURE_AGENT, 0,
		(void (*)(struct RPC_STRUCT *, int, pthread_mutex_t*))SECURE_AGENT_0);

}
