/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <SecureRPC_System.h>
#include <RPCBaseDS.h>
#include <SecureRPCBaseDS.h>

bool_t
xdr_RPC_sstore_rpc_cmd_t (XDR *xdrs, RPC_sstore_rpc_cmd_t *objp)
{
	 if (!xdr_u_int (xdrs, &objp->ulCmd))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->algo))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->keyType))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->pkey))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->keyLen))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->pIV))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->IVLen))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->pDataIn))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->dataInLen))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->pDataOut))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->dataOutLen))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->pHmacKey))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RPC_tee_rpc_cmd_t (XDR *xdrs, RPC_tee_rpc_cmd_t *objp)
{
	 if (!xdr_RPC_RtkDrmCode (xdrs, &objp->func_code))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->pSharedMem))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->sharedMemSize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RPC_tee_manager_cmd_t (XDR *xdrs, RPC_tee_manager_cmd_t *objp)
{
	 if (!xdr_vector (xdrs, (char *)objp->procName, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RPC_tee_manager_time_t (XDR *xdrs, RPC_tee_manager_time_t *objp)
{
	 if (!xdr_long (xdrs, &objp->tv_sec))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->tv_usec))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RPC_tee_manager_key_t (XDR *xdrs, RPC_tee_manager_key_t *objp)
{
	 if (!xdr_vector (xdrs, (char *)objp->esnkey, 2048,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->esnkeyLen))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->playReadyKey, 51200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->playReadyKeyLen))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RPC_tee_manager_memInfo_t (XDR *xdrs, RPC_tee_manager_memInfo_t *objp)
{
	 if (!xdr_long (xdrs, &objp->pPhysicalMem))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->procName, 256,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RPC_tee_protection_cmd_t (XDR *xdrs, RPC_tee_protection_cmd_t *objp)
{
	 if (!xdr_u_long (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->arg))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->start_addr))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->end_addr))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->reserve, 3,
		sizeof (u_long), (xdrproc_t) xdr_u_long))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SECURE_RPC_DTVAPI_SS (XDR *xdrs, SECURE_RPC_DTVAPI_SS *objp)
{
	 if (!xdr_long (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 5,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SECURE_RPC_DTVAPI_S (XDR *xdrs, SECURE_RPC_DTVAPI_S *objp)
{
	 if (!xdr_long (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 10,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SECURE_RPC_DTVAPI_M (XDR *xdrs, SECURE_RPC_DTVAPI_M *objp)
{
	 if (!xdr_long (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 30,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SECURE_RPC_DTVAPI_MM (XDR *xdrs, SECURE_RPC_DTVAPI_MM *objp)
{
	 if (!xdr_long (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 80,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SECURE_RPC_DTVAPI_L (XDR *xdrs, SECURE_RPC_DTVAPI_L *objp)
{
	 if (!xdr_long (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 320,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SECURE_RPC_DTVAPI_LL (XDR *xdrs, SECURE_RPC_DTVAPI_LL *objp)
{
	 if (!xdr_long (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 400,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RPCRES_SS (XDR *xdrs, RPCRES_SS *objp)
{
	 if (!xdr_HRESULT (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 5,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RPCRES_S (XDR *xdrs, RPCRES_S *objp)
{
	 if (!xdr_HRESULT (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 10,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RPCRES_M (XDR *xdrs, RPCRES_M *objp)
{
	 if (!xdr_HRESULT (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 30,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RPCRES_MM (XDR *xdrs, RPCRES_MM *objp)
{
	 if (!xdr_HRESULT (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 80,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RPCRES_L (XDR *xdrs, RPCRES_L *objp)
{
	 if (!xdr_HRESULT (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 320,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}
