/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <SecureRPC_System.h>
#include <rt/misc/SVCFunc.h>
#include <rt/posix/pthread.h>
#include <RPCBaseDS.h>
#include <SecureRPCBaseDS.h>

void *memset( void *s, int c, unsigned int n );

static void
SECURE_SYSTEM_0(RPC_STRUCT * rpc, int opt, pthread_mutex_t *pMutex)
{
	union {
		RPC_tee_rpc_cmd_t SECURE_RPC_ToAgent_PlayReady_0_arg;
		long SECURE_RPC_ToAgent_GetTeeManagerPid_0_arg;
		RPC_tee_manager_cmd_t SECURE_RPC_ToAgent_ForkProcessByName_0_arg;
		RPC_tee_manager_cmd_t SECURE_RPC_ToAgent_DeleteProcessByName_0_arg;
		RPC_tee_manager_time_t SECURE_RPC_ToAgent_SetSystemTime_0_arg;
		RPC_tee_manager_key_t SECURE_RPC_ToAgent_PrepareKStoreEnv_0_arg;
		RPC_tee_manager_memInfo_t SECURE_RPC_ToAgent_DeleteMemoryInKcup_0_arg;
		RPC_tee_manager_memInfo_t SECURE_RPC_ToAgent_AllocateMemoryInKcup_0_arg;
		RPC_tee_protection_cmd_t SECURE_RPC_ToAgent_SetTeeProtection_0_arg;
		SECURE_RPC_DTVAPI_SS SECURE_RPC_ToAgent_DtvApi_SS_0_arg;
		RPC_sstore_rpc_cmd_t SECURE_RPC_ToAgent_Sstore_Cypto_0_arg;
		SECURE_RPC_DTVAPI_S SECURE_RPC_ToAgent_DtvApi_S_0_arg;
		SECURE_RPC_DTVAPI_M SECURE_RPC_ToAgent_DtvApi_M_0_arg;
		SECURE_RPC_DTVAPI_MM SECURE_RPC_ToAgent_DtvApi_MM_0_arg;
		SECURE_RPC_DTVAPI_L SECURE_RPC_ToAgent_DtvApi_L_0_arg;
		SECURE_RPC_DTVAPI_SS SECURE_RPC_ToAgent_DtvApiWithRes_0_arg;
		SECURE_RPC_DTVAPI_S SECURE_RPC_ToAgent_DtvApiWithRes_rl_S_0_arg;
		SECURE_RPC_DTVAPI_M SECURE_RPC_ToAgent_DtvApiWithRes_rl_M_0_arg;
		SECURE_RPC_DTVAPI_MM SECURE_RPC_ToAgent_DtvApiWithRes_rl_MM_0_arg;
		SECURE_RPC_DTVAPI_L SECURE_RPC_ToAgent_DtvApiWithRes_rl_L_0_arg;
		SECURE_RPC_DTVAPI_LL SECURE_RPC_ToAgent_DtvApiWithRes_rl_LL_0_arg;
		SECURE_RPC_DTVAPI_SS SECURE_RPC_ToAgent_DtvApiWithRes_rss_0_arg;
		SECURE_RPC_DTVAPI_S SECURE_RPC_ToAgent_DtvApiWithRes_rss_S_0_arg;
		SECURE_RPC_DTVAPI_M SECURE_RPC_ToAgent_DtvApiWithRes_rss_M_0_arg;
		SECURE_RPC_DTVAPI_MM SECURE_RPC_ToAgent_DtvApiWithRes_rss_MM_0_arg;
		SECURE_RPC_DTVAPI_L SECURE_RPC_ToAgent_DtvApiWithRes_rss_L_0_arg;
		SECURE_RPC_DTVAPI_SS SECURE_RPC_ToAgent_DtvApiWithRes_S_0_arg;
		SECURE_RPC_DTVAPI_SS SECURE_RPC_ToAgent_DtvApiWithRes_M_0_arg;
		SECURE_RPC_DTVAPI_SS SECURE_RPC_ToAgent_DtvApiWithRes_MM_0_arg;
		SECURE_RPC_DTVAPI_SS SECURE_RPC_ToAgent_DtvApiWithRes_L_0_arg;
		SECURE_RPC_DTVAPI_L SECURE_RPC_ToAgent_DtvApiWithRes_L_L_0_arg;
		RPC_tee_rpc_cmd_t SECURE_RPC_ToAgent_SecureKeyBox_0_arg;
	} argument;

	union {
		HRESULT SECURE_RPC_ToAgent_PlayReady_0_ret;
		long SECURE_RPC_ToAgent_GetTeeManagerPid_0_ret;
		long SECURE_RPC_ToAgent_ForkProcessByName_0_ret;
		HRESULT SECURE_RPC_ToAgent_DeleteProcessByName_0_ret;
		HRESULT SECURE_RPC_ToAgent_SetSystemTime_0_ret;
		HRESULT SECURE_RPC_ToAgent_PrepareKStoreEnv_0_ret;
		HRESULT SECURE_RPC_ToAgent_DeleteMemoryInKcup_0_ret;
		long SECURE_RPC_ToAgent_AllocateMemoryInKcup_0_ret;
		long SECURE_RPC_ToAgent_SetTeeProtection_0_ret;
		HRESULT SECURE_RPC_ToAgent_DtvApi_SS_0_ret;
		HRESULT SECURE_RPC_ToAgent_Sstore_Cypto_0_ret;
		HRESULT SECURE_RPC_ToAgent_DtvApi_S_0_ret;
		HRESULT SECURE_RPC_ToAgent_DtvApi_M_0_ret;
		HRESULT SECURE_RPC_ToAgent_DtvApi_MM_0_ret;
		HRESULT SECURE_RPC_ToAgent_DtvApi_L_0_ret;
		RPCRES_LONG SECURE_RPC_ToAgent_DtvApiWithRes_0_ret;
		RPCRES_LONG SECURE_RPC_ToAgent_DtvApiWithRes_rl_S_0_ret;
		RPCRES_LONG SECURE_RPC_ToAgent_DtvApiWithRes_rl_M_0_ret;
		RPCRES_LONG SECURE_RPC_ToAgent_DtvApiWithRes_rl_MM_0_ret;
		RPCRES_LONG SECURE_RPC_ToAgent_DtvApiWithRes_rl_L_0_ret;
		RPCRES_LONG SECURE_RPC_ToAgent_DtvApiWithRes_rl_LL_0_ret;
		RPCRES_SS SECURE_RPC_ToAgent_DtvApiWithRes_rss_0_ret;
		RPCRES_SS SECURE_RPC_ToAgent_DtvApiWithRes_rss_S_0_ret;
		RPCRES_SS SECURE_RPC_ToAgent_DtvApiWithRes_rss_M_0_ret;
		RPCRES_SS SECURE_RPC_ToAgent_DtvApiWithRes_rss_MM_0_ret;
		RPCRES_SS SECURE_RPC_ToAgent_DtvApiWithRes_rss_L_0_ret;
		RPCRES_S SECURE_RPC_ToAgent_DtvApiWithRes_S_0_ret;
		RPCRES_M SECURE_RPC_ToAgent_DtvApiWithRes_M_0_ret;
		RPCRES_MM SECURE_RPC_ToAgent_DtvApiWithRes_MM_0_ret;
		RPCRES_L SECURE_RPC_ToAgent_DtvApiWithRes_L_0_ret;
		RPCRES_L SECURE_RPC_ToAgent_DtvApiWithRes_L_L_0_ret;
		int SECURE_RPC_ToAgent_SecureKeyBox_0_ret;
	} retval;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct RPC_STRUCT *, char *);
	int ReplyParaSize;


	switch (rpc->procedureID) {
	case SECURE_RPC_ToAgent_PlayReady:
		_xdr_argument = (xdrproc_t) xdr_RPC_tee_rpc_cmd_t;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_PlayReady_0_svc;
		break;

	case SECURE_RPC_ToAgent_GetTeeManagerPid:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_long;
		ReplyParaSize = sizeof(long);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_GetTeeManagerPid_0_svc;
		break;

	case SECURE_RPC_ToAgent_ForkProcessByName:
		_xdr_argument = (xdrproc_t) xdr_RPC_tee_manager_cmd_t;
		_xdr_result = (xdrproc_t) xdr_long;
		ReplyParaSize = sizeof(long);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_ForkProcessByName_0_svc;
		break;

	case SECURE_RPC_ToAgent_DeleteProcessByName:
		_xdr_argument = (xdrproc_t) xdr_RPC_tee_manager_cmd_t;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DeleteProcessByName_0_svc;
		break;

	case SECURE_RPC_ToAgent_SetSystemTime:
		_xdr_argument = (xdrproc_t) xdr_RPC_tee_manager_time_t;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_SetSystemTime_0_svc;
		break;

	case SECURE_RPC_ToAgent_PrepareKStoreEnv:
		_xdr_argument = (xdrproc_t) xdr_RPC_tee_manager_key_t;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_PrepareKStoreEnv_0_svc;
		break;

	case SECURE_RPC_ToAgent_DeleteMemoryInKcup:
		_xdr_argument = (xdrproc_t) xdr_RPC_tee_manager_memInfo_t;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DeleteMemoryInKcup_0_svc;
		break;

	case SECURE_RPC_ToAgent_AllocateMemoryInKcup:
		_xdr_argument = (xdrproc_t) xdr_RPC_tee_manager_memInfo_t;
		_xdr_result = (xdrproc_t) xdr_long;
		ReplyParaSize = sizeof(long);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_AllocateMemoryInKcup_0_svc;
		break;

	case SECURE_RPC_ToAgent_SetTeeProtection:
		_xdr_argument = (xdrproc_t) xdr_RPC_tee_protection_cmd_t;
		_xdr_result = (xdrproc_t) xdr_long;
		ReplyParaSize = sizeof(long);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_SetTeeProtection_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApi_SS:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_SS;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApi_SS_0_svc;
		break;

	case SECURE_RPC_ToAgent_Sstore_Cypto:
		_xdr_argument = (xdrproc_t) xdr_RPC_sstore_rpc_cmd_t;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_Sstore_Cypto_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApi_S:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_S;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApi_S_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApi_M:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_M;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApi_M_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApi_MM:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_MM;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApi_MM_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApi_L:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_L;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApi_L_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApiWithRes:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_SS;
		_xdr_result = (xdrproc_t) xdr_RPCRES_LONG;
		ReplyParaSize = sizeof(RPCRES_LONG);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApiWithRes_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApiWithRes_rl_S:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_S;
		_xdr_result = (xdrproc_t) xdr_RPCRES_LONG;
		ReplyParaSize = sizeof(RPCRES_LONG);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApiWithRes_rl_S_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApiWithRes_rl_M:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_M;
		_xdr_result = (xdrproc_t) xdr_RPCRES_LONG;
		ReplyParaSize = sizeof(RPCRES_LONG);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApiWithRes_rl_M_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApiWithRes_rl_MM:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_MM;
		_xdr_result = (xdrproc_t) xdr_RPCRES_LONG;
		ReplyParaSize = sizeof(RPCRES_LONG);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApiWithRes_rl_MM_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApiWithRes_rl_L:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_L;
		_xdr_result = (xdrproc_t) xdr_RPCRES_LONG;
		ReplyParaSize = sizeof(RPCRES_LONG);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApiWithRes_rl_L_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApiWithRes_rl_LL:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_LL;
		_xdr_result = (xdrproc_t) xdr_RPCRES_LONG;
		ReplyParaSize = sizeof(RPCRES_LONG);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApiWithRes_rl_LL_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApiWithRes_rss:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_SS;
		_xdr_result = (xdrproc_t) xdr_RPCRES_SS;
		ReplyParaSize = sizeof(RPCRES_SS);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApiWithRes_rss_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApiWithRes_rss_S:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_S;
		_xdr_result = (xdrproc_t) xdr_RPCRES_SS;
		ReplyParaSize = sizeof(RPCRES_SS);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApiWithRes_rss_S_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApiWithRes_rss_M:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_M;
		_xdr_result = (xdrproc_t) xdr_RPCRES_SS;
		ReplyParaSize = sizeof(RPCRES_SS);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApiWithRes_rss_M_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApiWithRes_rss_MM:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_MM;
		_xdr_result = (xdrproc_t) xdr_RPCRES_SS;
		ReplyParaSize = sizeof(RPCRES_SS);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApiWithRes_rss_MM_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApiWithRes_rss_L:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_L;
		_xdr_result = (xdrproc_t) xdr_RPCRES_SS;
		ReplyParaSize = sizeof(RPCRES_SS);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApiWithRes_rss_L_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApiWithRes_S:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_SS;
		_xdr_result = (xdrproc_t) xdr_RPCRES_S;
		ReplyParaSize = sizeof(RPCRES_S);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApiWithRes_S_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApiWithRes_M:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_SS;
		_xdr_result = (xdrproc_t) xdr_RPCRES_M;
		ReplyParaSize = sizeof(RPCRES_M);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApiWithRes_M_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApiWithRes_MM:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_SS;
		_xdr_result = (xdrproc_t) xdr_RPCRES_MM;
		ReplyParaSize = sizeof(RPCRES_MM);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApiWithRes_MM_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApiWithRes_L:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_SS;
		_xdr_result = (xdrproc_t) xdr_RPCRES_L;
		ReplyParaSize = sizeof(RPCRES_L);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApiWithRes_L_0_svc;
		break;

	case SECURE_RPC_ToAgent_DtvApiWithRes_L_L:
		_xdr_argument = (xdrproc_t) xdr_SECURE_RPC_DTVAPI_L;
		_xdr_result = (xdrproc_t) xdr_RPCRES_L;
		ReplyParaSize = sizeof(RPCRES_L);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_DtvApiWithRes_L_L_0_svc;
		break;

	case SECURE_RPC_ToAgent_SecureKeyBox:
		_xdr_argument = (xdrproc_t) xdr_RPC_tee_rpc_cmd_t;
		_xdr_result = (xdrproc_t) xdr_int;
		ReplyParaSize = sizeof(int);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) SECURE_RPC_ToAgent_SecureKeyBox_0_svc;
		break;

	default:
#ifdef IS_SCPU
		RPC_EMERG("unknown procedure:pid = %d, procedureID = %d\n", (int)gettid(), (int)rpc->procedureID);
#endif
		return;
	}


	memset ((char *)&argument, 0, sizeof (argument));


	if (!rpc_getargs (rpc, (xdrproc_t) _xdr_argument, (caddr_t) &argument, opt)) {
		printf("get args error\n");
#ifdef IS_SCPU
		RPC_EMERG("rpc_getargs error:pid = %d, procedureID = %d\n", (int)gettid(), (int)rpc->procedureID);
#endif
		return;
	}

#ifdef IS_SCPU
	Q9527_DEBUG()

#endif
	pthread_mutex_unlock(pMutex);

	(*local)((char *)&argument, rpc, (char *)&retval);


	// When source msg is BLOCK_MODE,
	// we must help it reply
	// ps: reply mode is NON_BLOCK and use request's ringbuf type
	if (rpc->taskID != 0) {
	    SendReply(rpc->taskID, rpc->mycontext, (char *)&retval, ReplyParaSize,
			 (xdrproc_t) _xdr_result, opt);
	}

	return;
}


struct REG_STRUCT * SECURE_SYSTEM_0_register(struct REG_STRUCT *rnode) {

	return (struct REG_STRUCT *)ipc_register(rnode, SECURE_SYSTEM, 0,
		(void (*)(struct RPC_STRUCT *, int, pthread_mutex_t*))SECURE_SYSTEM_0);

}
