/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <VideoRPC_System.h>
#include <rt/misc/SVCFunc.h>
#include <rt/posix/pthread.h>
#include <RPCBaseDS.h>
#include <VideoRPCBaseDS.h>

void *memset( void *s, int c, unsigned int n );

static void
VIDEO_SYSTEM_0(RPC_STRUCT * rpc, int opt, pthread_mutex_t *pMutex)
{
	union {
		VIDEO_RPC_INSTANCE VIDEO_RPC_ToAgent_Create_0_arg;
		RPC_CONNECTION VIDEO_RPC_ToAgent_Connect_0_arg;
		RPC_RINGBUFFER VIDEO_RPC_ToAgent_InitRingBuffer_0_arg;
		long VIDEO_RPC_ToAgent_Run_0_arg;
		long VIDEO_RPC_ToAgent_Pause_0_arg;
		long VIDEO_RPC_ToAgent_Stop_0_arg;
		long VIDEO_RPC_ToAgent_Destroy_0_arg;
		long VIDEO_RPC_ToAgent_Flush_0_arg;
		VIDEO_RPC_SET_REFCLOCK VIDEO_RPC_ToAgent_SetRefClock_0_arg;
		VIDEO_INIT_DATA VIDEO_RPC_ToAgent_VideoCreate_0_arg;
		VIDEO_CONFIG_DATA VIDEO_RPC_ToAgent_VideoConfig_0_arg;
		long VIDEO_RPC_ToAgent_GetVideoConfigure_0_arg;
		long VIDEO_RPC_ToAgent_VideoMemoryConfig_0_arg;
		VIDEO_RPC_CONFIG_CHUNK VIDEO_RPC_ToAgent_VideoChunkConfig_0_arg;
		VIDEO_INIT_DATA VIDEO_RPC_ToAgent_VideoDestroy_0_arg;
		VIDEO_RPC_REQUEST_BUFFER VIDEO_RPC_ToAgent_RequestBuffer_0_arg;
		long VIDEO_RPC_ToAgent_ReleaseBuffer_0_arg;
		VIDEO_RPC_LOW_DELAY VIDEO_RPC_ToAgent_ConfigLowDelay_0_arg;
		VIDEO_RPC_DEC_CMPRS_CTRL VIDEO_RPC_DEC_ToAgent_CmprsCtrl_0_arg;
		long VIDEO_RPC_ToAgent_SetDebugMemory_0_arg;
		long VIDEO_RPC_ToAgent_VideoHalt_0_arg;
		VIDEO_RPC_YUYV_TO_RGB VIDEO_RPC_ToAgent_YUYV2RGB_0_arg;
		VIDEO_RPC_SET_SCALE VIDEO_RPC_ToAgent_SetScale_0_arg;
		SCALER_RPC_STRUCT VIDEO_RPC_ToAgent_ScalerDrv_0_arg;
		SCALER_RPC_SHARE_MEM VIDEO_RPC_ToAgent_SetShareMemAddr_0_arg;
		VIDEO_RPC_RESOURCE_INFO VIDEO_RPC_ToAgent_SetResourceInfo_0_arg;
		VIDEO_RPC_COMP_CTRL VIDEO_RPC_ToAgent_CompCtrl_0_arg;
		VIDEO_RPC_DEC_SET_SPEED VIDEO_RPC_DEC_ToAgent_SetSpeed_0_arg;
		VIDEO_RPC_DEC_SET_ERR_CONCEALMENT_LEVEL VIDEO_RPC_DEC_ToAgent_SetErrorConcealmentLevel_0_arg;
		VIDEO_RPC_DEC_INIT VIDEO_RPC_DEC_ToAgent_Init_0_arg;
		VIDEO_RPC_DEC_SET_DEBLOCK VIDEO_RPC_DEC_ToAgent_SetDeblock_0_arg;
		long VIDEO_RPC_DEC_ToAgent_GetVideoSequenceInfo_0_arg;
		VIDEO_RPC_DEC_BITSTREAM_BUFFER VIDEO_RPC_DEC_ToAgent_BitstreamValidation_0_arg;
		VIDEO_RPC_DEC_CAPABILITY VIDEO_RPC_DEC_ToAgent_Capability_0_arg;
		VIDEO_RPC_DEC_CC_BYPASS_MODE VIDEO_RPC_DEC_ToAgent_SetDecoderCCBypass_0_arg;
		VIDEO_RPC_DEC_SET_DNR VIDEO_RPC_DEC_ToAgent_SetDNR_0_arg;
		VIDEO_RPC_DEC_SET_REF_SYNC_LIMIT VIDEO_RPC_DEC_ToAgent_SetRefSyncLimit_0_arg;
		VIDEO_RPC_THUMBNAIL_SET_VSCALER_OUTFORMAT VIDEO_RPC_THUMBNAIL_ToAgent_SetVscalerOutputFormat_0_arg;
		VIDEO_RPC_THUMBNAIL_SET_THRESHOLD VIDEO_RPC_THUMBNAIL_ToAgent_SetThreshold_0_arg;
		VIDEO_RPC_FLASH_SET_OUTPUT VIDEO_RPC_FLASH_ToAgent_SetOutput_0_arg;
		VIDEO_RPC_THUMBNAIL_SET_STARTPIC VIDEO_RPC_THUMBNAIL_ToAgent_SetStartPictureNumber_0_arg;
		long VIDEO_RPC_DEC_ToAgent_GetMPEGSequenceHdr_0_arg;
		VIDEO_RPC_DEC_MPEG_SEQ_HDR VIDEO_RPC_DEC_ToAgent_SetMPEGSequenceHdr_0_arg;
		VIDEO_RPC_DEC_MPEG_SEQ_HDR VIDEO_RPC_DEC_ToAgent_GetMPEGSequenceHdr_New_0_arg;
		VIDEO_RPC_DEC_PARSE_FRAME_BOUNDARY VIDEO_RPC_DEC_ToAgent_ParseFrameBoundary_0_arg;
		VIDEO_RPC_DEC_DRIP_INFO VIDEO_RPC_DEC_ToAgent_SetDripDec_0_arg;
		VIDEO_RPC_DEC_BITSTREAM_BUFFER VIDEO_RPC_DEC_ToAgent_ParseResolution_0_arg;
		VIDEO_RPC_DEC_SET_DECODEMODE VIDEO_RPC_DEC_ToAgent_SetDecodeMode_0_arg;
		VIDEO_RPC_DEC_MEASURE_DECODE_TIME VIDEO_RPC_DEC_ToAgent_MeasureDecodeTime_0_arg;
		VIDEO_RPC_CAP_START_CAPTURE VIDEO_RPC_CAP_ToAgent_StartCapture_0_arg;
		VIDEO_RPC_CAP_STOP_CAPTURE VIDEO_RPC_CAP_ToAgent_StopCapture_0_arg;
		VIDEO_RPC_CAP_CAPTURE_ONE_FRAME VIDEO_RPC_CAP_ToAgent_CaptureOneFrame_0_arg;
		VIDEO_RPC_CAP_START_CAPTURE VIDEO_RPC_CAP_ToAgent_SetCaptureMode_0_arg;
		VIDEO_RPC_CAP_SET_FRAME_RATE VIDEO_RPC_CAP_ToAgent_SetFrameRate_0_arg;
		VIDEO_RPC_ENC_INIT VIDEO_RPC_ENC_ToAgent_Init_0_arg;
		VIDEO_RPC_ENC_VIDEOSOURCE VIDEO_RPC_ENC_ToAgent_SetVideoSource_0_arg;
		VIDEO_RPC_ENC_SOURCEFILE VIDEO_RPC_ENC_ToAgent_SetSourceFile_0_arg;
		VIDEO_RPC_ENC_SET_RESOLUTION VIDEO_RPC_ENC_ToAgent_SetResolution_0_arg;
		VIDEO_RPC_ENC_SET_NEW_RESOLUTION VIDEO_RPC_ENC_ToAgent_SetNewResolution_0_arg;
		VIDEO_RPC_ENC_SET_BITRATE VIDEO_RPC_ENC_ToAgent_SetBitRate_0_arg;
		VIDEO_RPC_ENC_SET_GOPSTRUCTURE VIDEO_RPC_ENC_ToAgent_SetGOPStructure_0_arg;
		VIDEO_RPC_ENC_SET_NEWGOPONSC VIDEO_RPC_ENC_ToAgent_SetNewGOPOnSceneChange_0_arg;
		VIDEO_RPC_ENC_SET_INV32DETECT VIDEO_RPC_ENC_ToAgent_SetInverseTelecineDetection_0_arg;
		VIDEO_RPC_ENC_SET_TF VIDEO_RPC_ENC_ToAgent_SetTF_0_arg;
		VIDEO_RPC_ENC_SET_NR VIDEO_RPC_ENC_ToAgent_SetNR_0_arg;
		VIDEO_RPC_ENC_SET_ENCFORMAT VIDEO_RPC_ENC_ToAgent_SetEncodeFormat_0_arg;
		VIDEO_RPC_ENC_CONFIG_CCDATA VIDEO_RPC_ENC_ToAgent_ConfigureCCData_0_arg;
		VIDEO_RPC_ENC_SET_CLOSEDGOPFREQ VIDEO_RPC_ENC_ToAgent_SetClosedGOPFrequency_0_arg;
		VIDEO_RPC_ENC_START_ENC VIDEO_RPC_ENC_ToAgent_StartRecord_0_arg;
		VIDEO_RPC_ENC_PAUSE_ENC VIDEO_RPC_ENC_ToAgent_PauseRecord_0_arg;
		VIDEO_RPC_ENC_STOP_ENC VIDEO_RPC_ENC_ToAgent_StopRecord_0_arg;
		VIDEO_RPC_ENC_CONFIG_VOBU VIDEO_RPC_ENC_ToAgent_ConfigVOBU_0_arg;
		VIDEO_RPC_ENC_MPEG_I_ENC VIDEO_RPC_ENC_ToAgent_MPEGIFrameEncode_0_arg;
		VIDEO_RPC_ENC_SET_VBID_WSS_FREQ VIDEO_RPC_ENC_ToAgent_SetVbidWssFreq_0_arg;
		long VIDEO_RPC_ENC_ToAgent_IsRunnable_0_arg;
		VIDEO_RPC_ENC_SET_VBV VIDEO_RPC_ENC_ToAgent_SetVBV_0_arg;
		VIDEO_RPC_ENC_SET_NONREALTIME VIDEO_RPC_ENC_ToAgent_SetNonRealTime_0_arg;
		VIDEO_RPC_ENC_SEND_TVD_INFO VIDEO_RPC_ENC_ToAgent_SendTVDInfo_0_arg;
		VIDEO_RPC_ENC_SET_FRAME_RATE VIDEO_RPC_ENC_ToAgent_SetFrameRate_0_arg;
		VIDEO_RPC_ENC_REQ_KEY_FRAME VIDEO_RPC_ENC_ToAgent_ReqKeyFrame_0_arg;
		VIDEO_RPC_ENC_SET_PROFILE VIDEO_RPC_ENC_ToAgent_SetProfile_0_arg;
		VIDEO_RPC_VOUT_SET_VIDEO_STANDARD VIDEO_RPC_VOUT_ToAgent_SetVideoStandard_0_arg;
		VIDEO_RPC_VOUT_SET_HDMI VIDEO_RPC_VOUT_ToAgent_SetHDMI_0_arg;
		VIDEO_RPC_VOUT_CONFIG_HDMI VIDEO_RPC_VOUT_ToAgent_ConfigHDMI_0_arg;
		VIDEO_RPC_VOUT_CONFIG_HDMI_INFO_FRAME VIDEO_RPC_VOUT_ToAgent_ConfigHdmiInfoFrame_0_arg;
		VIDEO_RPC_VOUT_CONFIG_VIDEO_STANDARD VIDEO_RPC_VOUT_ToAgent_ConfigVideoStandard_0_arg;
		VO_TV_TYPE VIDEO_RPC_VOUT_ToAgent_SetTVtype_0_arg;
		VIDEO_RPC_VOUT_SET_BKGRND VIDEO_RPC_VOUT_ToAgent_SetBackground_0_arg;
		VIDEO_RPC_VOUT_SET_MIXER_ORDER VIDEO_RPC_VOUT_ToAgent_SetMixerOrder_0_arg;
		VIDEO_RPC_VOUT_SET_CC VIDEO_RPC_VOUT_ToAgent_SetClosedCaption_0_arg;
		VIDEO_RPC_VOUT_SET_APS VIDEO_RPC_VOUT_ToAgent_SetAPS_0_arg;
		VIDEO_RPC_VOUT_SET_COPY_MODE VIDEO_RPC_VOUT_ToAgent_SetCopyMode_0_arg;
		VIDEO_RPC_VOUT_SET_AR VIDEO_RPC_VOUT_ToAgent_SetAspectRatio_0_arg;
		VIDEO_RPC_VOUT_CONFIG_DISP_WIN VIDEO_RPC_VOUT_ToAgent_ConfigureDisplayWindow_0_arg;
		u_char VIDEO_RPC_VOUT_ToAgent_SetV2alpha_0_arg;
		VIDEO_RPC_VOUT_SET_RESCALE_MODE VIDEO_RPC_VOUT_ToAgent_SetRescaleMode_0_arg;
		VIDEO_RPC_VOUT_SET_DEINT_MODE VIDEO_RPC_VOUT_ToAgent_SetDeintMode_0_arg;
		VIDEO_RPC_VOUT_ZOOM VIDEO_RPC_VOUT_ToAgent_Zoom_0_arg;
		VIDEO_RPC_VOUT_PAN_ZOOM VIDEO_RPC_VOUT_ToAgent_Pan_Zoom_0_arg;
		VIDEO_RPC_VOUT_TRANSPARENCY VIDEO_RPC_VOUT_ToAgent_SetTransparency_0_arg;
		VIDEO_RPC_VOUT_CONFIG_OSD VIDEO_RPC_VOUT_ToAgent_ConfigureOSD_0_arg;
		VIDEO_RPC_VOUT_CONFIG_OSD_PALETTE VIDEO_RPC_VOUT_ToAgent_ConfigureOSDPalette_0_arg;
		VIDEO_RPC_VOUT_CREATE_OSD_WIN VIDEO_RPC_VOUT_ToAgent_CreateOSDwindow_0_arg;
		VIDEO_RPC_VOUT_SET_OSD_WIN_PALETTE VIDEO_RPC_VOUT_ToAgent_SetOSDwindowPalette_0_arg;
		VIDEO_RPC_VOUT_MODIFY_OSD_WIN VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindow_0_arg;
		VIDEO_RPC_VOUT_MODIFY_OSD_WIN VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindowOnGo_0_arg;
		u_char VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindow_0_arg;
		VIDEO_RPC_VOUT_DELETE_OSD_WIN VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindowOnGo_0_arg;
		VIDEO_RPC_VOUT_DRAW_OSD_WIN VIDEO_RPC_VOUT_ToAgent_DrawOSDwindow_0_arg;
		VIDEO_RPC_VOUT_DRAW_OSD_WIN VIDEO_RPC_VOUT_ToAgent_DrawOSDwindowOnGo_0_arg;
		u_char VIDEO_RPC_VOUT_ToAgent_HideOSDwindow_0_arg;
		VIDEO_RPC_VOUT_HIDE_OSD_WIN VIDEO_RPC_VOUT_ToAgent_HideOSDwindowOnGo_0_arg;
		VIDEO_RPC_VOUT_CONFIG_OSD_CANVAS VIDEO_RPC_VOUT_ToAgent_ConfigOSDCanvas_0_arg;
		VIDEO_RPC_VOUT_CONFIG_GRAPHIC_CANVAS VIDEO_RPC_VOUT_ToAgent_ConfigureGraphicCanvas_0_arg;
		VIDEO_RPC_VOUT_CREATE_GRAPHIC_WIN VIDEO_RPC_VOUT_ToAgent_CreateGraphicWindow_0_arg;
		VIDEO_RPC_VOUT_HIDE_GRAPHIC_WIN VIDEO_RPC_VOUT_ToAgent_HideGraphicWindow_0_arg;
		VIDEO_RPC_VOUT_MODIFY_GRAPHIC_WIN VIDEO_RPC_VOUT_ToAgent_ModifyGraphicWindow_0_arg;
		VIDEO_RPC_VOUT_DELETE_GRAPHIC_WIN VIDEO_RPC_VOUT_ToAgent_DeleteGraphicWindow_0_arg;
		VIDEO_RPC_VOUT_DRAW_GRAPHIC_WIN VIDEO_RPC_VOUT_ToAgent_DrawGraphicWindow_0_arg;
		VIDEO_RPC_VOUT_DISPLAY_GRAPHIC VIDEO_RPC_VOUT_ToAgent_DisplayGraphic_0_arg;
		VIDEO_RPC_VOUT_HACK_GRAPHICCANVAS VIDEO_RPC_VOUT_ToAgent_HackGraphicCanvas_0_arg;
		VIDEO_RPC_VOUT_CONFIG_CURSOR VIDEO_RPC_VOUT_ToAgent_ConfigureCursor_0_arg;
		VIDEO_RPC_VOUT_CONFIG_MARS_CURSOR VIDEO_RPC_VOUT_ToAgent_ConfigureMarsCursor_0_arg;
		VIDEO_RPC_VOUT_DRAW_CURSOR VIDEO_RPC_VOUT_ToAgent_DrawCursor_0_arg;
		u_char VIDEO_RPC_VOUT_ToAgent_SetPeakingStrength_0_arg;
		u_char VIDEO_RPC_VOUT_ToAgent_SetBrightness_0_arg;
		u_char VIDEO_RPC_VOUT_ToAgent_SetHue_0_arg;
		u_char VIDEO_RPC_VOUT_ToAgent_SetSaturation_0_arg;
		u_char VIDEO_RPC_VOUT_ToAgent_SetContrast_0_arg;
		VIDEO_RPC_VOUT_CONFIG_COLOR_MATRIX VIDEO_RPC_VOUT_ToAgent_ConfigColorMatrix_0_arg;
		VIDEO_RPC_VOUT_VIDEO_CAPTURE VIDEO_RPC_VOUT_ToAgent_VideoCapture_0_arg;
		short VIDEO_RPC_VOUT_ToAgent_SetSubtitleYoffset_0_arg;
		short VIDEO_RPC_VOUT_ToAgent_SwitchSPDomination_0_arg;
		VIDEO_RPC_VO_FILTER_DISPLAY VIDEO_RPC_VO_FILTER_ToAgent_Display_0_arg;
		VIDEO_RPC_VO_FILTER_CAPTURE VIDEO_RPC_VO_FILTER_ToAgent_Capture_0_arg;
		VIDEO_RPC_VO_FILTER_SET_SPEED VIDEO_RPC_VO_FILTER_ToAgent_SetSpeed_0_arg;
		long VIDEO_RPC_VO_FILTER_ToAgent_Step_0_arg;
		VIDEO_RPC_VO_FILTER_SHOW_STILL_PIC VIDEO_RPC_VO_FILTER_ToAgent_ShowStillPicture_0_arg;
		VIDEO_RPC_VO_FILTER_FILL_VIDEO_BORDER VIDEO_RPC_VO_FILTER_ToAgent_FillVideoBorder_0_arg;
		VIDEO_RPC_VO_FILTER_SET_FAST_DISPLAY VIDEO_RPC_VO_FILTER_ToAgent_SetFastDisplay_0_arg;
		VIDEO_RPC_VO_FILTER_ENABLE_3D_MODE_DETECT VIDEO_RPC_VO_FILTER_ToAgent_Enable3DModeDetect_0_arg;
		VIDEO_RPC_VO_FILTER_CLEAR_VIDEO VIDEO_RPC_VO_FILTER_ToAgent_ClearVideo_0_arg;
		long VIDEO_RPC_VO_FILTER_ToAgent_FlushVideoOut_0_arg;
		VIDEO_RPC_VO_FILTER_Config_SyncAV VIDEO_RPC_VO_FILTER_ToAgent_ConfigSyncAV_0_arg;
		VIDEO_RPC_VO_FILTER_Config_VoFreeze VIDEO_RPC_VO_FILTER_ToAgent_ConfigVoFreeze_0_arg;
		VIDEO_RPC_VO_FILTER_Config_DisplayDelay VIDEO_RPC_VO_FILTER_ToAgent_ConfigDisplayDelay_0_arg;
		VIDEO_RPC_VO_FILTER_ConnectVDec VIDEO_RPC_VO_FILTER_ToAgent_ConnectVDec_0_arg;
		VIDEO_RPC_VO_FILTER_Config_Mastership VIDEO_RPC_VO_FILTER_ToAgent_ConfigMastership_0_arg;
		VIDEO_RPC_VO_FILTER_Config_Dual3D VIDEO_RPC_VO_FILTER_ToAgent_ConfigDual3D_0_arg;
		VIDEO_RPC_VO_FILTER_SET_SOURCE_TYPE VIDEO_RPC_VO_FILTER_ToAgent_SetSourceType_0_arg;
		VIDEO_RPC_VOUT_VODMA_ENABLE VIDEO_RPC_VOUT_ToAgent_VodmaEnable_0_arg;
		VIDEO_RPC_VOUT_FRAMERATE_CONTROL_STRUCT VIDEO_RPC_VOUT_ToAgent_VodmaFrameRateControl_0_arg;
		VIDEO_RPC_VOUT_DECIMATE_STRUCT VIDEO_RPC_VOUT_ToAgent_VideoDecimate_0_arg;
		VIDEO_RPC_VOUT_SET_SCALER_AR_MODE VIDEO_RPC_VOUT_ToAgent_SetScalerARMode_0_arg;
		VIDEO_RPC_VOUT_CONFIG_SCALER_AR_CUSTOMER_MODE VIDEO_RPC_VOUT_ToAgent_ConfigScalerARCustomerMode_0_arg;
		VIDEO_RPC_VOUT_VODMA_VFLIP_ENABLE VIDEO_RPC_VOUT_ToAgent_ConfigVodmaVFlip_0_arg;
		VIDEO_RPC_VOUT_VODMA_ZOOM_RATE VIDEO_RPC_VOUT_ToAgent_ConfigVodmaZoom_0_arg;
		VIDEO_RPC_VOUT_VODMA_POS_FIUNTUNE VIDEO_RPC_VOUT_ToAgent_ConfigVodmaPosFinetune_0_arg;
		VIDEO_RPC_VOUT_FORCEBG_CTRL VIDEO_RPC_VOUT_ToAgent_ConfigVoForceBG_0_arg;
		VIDEO_RPC_VOUT_CONFIG_SCALEUP VIDEO_RPC_VOUT_ToAgent_ConfigVoScaleUp_0_arg;
		VIDEO_RPC_VOUT_VODMA_CONFIG_VSGEN_IV_SRC VIDEO_RPC_VOUT_FILTER_ToAgent_VODMA_ConfigVsyncGenIvSrc_0_arg;
		VIDEO_RPC_VOUT_VSCINPUTTYPE VIDEO_RPC_VOUT_ToAgent_VSCINPUTTYPE_TO_VODMA_0_arg;
		long VIDEO_RPC_ToAgent_SetScalerVBICCBuf_0_arg;
		VIDEO_RPC_VOUT_CURRENT_BLK_TO_SEQ VIDEO_RPC_VOUT_ToAgent_CurrentBlockToSequential_0_arg;
		VIDEO_RPC_VOUT_SET_3D_MODE VIDEO_RPC_VOUT_ToAgent_Set_3D_Mode_0_arg;
		VIDEO_RPC_VOUT_SET_3D_OUTPUT_MODE VIDEO_RPC_VOUT_ToAgent_Set_3D_Output_Mode_0_arg;
		VIDEO_RPC_VOUT_FORCE2D_MODE VIDEO_RPC_VOUT_ToAgent_Force2D_0_arg;
		VO_2D3D_CONFIG VIDEO_RPC_ToAgent_Set2Dcvt3DVOConfig_0_arg;
		VIDEO_RPC_VOUT_CONFIG_HDMI_3D VIDEO_RPC_VOUT_ToAgent_ConfigHDMI_3D_0_arg;
		VIDEO_RPC_VOUT_FORCE_HDMI_2D VIDEO_RPC_VOUT_ToAgent_Force_HDMI_2D_0_arg;
		VO_CAPTURE_CONFIG VIDEO_RPC_ToAgent_SetVOCaptureConfig_0_arg;
		VIDEO_RPC_VOUT_SET_OSD_4K2K_MODE VIDEO_RPC_VOUT_ToAgent_Set_OSD_4K2K_Mode_0_arg;
		VIDEO_RPC_VOUT_4K2K_SEQUENCE_CONTORL VIDEO_RPC_VOUT_ToAgent_4K2K_Sequence_Control_0_arg;
		VIDEO_RPC_VOUT_CONFIG_3D_STRUCT VIDEO_RPC_VOUT_ToAgent_ConfigGDMA3D_0_arg;
		VIDEO_RPC_VOUT_CONFIG_3D_OFFSET_STRUCT VIDEO_RPC_VOUT_ToAgent_ConfigGDMA3DOffset_0_arg;
		u_char VIDEO_RPC_VOUT_ToAgent_ConfigGDMAVFlip_0_arg;
		u_char VIDEO_RPC_VOUT_ToAgent_Force_VO_Chroma_422_0_arg;
		VIDEO_RPC_VO_FILTER_SET_APP_TYPE VIDEO_RPC_VO_FILTER_ToAgent_SetAppType_0_arg;
		VIDEO_RPC_SUBPIC_DEC_ENABLE_SUBPIC VIDEO_RPC_SUBPIC_DEC_ToAgent_EnableSubPicture_0_arg;
		long VIDEO_RPC_SUBPIC_DEC_ToAgent_ShowSubPicture_0_arg;
		long VIDEO_RPC_SUBPIC_DEC_ToAgent_HideSubPicture_0_arg;
		VIDEO_RPC_SUBPIC_DEC_CONFIGURE VIDEO_RPC_SUBPIC_DEC_ToAgent_Configure_0_arg;
		VIDEO_RPC_SUBPIC_DEC_PAGE VIDEO_RPC_SUBPIC_DEC_ToAgent_Page_0_arg;
		VIDEO_RPC_TVD_CONFIG VIDEO_RPC_TVD_ToAgent_TVD_Configure_0_arg;
		VIDEO_RPC_TVD_INPUT_FORMAT VIDEO_RPC_TVD_ToAgent_Select_INFMT_0_arg;
		VIDEO_RPC_TVD_YC_SEP_MODE VIDEO_RPC_TVD_ToAgent_YC_Separation_0_arg;
		VIDEO_RPC_TVD_VBI_CTRL VIDEO_RPC_TVD_ToAgent_VBI_Ctrl_0_arg;
		VIDEO_RPC_TVD_ADJ_CONTRAST VIDEO_RPC_TVD_ToAgent_Adjust_Contrast_0_arg;
		VIDEO_RPC_TVD_ADJ_BRIGHTNESS VIDEO_RPC_TVD_ToAgent_Adjust_Brightness_0_arg;
		VIDEO_RPC_TVD_ADJ_SATURATION VIDEO_RPC_TVD_ToAgent_Adjust_Saturation_0_arg;
		VIDEO_RPC_TVD_ADJ_HUE VIDEO_RPC_TVD_ToAgent_Adjust_Hue_0_arg;
		VIDEO_RPC_TVD_BLUE_MODE VIDEO_RPC_TVD_ToAgent_Blue_Screen_Ctrl_0_arg;
		VIDEO_RPC_TVD_VIDEO_FORMAT VIDEO_RPC_TVD_ToAgent_Query_VIDEO_FORMAT_0_arg;
		VIDEO_RPC_VIN_ADJ_SCALE_COEF VIDEO_RPC_VIN_ToAgent_Adjust_Scale_Coef_0_arg;
		long VIDEO_RPC_TVD_ToAgent_ChangeChannel_Start_0_arg;
		VIDEO_RPC_JPEG_DEC VIDEO_RPC_JPEG_ToAgent_DEC_0_arg;
		VIDEO_RPC_JPEG_DEC_BATCH VIDEO_RPC_JPEG_ToAgent_DEC_BATCH_0_arg;
		VIDEO_RPC_TRANSITION_EFFECT VIDEO_RPC_TRANSITION_ToAgent_Start_0_arg;
		VIDEO_RPC_MIXER_FILTER_CONFIGURE VIDEO_RPC_MIXER_FILTER_ToAgent_Configure_0_arg;
		VIDEO_RPC_MIXER_FILTER_CONFIGURE_WIN VIDEO_RPC_MIXER_FILTER_ToAgent_ConfigureWindow_0_arg;
		VIDEO_RPC_MIXER_FILTER_SET_MASTER_WIN VIDEO_RPC_MIXER_FILTER_ToAgent_SetMasterWindow_0_arg;
		VIDEO_RPC_MIXER_PLAY_ONE_MOTION_JPEG_FRAME VIDEO_RPC_MIXER_ToAgent_PlayOneMotionJpegFrame_0_arg;
		VIDEO_RPC_MIXER_FILTER_CAPTURE VIDEO_RPC_MIXER_FILTER_ToAgent_Capture_0_arg;
		VIDEO_RPC_DIRECT_VO_OPEN VIDEO_RPC_DIRECT_VO_ToAgent_open_0_arg;
		VIDEO_RPC_DIRECT_VO_RUN VIDEO_RPC_DIRECT_VO_ToAgent_run_0_arg;
		VIDEO_RPC_DIRECT_VO_STOP VIDEO_RPC_DIRECT_VO_ToAgent_stop_0_arg;
		VIDEO_RPC_DIRECT_VO_FLUSH VIDEO_RPC_DIRECT_VO_ToAgent_flush_0_arg;
		VIDEO_RPC_DOLBY_VISION_HDMI_SET_DETECT_ENABLE VIDEO_RPC_DOLBY_VISION_HDMI_Set_Detect_Enable_0_arg;
		VIDEO_RPC_DOLBY_VISION_HDMI_GET_DETECT_INFO VIDEO_RPC_DOLBY_VISION_HDMI_Get_Detect_Info_0_arg;
		VIDEO_RPC_DOLBY_VISION_HDMI_SET_DISPLAY_ENABLE VIDEO_RPC_DOLBY_VISION_HDMI_Set_Display_Enable_0_arg;
		VIDEO_RPC_K2V_PARAM VIDEO_RPC_ToAgent_K2VParameter_0_arg;
		VIDEO_RPC_VO_PHOTO_OPEN_T VIDEO_RPC_VO_PHOTO_ToAgent_Open_0_arg;
		VIDEO_RPC_VO_PHOTO_CONFIG_T VIDEO_RPC_VO_PHOTO_ToAgent_Config_0_arg;
		VIDEO_RPC_VO_DISPLAYPICTURE_T VIDEO_RPC_VO_PHOTO_ToAgent_DisplayPicture_0_arg;
		u_int VIDEO_RPC_VO_PHOTO_ToAgent_RedrawPicture_0_arg;
		u_int VIDEO_RPC_VO_PHOTO_ToAgent_Close_0_arg;
		VIDEO_RPC_VO_GETDEVICECAPABILITY_T VIDEO_RPC_VO_PHOTO_ToAgent_GetDeviceCapability_0_arg;
	} argument;

	union {
		RPCRES_LONG VIDEO_RPC_ToAgent_Create_0_ret;
		HRESULT VIDEO_RPC_ToAgent_Connect_0_ret;
		HRESULT VIDEO_RPC_ToAgent_InitRingBuffer_0_ret;
		HRESULT VIDEO_RPC_ToAgent_Run_0_ret;
		HRESULT VIDEO_RPC_ToAgent_Pause_0_ret;
		HRESULT VIDEO_RPC_ToAgent_Stop_0_ret;
		HRESULT VIDEO_RPC_ToAgent_Destroy_0_ret;
		HRESULT VIDEO_RPC_ToAgent_Flush_0_ret;
		HRESULT VIDEO_RPC_ToAgent_SetRefClock_0_ret;
		HRESULT VIDEO_RPC_ToAgent_VideoCreate_0_ret;
		HRESULT VIDEO_RPC_ToAgent_VideoConfig_0_ret;
		VIDEO_CONFIG_DATA VIDEO_RPC_ToAgent_GetVideoConfigure_0_ret;
		VIDEO_RPC_VIDEO_FREE_MEMORY VIDEO_RPC_ToAgent_VideoMemoryConfig_0_ret;
		HRESULT VIDEO_RPC_ToAgent_VideoChunkConfig_0_ret;
		HRESULT VIDEO_RPC_ToAgent_VideoDestroy_0_ret;
		RPCRES_LONG VIDEO_RPC_ToAgent_RequestBuffer_0_ret;
		HRESULT VIDEO_RPC_ToAgent_ReleaseBuffer_0_ret;
		HRESULT VIDEO_RPC_ToAgent_ConfigLowDelay_0_ret;
		HRESULT VIDEO_RPC_DEC_ToAgent_CmprsCtrl_0_ret;
		HRESULT VIDEO_RPC_ToAgent_SetDebugMemory_0_ret;
		HRESULT VIDEO_RPC_ToAgent_VideoHalt_0_ret;
		HRESULT VIDEO_RPC_ToAgent_YUYV2RGB_0_ret;
		HRESULT VIDEO_RPC_ToAgent_SetScale_0_ret;
		HRESULT VIDEO_RPC_ToAgent_ScalerDrv_0_ret;
		HRESULT VIDEO_RPC_ToAgent_SetShareMemAddr_0_ret;
		HRESULT VIDEO_RPC_ToAgent_SetResourceInfo_0_ret;
		HRESULT VIDEO_RPC_ToAgent_CompCtrl_0_ret;
		HRESULT VIDEO_RPC_DEC_ToAgent_SetSpeed_0_ret;
		HRESULT VIDEO_RPC_DEC_ToAgent_SetErrorConcealmentLevel_0_ret;
		HRESULT VIDEO_RPC_DEC_ToAgent_Init_0_ret;
		HRESULT VIDEO_RPC_DEC_ToAgent_SetDeblock_0_ret;
		VIDEO_RPC_DEC_SEQ_INFO VIDEO_RPC_DEC_ToAgent_GetVideoSequenceInfo_0_ret;
		VIDEO_RPC_DEC_BV_RESULT VIDEO_RPC_DEC_ToAgent_BitstreamValidation_0_ret;
		HRESULT VIDEO_RPC_DEC_ToAgent_Capability_0_ret;
		HRESULT VIDEO_RPC_DEC_ToAgent_SetDecoderCCBypass_0_ret;
		HRESULT VIDEO_RPC_DEC_ToAgent_SetDNR_0_ret;
		HRESULT VIDEO_RPC_DEC_ToAgent_SetRefSyncLimit_0_ret;
		HRESULT VIDEO_RPC_THUMBNAIL_ToAgent_SetVscalerOutputFormat_0_ret;
		HRESULT VIDEO_RPC_THUMBNAIL_ToAgent_SetThreshold_0_ret;
		HRESULT VIDEO_RPC_FLASH_ToAgent_SetOutput_0_ret;
		HRESULT VIDEO_RPC_THUMBNAIL_ToAgent_SetStartPictureNumber_0_ret;
		VIDEO_RPC_DEC_MPEG_SEQ_HDR VIDEO_RPC_DEC_ToAgent_GetMPEGSequenceHdr_0_ret;
		HRESULT VIDEO_RPC_DEC_ToAgent_SetMPEGSequenceHdr_0_ret;
		HRESULT VIDEO_RPC_DEC_ToAgent_GetMPEGSequenceHdr_New_0_ret;
		HRESULT VIDEO_RPC_DEC_ToAgent_ParseFrameBoundary_0_ret;
		VIDEO_RPC_DEC_DRIP_RESULT VIDEO_RPC_DEC_ToAgent_SetDripDec_0_ret;
		VIDEO_RPC_DEC_PV_RESULT VIDEO_RPC_DEC_ToAgent_ParseResolution_0_ret;
		HRESULT VIDEO_RPC_DEC_ToAgent_SetDecodeMode_0_ret;
		HRESULT VIDEO_RPC_DEC_ToAgent_MeasureDecodeTime_0_ret;
		HRESULT VIDEO_RPC_CAP_ToAgent_StartCapture_0_ret;
		HRESULT VIDEO_RPC_CAP_ToAgent_StopCapture_0_ret;
		HRESULT VIDEO_RPC_CAP_ToAgent_CaptureOneFrame_0_ret;
		HRESULT VIDEO_RPC_CAP_ToAgent_SetCaptureMode_0_ret;
		HRESULT VIDEO_RPC_CAP_ToAgent_SetFrameRate_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_Init_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetVideoSource_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetSourceFile_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetResolution_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetNewResolution_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetBitRate_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetGOPStructure_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetNewGOPOnSceneChange_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetInverseTelecineDetection_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetTF_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetNR_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetEncodeFormat_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_ConfigureCCData_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetClosedGOPFrequency_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_StartRecord_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_PauseRecord_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_StopRecord_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_ConfigVOBU_0_ret;
		RPCRES_LONG VIDEO_RPC_ENC_ToAgent_MPEGIFrameEncode_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetVbidWssFreq_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_IsRunnable_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetVBV_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetNonRealTime_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SendTVDInfo_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetFrameRate_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_ReqKeyFrame_0_ret;
		HRESULT VIDEO_RPC_ENC_ToAgent_SetProfile_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetVideoStandard_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetHDMI_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigHDMI_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigHdmiInfoFrame_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigVideoStandard_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetTVtype_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetBackground_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetMixerOrder_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetClosedCaption_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetAPS_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetCopyMode_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetAspectRatio_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigureDisplayWindow_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetV2alpha_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetRescaleMode_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetDeintMode_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_Zoom_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_Pan_Zoom_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetTransparency_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigureOSD_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigureOSDPalette_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_CreateOSDwindow_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetOSDwindowPalette_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindow_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindowOnGo_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindow_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindowOnGo_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_DrawOSDwindow_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_DrawOSDwindowOnGo_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_HideOSDwindow_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_HideOSDwindowOnGo_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigOSDCanvas_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigureGraphicCanvas_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_CreateGraphicWindow_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_HideGraphicWindow_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ModifyGraphicWindow_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_DeleteGraphicWindow_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_DrawGraphicWindow_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_DisplayGraphic_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_HackGraphicCanvas_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigureCursor_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigureMarsCursor_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_DrawCursor_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetPeakingStrength_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetBrightness_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetHue_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetSaturation_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetContrast_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigColorMatrix_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_VideoCapture_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetSubtitleYoffset_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SwitchSPDomination_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_Display_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_Capture_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_SetSpeed_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_Step_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_ShowStillPicture_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_FillVideoBorder_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_SetFastDisplay_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_Enable3DModeDetect_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_ClearVideo_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_FlushVideoOut_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_ConfigSyncAV_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_ConfigVoFreeze_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_ConfigDisplayDelay_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_ConnectVDec_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_ConfigMastership_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_ConfigDual3D_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_SetSourceType_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_VodmaEnable_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_VodmaFrameRateControl_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_VideoDecimate_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_SetScalerARMode_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigScalerARCustomerMode_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigVodmaVFlip_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigVodmaZoom_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigVodmaPosFinetune_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigVoForceBG_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigVoScaleUp_0_ret;
		HRESULT VIDEO_RPC_VOUT_FILTER_ToAgent_VODMA_ConfigVsyncGenIvSrc_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_VSCINPUTTYPE_TO_VODMA_0_ret;
		HRESULT VIDEO_RPC_ToAgent_SetScalerVBICCBuf_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_CurrentBlockToSequential_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_Set_3D_Mode_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_Set_3D_Output_Mode_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_Force2D_0_ret;
		HRESULT VIDEO_RPC_ToAgent_Set2Dcvt3DVOConfig_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigHDMI_3D_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_Force_HDMI_2D_0_ret;
		HRESULT VIDEO_RPC_ToAgent_SetVOCaptureConfig_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_Set_OSD_4K2K_Mode_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_4K2K_Sequence_Control_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigGDMA3D_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigGDMA3DOffset_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_ConfigGDMAVFlip_0_ret;
		HRESULT VIDEO_RPC_VOUT_ToAgent_Force_VO_Chroma_422_0_ret;
		HRESULT VIDEO_RPC_VO_FILTER_ToAgent_SetAppType_0_ret;
		HRESULT VIDEO_RPC_SUBPIC_DEC_ToAgent_EnableSubPicture_0_ret;
		HRESULT VIDEO_RPC_SUBPIC_DEC_ToAgent_ShowSubPicture_0_ret;
		HRESULT VIDEO_RPC_SUBPIC_DEC_ToAgent_HideSubPicture_0_ret;
		HRESULT VIDEO_RPC_SUBPIC_DEC_ToAgent_Configure_0_ret;
		HRESULT VIDEO_RPC_SUBPIC_DEC_ToAgent_Page_0_ret;
		HRESULT VIDEO_RPC_TVD_ToAgent_TVD_Configure_0_ret;
		HRESULT VIDEO_RPC_TVD_ToAgent_Select_INFMT_0_ret;
		HRESULT VIDEO_RPC_TVD_ToAgent_YC_Separation_0_ret;
		HRESULT VIDEO_RPC_TVD_ToAgent_VBI_Ctrl_0_ret;
		HRESULT VIDEO_RPC_TVD_ToAgent_Adjust_Contrast_0_ret;
		HRESULT VIDEO_RPC_TVD_ToAgent_Adjust_Brightness_0_ret;
		HRESULT VIDEO_RPC_TVD_ToAgent_Adjust_Saturation_0_ret;
		HRESULT VIDEO_RPC_TVD_ToAgent_Adjust_Hue_0_ret;
		HRESULT VIDEO_RPC_TVD_ToAgent_Blue_Screen_Ctrl_0_ret;
		HRESULT VIDEO_RPC_TVD_ToAgent_Query_VIDEO_FORMAT_0_ret;
		HRESULT VIDEO_RPC_VIN_ToAgent_Adjust_Scale_Coef_0_ret;
		CHANNEL_RES VIDEO_RPC_TVD_ToAgent_ChangeChannel_Start_0_ret;
		HRESULT VIDEO_RPC_JPEG_ToAgent_DEC_0_ret;
		HRESULT VIDEO_RPC_JPEG_ToAgent_DEC_BATCH_0_ret;
		HRESULT VIDEO_RPC_TRANSITION_ToAgent_Start_0_ret;
		HRESULT VIDEO_RPC_MIXER_FILTER_ToAgent_Configure_0_ret;
		HRESULT VIDEO_RPC_MIXER_FILTER_ToAgent_ConfigureWindow_0_ret;
		HRESULT VIDEO_RPC_MIXER_FILTER_ToAgent_SetMasterWindow_0_ret;
		HRESULT VIDEO_RPC_MIXER_ToAgent_PlayOneMotionJpegFrame_0_ret;
		HRESULT VIDEO_RPC_MIXER_FILTER_ToAgent_Capture_0_ret;
		HRESULT VIDEO_RPC_DIRECT_VO_ToAgent_open_0_ret;
		HRESULT VIDEO_RPC_DIRECT_VO_ToAgent_run_0_ret;
		HRESULT VIDEO_RPC_DIRECT_VO_ToAgent_stop_0_ret;
		HRESULT VIDEO_RPC_DIRECT_VO_ToAgent_flush_0_ret;
		HRESULT VIDEO_RPC_DOLBY_VISION_HDMI_Set_Detect_Enable_0_ret;
		HRESULT VIDEO_RPC_DOLBY_VISION_HDMI_Get_Detect_Info_0_ret;
		HRESULT VIDEO_RPC_DOLBY_VISION_HDMI_Set_Display_Enable_0_ret;
		HRESULT VIDEO_RPC_ToAgent_K2VParameter_0_ret;
		VIDEO_RPC_DEC_PV_RESULT VIDEO_RPC_VO_PHOTO_ToAgent_Open_0_ret;
		HRESULT VIDEO_RPC_VO_PHOTO_ToAgent_Config_0_ret;
		HRESULT VIDEO_RPC_VO_PHOTO_ToAgent_DisplayPicture_0_ret;
		HRESULT VIDEO_RPC_VO_PHOTO_ToAgent_RedrawPicture_0_ret;
		HRESULT VIDEO_RPC_VO_PHOTO_ToAgent_Close_0_ret;
		HRESULT VIDEO_RPC_VO_PHOTO_ToAgent_GetDeviceCapability_0_ret;
	} retval;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct RPC_STRUCT *, char *);
	int ReplyParaSize;


	switch (rpc->procedureID) {
	case VIDEO_RPC_ToAgent_Create:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_INSTANCE;
		_xdr_result = (xdrproc_t) xdr_RPCRES_LONG;
		ReplyParaSize = sizeof(RPCRES_LONG);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_Create_0_svc;
		break;

	case VIDEO_RPC_ToAgent_Connect:
		_xdr_argument = (xdrproc_t) xdr_RPC_CONNECTION;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_Connect_0_svc;
		break;

	case VIDEO_RPC_ToAgent_InitRingBuffer:
		_xdr_argument = (xdrproc_t) xdr_RPC_RINGBUFFER;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_InitRingBuffer_0_svc;
		break;

	case VIDEO_RPC_ToAgent_Run:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_Run_0_svc;
		break;

	case VIDEO_RPC_ToAgent_Pause:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_Pause_0_svc;
		break;

	case VIDEO_RPC_ToAgent_Stop:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_Stop_0_svc;
		break;

	case VIDEO_RPC_ToAgent_Destroy:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_Destroy_0_svc;
		break;

	case VIDEO_RPC_ToAgent_Flush:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_Flush_0_svc;
		break;

	case VIDEO_RPC_ToAgent_SetRefClock:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_SET_REFCLOCK;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_SetRefClock_0_svc;
		break;

	case VIDEO_RPC_ToAgent_VideoCreate:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_INIT_DATA;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_VideoCreate_0_svc;
		break;

	case VIDEO_RPC_ToAgent_VideoConfig:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_CONFIG_DATA;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_VideoConfig_0_svc;
		break;

	case VIDEO_RPC_ToAgent_GetVideoConfigure:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_VIDEO_CONFIG_DATA;
		ReplyParaSize = sizeof(VIDEO_CONFIG_DATA);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_GetVideoConfigure_0_svc;
		break;

	case VIDEO_RPC_ToAgent_VideoMemoryConfig:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_VIDEO_RPC_VIDEO_FREE_MEMORY;
		ReplyParaSize = sizeof(VIDEO_RPC_VIDEO_FREE_MEMORY);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_VideoMemoryConfig_0_svc;
		break;

	case VIDEO_RPC_ToAgent_VideoChunkConfig:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_CONFIG_CHUNK;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_VideoChunkConfig_0_svc;
		break;

	case VIDEO_RPC_ToAgent_VideoDestroy:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_INIT_DATA;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_VideoDestroy_0_svc;
		break;

	case VIDEO_RPC_ToAgent_RequestBuffer:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_REQUEST_BUFFER;
		_xdr_result = (xdrproc_t) xdr_RPCRES_LONG;
		ReplyParaSize = sizeof(RPCRES_LONG);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_RequestBuffer_0_svc;
		break;

	case VIDEO_RPC_ToAgent_ReleaseBuffer:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_ReleaseBuffer_0_svc;
		break;

	case VIDEO_RPC_ToAgent_ConfigLowDelay:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_LOW_DELAY;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_ConfigLowDelay_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_CmprsCtrl:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_CMPRS_CTRL;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_CmprsCtrl_0_svc;
		break;

	case VIDEO_RPC_ToAgent_SetDebugMemory:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_SetDebugMemory_0_svc;
		break;

	case VIDEO_RPC_ToAgent_VideoHalt:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_VideoHalt_0_svc;
		break;

	case VIDEO_RPC_ToAgent_YUYV2RGB:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_YUYV_TO_RGB;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_YUYV2RGB_0_svc;
		break;

	case VIDEO_RPC_ToAgent_SetScale:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_SET_SCALE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_SetScale_0_svc;
		break;

	case VIDEO_RPC_ToAgent_ScalerDrv:
		_xdr_argument = (xdrproc_t) xdr_SCALER_RPC_STRUCT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_ScalerDrv_0_svc;
		break;

	case VIDEO_RPC_ToAgent_SetShareMemAddr:
		_xdr_argument = (xdrproc_t) xdr_SCALER_RPC_SHARE_MEM;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_SetShareMemAddr_0_svc;
		break;

	case VIDEO_RPC_ToAgent_SetResourceInfo:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_RESOURCE_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_SetResourceInfo_0_svc;
		break;

	case VIDEO_RPC_ToAgent_CompCtrl:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_COMP_CTRL;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_CompCtrl_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_SetSpeed:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_SET_SPEED;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_SetSpeed_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_SetErrorConcealmentLevel:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_SET_ERR_CONCEALMENT_LEVEL;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_SetErrorConcealmentLevel_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_Init:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_INIT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_Init_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_SetDeblock:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_SET_DEBLOCK;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_SetDeblock_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_GetVideoSequenceInfo:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_VIDEO_RPC_DEC_SEQ_INFO;
		ReplyParaSize = sizeof(VIDEO_RPC_DEC_SEQ_INFO);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_GetVideoSequenceInfo_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_BitstreamValidation:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_BITSTREAM_BUFFER;
		_xdr_result = (xdrproc_t) xdr_VIDEO_RPC_DEC_BV_RESULT;
		ReplyParaSize = sizeof(VIDEO_RPC_DEC_BV_RESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_BitstreamValidation_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_Capability:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_CAPABILITY;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_Capability_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_SetDecoderCCBypass:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_CC_BYPASS_MODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_SetDecoderCCBypass_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_SetDNR:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_SET_DNR;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_SetDNR_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_SetRefSyncLimit:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_SET_REF_SYNC_LIMIT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_SetRefSyncLimit_0_svc;
		break;

	case VIDEO_RPC_THUMBNAIL_ToAgent_SetVscalerOutputFormat:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_THUMBNAIL_SET_VSCALER_OUTFORMAT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_THUMBNAIL_ToAgent_SetVscalerOutputFormat_0_svc;
		break;

	case VIDEO_RPC_THUMBNAIL_ToAgent_SetThreshold:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_THUMBNAIL_SET_THRESHOLD;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_THUMBNAIL_ToAgent_SetThreshold_0_svc;
		break;

	case VIDEO_RPC_FLASH_ToAgent_SetOutput:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_FLASH_SET_OUTPUT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_FLASH_ToAgent_SetOutput_0_svc;
		break;

	case VIDEO_RPC_THUMBNAIL_ToAgent_SetStartPictureNumber:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_THUMBNAIL_SET_STARTPIC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_THUMBNAIL_ToAgent_SetStartPictureNumber_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_GetMPEGSequenceHdr:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_VIDEO_RPC_DEC_MPEG_SEQ_HDR;
		ReplyParaSize = sizeof(VIDEO_RPC_DEC_MPEG_SEQ_HDR);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_GetMPEGSequenceHdr_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_SetMPEGSequenceHdr:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_MPEG_SEQ_HDR;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_SetMPEGSequenceHdr_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_GetMPEGSequenceHdr_New:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_MPEG_SEQ_HDR;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_GetMPEGSequenceHdr_New_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_ParseFrameBoundary:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_PARSE_FRAME_BOUNDARY;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_ParseFrameBoundary_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_SetDripDec:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_DRIP_INFO;
		_xdr_result = (xdrproc_t) xdr_VIDEO_RPC_DEC_DRIP_RESULT;
		ReplyParaSize = sizeof(VIDEO_RPC_DEC_DRIP_RESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_SetDripDec_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_ParseResolution:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_BITSTREAM_BUFFER;
		_xdr_result = (xdrproc_t) xdr_VIDEO_RPC_DEC_PV_RESULT;
		ReplyParaSize = sizeof(VIDEO_RPC_DEC_PV_RESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_ParseResolution_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_SetDecodeMode:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_SET_DECODEMODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_SetDecodeMode_0_svc;
		break;

	case VIDEO_RPC_DEC_ToAgent_MeasureDecodeTime:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_MEASURE_DECODE_TIME;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToAgent_MeasureDecodeTime_0_svc;
		break;

	case VIDEO_RPC_CAP_ToAgent_StartCapture:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_CAP_START_CAPTURE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_CAP_ToAgent_StartCapture_0_svc;
		break;

	case VIDEO_RPC_CAP_ToAgent_StopCapture:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_CAP_STOP_CAPTURE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_CAP_ToAgent_StopCapture_0_svc;
		break;

	case VIDEO_RPC_CAP_ToAgent_CaptureOneFrame:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_CAP_CAPTURE_ONE_FRAME;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_CAP_ToAgent_CaptureOneFrame_0_svc;
		break;

	case VIDEO_RPC_CAP_ToAgent_SetCaptureMode:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_CAP_START_CAPTURE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_CAP_ToAgent_SetCaptureMode_0_svc;
		break;

	case VIDEO_RPC_CAP_ToAgent_SetFrameRate:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_CAP_SET_FRAME_RATE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_CAP_ToAgent_SetFrameRate_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_Init:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_INIT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_Init_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetVideoSource:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_VIDEOSOURCE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetVideoSource_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetSourceFile:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SOURCEFILE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetSourceFile_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetResolution:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SET_RESOLUTION;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetResolution_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetNewResolution:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SET_NEW_RESOLUTION;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetNewResolution_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetBitRate:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SET_BITRATE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetBitRate_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetGOPStructure:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SET_GOPSTRUCTURE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetGOPStructure_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetNewGOPOnSceneChange:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SET_NEWGOPONSC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetNewGOPOnSceneChange_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetInverseTelecineDetection:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SET_INV32DETECT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetInverseTelecineDetection_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetTF:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SET_TF;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetTF_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetNR:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SET_NR;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetNR_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetEncodeFormat:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SET_ENCFORMAT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetEncodeFormat_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_ConfigureCCData:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_CONFIG_CCDATA;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_ConfigureCCData_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetClosedGOPFrequency:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SET_CLOSEDGOPFREQ;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetClosedGOPFrequency_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_StartRecord:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_START_ENC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_StartRecord_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_PauseRecord:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_PAUSE_ENC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_PauseRecord_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_StopRecord:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_STOP_ENC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_StopRecord_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_ConfigVOBU:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_CONFIG_VOBU;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_ConfigVOBU_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_MPEGIFrameEncode:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_MPEG_I_ENC;
		_xdr_result = (xdrproc_t) xdr_RPCRES_LONG;
		ReplyParaSize = sizeof(RPCRES_LONG);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_MPEGIFrameEncode_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetVbidWssFreq:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SET_VBID_WSS_FREQ;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetVbidWssFreq_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_IsRunnable:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_IsRunnable_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetVBV:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SET_VBV;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetVBV_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetNonRealTime:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SET_NONREALTIME;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetNonRealTime_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SendTVDInfo:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SEND_TVD_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SendTVDInfo_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetFrameRate:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SET_FRAME_RATE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetFrameRate_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_ReqKeyFrame:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_REQ_KEY_FRAME;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_ReqKeyFrame_0_svc;
		break;

	case VIDEO_RPC_ENC_ToAgent_SetProfile:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_SET_PROFILE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToAgent_SetProfile_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetVideoStandard:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_SET_VIDEO_STANDARD;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetVideoStandard_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetHDMI:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_SET_HDMI;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetHDMI_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigHDMI:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CONFIG_HDMI;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigHDMI_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigHdmiInfoFrame:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CONFIG_HDMI_INFO_FRAME;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigHdmiInfoFrame_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigVideoStandard:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CONFIG_VIDEO_STANDARD;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigVideoStandard_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetTVtype:
		_xdr_argument = (xdrproc_t) xdr_VO_TV_TYPE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetTVtype_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetBackground:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_SET_BKGRND;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetBackground_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetMixerOrder:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_SET_MIXER_ORDER;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetMixerOrder_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_GetMixerOrder:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_VIDEO_RPC_VOUT_SET_MIXER_ORDER;
		ReplyParaSize = sizeof(VIDEO_RPC_VOUT_SET_MIXER_ORDER);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_GetMixerOrder_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetClosedCaption:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_SET_CC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetClosedCaption_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetAPS:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_SET_APS;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetAPS_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetCopyMode:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_SET_COPY_MODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetCopyMode_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetAspectRatio:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_SET_AR;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetAspectRatio_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigureDisplayWindow:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CONFIG_DISP_WIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigureDisplayWindow_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetV2alpha:
		_xdr_argument = (xdrproc_t) xdr_u_char;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetV2alpha_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetRescaleMode:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_SET_RESCALE_MODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetRescaleMode_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetDeintMode:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_SET_DEINT_MODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetDeintMode_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_Zoom:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_ZOOM;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_Zoom_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_Pan_Zoom:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_PAN_ZOOM;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_Pan_Zoom_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetTransparency:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_TRANSPARENCY;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetTransparency_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigureOSD:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CONFIG_OSD;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigureOSD_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigureOSDPalette:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CONFIG_OSD_PALETTE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigureOSDPalette_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_CreateOSDwindow:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CREATE_OSD_WIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_CreateOSDwindow_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetOSDwindowPalette:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_SET_OSD_WIN_PALETTE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetOSDwindowPalette_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindow:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_MODIFY_OSD_WIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindow_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindowOnGo:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_MODIFY_OSD_WIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindowOnGo_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindow:
		_xdr_argument = (xdrproc_t) xdr_u_char;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindow_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindowOnGo:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_DELETE_OSD_WIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindowOnGo_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_DrawOSDwindow:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_DRAW_OSD_WIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_DrawOSDwindow_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_DrawOSDwindowOnGo:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_DRAW_OSD_WIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_DrawOSDwindowOnGo_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_HideOSDwindow:
		_xdr_argument = (xdrproc_t) xdr_u_char;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_HideOSDwindow_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_HideOSDwindowOnGo:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_HIDE_OSD_WIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_HideOSDwindowOnGo_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigOSDCanvas:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CONFIG_OSD_CANVAS;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigOSDCanvas_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigureGraphicCanvas:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CONFIG_GRAPHIC_CANVAS;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigureGraphicCanvas_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_CreateGraphicWindow:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CREATE_GRAPHIC_WIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_CreateGraphicWindow_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_HideGraphicWindow:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_HIDE_GRAPHIC_WIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_HideGraphicWindow_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ModifyGraphicWindow:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_MODIFY_GRAPHIC_WIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ModifyGraphicWindow_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_DeleteGraphicWindow:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_DELETE_GRAPHIC_WIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_DeleteGraphicWindow_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_DrawGraphicWindow:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_DRAW_GRAPHIC_WIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_DrawGraphicWindow_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_DisplayGraphic:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_DISPLAY_GRAPHIC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_DisplayGraphic_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_HackGraphicCanvas:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_HACK_GRAPHICCANVAS;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_HackGraphicCanvas_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigureCursor:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CONFIG_CURSOR;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigureCursor_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigureMarsCursor:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CONFIG_MARS_CURSOR;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigureMarsCursor_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_DrawCursor:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_DRAW_CURSOR;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_DrawCursor_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_HideCursor:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_HideCursor_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetPeakingStrength:
		_xdr_argument = (xdrproc_t) xdr_u_char;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetPeakingStrength_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetBrightness:
		_xdr_argument = (xdrproc_t) xdr_u_char;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetBrightness_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetHue:
		_xdr_argument = (xdrproc_t) xdr_u_char;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetHue_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetSaturation:
		_xdr_argument = (xdrproc_t) xdr_u_char;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetSaturation_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetContrast:
		_xdr_argument = (xdrproc_t) xdr_u_char;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetContrast_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigColorMatrix:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CONFIG_COLOR_MATRIX;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigColorMatrix_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_VideoCapture:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_VIDEO_CAPTURE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_VideoCapture_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetSubtitleYoffset:
		_xdr_argument = (xdrproc_t) xdr_short;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetSubtitleYoffset_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SwitchSPDomination:
		_xdr_argument = (xdrproc_t) xdr_short;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SwitchSPDomination_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_Display:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_FILTER_DISPLAY;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_Display_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_Capture:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_FILTER_CAPTURE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_Capture_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_SetSpeed:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_FILTER_SET_SPEED;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_SetSpeed_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_Step:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_Step_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_ShowStillPicture:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_FILTER_SHOW_STILL_PIC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_ShowStillPicture_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_FillVideoBorder:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_FILTER_FILL_VIDEO_BORDER;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_FillVideoBorder_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_SetFastDisplay:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_FILTER_SET_FAST_DISPLAY;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_SetFastDisplay_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_Enable3DModeDetect:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_FILTER_ENABLE_3D_MODE_DETECT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_Enable3DModeDetect_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_ClearVideo:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_FILTER_CLEAR_VIDEO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_ClearVideo_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_FlushVideoOut:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_FlushVideoOut_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_ConfigSyncAV:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_FILTER_Config_SyncAV;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_ConfigSyncAV_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_ConfigVoFreeze:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_FILTER_Config_VoFreeze;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_ConfigVoFreeze_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_ConfigDisplayDelay:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_FILTER_Config_DisplayDelay;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_ConfigDisplayDelay_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_ConnectVDec:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_FILTER_ConnectVDec;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_ConnectVDec_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_ConfigMastership:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_FILTER_Config_Mastership;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_ConfigMastership_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_ConfigDual3D:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_FILTER_Config_Dual3D;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_ConfigDual3D_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_SetSourceType:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_FILTER_SET_SOURCE_TYPE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_SetSourceType_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_VodmaEnable:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_VODMA_ENABLE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_VodmaEnable_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_VodmaFrameRateControl:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_FRAMERATE_CONTROL_STRUCT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_VodmaFrameRateControl_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_VideoDecimate:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_DECIMATE_STRUCT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_VideoDecimate_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_SetScalerARMode:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_SET_SCALER_AR_MODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_SetScalerARMode_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigScalerARCustomerMode:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CONFIG_SCALER_AR_CUSTOMER_MODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigScalerARCustomerMode_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigVodmaVFlip:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_VODMA_VFLIP_ENABLE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigVodmaVFlip_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigVodmaZoom:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_VODMA_ZOOM_RATE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigVodmaZoom_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigVodmaPosFinetune:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_VODMA_POS_FIUNTUNE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigVodmaPosFinetune_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigVoForceBG:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_FORCEBG_CTRL;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigVoForceBG_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigVoScaleUp:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CONFIG_SCALEUP;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigVoScaleUp_0_svc;
		break;

	case VIDEO_RPC_VOUT_FILTER_ToAgent_VODMA_ConfigVsyncGenIvSrc:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_VODMA_CONFIG_VSGEN_IV_SRC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_FILTER_ToAgent_VODMA_ConfigVsyncGenIvSrc_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_VSCINPUTTYPE_TO_VODMA:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_VSCINPUTTYPE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_VSCINPUTTYPE_TO_VODMA_0_svc;
		break;

	case VIDEO_RPC_ToAgent_SetScalerVBICCBuf:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_SetScalerVBICCBuf_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_CurrentBlockToSequential:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CURRENT_BLK_TO_SEQ;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_CurrentBlockToSequential_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_Set_3D_Mode:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_SET_3D_MODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_Set_3D_Mode_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_Set_3D_Output_Mode:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_SET_3D_OUTPUT_MODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_Set_3D_Output_Mode_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_Force2D:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_FORCE2D_MODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_Force2D_0_svc;
		break;

	case VIDEO_RPC_ToAgent_Set2Dcvt3DVOConfig:
		_xdr_argument = (xdrproc_t) xdr_VO_2D3D_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_Set2Dcvt3DVOConfig_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigHDMI_3D:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CONFIG_HDMI_3D;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigHDMI_3D_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_Force_HDMI_2D:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_FORCE_HDMI_2D;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_Force_HDMI_2D_0_svc;
		break;

	case VIDEO_RPC_ToAgent_SetVOCaptureConfig:
		_xdr_argument = (xdrproc_t) xdr_VO_CAPTURE_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_SetVOCaptureConfig_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_Set_OSD_4K2K_Mode:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_SET_OSD_4K2K_MODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_Set_OSD_4K2K_Mode_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_4K2K_Sequence_Control:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_4K2K_SEQUENCE_CONTORL;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_4K2K_Sequence_Control_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigGDMA3D:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CONFIG_3D_STRUCT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigGDMA3D_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigGDMA3DOffset:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_CONFIG_3D_OFFSET_STRUCT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigGDMA3DOffset_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_ConfigGDMAVFlip:
		_xdr_argument = (xdrproc_t) xdr_u_char;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_ConfigGDMAVFlip_0_svc;
		break;

	case VIDEO_RPC_VOUT_ToAgent_Force_VO_Chroma_422:
		_xdr_argument = (xdrproc_t) xdr_u_char;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VOUT_ToAgent_Force_VO_Chroma_422_0_svc;
		break;

	case VIDEO_RPC_VO_FILTER_ToAgent_SetAppType:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_FILTER_SET_APP_TYPE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_FILTER_ToAgent_SetAppType_0_svc;
		break;

	case VIDEO_RPC_SUBPIC_DEC_ToAgent_EnableSubPicture:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_SUBPIC_DEC_ENABLE_SUBPIC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_SUBPIC_DEC_ToAgent_EnableSubPicture_0_svc;
		break;

	case VIDEO_RPC_SUBPIC_DEC_ToAgent_ShowSubPicture:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_SUBPIC_DEC_ToAgent_ShowSubPicture_0_svc;
		break;

	case VIDEO_RPC_SUBPIC_DEC_ToAgent_HideSubPicture:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_SUBPIC_DEC_ToAgent_HideSubPicture_0_svc;
		break;

	case VIDEO_RPC_SUBPIC_DEC_ToAgent_Configure:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_SUBPIC_DEC_CONFIGURE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_SUBPIC_DEC_ToAgent_Configure_0_svc;
		break;

	case VIDEO_RPC_SUBPIC_DEC_ToAgent_Page:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_SUBPIC_DEC_PAGE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_SUBPIC_DEC_ToAgent_Page_0_svc;
		break;

	case VIDEO_RPC_TVD_ToAgent_TVD_Configure:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_TVD_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_TVD_ToAgent_TVD_Configure_0_svc;
		break;

	case VIDEO_RPC_TVD_ToAgent_Select_INFMT:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_TVD_INPUT_FORMAT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_TVD_ToAgent_Select_INFMT_0_svc;
		break;

	case VIDEO_RPC_TVD_ToAgent_YC_Separation:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_TVD_YC_SEP_MODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_TVD_ToAgent_YC_Separation_0_svc;
		break;

	case VIDEO_RPC_TVD_ToAgent_VBI_Ctrl:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_TVD_VBI_CTRL;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_TVD_ToAgent_VBI_Ctrl_0_svc;
		break;

	case VIDEO_RPC_TVD_ToAgent_Adjust_Contrast:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_TVD_ADJ_CONTRAST;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_TVD_ToAgent_Adjust_Contrast_0_svc;
		break;

	case VIDEO_RPC_TVD_ToAgent_Adjust_Brightness:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_TVD_ADJ_BRIGHTNESS;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_TVD_ToAgent_Adjust_Brightness_0_svc;
		break;

	case VIDEO_RPC_TVD_ToAgent_Adjust_Saturation:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_TVD_ADJ_SATURATION;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_TVD_ToAgent_Adjust_Saturation_0_svc;
		break;

	case VIDEO_RPC_TVD_ToAgent_Adjust_Hue:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_TVD_ADJ_HUE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_TVD_ToAgent_Adjust_Hue_0_svc;
		break;

	case VIDEO_RPC_TVD_ToAgent_Blue_Screen_Ctrl:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_TVD_BLUE_MODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_TVD_ToAgent_Blue_Screen_Ctrl_0_svc;
		break;

	case VIDEO_RPC_TVD_ToAgent_Query_VIDEO_FORMAT:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_TVD_VIDEO_FORMAT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_TVD_ToAgent_Query_VIDEO_FORMAT_0_svc;
		break;

	case VIDEO_RPC_VIN_ToAgent_Adjust_Scale_Coef:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VIN_ADJ_SCALE_COEF;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VIN_ToAgent_Adjust_Scale_Coef_0_svc;
		break;

	case VIDEO_RPC_TVD_ToAgent_ChangeChannel_Start:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_CHANNEL_RES;
		ReplyParaSize = sizeof(CHANNEL_RES);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_TVD_ToAgent_ChangeChannel_Start_0_svc;
		break;

	case VIDEO_RPC_JPEG_ToAgent_DEC:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_JPEG_DEC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_JPEG_ToAgent_DEC_0_svc;
		break;

	case VIDEO_RPC_JPEG_ToAgent_DEC_BATCH:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_JPEG_DEC_BATCH;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_JPEG_ToAgent_DEC_BATCH_0_svc;
		break;

	case VIDEO_RPC_TRANSITION_ToAgent_Start:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_TRANSITION_EFFECT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_TRANSITION_ToAgent_Start_0_svc;
		break;

	case VIDEO_RPC_MIXER_FILTER_ToAgent_Configure:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_MIXER_FILTER_CONFIGURE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_MIXER_FILTER_ToAgent_Configure_0_svc;
		break;

	case VIDEO_RPC_MIXER_FILTER_ToAgent_ConfigureWindow:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_MIXER_FILTER_CONFIGURE_WIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_MIXER_FILTER_ToAgent_ConfigureWindow_0_svc;
		break;

	case VIDEO_RPC_MIXER_FILTER_ToAgent_SetMasterWindow:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_MIXER_FILTER_SET_MASTER_WIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_MIXER_FILTER_ToAgent_SetMasterWindow_0_svc;
		break;

	case VIDEO_RPC_MIXER_ToAgent_PlayOneMotionJpegFrame:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_MIXER_PLAY_ONE_MOTION_JPEG_FRAME;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_MIXER_ToAgent_PlayOneMotionJpegFrame_0_svc;
		break;

	case VIDEO_RPC_MIXER_FILTER_ToAgent_Capture:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_MIXER_FILTER_CAPTURE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_MIXER_FILTER_ToAgent_Capture_0_svc;
		break;

	case VIDEO_RPC_DIRECT_VO_ToAgent_open:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DIRECT_VO_OPEN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DIRECT_VO_ToAgent_open_0_svc;
		break;

	case VIDEO_RPC_DIRECT_VO_ToAgent_run:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DIRECT_VO_RUN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DIRECT_VO_ToAgent_run_0_svc;
		break;

	case VIDEO_RPC_DIRECT_VO_ToAgent_stop:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DIRECT_VO_STOP;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DIRECT_VO_ToAgent_stop_0_svc;
		break;

	case VIDEO_RPC_DIRECT_VO_ToAgent_flush:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DIRECT_VO_FLUSH;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DIRECT_VO_ToAgent_flush_0_svc;
		break;

	case VIDEO_RPC_DOLBY_VISION_HDMI_Set_Detect_Enable:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DOLBY_VISION_HDMI_SET_DETECT_ENABLE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DOLBY_VISION_HDMI_Set_Detect_Enable_0_svc;
		break;

	case VIDEO_RPC_DOLBY_VISION_HDMI_Get_Detect_Info:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DOLBY_VISION_HDMI_GET_DETECT_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DOLBY_VISION_HDMI_Get_Detect_Info_0_svc;
		break;

	case VIDEO_RPC_DOLBY_VISION_HDMI_Set_Display_Enable:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DOLBY_VISION_HDMI_SET_DISPLAY_ENABLE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DOLBY_VISION_HDMI_Set_Display_Enable_0_svc;
		break;

	case VIDEO_RPC_ToAgent_K2VParameter:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_K2V_PARAM;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToAgent_K2VParameter_0_svc;
		break;

	case VIDEO_RPC_VO_PHOTO_ToAgent_Open:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_PHOTO_OPEN_T;
		_xdr_result = (xdrproc_t) xdr_VIDEO_RPC_DEC_PV_RESULT;
		ReplyParaSize = sizeof(VIDEO_RPC_DEC_PV_RESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_PHOTO_ToAgent_Open_0_svc;
		break;

	case VIDEO_RPC_VO_PHOTO_ToAgent_Config:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_PHOTO_CONFIG_T;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_PHOTO_ToAgent_Config_0_svc;
		break;

	case VIDEO_RPC_VO_PHOTO_ToAgent_DisplayPicture:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_DISPLAYPICTURE_T;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_PHOTO_ToAgent_DisplayPicture_0_svc;
		break;

	case VIDEO_RPC_VO_PHOTO_ToAgent_RedrawPicture:
		_xdr_argument = (xdrproc_t) xdr_u_int;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_PHOTO_ToAgent_RedrawPicture_0_svc;
		break;

	case VIDEO_RPC_VO_PHOTO_ToAgent_Close:
		_xdr_argument = (xdrproc_t) xdr_u_int;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_PHOTO_ToAgent_Close_0_svc;
		break;

	case VIDEO_RPC_VO_PHOTO_ToAgent_Connect:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_PHOTO_ToAgent_Connect_0_svc;
		break;

	case VIDEO_RPC_VO_PHOTO_ToAgent_GetDeviceCapability:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VO_GETDEVICECAPABILITY_T;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_VO_PHOTO_ToAgent_GetDeviceCapability_0_svc;
		break;

	default:
#ifdef IS_SCPU
		RPC_EMERG("unknown procedure:pid = %d, procedureID = %d\n", (int)gettid(), (int)rpc->procedureID);
#endif
		return;
	}


	memset ((char *)&argument, 0, sizeof (argument));


	if (!rpc_getargs (rpc, (xdrproc_t) _xdr_argument, (caddr_t) &argument, opt)) {
		printf("get args error\n");
#ifdef IS_SCPU
		RPC_EMERG("rpc_getargs error:pid = %d, procedureID = %d\n", (int)gettid(), (int)rpc->procedureID);
#endif
		return;
	}

#ifdef IS_SCPU
	Q9527_DEBUG()

#endif
	pthread_mutex_unlock(pMutex);

	(*local)((char *)&argument, rpc, (char *)&retval);


	// When source msg is BLOCK_MODE,
	// we must help it reply
	// ps: reply mode is NON_BLOCK and use request's ringbuf type
	if (rpc->taskID != 0) {
	    SendReply(rpc->taskID, rpc->mycontext, (char *)&retval, ReplyParaSize,
			 (xdrproc_t) _xdr_result, opt);
	}

	return;
}


struct REG_STRUCT * VIDEO_SYSTEM_0_register(struct REG_STRUCT *rnode) {

	return (struct REG_STRUCT *)ipc_register(rnode, VIDEO_SYSTEM, 0,
		(void (*)(struct RPC_STRUCT *, int, pthread_mutex_t*))VIDEO_SYSTEM_0);

}
