/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <VideoRPC_Agent.h>
#include <rt/misc/SVCFunc.h>
#include <rt/posix/pthread.h>
#include <RPCBaseDS.h>
#include <VideoRPCBaseDS.h>

void *memset( void *s, int c, unsigned int n );

static void
VIDEO_AGENT_0(RPC_STRUCT * rpc, int opt, pthread_mutex_t *pMutex)
{
	union {
		long VIDEO_RPC_ENC_ToSystem_EndOfStream_0_arg;
		VIDEO_RPC_ENDOFSTREAM VIDEO_RPC_ToSystem_EndOfStream_0_arg;
		long VIDEO_RPC_ToSystem_Deliver_GenInfo_0_arg;
		long VIDEO_RPC_ToSystem_Deliver_FrameInfo_0_arg;
		VIDEO_RPC_DEC_JPEG_INFO VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg_0_arg;
		long VIDEO_RPC_ToSystem_Deliver_WSSInfo_0_arg;
		long VIDEO_RPC_ToSystem_Deliver_PauseInfo_0_arg;
		VIDEO_RPC_DEC_ERROR_INFO VIDEO_RPC_DEC_ToSystem_FatalError_0_arg;
		long VIDEO_RPC_ToSystem_ScaleModeSCART_0_arg;
		VIDEO_RPC_ENC_AUTOPAUSE VIDEO_RPC_ToSystem_Deliver_AutoPauseInfo_0_arg;
		long VIDEO_RPC_ToSystem_VideoHaltDone_0_arg;
		VIDEO_RPC_SCALER_MESSAGE VIDEO_RPC_ToSystem_SendScalerMsg_0_arg;
		VIDEO_RPC_DEC_MESSAGE VIDEO_RPC_ToSystem_DecoderMessage_0_arg;
		VIDEO_RPC_VOUT_MESSAGE VIDEO_RPC_ToSystem_VoutMessage_0_arg;
		VIDEO_RPC_DEC_FRAME_INFO VIDEO_RPC_DEC_ToSystem_Deliver_FrameInfo_0_arg;
		VIDEO_RPC_DEC_PIC_INFO VIDEO_RPC_DEC_ToSystem_Deliver_PicInfo_0_arg;
		VIDEO_RPC_DEC_MEDIA_INFO VIDEO_RPC_DEC_ToSystem_Deliver_MediaInfo_0_arg;
		VIDEO_RPC_TO_KERNEL_PARAMETER VIDEO_RPC_ToSystem_KernelRPC_0_arg;
	} argument;

	union {
		HRESULT VIDEO_RPC_ENC_ToSystem_EndOfStream_0_ret;
		HRESULT VIDEO_RPC_ToSystem_EndOfStream_0_ret;
		HRESULT VIDEO_RPC_ToSystem_Deliver_GenInfo_0_ret;
		HRESULT VIDEO_RPC_ToSystem_Deliver_FrameInfo_0_ret;
		HRESULT VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg_0_ret;
		HRESULT VIDEO_RPC_ToSystem_Deliver_WSSInfo_0_ret;
		HRESULT VIDEO_RPC_ToSystem_Deliver_PauseInfo_0_ret;
		HRESULT VIDEO_RPC_DEC_ToSystem_FatalError_0_ret;
		HRESULT VIDEO_RPC_ToSystem_ScaleModeSCART_0_ret;
		HRESULT VIDEO_RPC_ToSystem_Deliver_AutoPauseInfo_0_ret;
		HRESULT VIDEO_RPC_ToSystem_VideoHaltDone_0_ret;
		HRESULT VIDEO_RPC_ToSystem_SendScalerMsg_0_ret;
		HRESULT VIDEO_RPC_ToSystem_DecoderMessage_0_ret;
		HRESULT VIDEO_RPC_ToSystem_VoutMessage_0_ret;
		HRESULT VIDEO_RPC_DEC_ToSystem_Deliver_FrameInfo_0_ret;
		HRESULT VIDEO_RPC_DEC_ToSystem_Deliver_PicInfo_0_ret;
		HRESULT VIDEO_RPC_DEC_ToSystem_Deliver_MediaInfo_0_ret;
		HRESULT VIDEO_RPC_ToSystem_KernelRPC_0_ret;
	} retval;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct RPC_STRUCT *, char *);
	int ReplyParaSize;


	switch (rpc->procedureID) {
	case VIDEO_RPC_ENC_ToSystem_EndOfStream:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ENC_ToSystem_EndOfStream_0_svc;
		break;

	case VIDEO_RPC_ToSystem_EndOfStream:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENDOFSTREAM;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToSystem_EndOfStream_0_svc;
		break;

	case VIDEO_RPC_ToSystem_Deliver_GenInfo:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToSystem_Deliver_GenInfo_0_svc;
		break;

	case VIDEO_RPC_ToSystem_Deliver_FrameInfo:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToSystem_Deliver_FrameInfo_0_svc;
		break;

	case VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_JPEG_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg_0_svc;
		break;

	case VIDEO_RPC_ToSystem_Deliver_WSSInfo:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToSystem_Deliver_WSSInfo_0_svc;
		break;

	case VIDEO_RPC_ToSystem_Deliver_PauseInfo:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToSystem_Deliver_PauseInfo_0_svc;
		break;

	case VIDEO_RPC_DEC_ToSystem_FatalError:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_ERROR_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToSystem_FatalError_0_svc;
		break;

	case VIDEO_RPC_ToSystem_ScaleModeSCART:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToSystem_ScaleModeSCART_0_svc;
		break;

	case VIDEO_RPC_ToSystem_Deliver_AutoPauseInfo:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_ENC_AUTOPAUSE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToSystem_Deliver_AutoPauseInfo_0_svc;
		break;

	case VIDEO_RPC_ToSystem_VideoHaltDone:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToSystem_VideoHaltDone_0_svc;
		break;

	case VIDEO_RPC_ToSystem_SendScalerMsg:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_SCALER_MESSAGE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToSystem_SendScalerMsg_0_svc;
		break;

	case VIDEO_RPC_ToSystem_DecoderMessage:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_MESSAGE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToSystem_DecoderMessage_0_svc;
		break;

	case VIDEO_RPC_ToSystem_VoutMessage:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_VOUT_MESSAGE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToSystem_VoutMessage_0_svc;
		break;

	case VIDEO_RPC_DEC_ToSystem_Deliver_FrameInfo:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_FRAME_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToSystem_Deliver_FrameInfo_0_svc;
		break;

	case VIDEO_RPC_DEC_ToSystem_Deliver_PicInfo:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_PIC_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToSystem_Deliver_PicInfo_0_svc;
		break;

	case VIDEO_RPC_DEC_ToSystem_Deliver_MediaInfo:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_DEC_MEDIA_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_DEC_ToSystem_Deliver_MediaInfo_0_svc;
		break;

	case VIDEO_RPC_ToSystem_KernelRPC:
		_xdr_argument = (xdrproc_t) xdr_VIDEO_RPC_TO_KERNEL_PARAMETER;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) VIDEO_RPC_ToSystem_KernelRPC_0_svc;
		break;

	default:
#ifdef IS_SCPU
		RPC_EMERG("unknown procedure:pid = %d, procedureID = %d\n", (int)gettid(), (int)rpc->procedureID);
#endif
		return;
	}


	memset ((char *)&argument, 0, sizeof (argument));


	if (!rpc_getargs (rpc, (xdrproc_t) _xdr_argument, (caddr_t) &argument, opt)) {
		printf("get args error\n");
#ifdef IS_SCPU
		RPC_EMERG("rpc_getargs error:pid = %d, procedureID = %d\n", (int)gettid(), (int)rpc->procedureID);
#endif
		return;
	}

#ifdef IS_SCPU
	Q9527_DEBUG()

#endif
	pthread_mutex_unlock(pMutex);

	(*local)((char *)&argument, rpc, (char *)&retval);


	// When source msg is BLOCK_MODE,
	// we must help it reply
	// ps: reply mode is NON_BLOCK and use request's ringbuf type
	if (rpc->taskID != 0) {
	    SendReply(rpc->taskID, rpc->mycontext, (char *)&retval, ReplyParaSize,
			 (xdrproc_t) _xdr_result, opt);
	}

	return;
}


struct REG_STRUCT * VIDEO_AGENT_0_register(struct REG_STRUCT *rnode) {

	return (struct REG_STRUCT *)ipc_register(rnode, VIDEO_AGENT, 0,
		(void (*)(struct RPC_STRUCT *, int, pthread_mutex_t*))VIDEO_AGENT_0);

}
