/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <AudioRPC_System.h>
#include <rt/misc/SVCFunc.h>
#include <rt/posix/pthread.h>
#include <RPCBaseDS.h>
#include <AudioRPCBaseDS.h>

void *memset( void *s, int c, unsigned int n );

static void
AUDIO_SYSTEM_0(RPC_STRUCT * rpc, int opt, pthread_mutex_t *pMutex)
{
	union {
		AUDIO_RPC_INSTANCE AUDIO_RPC_ToAgent_Create_0_arg;
		AUDIO_RPC_CONNECTION AUDIO_RPC_ToAgent_Connect_0_arg;
		AUDIO_RPC_RINGBUFFER_HEADER AUDIO_RPC_ToAgent_InitRingBufferHeader_0_arg;
		long AUDIO_RPC_ToAgent_Run_0_arg;
		long AUDIO_RPC_ToAgent_Pause_0_arg;
		long AUDIO_RPC_ToAgent_Stop_0_arg;
		long AUDIO_RPC_ToAgent_Destroy_0_arg;
		AUDIO_RPC_SENDIO AUDIO_RPC_ToAgent_Flush_0_arg;
		AUDIO_RPC_REFCLOCK AUDIO_RPC_ToAgent_SetRefClock_0_arg;
		AUDIO_RPC_SEND_LONG AUDIO_RPC_ToAgent_GetStatus_0_arg;
		AUDIO_RPC_SEEK AUDIO_RPC_ToAgent_SetSeeking_0_arg;
		AUDIO_RPC_CONNECTION AUDIO_RPC_ToAgent_DisConnect_0_arg;
		AUDIO_RPC_DEC_BITSTREAM_BUFFER AUDIO_RPC_ToAgent_BitstreamValidation_0_arg;
		int AUDIO_RPC_AO_ToAgent_IsFinishPlaySoundEvent_0_arg;
		AUDIO_CONFIG_COMMAND AUDIO_RPC_ToAgent_AudioConfig_0_arg;
		AUDIO_RPC_DEC_INIT AUDIO_RPC_DEC_ToAgent_Init_0_arg;
		AUDIO_RPC_SEND_LONG AUDIO_RPC_DEC_ToAgent_SkipMode_0_arg;
		AUDIO_RPC_CHANNEL_OUT_MODE AUDIO_RPC_DEC_ToAgent_SetDualMonoOutMode_0_arg;
		long AUDIO_RPC_DEC_ToAgent_GetPTS_0_arg;
		AUDIO_RPC_ENC_INIT AUDIO_RPC_ENC_ToAgent_Init_0_arg;
		AUDIO_RPC_ENC_SET_BITRATE AUDIO_RPC_ENC_ToAgent_SetBitRate_0_arg;
		AUDIO_RPC_SEND_LONG AUDIO_RPC_ENC_ToAgent_StartEncoder_0_arg;
		AUDIO_RPC_SEND_LONG AUDIO_RPC_ENC_ToAgent_PauseEncoder_0_arg;
		AUDIO_RPC_SEND_LONG AUDIO_RPC_ENC_ToAgent_StopEncoder_0_arg;
		AUDIO_RPC_ENC_SOURCEFILE AUDIO_RPC_ENC_ToAgent_SetSourceFile_0_arg;
		AUDIO_RPC_ENC_COMMAND AUDIO_RPC_ENC_ToAgent_Command_0_arg;
		AUDIO_RPC_SEND_LONG AUDIO_RPC_ENC_ToAgent_MuteEncoder_0_arg;
		AUDIO_RPC_ENC_INFO AUDIO_RPC_ENC_SetEncoder_0_arg;
		AUDIO_RPC_ENC_DV_MIXER AUDIO_RPC_ENC_ToAgent_SetDVMixer_0_arg;
		AUDIO_RPC_SEND_LONG AUDIO_RPC_ENC_ToAgent_SetNonRealTime_0_arg;
		AUDIO_RPC_SEND_LONG AUDIO_RPC_ENC_ToAgent_SetInputSR_0_arg;
		AUDIO_RPC_AO_INIT AUDIO_RPC_AO_ToAgent_Init_0_arg;
		AUDIO_RPC_AO_SET_EQUALIZER AUDIO_RPC_AO_ToAgent_SetEaqualizer_0_arg;
		AUDIO_AO_RPC_CONFIG_DELAY_CONTROL AUDIO_RPC_AO_ToAgent_ConfigDelayControl_0_arg;
		AUDIO_RPC_AO_CONFIG_KARAOKE AUDIO_RPC_AO_ToAgent_ConfigKaraoke_0_arg;
		AUDIO_RPC_AO_MIXER AUDIO_RPC_AO_ToAgent_ConfigMixer_0_arg;
		AUDIO_RPC_PP_CFG AUDIO_RPC_AO_ToAgent_ConfigPP_0_arg;
		AUDIO_OUT_MUTE_INFO AUDIO_RPC_AO_ToAgent_Mute_0_arg;
		AUDIO_RPC_AO_DAC AUDIO_RPC_AO_ToAgent_ConfigDAC_0_arg;
		AUDIO_RPC_PP_PROLOGIC AUDIO_RPC_AO_ToAgent_ConfigPrologic_0_arg;
		AUDIO_RPC_SPDIFO_SOURCE AUDIO_RPC_AO_ToAgent_SPDIFO_Source_Config_0_arg;
		AUDIO_RPC_RESAMPLE_INFO AUDIO_RPC_AO_ToAgent_ResampleTable_0_arg;
		AUDIO_CONFIG_ADC AUDIO_RPC_ToAgent_ADC0_Config_0_arg;
		AUDIO_CONFIG_ADC AUDIO_RPC_ToAgent_ADC1_Config_0_arg;
		AUDIO_CONFIG_SPDIF AUDIO_RPC_ToAgent_SPDIF_Config_0_arg;
		AUDIO_BACKDOOR_AI_INIT AUDIO_RPC_ToAgent_AI_BackDoor_Init_0_arg;
		AUDIO_CONFIG_SPDIF_ERR AUDIO_RPC_ToAgent_SPDIF_Err_Threshold_Config_0_arg;
		AUDIO_IN_SOURCE AUDIO_RPC_ToAgent_AIN_Switch_Focus_0_arg;
		AUDIO_OUT_COPY_SOURCE AUDIO_RPC_ToAgent_AOUT_Copy_Source_0_arg;
		AUDIO_VOLUME_CONTROL AUDIO_RPC_ToAgent_AOUT_Volume_Control_0_arg;
		AUDIO_OUT_SPDIF_SOURCE AUDIO_RPC_ToAgent_AOUT_SPDIF_Source_0_arg;
		AUDIO_KARAOKE_CONTROL_INFO AUDIO_RPC_ToAgent_Karaoke_Control_0_arg;
		AUDIO_IN_MUTE_INFO AUDIO_RPC_ToAgent_AIN_Mute_0_arg;
		AUDIO_DROP_SAMPLE AUDIO_RPC_ToAgent_AOUT_Drop_Sample_0_arg;
		AUDIO_P_W_NOISE_CFG AUDIO_RPC_ToAgent_AOUT_Pink_White_Noise_0_arg;
		AUDIO_SPECTRUM_CFG AUDIO_RPC_ToAgent_AOUT_Send_Spectrum_Data_0_arg;
		AUDIO_SOUND_EVENT AUDIO_RPC_ToAgent_PlaySoundEvent_0_arg;
		long AUDIO_RPC_ToAgent_AOUT_ResetPin_0_arg;
		AUDIO_CONFIG_AFC AUDIO_RPC_ToAgent_AFC_Config_0_arg;
		AUDISTRY_CONFIG_COMMAND AUDIO_RPC_ToAgent_Audistry_Config_0_arg;
		AUDIO_HDMI_MUTE_INFO AUDIO_RPC_ToAgent_HDMI_Mute_0_arg;
		AUDIO_CONFIG_ADC AUDIO_RPC_ToAgent_ADC2_Config_0_arg;
		AUDIO_HDMI_SET AUDIO_RPC_ToAgent_AOUT_HDMI_Set_0_arg;
		AUDIO_RPC_AO_FOCUS AUDIO_RPC_ToAgent_AO_Only_Switchfocus_0_arg;
		AUDIO_IN_DATA_MEASURE AUDIO_RPC_ToAgent_AIN_Data_Measurement_0_arg;
		AUDIO_RPC_BBADC_CONFIG AUDIO_RPC_ToAgent_BBADC_Config_0_arg;
		AUDIO_RPC_I2SI_CONFIG AUDIO_RPC_ToAgent_I2SI_Config_0_arg;
		AUDIO_RPC_SPDIFI_CONFIG AUDIO_RPC_ToAgent_SPDIFI_Config_0_arg;
		AUDIO_RPC_IPT_SRC AUDIO_RPC_ToAgent_ChangeInputSource_0_arg;
		AUDIO_RPC_SET_ATV_CLOCK AUDIO_RPC_ToAgent_SET_ATV_CLOCK_0_arg;
		AUDIO_RPC_INOUT_CH_SELECT AUDIO_RPC_ToAgent_INOUT_CH_SELECT_0_arg;
		AUDIO_RPC_SET_FS_CLOCKSRC AUDIO_RPC_ToAgent_SET_FS_CLOCKSRC_0_arg;
		AUDIO_RPC_SET_PATH_DATA_OUT AUDIO_RPC_ToAgent_SET_PATH_DATA_OUT_0_arg;
		AUDIO_RPC_SET_INTERLEAVE_OUT AUDIO_RPC_ToAgent_SET_INTERLEAVE_OUT_0_arg;
		AUDIO_RPC_AO_CHANNEL_OPT_SWAP AUDIO_RPC_ToAgent_SET_CHANNEL_OUT_SWAP_0_arg;
		long AUDIO_RPC_ToAgent_SetAuthorityKey_0_arg;
		AUDIO_SPDIF_CS AUDIO_RPC_ToAgent_GET_SPDIF_CS_0_arg;
		AUDIO_RPC_SET_SIF_ADC_INIT AUDIO_RPC_ToAgent_SET_SIF_ADC_INIT_0_arg;
		AUDIO_HDMI_OUT_EDID_DATA AUDIO_RPC_ToAgent_HDMI_OUT_EDID_0_arg;
		HDMI_INFO AUDIO_RPC_ToAgent_HDMI_INFO_0_arg;
		AUDIO_RPC_PTS_INFO AUDIO_RPC_ToAgent_UpdatePTS_0_arg;
		AUDIO_RPC_SENDPIN_LONG AUDIO_RPC_ToAgent_EndOfStream_0_arg;
		AUDIO_RPC_FOCUS AUDIO_RPC_ToAgent_SwitchFocus_0_arg;
		AUDIO_CONFIG_DAC_I2S AUDIO_RPC_ToAgent_DAC_I2S_Config_0_arg;
		AUDIO_CONFIG_DAC_SPDIF AUDIO_RPC_ToAgent_DAC_SPDIF_Config_0_arg;
		AUDIO_HDMI_OUT_VSDB_DATA AUDIO_RPC_ToAgent_HDMI_OUT_VSDB_0_arg;
		AUDIO_HDMI_OUT_EDID_DATA2 AUDIO_RPC_ToAgent_HDMI_OUT_EDID2_0_arg;
		AUDIO_RPC_DECCFG AUDIO_RPC_ToAgent_DecoderConfig_0_arg;
		AUDIO_RPC_NIGHTMODE AUDIO_RPC_ToAgent_NightMode_0_arg;
		long AUDIO_RPC_ToAgent_PP_InitPin_0_arg;
		u_long AUDIO_RPC_ToAgent_AskDebugMemoryAddress_0_arg;
		AUDIO_PP_CONFIG AUDIO_RPC_ToAgent_PP_Config_0_arg;
		AUDIO_SRC_CONFIG AUDIO_RPC_ToAgent_PP_SRC_Config_0_arg;
		AUDIO_PROLOGIC2_CONFIG AUDIO_RPC_ToAgent_PP_PL2_Config_0_arg;
		AUDIO_MIXER_CONFIG AUDIO_RPC_ToAgent_PP_MIXER_Config_0_arg;
		AUDIO_BASS_MANAGEMENT_CONFIG AUDIO_RPC_ToAgent_PP_BASS_MANAGEMENT_Config_0_arg;
		AUDIO_KEY_SHIFT_CONFIG AUDIO_RPC_ToAgent_PP_KEY_SHIFT_Config_0_arg;
		AUDIO_REVERB_CONFIG AUDIO_RPC_ToAgent_PP_REVERB_Config_0_arg;
		AUDIO_AGC_MODE AUDIO_RPC_ToAgent_PP_COMFORT_LISTEN_0_arg;
		AUDIO_EQUALIZER_CONFIG AUDIO_RPC_ToAgent_PP_EQ_Config_0_arg;
		AUDIO_VOCAL_REMOVER_CONFIG AUDIO_RPC_ToAgent_PP_VOCAL_REMOVER_Config_0_arg;
		long AUDIO_RPC_DEC_ToAgent_GetAudioFormatInfo_0_arg;
		AUDIO_DVS_CONFIG AUDIO_RPC_ToAgent_PP_DVS_Config_0_arg;
		AUDIO_RPC_TSXT AUDIO_RPC_ToAgent_PP_TSXT_Config_0_arg;
		AUDIO_RPC_PTS_MIXER_CONFIG AUDIO_RPC_ToAgent_PP_PTS_MIXER_Config_0_arg;
		AUDIO_RPC_PCBU_BASSBACK AUDIO_RPC_ToAgent_PP_BASSBACK_PCBU_Config_0_arg;
		AUDIO_RPC_TV_BASSBACK AUDIO_RPC_ToAgent_PP_BASSBACK_TV_Config_0_arg;
		AUDIO_RPC_TV_BASSBACK_CHANGE_BASS_GAIN AUDIO_RPC_ToAgent_PP_BASSBACK_Change_Bass_Gain_0_arg;
		AUDIO_RPC_PP_AGC AUDIO_RPC_ToAgent_PP_AGC_0_arg;
		AUDIO_RPC_TRUVOLUME AUDIO_RPC_ToAgent_PP_TRUVOLUME_Config_0_arg;
		AUDIO_RPC_FREQ_EQ AUDIO_RPC_ToAgent_PP_FREQ_EQ_Config_0_arg;
		AUDIO_RPC_PP_ASF_ON_OFF AUDIO_RPC_ToAgent_PP_ASF_ON_OFF_Config_0_arg;
		AUDIO_RPC_PP_ASF_BALANCE AUDIO_RPC_ToAgent_PP_ASF_BALANCE_Config_0_arg;
		AUDIO_RPC_PP_ASF_MASTER_VOLUME AUDIO_RPC_ToAgent_PP_ASF_VOLUME_Config_0_arg;
		AUDIO_RPC_SUBCHANNEL AUDIO_RPC_ToAgent_SubChannel_0_arg;
		AUDIO_RPC_TRUEHD_LOSSLESSMODE AUDIO_RPC_ToAgent_TrueHD_LosslessMode_0_arg;
		AUDIO_RPC_TSHD AUDIO_RPC_ToAgent_PP_TSHD_Config_0_arg;
		AUDIO_RPC_LGSE_SETMODE AUDIO_RPC_ToAgent_AO_LGSE_SetMode_0_arg;
		AUDIO_RPC_LGSE_SETMAIN AUDIO_RPC_ToAgent_AO_LGSE_SetMain_0_arg;
		AUDIO_RPC_LGSE_SETFN000 AUDIO_RPC_ToAgent_AO_LGSE_SetFn000_0_arg;
		AUDIO_RPC_LGSE_SETFN001 AUDIO_RPC_ToAgent_AO_LGSE_SetFn001_0_arg;
		AUDIO_RPC_LGSE_SETFN009 AUDIO_RPC_ToAgent_AO_LGSE_SetFn009_0_arg;
		AUDIO_RPC_LGSE_SETFN010 AUDIO_RPC_ToAgent_AO_LGSE_SetFn010_0_arg;
		AUDIO_RPC_LGSE_SETFN004 AUDIO_RPC_ToAgent_AO_LGSE_SetFn004_0_arg;
		AUDIO_RPC_LGSE_SETFN005 AUDIO_RPC_ToAgent_AO_LGSE_SetFn005_0_arg;
		AUDIO_RPC_LGSE_SETFN008 AUDIO_RPC_ToAgent_AO_LGSE_SetFn008_0_arg;
		AUDIO_RPC_LGSE_SETFN014 AUDIO_RPC_ToAgent_AO_LGSE_SetFn014_0_arg;
		AUDIO_RPC_LGSE_SETFN017 AUDIO_RPC_ToAgent_AO_LGSE_SetFn017_0_arg;
		AUDIO_RPC_LGSE_SETFN019 AUDIO_RPC_ToAgent_AO_LGSE_SetFn019_0_arg;
		AUDIO_RPC_LGSE_SETFN022 AUDIO_RPC_ToAgent_AO_LGSE_SetFn022_0_arg;
		AUDIO_RPC_LGSE_SETFN018 AUDIO_RPC_ToAgent_AO_LGSE_SetFn018_0_arg;
		AUDIO_RPC_LGSE_SETFN026 AUDIO_RPC_ToAgent_AO_LGSE_SetFn026_0_arg;
		AUDIO_RPC_LGSE_SETFN027 AUDIO_RPC_ToAgent_AO_LGSE_SetFn027_0_arg;
		AUDIO_RPC_LGSE_SETFN028 AUDIO_RPC_ToAgent_AO_LGSE_SetFn028_0_arg;
		AUDIO_RPC_LGSE_SETFN029 AUDIO_RPC_ToAgent_AO_LGSE_SetFn029_0_arg;
		AUDIO_RPC_LGSE_GETDATA AUDIO_RPC_ToAgent_AO_LGSE_GetData_0_arg;
		AUDIO_RPC_LGSE_SETFN024 AUDIO_RPC_ToAgent_AO_LGSE_SetFn024_0_arg;
		AUDIO_DEC_TYPE AUDIO_RPC_DEC_ToAgent_GetAudioDecoderSeekCap_0_arg;
		long AUDIO_RPC_ToAgent_Capability_SetMask_0_arg;
		long AUDIO_RPC_AIN_ToAgent_GetAudioFormatInfo_0_arg;
		long AUDIO_RPC_ToAgent_AudioHalt_0_arg;
		AUDIO_LICENSE_STATUS_CONFIG AUDIO_RPC_ToAgent_Full_Capability_SetMask_0_arg;
		AUDIO_RPC_PRIVATEINFO_PARAMETERS AUDIO_RPC_ToAgent_PrivateInfo_0_arg;
		AUDIO_PASSTHROUGH_INFO AUDIO_RPC_ToAgent_Capability_SetPassThroughMode_0_arg;
		AUDIO_AI_DEVICE_USB_INFO AUDIO_RPC_ToAgent_AI_Device_USBinfo_0_arg;
		AUDIO_DUMMY_DATA AUDIO_RPC_ToAgent_Set_Dummy_Value_0_arg;
	} argument;

	union {
		RPCRES_LONG AUDIO_RPC_ToAgent_Create_0_ret;
		HRESULT AUDIO_RPC_ToAgent_Connect_0_ret;
		HRESULT AUDIO_RPC_ToAgent_InitRingBufferHeader_0_ret;
		HRESULT AUDIO_RPC_ToAgent_Run_0_ret;
		HRESULT AUDIO_RPC_ToAgent_Pause_0_ret;
		HRESULT AUDIO_RPC_ToAgent_Stop_0_ret;
		HRESULT AUDIO_RPC_ToAgent_Destroy_0_ret;
		HRESULT AUDIO_RPC_ToAgent_Flush_0_ret;
		HRESULT AUDIO_RPC_ToAgent_SetRefClock_0_ret;
		RPCRES_LONG AUDIO_RPC_ToAgent_GetStatus_0_ret;
		HRESULT AUDIO_RPC_ToAgent_SetSeeking_0_ret;
		HRESULT AUDIO_RPC_ToAgent_DisConnect_0_ret;
		AUDIO_RPC_FORMAT_INFO AUDIO_RPC_ToAgent_BitstreamValidation_0_ret;
		int AUDIO_RPC_AO_ToAgent_IsFinishPlaySoundEvent_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AudioConfig_0_ret;
		HRESULT AUDIO_RPC_DEC_ToAgent_Init_0_ret;
		HRESULT AUDIO_RPC_DEC_ToAgent_SkipMode_0_ret;
		HRESULT AUDIO_RPC_DEC_ToAgent_SetDualMonoOutMode_0_ret;
		AUDIO_RPC_GET_PTS_INFO AUDIO_RPC_DEC_ToAgent_GetPTS_0_ret;
		HRESULT AUDIO_RPC_ENC_ToAgent_Init_0_ret;
		HRESULT AUDIO_RPC_ENC_ToAgent_SetBitRate_0_ret;
		HRESULT AUDIO_RPC_ENC_ToAgent_StartEncoder_0_ret;
		HRESULT AUDIO_RPC_ENC_ToAgent_PauseEncoder_0_ret;
		HRESULT AUDIO_RPC_ENC_ToAgent_StopEncoder_0_ret;
		HRESULT AUDIO_RPC_ENC_ToAgent_SetSourceFile_0_ret;
		HRESULT AUDIO_RPC_ENC_ToAgent_Command_0_ret;
		HRESULT AUDIO_RPC_ENC_ToAgent_MuteEncoder_0_ret;
		HRESULT AUDIO_RPC_ENC_SetEncoder_0_ret;
		HRESULT AUDIO_RPC_ENC_ToAgent_SetDVMixer_0_ret;
		HRESULT AUDIO_RPC_ENC_ToAgent_SetNonRealTime_0_ret;
		HRESULT AUDIO_RPC_ENC_ToAgent_SetInputSR_0_ret;
		HRESULT AUDIO_RPC_AO_ToAgent_Init_0_ret;
		HRESULT AUDIO_RPC_AO_ToAgent_SetEaqualizer_0_ret;
		HRESULT AUDIO_RPC_AO_ToAgent_ConfigDelayControl_0_ret;
		HRESULT AUDIO_RPC_AO_ToAgent_ConfigKaraoke_0_ret;
		HRESULT AUDIO_RPC_AO_ToAgent_ConfigMixer_0_ret;
		HRESULT AUDIO_RPC_AO_ToAgent_ConfigPP_0_ret;
		HRESULT AUDIO_RPC_AO_ToAgent_Mute_0_ret;
		HRESULT AUDIO_RPC_AO_ToAgent_ConfigDAC_0_ret;
		HRESULT AUDIO_RPC_AO_ToAgent_ConfigPrologic_0_ret;
		HRESULT AUDIO_RPC_AO_ToAgent_SPDIFO_Source_Config_0_ret;
		HRESULT AUDIO_RPC_AO_ToAgent_ResampleTable_0_ret;
		HRESULT AUDIO_RPC_ToAgent_ADC0_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_ADC1_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_SPDIF_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AI_BackDoor_Init_0_ret;
		HRESULT AUDIO_RPC_ToAgent_SPDIF_Err_Threshold_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AIN_Switch_Focus_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AOUT_Copy_Source_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AOUT_Volume_Control_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AOUT_SPDIF_Source_0_ret;
		HRESULT AUDIO_RPC_ToAgent_Karaoke_Control_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AIN_Mute_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AOUT_Drop_Sample_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AOUT_Pink_White_Noise_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AOUT_Send_Spectrum_Data_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PlaySoundEvent_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AOUT_ResetPin_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AFC_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_Audistry_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_HDMI_Mute_0_ret;
		HRESULT AUDIO_RPC_ToAgent_ADC2_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AOUT_HDMI_Set_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_Only_Switchfocus_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AIN_Data_Measurement_0_ret;
		HRESULT AUDIO_RPC_ToAgent_BBADC_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_I2SI_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_SPDIFI_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_ChangeInputSource_0_ret;
		HRESULT AUDIO_RPC_ToAgent_SET_ATV_CLOCK_0_ret;
		HRESULT AUDIO_RPC_ToAgent_INOUT_CH_SELECT_0_ret;
		HRESULT AUDIO_RPC_ToAgent_SET_FS_CLOCKSRC_0_ret;
		HRESULT AUDIO_RPC_ToAgent_SET_PATH_DATA_OUT_0_ret;
		HRESULT AUDIO_RPC_ToAgent_SET_INTERLEAVE_OUT_0_ret;
		HRESULT AUDIO_RPC_ToAgent_SET_CHANNEL_OUT_SWAP_0_ret;
		HRESULT AUDIO_RPC_ToAgent_SetAuthorityKey_0_ret;
		HRESULT AUDIO_RPC_ToAgent_GET_SPDIF_CS_0_ret;
		HRESULT AUDIO_RPC_ToAgent_SET_SIF_ADC_INIT_0_ret;
		HRESULT AUDIO_RPC_ToAgent_HDMI_OUT_EDID_0_ret;
		HRESULT AUDIO_RPC_ToAgent_HDMI_INFO_0_ret;
		HRESULT AUDIO_RPC_ToAgent_UpdatePTS_0_ret;
		HRESULT AUDIO_RPC_ToAgent_EndOfStream_0_ret;
		HRESULT AUDIO_RPC_ToAgent_SwitchFocus_0_ret;
		HRESULT AUDIO_RPC_ToAgent_DAC_I2S_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_DAC_SPDIF_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_HDMI_OUT_VSDB_0_ret;
		HRESULT AUDIO_RPC_ToAgent_HDMI_OUT_EDID2_0_ret;
		HRESULT AUDIO_RPC_ToAgent_DecoderConfig_0_ret;
		HRESULT AUDIO_RPC_ToAgent_NightMode_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_InitPin_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AskDebugMemoryAddress_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_SRC_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_PL2_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_MIXER_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_BASS_MANAGEMENT_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_KEY_SHIFT_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_REVERB_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_COMFORT_LISTEN_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_EQ_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_VOCAL_REMOVER_Config_0_ret;
		AUDIO_RPC_DEC_FORMAT_INFO AUDIO_RPC_DEC_ToAgent_GetAudioFormatInfo_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_DVS_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_TSXT_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_PTS_MIXER_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_BASSBACK_PCBU_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_BASSBACK_TV_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_BASSBACK_Change_Bass_Gain_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_AGC_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_TRUVOLUME_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_FREQ_EQ_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_ASF_ON_OFF_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_ASF_BALANCE_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_ASF_VOLUME_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_SubChannel_0_ret;
		HRESULT AUDIO_RPC_ToAgent_TrueHD_LosslessMode_0_ret;
		HRESULT AUDIO_RPC_ToAgent_PP_TSHD_Config_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetMode_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetMain_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetFn000_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetFn001_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetFn009_0_ret;
		AUDIO_RPC_LGSE_RETURNVAL AUDIO_RPC_ToAgent_AO_LGSE_SetFn010_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetFn004_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetFn005_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetFn008_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetFn014_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetFn017_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetFn019_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetFn022_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetFn018_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetFn026_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetFn027_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetFn028_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetFn029_0_ret;
		AUDIO_RPC_LGSE_RETURNVAL AUDIO_RPC_ToAgent_AO_LGSE_GetData_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AO_LGSE_SetFn024_0_ret;
		AUDIO_RPC_DEC_SEEKING_CAP AUDIO_RPC_DEC_ToAgent_GetAudioDecoderSeekCap_0_ret;
		HRESULT AUDIO_RPC_ToAgent_Capability_SetMask_0_ret;
		AUDIO_RPC_AIN_FORMAT_INFO AUDIO_RPC_AIN_ToAgent_GetAudioFormatInfo_0_ret;
		HRESULT AUDIO_RPC_ToAgent_AudioHalt_0_ret;
		HRESULT AUDIO_RPC_ToAgent_Full_Capability_SetMask_0_ret;
		AUDIO_RPC_PRIVATEINFO_RETURNVAL AUDIO_RPC_ToAgent_PrivateInfo_0_ret;
		HRESULT AUDIO_RPC_ToAgent_Capability_SetPassThroughMode_0_ret;
		USB_DEVICE_CONFIG_INFO AUDIO_RPC_ToAgent_AI_Device_USBinfo_0_ret;
		HRESULT AUDIO_RPC_ToAgent_Set_Dummy_Value_0_ret;
	} retval;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct RPC_STRUCT *, char *);
	int ReplyParaSize;


	switch (rpc->procedureID) {
	case AUDIO_RPC_ToAgent_Create:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_INSTANCE;
		_xdr_result = (xdrproc_t) xdr_RPCRES_LONG;
		ReplyParaSize = sizeof(RPCRES_LONG);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_Create_0_svc;
		break;

	case AUDIO_RPC_ToAgent_Connect:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_CONNECTION;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_Connect_0_svc;
		break;

	case AUDIO_RPC_ToAgent_InitRingBufferHeader:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_RINGBUFFER_HEADER;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_InitRingBufferHeader_0_svc;
		break;

	case AUDIO_RPC_ToAgent_Run:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_Run_0_svc;
		break;

	case AUDIO_RPC_ToAgent_Pause:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_Pause_0_svc;
		break;

	case AUDIO_RPC_ToAgent_Stop:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_Stop_0_svc;
		break;

	case AUDIO_RPC_ToAgent_Destroy:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_Destroy_0_svc;
		break;

	case AUDIO_RPC_ToAgent_Flush:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SENDIO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_Flush_0_svc;
		break;

	case AUDIO_RPC_ToAgent_SetRefClock:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_REFCLOCK;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_SetRefClock_0_svc;
		break;

	case AUDIO_RPC_ToAgent_GetStatus:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SEND_LONG;
		_xdr_result = (xdrproc_t) xdr_RPCRES_LONG;
		ReplyParaSize = sizeof(RPCRES_LONG);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_GetStatus_0_svc;
		break;

	case AUDIO_RPC_ToAgent_SetSeeking:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SEEK;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_SetSeeking_0_svc;
		break;

	case AUDIO_RPC_ToAgent_DisConnect:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_CONNECTION;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_DisConnect_0_svc;
		break;

	case AUDIO_RPC_ToAgent_BitstreamValidation:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_DEC_BITSTREAM_BUFFER;
		_xdr_result = (xdrproc_t) xdr_AUDIO_RPC_FORMAT_INFO;
		ReplyParaSize = sizeof(AUDIO_RPC_FORMAT_INFO);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_BitstreamValidation_0_svc;
		break;

	case AUDIO_RPC_AO_ToAgent_IsFinishPlaySoundEvent:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		ReplyParaSize = sizeof(int);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_AO_ToAgent_IsFinishPlaySoundEvent_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AudioConfig:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_CONFIG_COMMAND;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AudioConfig_0_svc;
		break;

	case AUDIO_RPC_DEC_ToAgent_Init:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_DEC_INIT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_DEC_ToAgent_Init_0_svc;
		break;

	case AUDIO_RPC_DEC_ToAgent_SkipMode:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SEND_LONG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_DEC_ToAgent_SkipMode_0_svc;
		break;

	case AUDIO_RPC_DEC_ToAgent_SetDualMonoOutMode:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_CHANNEL_OUT_MODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_DEC_ToAgent_SetDualMonoOutMode_0_svc;
		break;

	case AUDIO_RPC_DEC_ToAgent_GetPTS:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_AUDIO_RPC_GET_PTS_INFO;
		ReplyParaSize = sizeof(AUDIO_RPC_GET_PTS_INFO);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_DEC_ToAgent_GetPTS_0_svc;
		break;

	case AUDIO_RPC_ENC_ToAgent_Init:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_ENC_INIT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ENC_ToAgent_Init_0_svc;
		break;

	case AUDIO_RPC_ENC_ToAgent_SetBitRate:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_ENC_SET_BITRATE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ENC_ToAgent_SetBitRate_0_svc;
		break;

	case AUDIO_RPC_ENC_ToAgent_StartEncoder:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SEND_LONG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ENC_ToAgent_StartEncoder_0_svc;
		break;

	case AUDIO_RPC_ENC_ToAgent_PauseEncoder:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SEND_LONG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ENC_ToAgent_PauseEncoder_0_svc;
		break;

	case AUDIO_RPC_ENC_ToAgent_StopEncoder:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SEND_LONG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ENC_ToAgent_StopEncoder_0_svc;
		break;

	case AUDIO_RPC_ENC_ToAgent_SetSourceFile:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_ENC_SOURCEFILE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ENC_ToAgent_SetSourceFile_0_svc;
		break;

	case AUDIO_RPC_ENC_ToAgent_Command:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_ENC_COMMAND;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ENC_ToAgent_Command_0_svc;
		break;

	case AUDIO_RPC_ENC_ToAgent_MuteEncoder:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SEND_LONG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ENC_ToAgent_MuteEncoder_0_svc;
		break;

	case AUDIO_RPC_ENC_SetEncoder:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_ENC_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ENC_SetEncoder_0_svc;
		break;

	case AUDIO_RPC_ENC_ToAgent_SetDVMixer:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_ENC_DV_MIXER;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ENC_ToAgent_SetDVMixer_0_svc;
		break;

	case AUDIO_RPC_ENC_ToAgent_SetNonRealTime:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SEND_LONG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ENC_ToAgent_SetNonRealTime_0_svc;
		break;

	case AUDIO_RPC_ENC_ToAgent_SetInputSR:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SEND_LONG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ENC_ToAgent_SetInputSR_0_svc;
		break;

	case AUDIO_RPC_AO_ToAgent_Init:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_AO_INIT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_AO_ToAgent_Init_0_svc;
		break;

	case AUDIO_RPC_AO_ToAgent_SetEaqualizer:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_AO_SET_EQUALIZER;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_AO_ToAgent_SetEaqualizer_0_svc;
		break;

	case AUDIO_RPC_AO_ToAgent_ConfigDelayControl:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_AO_RPC_CONFIG_DELAY_CONTROL;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_AO_ToAgent_ConfigDelayControl_0_svc;
		break;

	case AUDIO_RPC_AO_ToAgent_ConfigKaraoke:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_AO_CONFIG_KARAOKE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_AO_ToAgent_ConfigKaraoke_0_svc;
		break;

	case AUDIO_RPC_AO_ToAgent_ConfigMixer:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_AO_MIXER;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_AO_ToAgent_ConfigMixer_0_svc;
		break;

	case AUDIO_RPC_AO_ToAgent_ConfigPP:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_PP_CFG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_AO_ToAgent_ConfigPP_0_svc;
		break;

	case AUDIO_RPC_AO_ToAgent_Mute:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_OUT_MUTE_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_AO_ToAgent_Mute_0_svc;
		break;

	case AUDIO_RPC_AO_ToAgent_ConfigDAC:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_AO_DAC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_AO_ToAgent_ConfigDAC_0_svc;
		break;

	case AUDIO_RPC_AO_ToAgent_ConfigPrologic:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_PP_PROLOGIC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_AO_ToAgent_ConfigPrologic_0_svc;
		break;

	case AUDIO_RPC_AO_ToAgent_SPDIFO_Source_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SPDIFO_SOURCE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_AO_ToAgent_SPDIFO_Source_Config_0_svc;
		break;

	case AUDIO_RPC_AO_ToAgent_ResampleTable:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_RESAMPLE_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_AO_ToAgent_ResampleTable_0_svc;
		break;

	case AUDIO_RPC_ToAgent_ADC0_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_CONFIG_ADC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_ADC0_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_ADC1_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_CONFIG_ADC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_ADC1_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_SPDIF_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_CONFIG_SPDIF;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_SPDIF_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AI_BackDoor_Init:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_BACKDOOR_AI_INIT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AI_BackDoor_Init_0_svc;
		break;

	case AUDIO_RPC_ToAgent_SPDIF_Err_Threshold_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_CONFIG_SPDIF_ERR;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_SPDIF_Err_Threshold_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AIN_Switch_Focus:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_IN_SOURCE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AIN_Switch_Focus_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AOUT_Copy_Source:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_OUT_COPY_SOURCE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AOUT_Copy_Source_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AOUT_Volume_Control:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_VOLUME_CONTROL;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AOUT_Volume_Control_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AOUT_SPDIF_Source:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_OUT_SPDIF_SOURCE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AOUT_SPDIF_Source_0_svc;
		break;

	case AUDIO_RPC_ToAgent_Karaoke_Control:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_KARAOKE_CONTROL_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_Karaoke_Control_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AIN_Mute:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_IN_MUTE_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AIN_Mute_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AOUT_Drop_Sample:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_DROP_SAMPLE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AOUT_Drop_Sample_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AOUT_Pink_White_Noise:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_P_W_NOISE_CFG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AOUT_Pink_White_Noise_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AOUT_Send_Spectrum_Data:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_SPECTRUM_CFG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AOUT_Send_Spectrum_Data_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PlaySoundEvent:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_SOUND_EVENT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PlaySoundEvent_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AOUT_ResetPin:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AOUT_ResetPin_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AFC_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_CONFIG_AFC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AFC_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_Audistry_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDISTRY_CONFIG_COMMAND;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_Audistry_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_HDMI_Mute:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_HDMI_MUTE_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_HDMI_Mute_0_svc;
		break;

	case AUDIO_RPC_ToAgent_ADC2_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_CONFIG_ADC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_ADC2_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AOUT_HDMI_Set:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_HDMI_SET;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AOUT_HDMI_Set_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_Only_Switchfocus:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_AO_FOCUS;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_Only_Switchfocus_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AIN_Data_Measurement:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_IN_DATA_MEASURE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AIN_Data_Measurement_0_svc;
		break;

	case AUDIO_RPC_ToAgent_BBADC_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_BBADC_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_BBADC_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_I2SI_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_I2SI_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_I2SI_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_SPDIFI_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SPDIFI_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_SPDIFI_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_ChangeInputSource:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_IPT_SRC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_ChangeInputSource_0_svc;
		break;

	case AUDIO_RPC_ToAgent_SET_ATV_CLOCK:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SET_ATV_CLOCK;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_SET_ATV_CLOCK_0_svc;
		break;

	case AUDIO_RPC_ToAgent_INOUT_CH_SELECT:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_INOUT_CH_SELECT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_INOUT_CH_SELECT_0_svc;
		break;

	case AUDIO_RPC_ToAgent_SET_FS_CLOCKSRC:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SET_FS_CLOCKSRC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_SET_FS_CLOCKSRC_0_svc;
		break;

	case AUDIO_RPC_ToAgent_SET_PATH_DATA_OUT:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SET_PATH_DATA_OUT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_SET_PATH_DATA_OUT_0_svc;
		break;

	case AUDIO_RPC_ToAgent_SET_INTERLEAVE_OUT:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SET_INTERLEAVE_OUT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_SET_INTERLEAVE_OUT_0_svc;
		break;

	case AUDIO_RPC_ToAgent_SET_CHANNEL_OUT_SWAP:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_AO_CHANNEL_OPT_SWAP;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_SET_CHANNEL_OUT_SWAP_0_svc;
		break;

	case AUDIO_RPC_ToAgent_SetAuthorityKey:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_SetAuthorityKey_0_svc;
		break;

	case AUDIO_RPC_ToAgent_GET_SPDIF_CS:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_SPDIF_CS;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_GET_SPDIF_CS_0_svc;
		break;

	case AUDIO_RPC_ToAgent_SET_SIF_ADC_INIT:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SET_SIF_ADC_INIT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_SET_SIF_ADC_INIT_0_svc;
		break;

	case AUDIO_RPC_ToAgent_HDMI_OUT_EDID:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_HDMI_OUT_EDID_DATA;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_HDMI_OUT_EDID_0_svc;
		break;

	case AUDIO_RPC_ToAgent_HDMI_INFO:
		_xdr_argument = (xdrproc_t) xdr_HDMI_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_HDMI_INFO_0_svc;
		break;

	case AUDIO_RPC_ToAgent_UpdatePTS:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_PTS_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_UpdatePTS_0_svc;
		break;

	case AUDIO_RPC_ToAgent_EndOfStream:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SENDPIN_LONG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_EndOfStream_0_svc;
		break;

	case AUDIO_RPC_ToAgent_SwitchFocus:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_FOCUS;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_SwitchFocus_0_svc;
		break;

	case AUDIO_RPC_ToAgent_DAC_I2S_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_CONFIG_DAC_I2S;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_DAC_I2S_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_DAC_SPDIF_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_CONFIG_DAC_SPDIF;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_DAC_SPDIF_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_HDMI_OUT_VSDB:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_HDMI_OUT_VSDB_DATA;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_HDMI_OUT_VSDB_0_svc;
		break;

	case AUDIO_RPC_ToAgent_HDMI_OUT_EDID2:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_HDMI_OUT_EDID_DATA2;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_HDMI_OUT_EDID2_0_svc;
		break;

	case AUDIO_RPC_ToAgent_DecoderConfig:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_DECCFG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_DecoderConfig_0_svc;
		break;

	case AUDIO_RPC_ToAgent_NightMode:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_NIGHTMODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_NightMode_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_InitPin:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_InitPin_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AskDebugMemoryAddress:
		_xdr_argument = (xdrproc_t) xdr_u_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AskDebugMemoryAddress_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_PP_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_SRC_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_SRC_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_SRC_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_PL2_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_PROLOGIC2_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_PL2_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_MIXER_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_MIXER_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_MIXER_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_BASS_MANAGEMENT_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_BASS_MANAGEMENT_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_BASS_MANAGEMENT_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_KEY_SHIFT_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_KEY_SHIFT_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_KEY_SHIFT_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_REVERB_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_REVERB_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_REVERB_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_COMFORT_LISTEN:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_AGC_MODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_COMFORT_LISTEN_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_EQ_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_EQUALIZER_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_EQ_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_VOCAL_REMOVER_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_VOCAL_REMOVER_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_VOCAL_REMOVER_Config_0_svc;
		break;

	case AUDIO_RPC_DEC_ToAgent_GetAudioFormatInfo:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_AUDIO_RPC_DEC_FORMAT_INFO;
		ReplyParaSize = sizeof(AUDIO_RPC_DEC_FORMAT_INFO);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_DEC_ToAgent_GetAudioFormatInfo_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_DVS_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_DVS_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_DVS_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_TSXT_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_TSXT;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_TSXT_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_PTS_MIXER_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_PTS_MIXER_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_PTS_MIXER_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_BASSBACK_PCBU_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_PCBU_BASSBACK;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_BASSBACK_PCBU_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_BASSBACK_TV_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_TV_BASSBACK;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_BASSBACK_TV_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_BASSBACK_Change_Bass_Gain:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_TV_BASSBACK_CHANGE_BASS_GAIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_BASSBACK_Change_Bass_Gain_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_AGC:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_PP_AGC;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_AGC_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_TRUVOLUME_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_TRUVOLUME;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_TRUVOLUME_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_FREQ_EQ_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_FREQ_EQ;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_FREQ_EQ_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_ASF_ON_OFF_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_PP_ASF_ON_OFF;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_ASF_ON_OFF_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_ASF_BALANCE_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_PP_ASF_BALANCE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_ASF_BALANCE_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_ASF_VOLUME_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_PP_ASF_MASTER_VOLUME;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_ASF_VOLUME_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_SubChannel:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_SUBCHANNEL;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_SubChannel_0_svc;
		break;

	case AUDIO_RPC_ToAgent_TrueHD_LosslessMode:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_TRUEHD_LOSSLESSMODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_TrueHD_LosslessMode_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PP_TSHD_Config:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_TSHD;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PP_TSHD_Config_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetMode:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETMODE;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetMode_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetMain:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETMAIN;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetMain_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn000:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN000;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn000_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn001:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN001;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn001_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn009:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN009;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn009_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn010:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN010;
		_xdr_result = (xdrproc_t) xdr_AUDIO_RPC_LGSE_RETURNVAL;
		ReplyParaSize = sizeof(AUDIO_RPC_LGSE_RETURNVAL);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn010_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn004:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN004;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn004_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn005:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN005;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn005_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn008:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN008;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn008_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn014:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN014;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn014_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn017:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN017;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn017_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn019:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN019;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn019_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn022:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN022;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn022_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn018:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN018;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn018_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn026:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN026;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn026_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn027:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN027;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn027_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn028:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN028;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn028_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn029:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN029;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn029_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_GetData:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_GETDATA;
		_xdr_result = (xdrproc_t) xdr_AUDIO_RPC_LGSE_RETURNVAL;
		ReplyParaSize = sizeof(AUDIO_RPC_LGSE_RETURNVAL);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_GetData_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AO_LGSE_SetFn024:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_LGSE_SETFN024;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AO_LGSE_SetFn024_0_svc;
		break;

	case AUDIO_RPC_DEC_ToAgent_GetAudioDecoderSeekCap:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_DEC_TYPE;
		_xdr_result = (xdrproc_t) xdr_AUDIO_RPC_DEC_SEEKING_CAP;
		ReplyParaSize = sizeof(AUDIO_RPC_DEC_SEEKING_CAP);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_DEC_ToAgent_GetAudioDecoderSeekCap_0_svc;
		break;

	case AUDIO_RPC_ToAgent_Capability_SetMask:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_Capability_SetMask_0_svc;
		break;

	case AUDIO_RPC_AIN_ToAgent_GetAudioFormatInfo:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_AUDIO_RPC_AIN_FORMAT_INFO;
		ReplyParaSize = sizeof(AUDIO_RPC_AIN_FORMAT_INFO);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_AIN_ToAgent_GetAudioFormatInfo_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AudioHalt:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AudioHalt_0_svc;
		break;

	case AUDIO_RPC_ToAgent_Full_Capability_SetMask:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_LICENSE_STATUS_CONFIG;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_Full_Capability_SetMask_0_svc;
		break;

	case AUDIO_RPC_ToAgent_PrivateInfo:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_RPC_PRIVATEINFO_PARAMETERS;
		_xdr_result = (xdrproc_t) xdr_AUDIO_RPC_PRIVATEINFO_RETURNVAL;
		ReplyParaSize = sizeof(AUDIO_RPC_PRIVATEINFO_RETURNVAL);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_PrivateInfo_0_svc;
		break;

	case AUDIO_RPC_ToAgent_Capability_SetPassThroughMode:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_PASSTHROUGH_INFO;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_Capability_SetPassThroughMode_0_svc;
		break;

	case AUDIO_RPC_ToAgent_AI_Device_USBinfo:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_AI_DEVICE_USB_INFO;
		_xdr_result = (xdrproc_t) xdr_USB_DEVICE_CONFIG_INFO;
		ReplyParaSize = sizeof(USB_DEVICE_CONFIG_INFO);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_AI_Device_USBinfo_0_svc;
		break;

	case AUDIO_RPC_ToAgent_Set_Dummy_Value:
		_xdr_argument = (xdrproc_t) xdr_AUDIO_DUMMY_DATA;
		_xdr_result = (xdrproc_t) xdr_HRESULT;
		ReplyParaSize = sizeof(HRESULT);
		local = (char *(*)(char *, struct RPC_STRUCT *, char *)) AUDIO_RPC_ToAgent_Set_Dummy_Value_0_svc;
		break;

	default:
#ifdef IS_SCPU
		RPC_EMERG("unknown procedure:pid = %d, procedureID = %d\n", (int)gettid(), (int)rpc->procedureID);
#endif
		return;
	}


	memset ((char *)&argument, 0, sizeof (argument));


	if (!rpc_getargs (rpc, (xdrproc_t) _xdr_argument, (caddr_t) &argument, opt)) {
		printf("get args error\n");
#ifdef IS_SCPU
		RPC_EMERG("rpc_getargs error:pid = %d, procedureID = %d\n", (int)gettid(), (int)rpc->procedureID);
#endif
		return;
	}

#ifdef IS_SCPU
	Q9527_DEBUG()

#endif
	pthread_mutex_unlock(pMutex);

	(*local)((char *)&argument, rpc, (char *)&retval);


	// When source msg is BLOCK_MODE,
	// we must help it reply
	// ps: reply mode is NON_BLOCK and use request's ringbuf type
	if (rpc->taskID != 0) {
	    SendReply(rpc->taskID, rpc->mycontext, (char *)&retval, ReplyParaSize,
			 (xdrproc_t) _xdr_result, opt);
	}

	return;
}


struct REG_STRUCT * AUDIO_SYSTEM_0_register(struct REG_STRUCT *rnode) {

	return (struct REG_STRUCT *)ipc_register(rnode, AUDIO_SYSTEM, 0,
		(void (*)(struct RPC_STRUCT *, int, pthread_mutex_t*))AUDIO_SYSTEM_0);

}
