KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/ademod
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/ademod/ademodcomm

ademodcore-objs := ifd_new.o \
                           ifd_agc.o \
					ifd_cr.o \
					ifd_video.o \
					ifd_table.o \
					ifd_analog.o \

					
					
obj-y += ademodcore.o 



