#ifndef _DEMOD_CMD_H_
#define _DEMOD_CMD_H_

#include <linux/init.h>
#include <linux/module.h>
#include <linux/version.h>
#include <linux/slab.h>
#include <linux/pci.h>
#include <linux/input.h>

// IO control define
#define RTK_DEMOD_CTL_CODE(code)            code
#define IOCTL_RTK_DEMOD_CONSTRUCTORS        RTK_DEMOD_CTL_CODE(0x100)
#define IOCTL_RTK_DEMOD_INIT                RTK_DEMOD_CTL_CODE(0x101)
#define IOCTL_RTK_DEMOD_SETIF               RTK_DEMOD_CTL_CODE(0x102)
#define IOCTL_RTK_DEMOD_SETTVMODE           RTK_DEMOD_CTL_CODE(0x103)
#define IOCTL_RTK_DEMOD_SETTVSYSEX          RTK_DEMOD_CTL_CODE(0x104)
#define IOCTL_RTK_DEMOD_ACQUIRESIGNAL       RTK_DEMOD_CTL_CODE(0x105)
#define IOCTL_RTK_DEMOD_UNINIT              RTK_DEMOD_CTL_CODE(0x106)
#define IOCTL_RTK_DEMOD_DESTRUCTORS         RTK_DEMOD_CTL_CODE(0x107)
#define IOCTL_RTK_DEMOD_SETTSMODE           RTK_DEMOD_CTL_CODE(0x108)
#define IOCTL_RTK_DEMOD_GETLOCK             RTK_DEMOD_CTL_CODE(0x109)
#define IOCTL_RTK_DEMOD_AUTO_TUNE           RTK_DEMOD_CTL_CODE(0x10a)
#define IOCTL_RTK_DEMOD_SETMODE             RTK_DEMOD_CTL_CODE(0x10b)
#define IOCTL_RTK_DEMOD_SETTVPARA           RTK_DEMOD_CTL_CODE(0x10c)
#define IOCTL_RTK_DEMOD_GETQUALITY          RTK_DEMOD_CTL_CODE(0x10d)
#define IOCTL_RTK_DEMOD_SETTVSYS            RTK_DEMOD_CTL_CODE(0x10e)
#define IOCTL_RTK_DEMOD_GET_SIGNAL_INFO     RTK_DEMOD_CTL_CODE(0x10f)
#define IOCTL_RTK_DEMOD_GET_DEBUG_INFO      RTK_DEMOD_CTL_CODE(0x110)
#define IOCTL_RTK_DEMOD_INSPECT_SIGNAL      RTK_DEMOD_CTL_CODE(0x111)
#define IOCTL_RTK_DEMOD_GETCROFFSET         RTK_DEMOD_CTL_CODE(0x112)
#define IOCTL_RTK_DEMOD_GETCHANNELINFO      RTK_DEMOD_CTL_CODE(0x113)
#define IOCTL_RTK_DEMOD_GETREGCMD           RTK_DEMOD_CTL_CODE(0x114)
#define IOCTL_RTK_DEMOD_SETREGCMD           RTK_DEMOD_CTL_CODE(0x115)
#define IOCTL_RTK_DEMOD_GET_DEMOD_INFO         RTK_DEMOD_CTL_CODE(0x116)


#define IOCTL_RTK_DEMOD_SETDISEQC_22K       RTK_DEMOD_CTL_CODE(0x120)
#define IOCTL_RTK_DEMOD_SETDISEQC_CMD       RTK_DEMOD_CTL_CODE(0x121)
#define IOCTL_RTK_DEMOD_SETDISEQC_BURST     RTK_DEMOD_CTL_CODE(0x122)
#define IOCTL_RTK_DEMOD_SETTUNER_INPUT_MODE RTK_DEMOD_CTL_CODE(0x123)

#define IOCTL_RTK_DEMOD_GETT2PLPINFO	    RTK_DEMOD_CTL_CODE(0x130)
#define IOCTL_RTK_DEMOD_CHANGET2PLP         RTK_DEMOD_CTL_CODE(0x131)

#define IOCTL_RTK_DEMOD_BLINDSCAN_INIT	            RTK_DEMOD_CTL_CODE(0x140)
#define IOCTL_RTK_DEMOD_BLINDSCAN_NEXTFREQ          RTK_DEMOD_CTL_CODE(0x141)
#define IOCTL_RTK_DEMOD_BLINDSCAN_GETTUNERFREQ	    RTK_DEMOD_CTL_CODE(0x142)
#define IOCTL_RTK_DEMOD_BLINDSCAN_END	            RTK_DEMOD_CTL_CODE(0x143)
#define IOCTL_RTK_DEMOD_BLINDSCAN_GETFOUNDTP	    RTK_DEMOD_CTL_CODE(0x144)
#define IOCTL_RTK_DEMOD_BLINDSCAN_GETSTATUS         RTK_DEMOD_CTL_CODE(0x145)
#define IOCTL_RTK_DEMOD_BLINDSCAN_ACQUIRE_SIGNAL    RTK_DEMOD_CTL_CODE(0x146)


#endif

