KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/ademod/ademodcore
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/demodcomm
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/demodcore

rtkdemod-objs := DemodMgr.o \
                                     demod_debug.o \
                                     demod.o \
                                     demod_rtk_all.o \
                                     demod_rtk_atsc.o \
                                     demod_rtk_isdbt.o \
                                     demod_rtk_qam.o \
                                     demod_rtk_dvbc.o \
                                     demod_rtk_dvbt2.o \
                                     demod_rtk_dvbs2.o \
                                     demod_rtk_dtmb.o \
                                     demod_rtk_atv.o \
                                     demod_rtk_common.o 
                                     					
obj-y += rtkdemod.o 
obj-y +=demodcore/
obj-y +=demodcomm/



