realtek_dmx-objs = rtkdemux_driver.o \
					rtkdemux.o \
					rtkdemux_clock.o \
					rtkdemux_dump.o \
					rtkdemux_debug.o \
					rtkdemux_ioctl.o \
					rtkdemux_pcrdebugger.o \
					rtkdemux_pcrsync.o \
					rtkdemux_pcrqueue.o \
					rtkdemux_pcrtracking.o \
					rtkdemux_rec.o \
					rtkdemux_refclk.o \
					rtkdemux_register.o \
					rtkdemux_specialhandling.o \
					rtkdemux_LinearRegression.o \
					rtkdemux_buf.o	\
					rtkdemux_MW.o   \
                                        rtkdemux_pvr.o

obj-y += realtek_dmx.o

