#
# Makefile for the linux kernel.
#

obj-$(CONFIG_MMC_BLOCK)         += rtksd_ops_299x.o
obj-$(CONFIG_MMC_RTKEMMC_PLUS)  += rtkemmc_299x.o
obj-$(CONFIG_MMC_RTKEMMC_PLUS)  += rtkemmc_raw.o
obj-$(CONFIG_MMC_RTKSD)         += rtksdio_299x.o


