/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SECURERPC_SYSTEM_DATA_H_RPCGEN
#define _SECURERPC_SYSTEM_DATA_H_RPCGEN

#include <RPCBaseDS.h>
#include <SecureRPCBaseDS.h>

struct RPC_sstore_rpc_cmd_t {
	u_int ulCmd;
	u_int algo;
	u_long keyType;
	u_long pkey;
	u_long keyLen;
	u_long pIV;
	u_long IVLen;
	u_long pDataIn;
	u_long dataInLen;
	u_long pDataOut;
	u_long dataOutLen;
	u_long pHmacKey;
};
typedef struct RPC_sstore_rpc_cmd_t RPC_sstore_rpc_cmd_t;

struct RPC_tee_rpc_cmd_t {
	RPC_RtkDrmCode func_code;
	u_long pSharedMem;
	u_long sharedMemSize;
};
typedef struct RPC_tee_rpc_cmd_t RPC_tee_rpc_cmd_t;

struct RPC_tee_manager_cmd_t {
	char procName[256];
};
typedef struct RPC_tee_manager_cmd_t RPC_tee_manager_cmd_t;

struct RPC_tee_manager_time_t {
	long tv_sec;
	long tv_usec;
};
typedef struct RPC_tee_manager_time_t RPC_tee_manager_time_t;

struct RPC_tee_manager_key_t {
	char esnkey[2048];
	long esnkeyLen;
	char playReadyKey[51200];
	long playReadyKeyLen;
};
typedef struct RPC_tee_manager_key_t RPC_tee_manager_key_t;

struct RPC_tee_manager_memInfo_t {
	long pPhysicalMem;
	long size;
	long procName[256];
};
typedef struct RPC_tee_manager_memInfo_t RPC_tee_manager_memInfo_t;

struct RPC_tee_protection_cmd_t {
	u_long type;
	u_long arg;
	u_long start_addr;
	u_long end_addr;
	u_long reserve[3];
	char name[32];
};
typedef struct RPC_tee_protection_cmd_t RPC_tee_protection_cmd_t;

struct SECURE_RPC_DTVAPI_SS {
	long type;
	long size;
	long data[5];
};
typedef struct SECURE_RPC_DTVAPI_SS SECURE_RPC_DTVAPI_SS;

struct SECURE_RPC_DTVAPI_S {
	long type;
	long size;
	long data[10];
};
typedef struct SECURE_RPC_DTVAPI_S SECURE_RPC_DTVAPI_S;

struct SECURE_RPC_DTVAPI_M {
	long type;
	long size;
	long data[30];
};
typedef struct SECURE_RPC_DTVAPI_M SECURE_RPC_DTVAPI_M;

struct SECURE_RPC_DTVAPI_MM {
	long type;
	long size;
	long data[80];
};
typedef struct SECURE_RPC_DTVAPI_MM SECURE_RPC_DTVAPI_MM;

struct SECURE_RPC_DTVAPI_L {
	long type;
	long size;
	long data[320];
};
typedef struct SECURE_RPC_DTVAPI_L SECURE_RPC_DTVAPI_L;

struct SECURE_RPC_DTVAPI_LL {
	long type;
	long size;
	long data[400];
};
typedef struct SECURE_RPC_DTVAPI_LL SECURE_RPC_DTVAPI_LL;

struct RPCRES_SS {
	HRESULT result;
	long size;
	long data[5];
};
typedef struct RPCRES_SS RPCRES_SS;

struct RPCRES_S {
	HRESULT result;
	long size;
	long data[10];
};
typedef struct RPCRES_S RPCRES_S;

struct RPCRES_M {
	HRESULT result;
	long size;
	long data[30];
};
typedef struct RPCRES_M RPCRES_M;

struct RPCRES_MM {
	HRESULT result;
	long size;
	long data[80];
};
typedef struct RPCRES_MM RPCRES_MM;

struct RPCRES_L {
	HRESULT result;
	long size;
	long data[320];
};
typedef struct RPCRES_L RPCRES_L;

#endif /* !_SECURERPC_SYSTEM_DATA_H_RPCGEN */
