#
# Makefile for the Realtek scaler drivers.

#open at Mac5
obj-y :=scaler_vfedev.o scaler_vscdev.o scaler_vbedev.o scaler_vpqdev.o scaler_vpqdev_unittest.o scaler_vpqdev_extern.o scaler_vpqleddev.o scaler_vtdev.o scaler_vrdev.o scaler_hdcp2dev.o scaler_vpqmemcdev.o io/ i3ddma/ vip/ vdc/ hdmirx/ adcSource/ panel/ scaler/ scalerdrv/ pcbsource/ vdac/ tve/ avd/ hdcp2_2/ vbi/ vo/

#unkown
#obj-y :=tve/ 

#obj-y := io/ adcSource/ frontend/ hdmirx/ scaler/ scalerdrv/ vdc/ vip/ tve/ vdac/ hdcp2_2/ i3ddma/
#SUBDIRS += io adcSource frontend hdmiRx scaler scalerDrv vdc vip tve vdac hdcp2_2
