#ifndef __SCALER_VPQDEV_EXTERN_H
#define  __SCALER_VPQDEV_EXTERN_H


/**
 * Video Picture Quality Information.
 *
 * @see DDI Implementation Guide
*/
#include <scalercommon/vipCommon.h>
#include <scalercommon/scalerDrvCommon.h>

#include <tvscalercontrol/vip/film.h>
#include <tvscalercontrol/vip/peaking.h>
#include <tvscalercontrol/vip/nr.h>
#include <tvscalercontrol/vip/icm.h>
//#include <tvscalercontrol/vip/scalerColor_tv010.h>
#include <tvscalercontrol/scaler/scalercolor_engmenu.h>

typedef enum{
	PQ_DEV_EXTERN_NOTHING = 0,
	PQ_DEV_EXTERN_INIT_DONE,
	PQ_DEV_EXTERN_OPEN_DONE,
	PQ_DEV_EXTERN_UNINIT,
	PQ_DEV_EXTERN_CLOSE,
} PQ_DEV_EXTERN_STATUS;

typedef struct _RTK_PQModule_T {
	unsigned int PQModule;
	unsigned char onOff;
} RTK_PQModule_T;
typedef struct _RTK_DEMO_MODE_T {
	unsigned int DEMO_MODE;
	unsigned char onOff;
} RTK_DEMO_MODE_T;

typedef struct _RTK_TV002_SR_T {
	unsigned short mode;// 0: off, 1: auto, 2: manual
	unsigned short value;// 0~100
} RTK_TV002_SR_T;

typedef struct _LC_BLK_Num_Size
{
        unsigned char nBlk_Hnum;
        unsigned char nBlk_Vnum;
}LC_BLK_Num_Size;

typedef struct _RTK_COLOR_GAMUT_T
{
	unsigned char mode;
	signed short		gamutmatrix_00;		// 3x3 matrix
	signed short		gamutmatrix_01;
	signed short		gamutmatrix_02;
	signed short		gamutmatrix_10;
	signed short		gamutmatrix_11;
	signed short		gamutmatrix_12;
	signed short		gamutmatrix_20;
	signed short		gamutmatrix_21;
	signed short		gamutmatrix_22;
	
}RTK_COLOR_GAMUT_T;

typedef struct _LC_BLKAPL
{
       UINT32 iRow;
       UINT32 iCol;
}LC_BLKAPL;

typedef struct _INTERNAL_PARTTEN
{
	unsigned char enable;
	unsigned short r_Val;
	unsigned short g_Val;
	unsigned short b_Val;

}INTERNAL_PARTTEN;

typedef struct _VPQ_SCREEN_PIXEL_INFO_TV030
{
	UINT16 h_sta;
	UINT16 h_end;
	UINT16 v_sta;
	UINT16 v_end;
	UINT32 r_sum;
	UINT32 g_sum;
	UINT32 b_sum;
} VPQ_SCREEN_PIXEL_INFO_TV030;

 typedef struct _RTK_BRIGHTNESS_LUT_OETF {
	 unsigned short 	un16_length;
	 unsigned short 	pf_LUT[256];
 }RTK_BRIGHTNESS_LUT_OETF;
 
 typedef struct
 {
	 short	 BT709Target[3][3]; 	 
	 short	 BT2020Target[3][3]; 	 
	 short	 DCIP3Target[3][3]; 	
 }RTK_VPQ_sRGB_Matrix;

typedef struct
{
   UINT8 flag_0;
   UINT8 flag_1;
   UINT8 flag_2;
   UINT8 flag_3;
   UINT8 flag_4;
   UINT8 flag_5;
   UINT8 flag_6;
   UINT8 flag_7;
   UINT8 flag_8;
   UINT8 flag_9;

}RTK_VIP_Flag;


#define VPQ_EXTERN_DEVICE_NAME						"vpqexdev"
#define VPQ_EXTERN_IOC_MAGIC 'q'
#define VPQ_EXTERN_IOC_MAGIC_TV030 'T'					//TV030

enum vpq_extend_ioc_pq_cmd
{
	VPQ_EXTERN_IOC_PQ_CMD_INIT = 0,
	VPQ_EXTERN_IOC_PQ_CMD_UNINIT = 1,/* 1*/
	VPQ_EXTERN_IOC_PQ_CMD_OPEN = 2,/* 2*/
	VPQ_EXTERN_IOC_PQ_CMD_CLOSE = 3,/* 3*/


	VPQ_EXTERN_IOC_PQ_CMD_SET_VGA_ADCGainOffset = 10,
	VPQ_EXTERN_IOC_PQ_CMD_SET_YPBPR_ADCGainOffset = 11,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SLR_VIP_TABLE_CUSTOM_TV001 = 12,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SLR_VIP_TABLE = 13,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PIC_MODE_DATA = 14,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PIC_MODE_DATA_defaultPictureModeSet = 15,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PIC_MODE_DATA_DolbyHDRPictureModeSet = 16,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataType = 17,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataType_defaultSDColorData = 18,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataType_defaultHDColorData = 19,
	VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_TEMP_DATA = 20,
	VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_TEMP_DATA_defColorTempSet = 21,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType = 22,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_defaultColorFacMode = 23,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_AvColorFacMode = 24,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_YppColorFacMode = 25,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_VgaColorFacMode = 26,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_HdmiColorFacMode = 27,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_HdmiSDColorFacMode = 28,
	VPQ_EXTERN_IOC_PQ_CMD_REGISTER_NEW_VIPTABLE = 29,
	VPQ_EXTERN_IOC_PQ_CMD_GET_CUR_SRC_FMT = 30,
	VPQ_EXTERN_IOC_PQ_CMD_GET_VIP_SRC_TIMING = 31,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacMode_EXTERN = 32,
	VPQ_EXTERN_IOC_PQ_CMD_GET_VIP_SRC_RESYNC = 33,
	VPQ_EXTERN_IOC_PQ_CMD_SET_VIP_SRC_RESYNC = 34,
	VPQ_EXTERN_IOC_PQ_CMD_SET_VIP_HANDLER_RESET = 35,

	VPQ_EXTERN_IOC_PQ_CMD_GET_BRIGHTNESS = 50,
	VPQ_EXTERN_IOC_PQ_CMD_SET_BRIGHTNESS = 51,
	VPQ_EXTERN_IOC_PQ_CMD_GET_CONTRAST = 52,
	VPQ_EXTERN_IOC_PQ_CMD_SET_CONTRAST = 53,
	VPQ_EXTERN_IOC_PQ_CMD_GET_SATURATION = 54,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SATURATION = 55,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HUE = 56,
	VPQ_EXTERN_IOC_PQ_CMD_SET_HUE = 57,
	VPQ_EXTERN_IOC_PQ_CMD_GET_NR = 58,
	VPQ_EXTERN_IOC_PQ_CMD_SET_NR = 59,
	VPQ_EXTERN_IOC_PQ_CMD_GET_SHARPNESS = 60,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SHARPNESS_EXTERN = 61,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DE_BLOCKING = 62,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DE_BLOCKING = 63,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DE_RINGING = 64,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DE_RINGING = 65,
	VPQ_EXTERN_IOC_PQ_CMD_GET_COLOR_TEMP = 66,
	VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_TEMP_EXTERN = 67,
	VPQ_EXTERN_IOC_PQ_CMD_GET_COLOR_GAIN = 68,
	VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_GAIN_EXTERN = 69,
	VPQ_EXTERN_IOC_PQ_CMD_GET_FLESH_TONE = 70,
	VPQ_EXTERN_IOC_PQ_CMD_SET_FLESH_TONE = 71,
	VPQ_EXTERN_IOC_PQ_CMD_GET_BACKLIGHT = 72,
	VPQ_EXTERN_IOC_PQ_CMD_SET_BACKLIGHT = 73,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PANEL_BL = 74,
	VPQ_EXTERN_IOC_PQ_CMD_GET_GAMMA_NUM = 75,
	VPQ_EXTERN_IOC_PQ_CMD_SET_GAMMA = 76,
	VPQ_EXTERN_IOC_PQ_CMD_GET_PQ_MODULE = 77,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PQ_MODULE = 78,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DEMO = 79,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DEBUG_MODE = 80,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DEBUG_MODE = 81,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HISTOGRAM = 82,
	VPQ_EXTERN_IOC_PQ_CMD_GET_SR_LEVEL = 83,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SR_LEVEL = 84,
	VPQ_EXTERN_IOC_PQ_CMD_SET_BLACK_PATTERN_OUTPUT = 85,
	VPQ_EXTERN_IOC_PQ_CMD_SET_WHITE_PATTERN_OUTPUT = 86,
	VPQ_EXTERN_IOC_PQ_CMD_GET_OD_LEVEL = 87,
	VPQ_EXTERN_IOC_PQ_CMD_SET_OD_READ_ENABLE =88,
	VPQ_EXTERN_IOC_PQ_CMD_GET_SRC_HDR_INFO =89,
	VPQ_EXTERN_IOC_PQ_CMD_GET_SDR2HDR =90,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SDR2HDR =91,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HDR_TYPE =92,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DCI_TYPE =93,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DOLBY_HDR_PIC_MODE =94,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DOLBY_HDR_PIC_MODE = 95,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HDR10_ENABLE = 96,
	VPQ_EXTERN_IOC_PQ_CMD_SET_HDR10_ENABLE = 97,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DREAM_PANEL_LOG_ENABLE = 98,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DREAM_PANEL_BACKLIGHT = 99,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DREAM_PANEL_BACKLIGHT = 100,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DCC_MODE = 101,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DCC_MODE = 102,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ICM_TBL_IDX = 103,
	VPQ_EXTERN_IOC_PQ_CMD_SET_ICM_TBL_IDX = 104,
	VPQ_EXTERN_IOC_PQ_CMD_GET_FILM_MODE = 105,
	VPQ_EXTERN_IOC_PQ_CMD_SET_FILM_MODE = 106,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HDMI_CSC_DATA_RANGE_MODE = 107,
	VPQ_EXTERN_IOC_PQ_CMD_SET_HDMI_CSC_DATA_RANGE_MODE = 108,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HDR_FORCE_MODE = 109,
	VPQ_EXTERN_IOC_PQ_CMD_SET_HDR_FORCE_MODE = 110,
	VPQ_EXTERN_IOC_PQ_CMD_GET_CINEMA_PIC_MODE = 111,
	VPQ_EXTERN_IOC_PQ_CMD_SET_CINEMA_PIC_MODE = 112,
	VPQ_EXTERN_IOC_PQ_CMD_GET_PQ_BYPASS_LV = 113,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PQ_BYPASS_LV = 114,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PQ_SOURCE_TYPE = 115,

	VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_TEMP_LEVEL = 123,
	VPQ_EXTERN_IOC_PQ_CMD_GET_LC_Blight_dat = 126,
	VPQ_EXTERN_IOC_PQ_CMD_GET_LC_Blight_size = 127,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DDOMAIN3DLUT_GAMMA = 128,
	VPQ_EXTERN_IOC_PQ_CMD_INIT_DDOMAIN3DLUT_GAMMA_TABLE = 129,
	
	VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU = 500,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_size = 501,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_item = 502,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_ID = 503,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_ID = 504,
	VPQ_EXTERN_IOC_PQ_CMD_SET_ENG_ID = 505,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DEBUG_BUFF_8 = 506,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DEBUG_BUFF_16 = 507,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DEBUG_BUFF_32 = 508,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DEBUG_BUFF_8 = 509,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DEBUG_BUFF_16 = 510,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DEBUG_BUFF_32 = 511,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_MENU_item = 512,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_MENU_ID = 513,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_ID = 514,
	VPQ_EXTERN_IOC_PQ_CMD_SET_ENG_TWOLAYER_ID = 515,

	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_EXT_FUN_EN = 600,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_BLE = 601,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_BLE = 602,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_SGAMMA = 603,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_SGAMMA = 604,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_MAGIC_GAMMA = 605,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_MAGIC_GAMMA = 606,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_SR = 607,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_SR = 608,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_LIVE_COLOUR = 609,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_LIVE_COLOUR = 610,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_MASTERED_4K = 611,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_MASTERED_4K = 612,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_PROJECT_STYLE = 613,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_DBC_POWER_SAVING_MODE = 614,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_DBC_UI_BACKLIGHT = 615,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_DBC_BACKLIGHT = 616,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_UI_PICTURE_MODE = 617,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_Black_Level = 618,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_Black_Level = 619,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_Reality_Creation = 620,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_Reality_Creation = 621,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_Resolution = 622,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_Resolution = 623,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_Black_Corrector = 624,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_Black_Corrector = 625,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_Black_Adjust = 626,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_Black_Adjust = 627,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_LED_Motion_Mode = 628,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_LED_Motion_Mode = 629,

	VPQ_EXTERN_IOC_PQ_CMD_GET_DOLBYHDR_ENABLE = 700,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DOLBYHDR_ENABLE = 701,
	VPQ_EXTERN_IOC_PQ_CMD_SETGAMMA_TABLESIZE= 702,
	VPQ_EXTERN_IOC_PQ_CMD_SET_GAMMA_LEVEL = 705,
	VPQ_EXTERN_IOC_PQ_CMD_HIGHLIGHTWINDOW_FORDEMO = 706,
	VPQ_EXTERN_IOC_PQ_CMD_BRIGHTNESS_LUT_OETF		= 708,
        VPQ_EXTERN_IOC_PQ_CMD_SET_PANORAMA_TYPE 		= 712,

	VPQ_EXTERN_IOC_PQ_CMD_SET_VDPQ_MEM_ENABLE = 800,

	VPQ_EXTERN_IOC_PQ_CMD_GET_GDBC_MODE = 900,
	VPQ_EXTERN_IOC_PQ_CMD_SET_GDBC_MODE = 901,
	VPQ_EXTERN_IOC_PQ_CMD_GET_GDBC_DCR_BACKLIGHT = 902,
	VPQ_EXTERN_IOC_CMD_Sync_PQ_table_bin_ENABLE = 999,
};

enum vpq_extend_ioc_pq_TV030_cmd
{
	VPQ_EXTERN_IOC_PQ_CMD_GET_MEMCLD_ENABLE_TV030 	=0,
	VPQ_EXTERN_IOC_PQ_CMD_SET_MEMCLD_ENABLE_TV030	=1,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HDR_PicInfo_TV030		=2,
	VPQ_EXTERN_IOC_PQ_CMD_GET_LC_BLK_HVNUM_TV030		=3,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SPLIT_DEMO_TV030		=4,
	VPQ_EXTERN_IOC_PQ_CMD_GET_LD_Enable_TV030			=5,
	VPQ_EXTERN_IOC_PQ_CMD_SET_COLORMATRIXSRGB_TV030	=6,
	//VPQ_EXTERN_IOC_PQ_CMD_GET_LC_BLKAPL_TV030			=7,
	//VPQ_EXTERN_IOC_PQ_CMD_SET_LCBLKSIZE_TV030			=8,
	VPQ_EXTERN_IOC_PQ_CMD_SET_LOWDELAY_MODE_TV030	=9,
	VPQ_EXTERN_IOC_PQ_CMD_GET_LC_HISTOGRAM_TV030		=10,
	VPQ_EXTERN_IOC_PQ_CMD_SET_LCHISBIN_TV030			=11,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HistoData_APL_TV030		=12,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HistoData_MAX_TV030		=13,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HistoData_MIN_TV030		=14,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PARTTENFORAUTOGAMMA_TV030	=15,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PICTUREMODE_TV030				=16,	
	VPQ_EXTERN_IOC_PQ_CMD_SET_BRIGHTNESS_OSDLAYER_TV030		=17,
	VPQ_EXTERN_IOC_PQ_CMD_SET_CONTRAST_OSDLAYER_TV030		=18,
	VPQ_EXTERN_IOC_PQ_CMD_GET_PIXELINFO_TV030					=19,	
	VPQ_EXTERN_IOC_PQ_CMD_SET_FILM_TABLE_TV030				=20,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DYNAMIC_RANGE_TV030			=21,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DYNAMIC_RANGE_CUR_SRC_TV030	=22,
	VPQ_EXTERN_IOC_PQ_CMD_SET_HDMI_MODE_TYPE_TV030			=23,
	VPQ_EXTERN_IOC_PQ_CMD_SET_COLORSPACE					=24,
	VPQ_EXTERN_IOC_PQ_CMD_SET_MAGICGAMMA_TV030				=25,
	
	VPQ_EXTERN_IOC_PQ_CMD_SET_OSDPIC_FLAG_TV030 				=28,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SET_RGBWTOSRGBMATRIX					=29,

};

#define VPQ_EXTERN_IOC_INIT						_IO(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_INIT)
#define VPQ_EXTERN_IOC_UNINIT						_IO(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_UNINIT)
#define VPQ_EXTERN_IOC_OPEN						_IO(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_OPEN)
#define VPQ_EXTERN_IOC_CLOSE						_IO(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_CLOSE)

/************************************************************************
 *  TV010 External variables
 ************************************************************************/
#define VPQ_EXTERN_IOC_REGISTER_NEW_VIPTABLE _IO(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_REGISTER_NEW_VIPTABLE)
#define VPQ_EXTERN_IOC_SET_VGA_ADCGainOffset  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_VGA_ADCGainOffset, unsigned int)
#define VPQ_EXTERN_IOC_SET_YPBPR_ADCGainOffset  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_YPBPR_ADCGainOffset, unsigned int)
#define VPQ_EXTERN_IOC_SET_SLR_VIP_TABLE_CUSTOM_TV001  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_SLR_VIP_TABLE_CUSTOM_TV001, unsigned int)
//#define VPQ_EXTERN_IOC_SET_SLR_VIP_TABLE  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_SLR_VIP_TABLE, SLR_VIP_TABLE)
#define VPQ_EXTERN_IOC_SET_SLR_VIP_TABLE  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_SLR_VIP_TABLE, unsigned int)
#define VPQ_EXTERN_IOC_SET_PIC_MODE_DATA  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_PIC_MODE_DATA, unsigned int)
#define VPQ_EXTERN_IOC_SET_PIC_MODE_DATA_defaultPictureModeSet  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_PIC_MODE_DATA_defaultPictureModeSet, unsigned int)
#define VPQ_EXTERN_IOC_SET_PIC_MODE_DATA_DolbyHDRPictureModeSet  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_PIC_MODE_DATA_DolbyHDRPictureModeSet, unsigned int)

#define VPQ_EXTERN_IOC_SET_StructColorDataType  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataType, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataType_defaultSDColorData  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataType_defaultSDColorData, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataType_defaultHDColorData  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataType_defaultHDColorData, unsigned int)

#define VPQ_EXTERN_IOC_SET_COLOR_TEMP_DATA  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_TEMP_DATA, unsigned int)
#define VPQ_EXTERN_IOC_SET_COLOR_TEMP_DATA_defColorTempSet  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_TEMP_DATA_defColorTempSet, unsigned int)

#define VPQ_EXTERN_IOC_SET_StructColorDataFacModeType  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataFacModeType_defaultColorFacMode  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_defaultColorFacMode, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataFacModeType_AvColorFacMode  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_AvColorFacMode, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataFacModeType_YppColorFacMode  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_YppColorFacMode, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataFacModeType_VgaColorFacMode  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_VgaColorFacMode, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataFacModeType_HdmiColorFacMode  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_HdmiColorFacMode, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataFacModeType_HdmiSDColorFacMode  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_HdmiSDColorFacMode, unsigned int)

#define VPQ_EXTERN_IOC_GET_CUR_SRC_FMT  _IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_CUR_SRC_FMT, unsigned int)
#define VPQ_EXTERN_IOC_GET_VIP_SRC_TIMING  _IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_VIP_SRC_TIMING, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataFacMode_EXTERN  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacMode_EXTERN, unsigned int)
#define VPQ_EXTERN_IOC_GET_VIP_SRC_RESYNC  _IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_VIP_SRC_RESYNC, unsigned int)
#define VPQ_EXTERN_IOC_SET_VIP_SRC_RESYNC  _IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_VIP_SRC_RESYNC, unsigned int)
#define VPQ_EXTERN_IOC_SET_VIP_SET_VIP_HANDLER_RESET  _IO(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_VIP_HANDLER_RESET)

#define VPQ_EXTERN_IOC_GET_BRIGHTNESS				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_BRIGHTNESS, unsigned int)
#define VPQ_EXTERN_IOC_SET_BRIGHTNESS				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_BRIGHTNESS, unsigned int)
#define VPQ_EXTERN_IOC_GET_CONTRAST				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_CONTRAST, unsigned int)
#define VPQ_EXTERN_IOC_SET_CONTRAST				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_CONTRAST, unsigned int)
#define VPQ_EXTERN_IOC_GET_SATURATION				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_SATURATION, unsigned int)
#define VPQ_EXTERN_IOC_SET_SATURATION				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_SATURATION, unsigned int)
#define VPQ_EXTERN_IOC_GET_HUE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_HUE, unsigned int)
#define VPQ_EXTERN_IOC_SET_HUE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_HUE, unsigned int)
#define VPQ_EXTERN_IOC_GET_NR				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_NR, unsigned int)
#define VPQ_EXTERN_IOC_SET_NR				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_NR, unsigned int)
#define VPQ_EXTERN_IOC_GET_SHARPNESS				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_SHARPNESS, unsigned int)
#define VPQ_EXTERN_IOC_SET_SHARPNESS_EXTERN				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_SHARPNESS_EXTERN, unsigned int)
#define VPQ_EXTERN_IOC_GET_DE_BLOCKING				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DE_BLOCKING, unsigned int)
#define VPQ_EXTERN_IOC_SET_DE_BLOCKING				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DE_BLOCKING, unsigned int)
#define VPQ_EXTERN_IOC_GET_DE_RINGING				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DE_RINGING, unsigned int)
#define VPQ_EXTERN_IOC_SET_DE_RINGING				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DE_RINGING, unsigned int)
#define VPQ_EXTERN_IOC_GET_COLOR_TEMP				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_COLOR_TEMP, unsigned int)
#define VPQ_EXTERN_IOC_SET_COLOR_TEMP_EXTERN				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_TEMP_EXTERN, unsigned int)
#define VPQ_EXTERN_IOC_SET_COLOR_TEMP_LEVEL					_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_TEMP_LEVEL, unsigned int)
#define VPQ_EXTERN_IOC_GET_LC_Blight_dat			_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_LC_Blight_dat, unsigned int)
#define VPQ_EXTERN_IOC_GET_LC_Blight_size			_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_LC_Blight_size, unsigned int)
#define VPQ_EXTERN_IOC_GET_COLOR_GAIN				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_COLOR_GAIN, unsigned int)
#define VPQ_EXTERN_IOC_SET_COLOR_GAIN_EXTERN				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_GAIN_EXTERN, unsigned int)
#define VPQ_EXTERN_IOC_GET_FLESH_TONE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_FLESH_TONE, unsigned int)
#define VPQ_EXTERN_IOC_SET_FLESH_TONE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_FLESH_TONE, unsigned int)
#define VPQ_EXTERN_IOC_GET_BACKLIGHT				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_BACKLIGHT, unsigned int)
#define VPQ_EXTERN_IOC_SET_BACKLIGHT				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_BACKLIGHT, unsigned int)
#define VPQ_EXTERN_IOC_SET_PANEL_BL				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_PANEL_BL, unsigned int)
#define VPQ_EXTERN_IOC_GET_GAMMA_NUM			_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_GAMMA_NUM, unsigned int)
#define VPQ_EXTERN_IOC_SET_GAMMA				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_GAMMA, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_MODULE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_PQ_MODULE, unsigned int)
#define VPQ_EXTERN_IOC_SET_PQ_MODULE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_PQ_MODULE, unsigned int)
#define VPQ_EXTERN_IOC_SET_DEMO				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DEMO, unsigned int)
#define VPQ_EXTERN_IOC_GET_DEBUG_MODE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DEBUG_MODE, unsigned int)
#define VPQ_EXTERN_IOC_SET_DEBUG_MODE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DEBUG_MODE, unsigned int)
#define VPQ_EXTERN_IOC_GET_HISTOGRAM				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_HISTOGRAM, unsigned int)
#define VPQ_EXTERN_IOC_GET_SR_LEVEL				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_SR_LEVEL, unsigned int)
#define VPQ_EXTERN_IOC_SET_SR_LEVEL				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_SR_LEVEL, unsigned int)
#define VPQ_EXTERN_IOC_SET_BLACK_PATTERN_OUTPUT				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_BLACK_PATTERN_OUTPUT, unsigned int)
#define VPQ_EXTERN_IOC_SET_WHITE_PATTERN_OUTPUT				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_WHITE_PATTERN_OUTPUT, unsigned int)
#define VPQ_EXTERN_IOC_GET_OD_LEVEL				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_OD_LEVEL, unsigned int)
#define VPQ_EXTERN_IOC_SET_OD_READ_ENABLE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_OD_READ_ENABLE, unsigned int)
#define VPQ_EXTERN_IOC_GET_SRC_HDR_INFO				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_SRC_HDR_INFO, unsigned int)
#define VPQ_EXTERN_IOC_GET_SDR2HDR				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_SDR2HDR, unsigned int)
#define VPQ_EXTERN_IOC_SET_SDR2HDR				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_SDR2HDR, unsigned int)
#define VPQ_EXTERN_IOC_GET_HDR_TYPE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_HDR_TYPE, unsigned int)
#define VPQ_EXTERN_IOC_SET_DCI_TYPE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DCI_TYPE, unsigned int)
#define VPQ_EXTERN_IOC_GET_DOLBY_HDR_PIC_MODE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DOLBY_HDR_PIC_MODE, unsigned int)
#define VPQ_EXTERN_IOC_SET_DOLBY_HDR_PIC_MODE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DOLBY_HDR_PIC_MODE, unsigned int)
#define VPQ_EXTERN_IOC_GET_HDR10_ENABLE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_HDR10_ENABLE, unsigned int)
#define VPQ_EXTERN_IOC_SET_HDR10_ENABLE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_HDR10_ENABLE, unsigned int)
#define VPQ_EXTERN_IOC_GET_DOLBYHDR_ENABLE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DOLBYHDR_ENABLE, unsigned int)
#define VPQ_EXTERN_IOC_SET_DOLBYHDR_ENABLE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DOLBYHDR_ENABLE, unsigned int)
#define VPQ_EXTERN_IOC_SET_DREAM_PANEL_LOG_ENABLE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DREAM_PANEL_LOG_ENABLE, unsigned int)
#define VPQ_EXTERN_IOC_GET_DREAM_PANEL_BACKLIGHT				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DREAM_PANEL_BACKLIGHT, unsigned int)
#define VPQ_EXTERN_IOC_SET_DREAM_PANEL_BACKLIGHT				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DREAM_PANEL_BACKLIGHT, unsigned int)
#define VPQ_EXTERN_IOC_GET_DCC_MODE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DCC_MODE, unsigned int)
#define VPQ_EXTERN_IOC_SET_DCC_MODE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DCC_MODE, unsigned int)
#define VPQ_EXTERN_IOC_GET_ICM_TBL_IDX				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_ICM_TBL_IDX, unsigned int)
#define VPQ_EXTERN_IOC_SET_ICM_TBL_IDX				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_ICM_TBL_IDX, unsigned int)
#define VPQ_EXTERN_IOC_GET_FILM_MODE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_FILM_MODE, unsigned int)
#define VPQ_EXTERN_IOC_SET_FILM_MODE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_FILM_MODE, unsigned int)
#define VPQ_EXTERN_IOC_GET_HDMI_CSC_DATA_RANGE_MODE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_HDMI_CSC_DATA_RANGE_MODE, unsigned int)
#define VPQ_EXTERN_IOC_SET_HDMI_CSC_DATA_RANGE_MODE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_HDMI_CSC_DATA_RANGE_MODE, unsigned int)
#define VPQ_EXTERN_IOC_GET_HDR_FORCE_MODE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_HDR_FORCE_MODE, unsigned int)
#define VPQ_EXTERN_IOC_SET_HDR_FORCE_MODE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_HDR_FORCE_MODE, unsigned int)
#define VPQ_EXTERN_IOC_GET_CINEMA_PIC_MODE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_CINEMA_PIC_MODE, unsigned int)
#define VPQ_EXTERN_IOC_SET_CINEMA_PIC_MODE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_CINEMA_PIC_MODE, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_BYPASS_LV				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_PQ_BYPASS_LV, unsigned int)
#define VPQ_EXTERN_IOC_SET_PQ_BYPASS_LV				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_PQ_BYPASS_LV, unsigned int)
#define VPQ_EXTERN_IOC_SET_PQ_SOURCE_TYPE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_PQ_SOURCE_TYPE, unsigned int)

#define VPQ_EXTERN_IOC_GET_PQ_ENGMENU				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_ENGMENU_size				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_size, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_ENGMENU_item				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_item, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_ENGMENU_ID				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_ID, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_ENG_ID				_IOWR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_ID, unsigned int)
#define VPQ_EXTERN_IOC_SET_PQ_ENG_ID				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_ENG_ID, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_DEBUG_BUFF_8				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DEBUG_BUFF_8, unsigned char)
#define VPQ_EXTERN_IOC_GET_PQ_DEBUG_BUFF_16				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DEBUG_BUFF_16, unsigned short)
#define VPQ_EXTERN_IOC_GET_PQ_DEBUG_BUFF_32				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DEBUG_BUFF_32, unsigned int)
#define VPQ_EXTERN_IOC_SET_PQ_DEBUG_BUFF_8				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DEBUG_BUFF_8, unsigned char)
#define VPQ_EXTERN_IOC_SET_PQ_DEBUG_BUFF_16				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DEBUG_BUFF_16, unsigned short)
#define VPQ_EXTERN_IOC_SET_PQ_DEBUG_BUFF_32				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DEBUG_BUFF_32, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_ENG_TWOLAYER_MENU_item			_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_MENU_item, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_ENG_TWOLAYER_MENU_ID			_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_MENU_ID, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_ENG_TWOLAYER_ID				_IOWR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_ID, unsigned int)
#define VPQ_EXTERN_IOC_SET_PQ_ENG_TWOLAYER_ID				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_ENG_TWOLAYER_ID, unsigned int)


#define VPQ_EXTERN_IOC_SET_TV002_EXT_FUN_EN			_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_EXT_FUN_EN, unsigned int)
#define VPQ_EXTERN_IOC_GET_TV002_BLE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_BLE, unsigned int)
#define VPQ_EXTERN_IOC_SET_TV002_BLE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_BLE, unsigned int)
#define VPQ_EXTERN_IOC_GET_TV002_SGAMMA				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_SGAMMA, unsigned int)
#define VPQ_EXTERN_IOC_SET_TV002_SGAMMA				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_SGAMMA, unsigned int)
#define VPQ_EXTERN_IOC_GET_TV002_MAGIC_GAMMA				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_MAGIC_GAMMA, VIP_MAGIC_GAMMA_Curve_Driver_Data)
#define VPQ_EXTERN_IOC_SET_TV002_MAGIC_GAMMA				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_MAGIC_GAMMA, VIP_MAGIC_GAMMA_Curve_Driver_Data)
#define VPQ_EXTERN_IOC_GET_TV002_SR				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_SR, RTK_TV002_SR_T)
#define VPQ_EXTERN_IOC_SET_TV002_SR				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_SR, RTK_TV002_SR_T)
#define VPQ_EXTERN_IOC_GET_TV002_LIVE_COLOUR				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_LIVE_COLOUR, unsigned int)
#define VPQ_EXTERN_IOC_SET_TV002_LIVE_COLOUR				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_LIVE_COLOUR, unsigned int)
#define VPQ_EXTERN_IOC_GET_TV002_MASTERED_4K				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_MASTERED_4K, unsigned int)
#define VPQ_EXTERN_IOC_SET_TV002_MASTERED_4K				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_MASTERED_4K, unsigned int)
#define VPQ_EXTERN_IOC_SET_TV002_PROJECT_STYLE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_PROJECT_STYLE, unsigned char)
#define VPQ_EXTERN_IOC_SET_TV002_DBC_POWER_SAVING_MODE	_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_DBC_POWER_SAVING_MODE, unsigned char)
#define VPQ_EXTERN_IOC_SET_TV002_DBC_UI_BACKLIGHT	_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_DBC_UI_BACKLIGHT, unsigned char)
#define VPQ_EXTERN_IOC_GET_TV002_DBC_BACKLIGHT	_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_DBC_BACKLIGHT, unsigned char)
#define VPQ_EXTERN_IOC_SET_TV002_UI_PICTURE_MODE	_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_UI_PICTURE_MODE, unsigned char)
#define VPQ_EXTERN_IOC_SET_TV002_Black_Level			_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_Black_Level, unsigned char)
#define VPQ_EXTERN_IOC_GET_TV002_Black_Level            _IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_Black_Level, unsigned char)
#define VPQ_EXTERN_IOC_SET_TV002_Reality_Creation       _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_Reality_Creation, unsigned char)
#define VPQ_EXTERN_IOC_GET_TV002_Reality_Creation       _IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_Reality_Creation, unsigned char)
#define VPQ_EXTERN_IOC_SET_TV002_Resolution             _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_Resolution, unsigned char)
#define VPQ_EXTERN_IOC_GET_TV002_Resolution             _IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_Resolution, unsigned char)
#define VPQ_EXTERN_IOC_SET_TV002_Black_Corrector        _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_Black_Corrector, unsigned char)
#define VPQ_EXTERN_IOC_GET_TV002_Black_Corrector        _IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_Black_Corrector, unsigned char)
#define VPQ_EXTERN_IOC_SET_TV002_Black_Adjust           _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_Black_Adjust, unsigned char)
#define VPQ_EXTERN_IOC_GET_TV002_Black_Adjust           _IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_Black_Adjust, unsigned char)
#define VPQ_EXTERN_IOC_SET_TV002_LED_Motion_Mode        _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_LED_Motion_Mode, unsigned char)
#define VPQ_EXTERN_IOC_GET_TV002_LED_Motion_Mode        _IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_LED_Motion_Mode, unsigned char)

#define VPQ_EXTERN_IOC_SET_PQ_SETGAMMA_TABLESIZE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SETGAMMA_TABLESIZE, unsigned int)
#define VPQ_EXTERN_IOC_SET_HIGHLIGHTWINDOW_FORDEMO	_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_HIGHLIGHTWINDOW_FORDEMO, unsigned int)
#define VPQ_EXTERN_IOC_SET_BRIGHTNESS_LUT_OETF	_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_BRIGHTNESS_LUT_OETF, unsigned int)
#define VPQ_EXTERN_IOC_SET_PANORAMA_TYPE					_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_PANORAMA_TYPE, unsigned int)
#define VPQ_EXTERN_IOC_SET_PQ_VDPQ_MEMORY_ENABLE			_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_VDPQ_MEM_ENABLE, unsigned int)
#define VPQ_EXTERN_IOC_SET_GAMMA_LEVEL				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_GAMMA_LEVEL, unsigned int)

#define VPQ_EXTERN_IOC_GET_GDBC_MODE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_GDBC_MODE, unsigned int)
#define VPQ_EXTERN_IOC_SET_GDBC_MODE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_GDBC_MODE, unsigned int)
#define VPQ_EXTERN_IOC_GET_GDBC_DCR_BACKLIGHT			_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_GDBC_DCR_BACKLIGHT, unsigned int)
#define VPQ_EXTERN_IOC_Sync_PQ_table_bin_ENABLE			_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_CMD_Sync_PQ_table_bin_ENABLE, unsigned int)

#define VPQ_EXTERN_IOC_GET_MEMCLD_ENABLE_TV030			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_MEMCLD_ENABLE_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_MEMCLD_ENABLE_TV030			_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_MEMCLD_ENABLE_TV030, unsigned int)
#define VPQ_EXTERN_IOC_GET_HDR_PicInfo_TV030				_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_HDR_PicInfo_TV030, unsigned char)
#define VPQ_EXTERN_IOC_GET_LC_BLK_HVNUM_TV030			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_LC_BLK_HVNUM_TV030, unsigned char)
#define VPQ_EXTERN_IOC_SET_SPLIT_DEMO_TV030				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_SPLIT_DEMO_TV030, unsigned int)
#define VPQ_EXTERN_IOC_GET_LD_Enable_TV030				_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_LD_Enable_TV030, unsigned char)
#define VPQ_EXTERN_IOC_SET_COLORMATRIXSRGB_TV030		_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_COLORMATRIXSRGB_TV030, unsigned int)
//#define VPQ_EXTERN_IOC_GET_LC_BLKAPL_TV030				_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_LC_BLKAPL_TV030, unsigned char)
//#define VPQ_EXTERN_IOC_SET_LCBLKSIZE_TV030				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_LCBLKSIZE_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_LOWDELAY_MODE_TV030			_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_LOWDELAY_MODE_TV030, unsigned int)
#define VPQ_EXTERN_IOC_GET_LC_HISTOGRAM_TV030			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_LC_HISTOGRAM_TV030, unsigned char)
#define VPQ_EXTERN_IOC_SET_LC_HISBIN_TV030				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_LCHISBIN_TV030, unsigned int)
#define VPQ_EXTERN_IOC_GET_HistoData_APL_TV030			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_HistoData_APL_TV030, unsigned int)
#define VPQ_EXTERN_IOC_GET_HistoData_Min_TV030			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_HistoData_MIN_TV030, signed int)
#define VPQ_EXTERN_IOC_GET_HistoData_Max_TV030			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_HistoData_MAX_TV030, signed int)
#define VPQ_EXTERN_IOC_SET_PARTTENFORAUTOGAMMA_TV030	_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_PARTTENFORAUTOGAMMA_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_PICTUREMODE_TV030			_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_PICTUREMODE_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_BRIGHTNESS_OSDLAYER_TV030	_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_BRIGHTNESS_OSDLAYER_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_CONTRAST_OSDLAYER_TV030		_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_CONTRAST_OSDLAYER_TV030, unsigned int)
#define VPQ_EXTERN_IOC_GET_PIXELINFO_TV030  				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_PIXELINFO_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_FILM_TABLE_TV030				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_FILM_TABLE_TV030	, unsigned int)
#define VPQ_EXTERN_IOC_GET_DYNAMIC_RANGE_TV030 			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_DYNAMIC_RANGE_TV030, unsigned char)
#define VPQ_EXTERN_IOC_SET_DYNAMIC_RANGE_CUR_SRC_TV030 	_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_DYNAMIC_RANGE_CUR_SRC_TV030, unsigned char)
#define VPQ_EXTERN_IOC_SET_HDMI_MODE_TYPE_TV030             		_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_HDMI_MODE_TYPE_TV030, unsigned char)
#define VPQ_EXTERN_IOC_SET_COLORSPACE					_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_COLORSPACE, unsigned int)
#define VPQ_EXTERN_IOC_SET_MAGICGAMMA_TV030				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_MAGICGAMMA_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_OSDPIC_FLAG_TV030				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_OSDPIC_FLAG_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_RGBWTOSRGBMATRIX				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_SET_RGBWTOSRGBMATRIX, unsigned char)

#define VPQ_EXTERN_IOC_SET_DDOMAIN3DLUT_GAMMA				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DDOMAIN3DLUT_GAMMA, unsigned char)
#define VPQ_EXTERN_IOC_INIT_DDOMAIN3DLUT_GAMMA_TABLE		_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_INIT_DDOMAIN3DLUT_GAMMA_TABLE, unsigned char)
	
#endif
