#ifndef VBE_EXPORT_H
#define VBE_EXPORT_H

#include <linux/types.h>
#include <rtd_types.h>

#define VBE_IOC_MAGIC  'e'
/* Please use a different 8-bit number in your code */
#define VBE_DEVICE_NAME		"vbedev"

//#define VBE_DISP_TCON_SELF_CHECK 1

#ifndef VBE_MAJOR
#define VBE_MAJOR 0   /* dynamic major by default */
#endif

#ifndef VBE_NR_DEVS
#define VBE_NR_DEVS 1    /* se0 through se3 */
#endif

#define VBE_IOC_DISP_INITIALIZE					_IOW(VBE_IOC_MAGIC, 0, DISP_PANEL_INFO_T)
#define VBE_IOC_DISP_UNINITIALIZE 	    		_IO(VBE_IOC_MAGIC,  1)
#define VBE_IOC_DISP_WRITE_DIAPLAYOUTPUT 		_IOW(VBE_IOC_MAGIC, 2, BOOLEAN)
#define VBE_IOC_DISP_WRITE_MUTE					_IOW(VBE_IOC_MAGIC, 3, BOOLEAN)
#define VBE_IOC_DISP_WRITE_SPREADSPECTRUM 		_IOW(VBE_IOC_MAGIC, 4, VBE_DISP_SpreadSpectrum_T)
#define VBE_IOC_DISP_WRITE_VIDEO_MIRROR			_IOW(VBE_IOC_MAGIC, 5, VBE_DISP_VideoMirror_T)
#define VBE_IOC_DISP_WRITE_DISPLAY_FORMAT 		_IOW(VBE_IOC_MAGIC, 6, VBE_DISP_FORMAT_T)
#define VBE_IOC_DISP_WRITE_FRAMERATE 			_IOW(VBE_IOC_MAGIC, 7, VBE_DISP_Framerate_T)
#define VBE_IOC_DISP_READ_OUTPUTFRAMERATE 		_IOR(VBE_IOC_MAGIC, 8, unsigned char)
#define VBE_IOC_DISP_WRITE_BGCOLOR 				_IOW(VBE_IOC_MAGIC, 9, VBE_DISP_BGColor_T)

#define VBE_IOC_DISP_OD_WRITE_TABLE 			_IOW(VBE_IOC_MAGIC, 10, int)
#define VBE_IOC_DISP_OD_ENABLE					_IOW(VBE_IOC_MAGIC, 11, BOOLEAN)

#define VBE_IOC_DISP_PCID_WRITE_TABLE 			_IOW(VBE_IOC_MAGIC, 12, int)
#define VBE_IOC_DISP_PCID_ENABLE				_IOW(VBE_IOC_MAGIC, 13, BOOLEAN)

#define VBE_IOC_DISP_SR_INITIALIZE 				_IO(VBE_IOC_MAGIC,  14)
#define VBE_IOC_DISP_SR_UNINITIALIZE 			_IO(VBE_IOC_MAGIC,  15)
#define VBE_IOC_DISP_SR_WRITE_CONTROL 			_IOW(VBE_IOC_MAGIC, 16, int)

#define VBE_IOC_DISP_TCON_INITILIZE  				_IOW(VBE_IOC_MAGIC, 17, int)
#define VBE_IOC_DISP_TCON_UNINITILIZE  			_IOW(VBE_IOC_MAGIC, 18, int)
#define VBE_IOC_DISP_TCON_ENABLE_TCON  			_IOW(VBE_IOC_MAGIC, 19, int)
#define VBE_IOC_DISP_TCON_EABLE_COLORTEMP  		_IOW(VBE_IOC_MAGIC, 20, int)
#define VBE_IOC_DISP_TCON_EABLE_DGA  				_IOW(VBE_IOC_MAGIC, 21, int)
#define VBE_IOC_DISP_TCON_ENABLE_DITHER  			_IOW(VBE_IOC_MAGIC, 22, int)
#define VBE_IOC_DISP_TCON_SET_DITHER_MODE  		_IOW(VBE_IOC_MAGIC, 23, int)
#define VBE_IOC_DISP_TCON_SET_GAMMA_TABLE  		_IOW(VBE_IOC_MAGIC, 24, int)
#define VBE_IOC_DISP_TCON_H_REVERSE  				_IOW(VBE_IOC_MAGIC, 25, int)
#define VBE_IOC_DISP_TCON_SET_CLOCK  				_IOW(VBE_IOC_MAGIC, 26, int)
#define VBE_IOC_DISP_TCON_WRITE_REGISTER  		_IOW(VBE_IOC_MAGIC, 27, int)
#define VBE_IOC_DISP_TCON_READ_REGISTER  			_IOW(VBE_IOC_MAGIC, 28, int)
#define VBE_IOC_DISP_TCON_SET_LVDS_FORMAT  		_IOW(VBE_IOC_MAGIC, 29, int)
#define VBE_IOC_DISP_TCON_DEBUG  					_IOW(VBE_IOC_MAGIC, 30, int)

#define VBE_IOC_AVE_INITILIZE  						_IOW(VBE_IOC_MAGIC, 31, int)
#define VBE_IOC_AVE_UNINITILIZE  					_IOW(VBE_IOC_MAGIC, 32, int)
#define VBE_IOC_AVE_OPEN  							_IOW(VBE_IOC_MAGIC, 33, int)
#define VBE_IOC_AVE_CLOSE  							_IOW(VBE_IOC_MAGIC, 34, int)
#define VBE_IOC_AVE_CONNECT  						_IOW(VBE_IOC_MAGIC, 35, int)
#define VBE_IOC_AVE_DISCONNECT  					_IOW(VBE_IOC_MAGIC, 36, int)
#define VBE_IOC_AVE_IS_ATV_WATCHING  				_IOW(VBE_IOC_MAGIC, 37, int)
#define VBE_IOC_AVE_SET_ATV_WATCHING  			_IOW(VBE_IOC_MAGIC, 38, int)
#define VBE_IOC_AVE_VBI_SET_INSERT  				_IOW(VBE_IOC_MAGIC, 39, int)
#define VBE_IOC_AVE_VBI_INSERT_DATA   				_IOW(VBE_IOC_MAGIC, 40, int)
#define VBE_IOC_AVE_SET_VCR_WIN_BLANK  			_IOW(VBE_IOC_MAGIC, 41, int)

#define VBE_IOC_DISP_RESUME						_IOW(VBE_IOC_MAGIC, 42, DISP_PANEL_INFO_T)
#define VBE_IOC_DISP_CONNECT					_IOW(VBE_IOC_MAGIC, 43, DISP_WINDOW_T)
#define VBE_IOC_DISP_DISCONNECT					_IOW(VBE_IOC_MAGIC, 44, DISP_WINDOW_T)

//for lvds to hdmi panel
#define VBI_IOC_DISP_LVDS_TO_HDMI				_IOW(VBE_IOC_MAGIC, 45, VBE_DISP_FORMAT_T)

#define VBE_IOC_TRIDFMT_INITIALIZE					_IOW(VBE_IOC_MAGIC, 46, int)
#define VBE_IOC_TRIDFMT_UNINITIALIZE				_IOW(VBE_IOC_MAGIC, 47, int)
#define VBE_IOC_TRIDFMT_OPEN						_IOW(VBE_IOC_MAGIC, 48, int)
#define VBE_IOC_TRIDFMT_CLOSE						_IOW(VBE_IOC_MAGIC, 49, int)
#define VBE_IOC_TRIDFMT_SETSCREENONOFF			_IOW(VBE_IOC_MAGIC, 50, int)
#define VBE_IOC_TRIDFMT_SETFMTMODE				_IOW(VBE_IOC_MAGIC, 51, int)
#define VBE_IOC_TRIDFMT_SETFMTMODE_TEMP			_IOW(VBE_IOC_MAGIC, 52, int)
#define VBE_IOC_TRIDFMT_SET3DMODEONOFF			_IOW(VBE_IOC_MAGIC, 53, int)
#define VBE_IOC_TRIDFMT_TOGGLEINPUTLRFRAME		_IOW(VBE_IOC_MAGIC, 54, int)
#define VBE_IOC_TRIDFMT_SELECTINPUTFORMAT		_IOW(VBE_IOC_MAGIC, 55, int)
#define VBE_IOC_TRIDFMT_SETINPUTFRAMERATE		_IOW(VBE_IOC_MAGIC, 56, int)
#define VBE_IOC_TRIDFMT_TOGGLEOUTPUTLRFRAME		_IOW(VBE_IOC_MAGIC, 57, int)
#define VBE_IOC_TRIDFMT_SELECTOUTPUTFORMAT		_IOW(VBE_IOC_MAGIC, 58, int)
#define VBE_IOC_TRIDFMT_SETOUTPUTFRAMERATE		_IOW(VBE_IOC_MAGIC, 59, int)
#define VBE_IOC_TRIDFMT_GET3DCFGINFO				_IOW(VBE_IOC_MAGIC, 60, int)
#define VBE_IOC_TRIDFMT_SET3DCFGINFO				_IOW(VBE_IOC_MAGIC, 61, int)
#define VBE_IOC_TRIDFMT_SETCONVVALUE				_IOW(VBE_IOC_MAGIC, 62, int)
#define VBE_IOC_TRIDFMT_CTRLDEPTH					_IOW(VBE_IOC_MAGIC, 63, int)
#define VBE_IOC_TRIDFMT_AUTOCONVERGENCEENABLE	_IOW(VBE_IOC_MAGIC, 64, int)
#define VBE_IOC_TRIDFMT_SET3DVIDEOOUTPUTMODE	_IOW(VBE_IOC_MAGIC, 65, int)
#define VBE_IOC_TRIDFMT_SET3DDEPTHCONTROLLER	_IOW(VBE_IOC_MAGIC, 66, int)
#define VBE_IOC_TRIDFMT_DEBUG						_IOW(VBE_IOC_MAGIC, 67, int)

#define V3D_IOC_INITIALIZE						_IOW(VBE_IOC_MAGIC, 68, int)
#define V3D_IOC_SET3DFMT						_IOW(VBE_IOC_MAGIC, 69, int)
#define V3D_IOC_SETLRSEQ						_IOW(VBE_IOC_MAGIC, 70, int)
#define V3D_IOC_CTRLCONVERGENCE					_IOW(VBE_IOC_MAGIC, 71, int)
#define V3D_IOC_CTRLDEPTH					_IOW(VBE_IOC_MAGIC, 72, int)
#define V3D_IOC_SETAUTOCONVENABLE				_IOW(VBE_IOC_MAGIC, 73, int)
#define V3D_IOC_GETAUTODETECTINGRESULT				_IOW(VBE_IOC_MAGIC, 74, int)
#define V3D_IOC_SETAUTODETECTINGTYPE				_IOW(VBE_IOC_MAGIC, 75, int)

#define VBE_IOC_SETORBIT						_IOW(VBE_IOC_MAGIC, 76, int)
#define VBE_IOC_SETBOEMODE						_IOW(VBE_IOC_MAGIC, 77, int)
#define VBE_IOC_GETBOEVERSION					_IOW(VBE_IOC_MAGIC, 78, int)
#define VBE_IOC_SETMLEMODE					_IOW(VBE_IOC_MAGIC, 79, int)
#define VBE_IOC_SETINNERPATTERN					_IOW(VBE_IOC_MAGIC, 80, int)
#define VBE_IOC_SETDGA4CH						_IOW(VBE_IOC_MAGIC, 81, int)
#define VBE_IOC_SETBOERGBWBYPASS				_IOW(VBE_IOC_MAGIC, 82, int)

#define VBE_IOC_SETFRAMEGAINLIMIT				_IOW(VBE_IOC_MAGIC, 83, int)
#define VBE_IOC_GETFRAMEGAINLIMIT				_IOR(VBE_IOC_MAGIC, 84, int)
#define VBE_IOC_SETPIXELGAINLIMIT				_IOW(VBE_IOC_MAGIC, 85, int)
#define VBE_IOC_GETPIXELGAINLIMIT				_IOR(VBE_IOC_MAGIC, 86, int)
#define VBE_IOC_GETPANELDISPSIZE                _IOW(VBE_IOC_MAGIC, 87, int)
#define VBE_IOC_PANEL_MODE_SET                _IOW(VBE_IOC_MAGIC, 88, KADP_PANEL_MODE_SET_T)
#define VBE_IOC_TSCIC_LOAD                      _IOW(VBE_IOC_MAGIC, 89, int)
#define VBE_IOC_SETOLEDLSR                      _IOW(VBE_IOC_MAGIC, 90, int)
#define VBE_IOC_SETEPIDATASCRAMBLE              _IOW(VBE_IOC_MAGIC, 91, int)
#define VBE_IOC_SETADVANCED10BIT                _IOW(VBE_IOC_MAGIC, 92, int)
#define VBE_IOC_SETOLEDLSRTUNNING               _IOW(VBE_IOC_MAGIC, 93, int)
#define VBE_IOC_SETOLEDCPCTUNNING               _IOW(VBE_IOC_MAGIC, 94, int)
#define VBE_IOC_DISP_DATAFRAMESYNC				_IOW(VBE_IOC_MAGIC, 95, BOOLEAN)
#define VBE_IOC_DISP_SETPAUSE					_IO(VBE_IOC_MAGIC, 96)
#define VBE_IOC_DISP_ADAPTIVESTREAM_FRAMERATE			_IOW(VBE_IOC_MAGIC, 97, int)
#define VBE_IOC_SET_FORCEBG_COLOR			_IO(VBE_IOC_MAGIC, 98)
#define VBE_IOC_SET_PANEL_SFG			_IO(VBE_IOC_MAGIC, 99)
#define VBE_IOC_SETOLEDGSR                  _IOW(VBE_IOC_MAGIC, 100, int)
#define VBE_IOC_MPLUSSET                  _IOW(VBE_IOC_MAGIC, 101, int)
#define VBE_IOC_MPLUSGET                  _IOW(VBE_IOC_MAGIC, 102, int)
#define VBE_IOC_GET_OSD_ALPHA_APL               _IOW(VBE_IOC_MAGIC, 103, int)
#define VBE_IOC_SET_OSD_RGB_LEVEL               _IOW(VBE_IOC_MAGIC, 104, int)
#define VBE_IOC_SET_PANEL_FORCEBG_COLOR	 _IO(VBE_IOC_MAGIC, 105)
#define VBE_IOC_SET_PANEL_TI_MODE 	 	_IO(VBE_IOC_MAGIC, 106)
#define VBE_IOC_SET_PANEL_BIT_MODE	    _IO(VBE_IOC_MAGIC, 107)
#define VBE_IOC_SET_PANEL_SWAP_MODE	    _IO(VBE_IOC_MAGIC, 108)
#define VBE_IOC_DISP_READ_SPREADSPECTRUM	_IOR(VBE_IOC_MAGIC, 109, VBE_DISP_SpreadSpectrum_T*)
#define VBE_IOC_MAXNR 110


#ifndef BOOLEAN
#ifndef _EMUL_WIN
typedef	unsigned int			__BOOLEAN;
#define BOOLEAN __BOOLEAN
#else
typedef	unsigned char		__BOOLEAN;
#define BOOLEAN __BOOLEAN
#endif
#endif

/** * DISPLAY Window ID.*/
typedef enum{
	DISP_WINDOW_0,
	DISP_WINDOW_1,
} DISP_WINDOW_T;

/**
  * Panel interface
  */
 typedef enum {
	DISP_PANEL_EPI = 0,
	DISP_PANEL_LVDS,
	DISP_PANEL_Vx1,
	DISP_PANEL_CEDS,
	DISP_PANEL_INTERFACE_MAX
 } DISP_PANEL_INTERFACE_T;

 /*** EPI Panel type*/
 typedef enum {
 	DISP_EPI_PANEL_V12 = 0,
 	DISP_EPI_PANEL_V13,
 	DISP_EPI_PANEL_V14,
 	DISP_EPI_PANEL_MAX
 } DISP_EPI_PANEL_TYPE_T;

 /** * Panel size Enum.*/
 typedef enum {
     DISP_PANEL_INCH_22 = 0,
     DISP_PANEL_INCH_23,
     DISP_PANEL_INCH_24,
     DISP_PANEL_INCH_26,
     DISP_PANEL_INCH_27,
     DISP_PANEL_INCH_28,
     DISP_PANEL_INCH_32,
     DISP_PANEL_INCH_39,
     DISP_PANEL_INCH_40,
     DISP_PANEL_INCH_42,
     DISP_PANEL_INCH_43,
     DISP_PANEL_INCH_47,
     DISP_PANEL_INCH_49,
     DISP_PANEL_INCH_50,
     DISP_PANEL_INCH_55,
     DISP_PANEL_INCH_58,
     DISP_PANEL_INCH_60,
     DISP_PANEL_INCH_65,
     DISP_PANEL_INCH_70,
     DISP_PANEL_INCH_75,
     DISP_PANEL_INCH_77,
     DISP_PANEL_INCH_79,
     DISP_PANEL_INCH_84,
     DISP_PANEL_INCH_86,
     DISP_PANEL_INCH_98,
     DISP_PANEL_INCH_105,

	 // 17Y Inch addition
	 DISP_PANEL_INCH_48,
     
     DISP_PANEL_INCH_BASE
 } DISP_PANEL_INCH_T;

 /** * Backlight Type Enum.*/
 typedef enum {
	DISP_BL_DIRECT_M = 0,
 	DISP_BL_DIRECT_L,
 	DISP_BL_EDGE_LED,
 	DISP_BL_ALEF_LED,
 	DISP_BL_OLED,
 	DISP_BL_END
} DISP_BACKLIGHT_TYPE_T;

 typedef enum {
	DISP_LCD_PANEL_MAKER_LGD = 0,
	DISP_LCD_PANEL_MAKER_CMI,
	DISP_LCD_PANEL_MAKER_AUO,
	DISP_LCD_PANEL_MAKER_SHARP,
	DISP_LCD_PANEL_MAKER_IPS,
	DISP_LCD_PANEL_MAKER_BOE,
	DISP_LCD_PANEL_MAKER_CSOT,
	DISP_LCD_PANEL_MAKER_INNOLUX,
	DISP_LCD_PANEL_MAKER_LGD_M,
	DISP_LCD_PANEL_MAKER_ODM_B,
	DISP_LCD_PANEL_MAKER_BOE_TPV,
	DISP_LCD_PANEL_MAKER_MAX,
 } DISP_PANEL_MAKER_T;

 /*** Panel Led_bar Type Enum.*/
 typedef enum {
	 DISP_LED_BAR_6 = 0,
	 DISP_LED_BAR_12,
	 DISP_LED_BAR_16,
	 DISP_LED_BAR_20,
	 DISP_LED_BAR_240,
	 DISP_LED_BAR_320,
	 DISP_LED_BAR_24,
	 DISP_LED_BAR_V8,
	 DISP_LED_BAR_MAX,
 } DISP_LED_BAR_TYPE_T;

  typedef enum {
	  DISP_PANEL_RESOLUTION_1024X768 = 0,
	  DISP_PANEL_RESOLUTION_1280X720,
	  DISP_PANEL_RESOLUTION_1366X768,
	  DISP_PANEL_RESOLUTION_1920X1080,
	  DISP_PANEL_RESOLUTION_2560X1080,
	  DISP_PANEL_RESOLUTION_3840X2160,
	  DISP_PANEL_RESOLUTION_5120X2160,
	  DISP_PANEL_RESOLUTION_7680X4320,
	  DISP_PANEL_RESOLUTION_MAX
 } DISP_PANEL_RESOLUTION_T;

  typedef enum {
	 DISP_PANEL_NONE  = 0,
	 DISP_PANEL_V12,
	 DISP_PANEL_V13,
	 DISP_PANEL_V14,
	 DISP_PANEL_V14_32inch,
	 DISP_PANEL_V15,
	 DISP_PANEL_V16,
	 DISP_PANEL_V17,
	 DISP_PANEL_MAX,
 } DISP_PANEL_VERSION_T;

  typedef enum {
	 DISP_FRC_CHIP_NONE   = 0,
	 DISP_FRC_CHIP_INTERNAL,
	 DISP_FRC_CHIP_UD_BE_URSA9,
	 DISP_FRC_CHIP_UD_BE_URSA9P,
	 DISP_FRC_CHIP_UD_BE_URSA11,
	 DISP_FRC_CHIP_UD_BE_URSA11P,
	 DISP_FRC_CHIP_UD_BE_F16,
	 DISP_FRC_CHIP_UD_BE_MAX,
 } DISP_FRC_CHIP_TYPE_T ;

  typedef enum {
	  DISP_CELL_TYPE_RGB=0,
	  DISP_CELL_TYPE_RGBW,
	  DISP_CELL_TYPE_MAX
 }DISP_CELL_TYPE_T;



 /*** Display Output Resolution*/
typedef struct {
	UINT32 video_width;
	UINT32 video_height;
	UINT32 osd_width;
	UINT32 osd_height;
} DISP_OUTPUT_RESOLUTION_T;

 /**
  * panel type.
  *
  * @see
 */
 typedef enum
 {
	 DISP_PANEL_TYPE_LCD,
	 DISP_PANEL_TYPE_LCD_TCON,	 // shjang_090904
	 DISP_PANEL_TYPE_LCD_FRC,

	 DISP_PANEL_TYPE_PDP,
	 DISP_PANEL_TYPE_LED,
	 DISP_PANEL_TYPE_OLED,

	 DISP_PANEL_TYPE_NUM,
 }DISP_PANEL_TYPE_T;

 /**
  * LVDS bit depth.
  *
  * @see
 */
 typedef enum
 {
	 DISP_COLOR_DEPTH_8BIT,
	 DISP_COLOR_DEPTH_10BIT,
	 DISP_COLOR_DEPTH_NUM,
 }DISP_COLOR_DEPTH_T;

 /**
  * LVDS chanel info.
  *
  * @see
 */
 typedef enum
 {
	 DISP_LVDS_PIXEL_SINGLE,  //HD 60hz
	 DISP_LVDS_PIXEL_DUAL,	 //FHD 60hz
	 DISP_LVDS_PIXEL_QUAD,	 //FHD 120hz
	 DISP_LVDS_PIXEL_NUM,
 }DISP_LVDS_PIXEL_T;

 /**
  * LVDS type.
  *
  * @see
 */
 typedef enum
 {
	 DISP_LVDS_SELECT_VESA,
	 DISP_LVDS_SELECT_JEIDA,
	 DISP_LVDS_SELECT_NUM,
 }DISP_LVDS_SELECT_T;

 typedef enum
 {
	 DISP_OUTPUT_LANE_BANDWIDTH_DEFAULT = 0,
	 DISP_OUTPUT_LANE_BANDWIDTH_1_5G,
	 DISP_OUTPUT_LANE_BANDWIDTH_2_1G,
	 DISP_OUTPUT_LANE_BANDWIDTH_3_0G,
	 DISP_OUTPUT_LANE_BANDWIDTH_MAX,
 }DISP_OUTPUT_LANE_BANDWIDTH_T;

 typedef enum
 {
	 DISP_PANEL_FRAMERATE_60Hz = 0,
	 DISP_PANEL_FRAMERATE_120Hz
 }DISP_PANEL_FRAMERATE_T;

 typedef struct {
	UINT32 DISP_WIDTH;
	UINT32 DISP_HEIGHT;
 } DISP_PANEL_SIZE_T;

 /**
 * Display User Option
 */
 typedef union {
	UINT32 all;
	struct
	{
	   UINT32
	   SocOptionBIT0 :1,
	   SocOptionBIT1 :1,
	   SocOptionBIT2 :1,
	   SocOptionBIT3 :1,
	   SocOptionBIT4 :1,
	   SocOptionBIT5 :1,
	   SocOptionBIT6 :1,
	   SocOptionBIT7 :1,
	   SocOptionBIT8 :1,
	   SocOptionBIT9 :1,
	   SocOptionBIT10	 :1,
	   SocOptionBIT11	 :1,
	   SocOptionBIT12	 :1,
	   SocOptionBIT13	 :1,
	   SocOptionBIT14	 :1,
	   SocOptionBIT15	 :1,
	   SocOptionBIT16	 :1,
	   SocOptionBIT17	 :1,
	   SocOptionBIT18	 :1,
	   SocOptionBIT19	 :1,
	   SocOptionBIT20	 :1,
	   SocOptionBIT21	 :1,
	   SocOptionBIT22	 :1,
	   SocOptionBIT23	 :1,
	   SocOptionBIT24	 :1,
	   SocOptionBIT25	 :1,
	   SocOptionBIT26	 :1,
	   SocOptionBIT27	 :1,
	   SocOptionBIT28	 :1,
	   SocOptionBIT29	 :1,
	   SocOptionBIT30	 :1,
	   SocOptionBIT31	 :1;
	} flags;
 } DISP_USER_OPTION_T;


 /*** Panel information*/
typedef struct
{
	DISP_PANEL_INCH_T  panel_inch;
	DISP_BACKLIGHT_TYPE_T panel_bl_type;
	DISP_PANEL_MAKER_T  panel_maker;
	DISP_LED_BAR_TYPE_T led_bar_type;
    DISP_PANEL_INTERFACE_T panelInterface;
    DISP_PANEL_RESOLUTION_T panelResolution;
	DISP_PANEL_VERSION_T panel_version;
	DISP_FRC_CHIP_TYPE_T frc_type;
    DISP_CELL_TYPE_T cell_type;
	DISP_OUTPUT_RESOLUTION_T disp_out_resolution;
	DISP_COLOR_DEPTH_T lvds_bit_mode;
	DISP_LVDS_SELECT_T lvds_type;
    DISP_OUTPUT_LANE_BANDWIDTH_T disp_out_lane_bw;
	DISP_PANEL_FRAMERATE_T panelFrameRate;
    DISP_USER_OPTION_T user_specific_option;
}DISP_PANEL_INFO_T;

/**
 * panel attribute.
 *
 * @see
*/
typedef struct
{
	DISP_PANEL_TYPE_T	ePanelType; /**PANEL_TYPE_T */
	DISP_COLOR_DEPTH_T	eColorDepth;	/**COLOR_DEPTH_T */
	DISP_LVDS_SELECT_T	eLVDSSelect;	/**LVDS_SELECT_T */
	DISP_LVDS_PIXEL_T	eLVDSPixel; /**LVDS_PIXEL_T */
	DISP_PANEL_INTERFACE_T	ePanelInterface;/**PANEL_INTERFACE_T*/
	UINT8 eFRCType;/**FRC_CHIP_TYPE_T*/

	signed int panelResolution; 	/** */
	UINT8 ePanelInch;		/** */
	//------------ signal timing -----------------
	//UINT16 TypDclkHz; 		/** panel D clock*/
	UINT16 horizTypPeriod;		/** panel Horizon Period */
	UINT16 vertTypPeriod60Hz;	/** panel Vertical Period for NTSC*/
	UINT8 vertSyncWidth60Hz;	/** panel Vertical Sync Width for NTSC*/
	UINT8 vertBackPorch60Hz;	/** panel Vertical Back Porch for NTSC*/
	UINT8 horizSyncWidth60Hz;	/** panel Horizontal Sync Width for NTSC*/
	UINT8 horizBackPorch60Hz;	/** panel Horizontal Back Porch for NTSC*/
	UINT16 vertTypPeriod50Hz;	/** panel Vertical Period for PAL*/
	UINT8 vertSyncWidth50Hz;	/** panel Vertical Sync Width for PAL*/
	UINT8 vertBackPorch50Hz;	/** panel Vertical Back Porch for PAL*/
	UINT8 horizSyncWidth50Hz;	/** panel Horizontal Sync Width for PAL*/
	UINT8 horizBackPorch50Hz;	/** panel Horizontal Back Porch for PAL*/
	UINT16 vertTypPeriod48Hz;	/** panel Vertical Period for 48Hz*/
	UINT8 vertSyncWidth48Hz;	/** panel Vertical Sync Width for 48Hz*/
	UINT8 vertBackPorch48Hz;	/** panel Vertical Back Porch for 48Hz*/
	UINT8 horizSyncWidth48Hz;	/** panel Horizontal Sync Width for 48Hz*/
	UINT8 horizBackPorch48Hz;	/** panel Horizontal Back Porch for 48Hz*/
}DISP_PANEL_ATTRIBUTE_T;

typedef struct
{
UINT8 command;					///< cotrol 0 : OFF, 1 :low , 2: midium, 3:high
UINT8 SR_a_global_scale;			///<PP_global scale
UINT8 SR_b_global_scale;			///<PP_local scale
}VBE_SR_CON_T;

typedef struct {
	BOOLEAN bEnable;
	UINT16 Percenct;
	UINT16 Period;
}VBE_DISP_SpreadSpectrum_T;

typedef struct{
	BOOLEAN bIsH;
	BOOLEAN bIsV;
}VBE_DISP_VideoMirror_T;

typedef struct{
	DISP_PANEL_ATTRIBUTE_T panel_attribute;
	UINT8 framerate;
}VBE_DISP_FORMAT_T;

typedef struct{
	BOOLEAN isForceFreeRun;
	UINT8 framerate;
}VBE_DISP_Framerate_T;

typedef struct{
	UINT8 red;
	UINT8 green;
	UINT8 blue;
}VBE_DISP_BGColor_T;

typedef enum
{
	VBE_DISP_NOTHING =0,		//Source don't do anything yet
	VBE_DISP_INIT_DONE,			//Source after initial
	VBE_DISP_CONNECT_DONE,		//Source after connect
	VBE_DISP_DISCONNECT, 		//Source disconnect
} VBE_DISP_STATUS;

typedef struct {
   UINT8 b0; // Romcode_B0 or Version_B0
   UINT8 b1; // Romcode_B1 or Version_B1
   UINT8 b2; // Romcode_B2 or Version_B2
} DISP_BOE_VERSION_T;

typedef struct{
	UINT8 *pFwData;
	UINT32 size;
}VBE_DISP_BOE_MODE_T;

typedef struct{
	DISP_BOE_VERSION_T stRomVer;
	DISP_BOE_VERSION_T stFwVer;
}VBE_DISP_BOE_VERSION_T;

typedef enum
{
	BOE_ROM_VERSION = 0,
	BOE_FW_VERSION
}VBE_DISP_BOE_VERSION_TYPE_T;

typedef enum
{
    VBE_DISP_HIGH_LUM1_MSE_ON = 0,
    VBE_DISP_HIGH_LUM2,
    VBE_DISP_LOW_POWER1,
    VBE_DISP_MLE_MODE_OFF,
    VBE_DISP_HIGH_LUM1_MSE_OFF,
    VBE_DISP_LOW_POWER2,
    VBE_DISP_LOW_POWER2_SC_OFF,
    VBE_DISP_MLE_MODE_MAX,
} VBE_DISP_MLE_MODE_T;

typedef enum
{
	VBE_DISP_INNER_PTG_BLOCK_VGIP = 0,
	VBE_DISP_INNER_PTG_BLOCK_UZU,
	VBE_DISP_INNER_PTG_BLOCK_MTG,
	VBE_DISP_INNER_PTG_BLOCK_MEMC_INPUTMUX,
	VBE_DISP_INNER_PTG_BLOCK_MEMC_OUTPUTMUX,
	VBE_DISP_INNER_PTG_BLOCK_SFG,
	VBE_DISP_INNER_PTG_BLOCK_MAX,
} VBE_DISP_INNER_PTG_BLOCK_T;

typedef enum
{
	VBE_DISP_INNER_PTG_TYPE_COLOR_R = 0,
	VBE_DISP_INNER_PTG_TYPE_COLOR_G,
	VBE_DISP_INNER_PTG_TYPE_COLOR_B,
	VBE_DISP_INNER_PTG_TYPE_COLOR_WHITE,
	VBE_DISP_INNER_PTG_TYPE_COLOR_BLACK,
	VBE_DISP_INNER_PTG_TYPE_RANDOM_GEN,
	VBE_DISP_INNER_PTG_TYPE_COLOR_BAR,
	VBE_DISP_INNER_PTG_TYPE_COLOR_MAX,
} VBE_DISP_INNER_PTG_TYPE_T;

typedef struct {
   UINT8 bOnOff;
   VBE_DISP_INNER_PTG_BLOCK_T block;
   VBE_DISP_INNER_PTG_TYPE_T type;
} VBE_DISP_INNER_PATTERN_CTRL_T;


/******************************************************************************
VBE_DISP_TCON (Global Type Definitions)
******************************************************************************/
typedef enum
{
	DISP_TCON_DITHER_TRUNC		= 0,
	DISP_TCON_DITHER_ROUND,
	DISP_TCON_DITHER_RANDOM
} DISP_TCON_DITHER_T;

typedef enum
{
	HAL_VBE_DISP_TCON_LVDS_JEIDA = 0,
	HAL_VBE_DISP_TCON_LVDS_VESA,
	HAL_VBE_DISP_TCON_LVDS_MAXNUM
} HAL_VBE_DISP_TCON_LVDS_TYPE_T;

typedef struct{
	UINT32 reg_address;
	UINT32 reg_data;
}HAL_VBE_DISP_TCON_WRITE_REGISTERS;

typedef struct{
	UINT32 reg_address;
	UINT32 *reg_data;
}HAL_VBE_DISP_TCON_READ_REGISTERS;


/*-----------------------------------------------------------------------------
	Local Type Definitions
	VBE_AVE (Global Type Definitions)
------------------------------------------------------------------------------*/
typedef enum
{
	VBE_AVE_VBI_PAL_TELETEXT = 0, /**< VBI teletxet */
	VBE_AVE_VBI_PAL_WSS,			/**< VBI wss */
	VBE_AVE_VBI_PAL_VPS,			/**< VBI vps */
	VBE_AVE_VBI_NTSC_CC608,		/**< VBI cc608 */
	VBE_AVE_VBI_NTSC_WSS, 		/**< VBI NTSC wss */ // 2013.04.25. yongsu.yoo
//	VIDEO_DDI_VBI_DVB_TELETEXT,
//	VIDEO_DDI_VBI_DVB_SUBTITLE,
//	VIDEO_DDI_VBI_ATSC_CC608,
//	VIDEO_DDI_VBI_ATSC_CC708,
	VBE_AVE_VBI_ALL,
	VBE_AVE_VBI_MAX_SERVICE,		/**< VBI max */
} VBE_AVE_VBI_TYPE_T;

typedef enum
{
	WSS_FULLFORMAT_4_3_MST      		= 0x08,
    	WSS_LETTRBOX_14_9_CENT_MST  		= 0x01,
    	WSS_LETTRBOX_14_9_TOP_MST   		= 0x02,
    	WSS_LETTRBOX_16_9_CENT_MST  		= 0x0b,
    	WSS_LETTRBOX_16_9_TOP_MST   		= 0x04,
    	WSS_LETTRBOX_16_9_ZOOM_MST  	= 0x0d,
    	WSS_FULLFORMAT_14_9_MST      		= 0x0e,
    	WSS_FULLFORMAT_16_9_MST      		= 0x07,
    	WSS_INVALD_MST
}WSS_ART_MODE_T_MST;

typedef enum
{
    	VSC_SCALER0,
	VSC_SCALER1,
	TUNER_OUTPUT,
    	VDEC0,
    	VDEC1,
}VBE_AVE_INPUT_INDEX;

typedef enum
{
	HAL_ATV_MODE_WATCHING,	///< Watching ATV or Recording (CVD Clamping ON)
	HAL_ATV_MODE_NOT_WATCHING,	///< CVD powerdown or ATV is not selected. (Buffer Clamping ON)
	HAL_ATV_MODE_NOT_DEFINED,	///< ATV Mode not defined
	HAL_ATV_MODE_MAX,
}	HAL_VBE_ATV_Mode_t;

typedef struct{
	VBE_AVE_VBI_TYPE_T type;
	UINT8 OnOff;
}VBE_AVE_VBI_SET_INSERT_T;

typedef struct{
	VBE_AVE_VBI_TYPE_T type;
	UINT32 nrLine;
	UINT32 *pLines;
	UINT32 size;
	UINT8 *pData;
}VBE_AVE_VBI_INSERT_DATA_T;

typedef enum
{
	DISP_TIMING_DEFAULT=0,
	DISP_FREE_RUN,
	DISP_FRAMESYNC,
}DISP_TIMING_INFO;

typedef struct{
	VBE_AVE_INPUT_INDEX AVEInput;
	BOOLEAN bIsATVWatching;
}VBE_AVE_SET_ATVWATCHING_T;

typedef enum
{
	VBE_AVE_NOTHING =0,		//Source don't do anything yet
	VBE_AVE_INIT_DONE,			//Source after initial
	VBE_AVE_OPEN_DONE,		//Source after open
	VBE_AVE_CONNECT_DONE,		//Source after connect

	VBE_AVE_UNINIT,				//Source uninitial
	VBE_AVE_CLOSE, 				// Source close
	VBE_AVE_DISCONNECT, 		//Source disconnect
} VBE_AVE_STATUS;

#ifdef CONFIG_PM
typedef enum
{
	VBE_AVE_SUSPEND_RESUME_DISABLE,
    	VBE_AVE_SUSPEND_RESUME_VSC_SCALER,
	VBE_AVE_SUSPEND_RESUME_TUNER_OUTPUT,
	VBE_AVE_SUSPEND_RESUME_VDEC0,	//LM15U
	VBE_AVE_SUSPEND_RESUME_VDEC1,	//LM15U
}VBE_AVE_INPUT_INDEX_SUSPEND_RESUME;
#endif

/*-----------------------------------------------------------------------------
	Global Type Definitions
	VBE_TRIDTV (Global Type Definitions)
------------------------------------------------------------------------------*/

/**
 * Define 3D Input LR Type.
 */
#ifndef VIDEO_WID_T
	typedef enum
	{
		VIDEO_WID_MIN	= 0,				/**< WID min */
		VIDEO_WID_0 	= VIDEO_WID_MIN,	/**< WID main window */
		VIDEO_WID_1,						/**< WID sub window */
		VIDEO_WID_MAX	= VIDEO_WID_1,		/**< WID max */
		VIDEO_WID_MAXN, 					/**< WID max number */
	} __VIDEO_WID_T;
#define VIDEO_WID_T __VIDEO_WID_T
#endif
typedef enum
{
	VBE_INPUT_LR_SEQ = 0,
	VBE_INPUT_RL_SEQ,
	VBE_INPUT_LR_MAX,
} HAL_TRIDTV_INPUT_LR_SEQ_T;


typedef enum
{
	/*	Drive에서 아래 value 사용 안함.	*/
	VBE_INPUT_TYPE_3DOFF = 0,			//VIDEO_3D_FORMAT_2D,

	//interim format - half
	VBE_INPUT_TYPE_TOPNBOTTOM,		//VIDEO_3D_FORMAT_TOP_BOTTOM,
	VBE_INPUT_TYPE_SIDEBYSIDE,		//VIDEO_3D_FORMAT_SIDEBYSIDE_HALF,
	VBE_INPUT_TYPE_CHECKERBOARD,	//VIDEO_3D_FORMAT_CHECKER_BOARD,
	VBE_INPUT_TYPE_FRAMESEQ,		//VIDEO_3D_FORMAT_FRAME_SEQ
	VBE_INPUT_TYPE_COLUMN_INTERLEAVE,	/**< for H.264*/
	VBE_INPUT_TYPE_LINE_INTERLEAVE_HALF,	/**< for H.264*/

	//Full format
	VBE_INPUT_TYPE_FRAMEPAC,			//VIDEO_3D_FORMAT_FRAME_PACKING
	VBE_INPUT_TYPE_FIELD_ALTERNATIVE,	//VIDEO_3D_FORMAT_FIELD_ALTERNATIVE
	VBE_INPUT_TYPE_LINE_ALTERNATIVE,	//VIDEO_3D_FORMAT_LINE_ALTERNATIVE
	VBE_INPUT_TYPE_SIDEBYSIDE_FULL,		//VIDEO_3D_FORMAT_SIDEBYSIDE_FULL,
	VBE_INPUT_TYPE_DUALSTREAM, 	/**< Full format*/

	/*	Drive에서 아래 value 사용 안함. */
	VBE_INPUT_TYPE_2DTO3D,			//VIDEO_3D_FORMAT_2DTO3D,

	VBE_INPUT_TYPE_MAX,
}HAL_TRIDTV_INPUT_TYPE_T;


/**
 * Define 3D Input Freq. (MAIN SOC OUTPUT FREQ TYPE= FORMATTER INPUT FREQ TYPE)
 */

typedef enum
{
	//scaler output frame rate.
	VBE_INPUT_FREQ_24HZ = 0,
	VBE_INPUT_FREQ_30HZ,
	VBE_INPUT_FREQ_48HZ,
	VBE_INPUT_FREQ_50HZ,
	VBE_INPUT_FREQ_60HZ,

	VBE_INPUT_FREQ_MAX,

} HAL_TRIDTV_INPUT_FREQ_T;


/**
 * Define 3D Output LR Type.
 */
typedef enum
{
	VBE_OUTPUT_RL_SEQ = 0,
	VBE_OUTPUT_LR_SEQ,
	VBE_OUTPUT_LR_MAX,
} HAL_TRIDTV_OUTPUT_LR_SEQ_T;


/**
 * Define 3D Output Type.
 */
typedef enum
{
	VBE_OUTPUT_TYPE_DUAL = 0,
	VBE_OUTPUT_TYPE_INTERIM,
	VBE_OUTPUT_TYPE_FRAMESEQ,
	VBE_OUTPUT_TYPE_FRAMESEQ_LRLR, //60Hz/120Hz/240Hz output
	VBE_OUTPUT_TYPE_FRAMESEQ_LLRR, //120Hz/240Hz output
	VBE_OUTPUT_TYPE_FRAMESEQ_LBRB, //240Hz
	VBE_OUTPUT_TYPE_FRAMESEQ_LURU, //240Hz
	VBE_OUTPUT_TYPE_LINEINTERLEAVED,
	VBE_OUTPUT_TYPE_MAX,
} HAL_TRIDTV_OUTPUT_TYPE_T;


/**
 * Define 3D Output Freq.
 */
typedef enum
{
	VBE_OUTPUT_FREQ_60HZ = 0,
	VBE_OUTPUT_FREQ_100HZ,
	VBE_OUTPUT_FREQ_120HZ,
	VBE_OUTPUT_FREQ_240HZ,
	VBE_OUTPUT_FREQ_50HZ,
	VBE_OUTPUT_FREQ_BYPASS,
	VBE_OUTPUT_FREQ_MAX,
} HAL_TRIDTV_OUTPUT_FREQ_T;


/**
 * Define 3D Cfg items.
 */
typedef enum
{
	VBE_TRIDTV_3DMODE_STATUS = 0,
	VBE_TRIDTV_3D_INPUT_TYPE,
	VBE_TRIDTV_3D_INPUT_LR_SEQ,
//	TRIDTV_3D_INPUT_FREQ,
#if 0
	TRIDTV_3D_OUTPUT_TYPE,
	TRIDTV_3D_OUTPUT_LR_SEQ,
	TRIDTV_3D_OUTPUT_FREQ,
#endif
	VBE_TRIDTV_CFG_ITEMS_MAX,
} HAL_TRIDTV_CFG_ITEMS_T;


 /**
 * Video Main SOC output type
 *
 */
typedef enum
{
	VBE_TRIDTV_3DMODE_OFF= 0,
	VBE_TRIDTV_3DMODE_ON 	,
	VBE_TRIDTV_3DMODE_2DTO3D,
	VBE_TRIDTV_3DMODE_3DTO2D,
	VBE_TRIDTV_3DMODE_MAX,
} HAL_TRIDTV_3DMODE_FLAG_T;


typedef enum
{
    VBE_SC_OUT_SINGLE_2D  = 0 ,///< single nomal
    VBE_SC_OUT_SINGLE_TB      ,///< top and bottom
    VBE_SC_OUT_SINGLE_SS      ,///< side by side
    VBE_SC_OUT_SINGLE_FS      ,///< Frame Sequential(Interleaving)

    VBE_SC_OUT_DUAL_FHD       ,///< dual screen
    VBE_SC_OUT_DUAL_TB        ,///< dual top and bottom for H13 internal type
    VBE_SC_OUT_DUAL_SS        ,///< dual side by side for H13 internal type
    VBE_SC_OUT_SINGLE_T       ,//<H13 DRIVE 요청 SINGLE TOP ONLY>
    VBE_SC_OUT_MAX            ,//MAX
}HAL_TRIDTV_SC_OUTPUT_TYPE_T;


typedef enum
{
	VBE_HAL_WIN_MODE_MIN = 0,
	VBE_HAL_WIN_MODE_FULLSIZE = VBE_HAL_WIN_MODE_MIN,
	VBE_HAL_WIN_MODE_RESIZE,
	VBE_HAL_WIN_MODE_4BY3,
	VBE_HAL_WIN_MODE_MAXN,
} VBE_WIN_MODE_T;


typedef enum
{
	VBE_OUT_SINGLE_2D  = 0 ,///< single nomal
	VBE_OUT_SINGLE_TB      ,///< top and bottom
	VBE_OUT_SINGLE_SS      ,///< side by side
	VBE_OUT_SINGLE_FS      ,///< Frame Sequential(Interleaving)

	VBE_OUT_DUAL_FHD       ,///< dual screen
	VBE_OUT_DUAL_TB        ,///< dual top and bottom for H13 internal type
	VBE_OUT_DUAL_SS        ,///< dual side by side for H13 internal type
	VBE_OUT_SINGLE_T       ,//<H13 DRIVE 요청 SINGLE TOP ONLY>
	VBE_OUT_SINGLE_LA      ,//line alternative
	VBE_OUT_SINGLE_2D3D      ,//line al2D->3D
	VBE_OUT_SINGLE_3D2D      ,//line al3D->2D
	VBE_OUT_MAX            ,//MAX
}VBE_3D_OUTPUT;


typedef struct {
	HAL_TRIDTV_3DMODE_FLAG_T	 mode;		///< select formatter operation mode. it controls 3D mode ON/OFF.
	HAL_TRIDTV_INPUT_TYPE_T  in_fmt;    ///< output image format(top/bottom, sidebyside, checkboard, frame, field seq)
VBE_3D_OUTPUT  out_fmt;    ///< output image format(top/bottom, sidebyside, checkboard, frame, field seq)
	HAL_TRIDTV_INPUT_LR_SEQ_T    lr;		///< output left/right first order
	UINT8                    depthCtrl; //0~20
    char                    convCtrl;  //-10~10
	BOOLEAN					 bAutoConvMode;	/* TRUE: 3D auto convergence, FALSE: 3D manual convergence */
}HAL_TRIDTV_FMT_CTRL_T;

typedef struct {
	HAL_TRIDTV_3DMODE_FLAG_T	 mode;		///< select formatter operation mode. it controls 3D mode ON/OFF.
	HAL_TRIDTV_INPUT_TYPE_T  in_fmt;    ///< input image format(top/bottom, sidebyside, checkboard, frame, field seq)
	VBE_3D_OUTPUT  out_fmt;    ///< output image format(top/bottom, sidebyside, checkboard, frame, field seq)
	HAL_TRIDTV_INPUT_LR_SEQ_T    lr;		///< output left/right first order
	UINT8                    depthCtrl; //0~20
    char                    convCtrl;  //-10~10
	BOOLEAN					 bAutoConvMode;	/* TRUE: 3D auto convergence, FALSE: 3D manual convergence */
}HAL_TRIDTV_FMT_CTRL_TEMP_T;


typedef struct HAL_TRIDTV_INPUT_CONFIG_INFO
{
	HAL_TRIDTV_3DMODE_FLAG_T	n3DInputMode;	// 0: 3D ON, 1:3D OFF, 2:2DTO3D, 3:3DTO2D
	HAL_TRIDTV_INPUT_TYPE_T 	n3DInputType;	// 1:TNB 2:SBS, 3:
	HAL_TRIDTV_INPUT_LR_SEQ_T	n3DInputLRSeq;	// 0:LR, 1:RL
//	TRIDTV_INPUT_FREQ_T 	n3DInputFreq;	// NOT USED.

	UINT8					n3DInputDepthCtrl;		// 0~10
	char					n3DInputConvertCtrl;	//-10~10
//	UINT16					nVerticalSize;			//
	BOOLEAN					bPositiveDepth;	/* TRUE: Positive depth, FALSE: Negative depth */
	BOOLEAN					bAutoConvMode;	/* TRUE: 3D auto convergence, FALSE: 3D manual convergence */
} HAL_TRIDTV_INPUT_CONFIG_INFO_T;


typedef struct
{
	UINT16		w;	/**< horizontal Size(Width)    in pixel [0,].*/
	UINT16		h;	/**< vertical	Size(Height)   in pixel [0,].*/
	UINT16		x;	/**< horizontal Start Position in pixel [0,].*/
	UINT16		y;	/**< vertical	Start Position in pixel [0,].*/
} VBE_WIN_T;

typedef enum
{
	V3D_FMT_2D = 0,
	V3D_FMT_TOPNBOTTOM,
	V3D_FMT_SIDEBYSIDE,
	V3D_FMT_CHECKERBOARD,
	V3D_FMT_FRAMESEQ,
	V3D_FMT_COLUMN_INTERLEAVE,
	V3D_FMT_LINE_INTERLEAVE_HALF,
	V3D_FMT_FRAMEPAC,
	V3D_FMT_FIELD_ALTERNATIVE,
	V3D_FMT_LINE_ALTERNATIVE,
	V3D_FMT_SIDEBYSIDE_FULL,
	V3D_FMT_DUALSTREAM,
	V3D_FMT_MAX
} V3D_FMT_TYPE_T;

typedef enum{
	V3D_LR_SEQ = 0,
	V3D_RL_SEQ ,
	V3D_LR_MAX
} V3D_LR_SEQ_T ;

//#define BIT0 0x01
typedef enum {
	V3D_FORMAT_TOP_BOTTOM = 0x01 << 1,
	V3D_FORMAT_SIDEBYSIDE_HALF = 0x01 << 2,
	V3D_FORMAT_CHECKER_BOARD = 0x01 << 3,
	V3D_FORMAT_FRAME_SEQ = 0x01 << 4,
	V3D_FORMAT_COLUMN_INTERLEAVE = 0x01 << 5,
	V3D_FORMAT_LINE_INTERLEAVE_HALF = 0x01 << 6,
	V3D_FORMAT_FRAME_PACKING = 0x01 << 7,
	V3D_FORMAT_FIELD_ALTERNATIVE = 0x01 << 8,
	V3D_FORMAT_LINE_ALTERNATIVE = 0x01 << 9,
	V3D_FORMAT_SIDEBYSIDE_FULL = 0x01 << 10,
	V3D_FORMAT_DUAL_STREAM = 0x01 << 11,
} V3D_FORMAT_TYPE_T;

typedef struct
{
	VIDEO_WID_T 	wid;
	V3D_FMT_TYPE_T 	in_fmt;
	V3D_FMT_TYPE_T	out_fmt;
}V3D_Set3DFMT_T;


typedef struct
{
	unsigned int wid;//main sub
	unsigned int COLORRGB;// color rgb format
}FORCEBG_COLOR_CTRL_TYPE;
/*-----------------------------------------------------------------------------
	Local Type Definitions
	VBE_TRIDTV (Local Type Definitions)
------------------------------------------------------------------------------*/
typedef struct
{
	VIDEO_WID_T wId;
	HAL_TRIDTV_FMT_CTRL_T *TriFRC;
}VBE_TRIDFMT_FMT_MODE_T;

typedef struct
{
	VIDEO_WID_T wId;
	HAL_TRIDTV_FMT_CTRL_TEMP_T *TriFRC;
}VBE_TRIDFMT_FMT_MODE_TEMP_T;

typedef struct
{
	HAL_TRIDTV_3DMODE_FLAG_T n3Dmode;
	UINT8 u8DepthLevel;
}VBE_TRIDFMT_CTRL_DEPTH_T;

typedef struct
{
	HAL_TRIDTV_CFG_ITEMS_T n3DCfgItems;
	UINT8 *nCurCfgInfo;
}VBE_TRIDFMT_3D_CFG_INFO_T;

typedef enum
{
	VBE_TRIDFMT_NOTHING =0,		//Source don't do anything yet
	VBE_TRIDFMT_INIT_DONE,			//Source after initial
	VBE_TRIDFMT_OPEN_DONE,		//Source after open
	VBE_TRIDFMT_CONNECT_DONE,		//Source after connect

	VBE_TRIDFMT_UNINIT,				//Source uninitial
	VBE_TRIDFMT_CLOSE, 				// Source close
	VBE_TRIDFMT_DISCONNECT, 		//Source disconnect
} VBE_TRIDFMT_STATUS;

typedef enum{
	KADP_DISP_PANEL_POWER_ONOFF = 0,
	KADP_DISP_PANEL_LVDS_SSC,
	KADP_DISP_PANEL_STR_BACKLIGHT_CTRL_BY_AP,
	KADP_DISP_PANEL_CTRL_MAX,
} KADP_DISP_PANEL_CTRL_T;

typedef struct
{
	unsigned char panel_type;
	unsigned char power_enable;
	KADP_DISP_PANEL_CTRL_T ctrl_set;
}KADP_PANEL_MODE_SET_T;
/*-----------------------------------------------------------------------------
	Suspend & Resume
------------------------------------------------------------------------------*/
#ifdef CONFIG_PM
typedef struct
{
	UINT8 ENALE_SUSPEND_RESUME;
}VBE_DISP_TCON_SUSPEND_RESUME_T;

typedef struct
{
	UINT8 ENALE_SUSPEND_RESUME;
	UINT8 VBI_DATA_ENALE_SUSPEND_RESUME;
	UINT8 VBI_DATA_TYPE_SUSPEND_RESUME;

	//TVEDMA
	UINT32 TVE_DMA_TVE_VDDMA_S_R;
	UINT32 TVE_DMA_TVEVDDMA_SATRT0_S_R;
	UINT32 TVE_DMA_TVEVDDMA_SATRT1_S_R;
	UINT32 TVE_DMA_TVEVDDMA_SATRT2_S_R;
	UINT32 TVE_DMA_TVEVDDMA_LINESTEP_S_R;

	//VDAC
	UINT32 IFD_ANALOG_VDAC_VDBSO_S_R;
	UINT32 IFD_ANALOG_VDAC_S_R;
	UINT32 IFD_ANALOG_VADC_IDACO_CTRL1_S_R;
	UINT32 IFD_ANALOG_VDAC_IDACO_CTRL2_S_R;
	UINT32 IFD_ANALOG_VDAC_SRC_SEL_S_R;

	//DMA VGIP
	UINT32 DMA_VGIP_DMA_VGIP_CTRL_S_R;
	UINT32 DMA_VGIP_DMA_VGIP_ACT_HSTA_WIDTH_S_R;
	UINT32 DMA_VGIP_DMA_VGIP_ACT_VSTA_LENGTH_S_R;
	UINT32 DMA_VGIP_DMA_VGIP_DELAY_S_R;
	UINT32 DMA_VGIP_DMA_VGIP_CTS_FIFO_CTL_S_R;

	//I3DDMA color space
	UINT32 I3DDMA_RGB2YUV_DITHER_4XXTO4XX_HDMI_RGB2YUV_CTRL_S_R;
	UINT32 I3DDMA_RGB2YUV_DITHER_4XXTO4XX_HDMI_RGB2YUV_TAB1_M1_S_R;
	UINT32 I3DDMA_RGB2YUV_DITHER_4XXTO4XX_HDMI_RGB2YUV_TAB1_M2_S_R;
	UINT32 I3DDMA_RGB2YUV_DITHER_4XXTO4XX_HDMI_RGB2YUV_TAB1_M3_S_R;
	UINT32 I3DDMA_RGB2YUV_DITHER_4XXTO4XX_HDMI_RGB2YUV_TAB1_Y_S_R;

	//I3DDMA UZD
	UINT32 I3DDMA_SCALEDOWN_HSD_CTRL0_S_R;
	UINT32 I3DDMA_SCALEDOWN_VSD_CTRL0_S_R;
	UINT32 I3DDMA_SCALEDOWN_UZD_FIR_COEF_TAB1_C0_S_R;
	UINT32 I3DDMA_SCALEDOWN_UZD_FIR_COEF_TAB2_C0_S_R;
	UINT32 I3DDMA_SCALEDOWN_HSD_SCALE_HOR_FACTOR_S_R;
	UINT32 I3DDMA_SCALEDOWN_VSD_SCALE_VER_FACTOR_S_R;
	UINT32 I3DDMA_SCALEDOWN_HSD_HOR_SEGMENT_S_R;
	UINT32 I3DDMA_SCALEDOWN_HSD_HOR_DELTA1_S_R;
	UINT32 I3DDMA_SCALEDOWN_VSD_INITIAL_VALUE_S_R;
	UINT32 I3DDMA_SCALEDOWN_HSD_INITIAL_VALUE_S_R;

	//I3DDMA Cap
	UINT32 I3DDMA_CAP_BOUNDARYADDR2_S_R;
	UINT32 I3DDMA_CAP_BOUNDARYADDR1_S_R;
	UINT32 I3DDMA_LR_SEPARATE_CTRL1_S_R;
       UINT32 I3DDMA_LR_SEPARATE_CTRL2_S_R;
	UINT32 I3DDMA_CAP_CTL1_S_R;
 	UINT32 I3DDMA_CAP_CTL0_S_R;
 	UINT32 I3DDMA_TG_V1_END_S_R;
 	UINT32 I3DDMA_I3DDMA_ENABLE_S_R;
	UINT32 I3DDMA_BYTE_CHANNEL_SWAP_S_R;
	UINT32 I3DDMA_CAP_L1_START_S_R;
	UINT32 I3DDMA_CAP_L2_START_S_R;
	UINT32 I3DDMA_CAP_L3_START_S_R;

	//VBI DATA - TT
	UINT32 TT_CTRL_S_R;
	UINT32 TT_VPOS_S_R;
	UINT32 TVE_DMA_TVEVBIDMA_CTRL_S_R;
	UINT32 TVE_DMA_TVEVBIDMA_START_S_R;
	UINT32 TVE_DMA_TVEVBIDMA_READ_WINDOW_S_R;

	//VBI DATA - WSS
	UINT32 WSS_CTRL_S_R;
	UINT32 WSS_POS_S_R;

	//VBI DATA - VPS
	UINT32 VPS_CTRL_S_R;
	UINT32 VPS_DATA_0_S_R;
	UINT32 VPS_DATA_1_S_R;
	UINT32 VPS_DATA_2_S_R;
	UINT32 VPS_DATA_3_S_R;

	//VBI DATA - CC
	UINT32 IP_CCD_ENBL_S_R;
	UINT32 IP_CCD_ODD_0_S_R;
	UINT32 IP_CCD_ODD_1_S_R;
	UINT32 IP_CCD_EVEN_0_S_R;
	UINT32 IP_CCD_EVEN_1_S_R;
}VBE_AVE_SUSPEND_RESUME_T;
typedef struct {
	UINT8 ENALE_SUSPEND_RESUME;
	UINT8 VBI_DATA_ENALE_SUSPEND_RESUME;
	UINT8 VBI_DATA_TYPE_SUSPEND_RESUME;

	/*VBE DISP*/
	UINT32 PPOVERLAY_DISPLAY_TIMING_CTRL1_S_R;
	UINT32 PPOVERLAY_DISPLAY_TIMING_CTRL2_S_R;
	UINT32 PPOVERLAY_DV_LENGTH_S_R;
	UINT32 PPOVERLAY_DV_TOTAL_S_R;
	UINT32 PPOVERLAY_DTG_PENDING_STATUS_S_R;
	UINT32 PPOVERLAY_DISPLAY_BACKGROUND_COLOR_S_R;
	UINT32 PPOVERLAY_DH_WIDTH_S_R;
	UINT32 PPOVERLAY_DH_TOTAL_LAST_LINE_LENGTH_S_R;
	UINT32 PPOVERLAY_DTG_IE_S_R;
	UINT32 PPOVERLAY_DH_DEN_START_END_S_R;
	UINT32 PPOVERLAY_DV_DEN_START_END_S_R;
	UINT32 SYS_DISPCLKSEL_S_R;
	UINT32 PPOVERLAY_FS_IV_DV_FINE_TUNING2_S_R;
	UINT32 PPOVERLAY_FS_IV_DV_FINE_TUNING5_S_R;
	UINT32 PPOVERLAY_FS_IV_DV_FINE_TUNING1_S_R;
	UINT32 PPOVERLAY_DOUBLE_BUFFER_CTRL_S_R;

	UINT32 PPOVERLAY_uzudtg_DV_TOTAL_S_R;
	UINT32 PPOVERLAY_uzudtg_DH_TOTAL_S_R;
	UINT32 PPOVERLAY_DH_DEN_Start_End_S_R;
	UINT32 PPOVERLAY_DV_DEN_Start_End_S_R;
	UINT32 PPOVERLAY_UZUDTG_COUNTROL_S_R;
	UINT32 PPOVERLAY_memcdtg_DV_TOTAL_S_R;
	UINT32 PPOVERLAY_memcdtg_DH_TOTAL_S_R;
	UINT32 PPOVERLAY_memcdtg_DH_DEN_Start_End_S_R;
	UINT32 PPOVERLAY_memcdtg_DV_DEN_Start_End_S_R;
	UINT32 PPOVERLAY_MEMCDTG_CONTROL_S_R;
	UINT32 PPOVERLAY_MEMC_MUX_CTRL_S_R;
	UINT32 PPOVERLAY_UZUDTG_FRACTIONAL_FSYNC_S_R;
    /*Clk*/
	UINT32 CRT_PLL_SSC0_S_R;
    	UINT32 CRT_PLL_SSC3_S_R;
	UINT32 CRT_PLL_SSC4_S_R;
	UINT32 CRT_SYS_DCLKSS_S_R;
	UINT32 CRT_SYS_PLL_DISP1_S_R;
	UINT32 CRT_SYS_PLL_DISP2_S_R;
	UINT32 CRT_SYS_PLL_DISP3_S_R;
	UINT32 CRT_SYS_DISPCLKSEL_S_R;

	//panel driver
	UINT32 PPOVERLAY_FS_IV_DV_Fine_Tuning1_S_R;
	UINT32 PPOVERLAY_FS_IV_DV_Fine_Tuning2_S_R;
	UINT32 PPOVERLAY_FS_IV_DV_Fine_Tuning3_S_R;
	UINT32 PPOVERLAY_FS_IV_DV_Fine_Tuning4_S_R;
	UINT32 PPOVERLAY_FS_IV_DV_Fine_Tuning5_S_R;

	UINT32 PPOVERLAY_Display_Background_Color_S_R;
	UINT32 PPOVERLAY_Display_Background_Color_2_S_R;
	UINT32 PPOVERLAY_Main_Display_Control_RSV_S_R;
	UINT32 PPOVERLAY_Main_Border_Highlight_Border_Color2_S_R;
	UINT32 PPOVERLAY_Main_Border_Highlight_Border_Color3_S_R;
	UINT32 PPOVERLAY_MAIN_DEN_H_Start_End_S_R;
	UINT32 PPOVERLAY_MAIN_DEN_V_Start_End_S_R;
	UINT32 PPOVERLAY_MAIN_Background_H_Start_End_S_R;
	UINT32 PPOVERLAY_MAIN_Background_V_Start_End_S_R;
	UINT32 PPOVERLAY_MAIN_Active_H_Start_End_S_R;
	UINT32 PPOVERLAY_MAIN_Active_V_Start_End_S_R;

	//sfg
	UINT32 SFG_SFG_ZZ_SHIFT_DBG_CTRL_S_R;
	UINT32 SFG_SFG_SWAP_CTRL0_S_R;
	UINT32 SFG_SFG_CRC_CTRL_S_R;
	UINT32 SFG_SFG_CRC_RESULT_S_R;
	UINT32 SFG_SFG_CRC_R_RESULT_S_R;
	UINT32 SFG_SFG_L_DES_CRC_S_R;
	UINT32 SFG_SFG_R_DES_CRC_S_R;
	UINT32 SFG_SFG_CRC_ERR_CNT_S_R;
	UINT32 SFG_SFG_FORCE_BG_AT_DIF_S_R;
	UINT32 SFG_ZZ_CTRL_S_R;
	UINT32 SFG_SFG_DUMMY_CTRL_0A_S_R;
	UINT32 SFG_SFG_DUMMY_CTRL_0B_S_R;
	UINT32 SFG_SFG_DUMMY_CTRL_1A_S_R;
	UINT32 SFG_SFG_DUMMY_CTRL_1B_S_R;
	UINT32 SFG_SFG_CTRL_0_S_R;
	UINT32 SFG_SFG_CTRL_1_S_R;
	UINT32 SFG_SFG_CTRL_2_S_R;
	UINT32 SFG_SFG_CTRL_3_S_R;
	UINT32 SFG_SFG_CTRL_4_S_R;
	UINT32 SFG_SFG_CTRL_6_S_R;
	UINT32 SFG_SFG_CTRL_7_S_R;
	UINT32 SFG_SFG_CTRL_8_S_R;
	UINT32 SFG_SFG_CTRL_9_S_R;
	UINT32 SFG_SFG_CTRL_5_S_R;
	UINT32 SFG_SFG_CTRL_A_S_R;
	UINT32 SFG_SFG_CTRL_B_S_R;
	UINT32 SFG_SFG_CTRL_C_S_R;
	UINT32 SFG_SFG_TG_AUTO_1_S_R;
	UINT32 SFG_SFG_TG_AUTO_2_S_R;
	UINT32 SFG_SFG_TG_AUTO_3_S_R;
	UINT32 SFG_SFG_TG_AUTO_4_S_R;
	UINT32 SFG_SFG_DUMMY_S_R;
	UINT32 SFG_SFG_BISR_SECOND_RUN_S_R;
	UINT32 SFG_SFG_BISR_DONE_S_R;
	UINT32 SFG_SFG_BISR_FAIL_GROUP_S_R;
	UINT32 SFG_SFG_BISR_FAIL_S_R;
	UINT32 SFG_SFG_DRF_MODE_S_R;
	UINT32 SFG_SFG_DRF_RESUME_S_R;
	UINT32 SFG_SFG_DRF_DONE_S_R;
	UINT32 SFG_SFG_DRF_PAUSE_S_R;
	UINT32 SFG_SFG_DRF_FAIL_GROUP_S_R;
	UINT32 SFG_SFG_DRF_FAI_S_R;
	UINT32 SFG_SFG_BIST_OTHER_S_R;
	UINT32 SFG_SFG_MID_DUMMY_0_S_R;
	UINT32 SFG_SFG_MID_DUMMY_1_S_R;
	UINT32 SFG_SFG_MID_DUMMY_2_S_R;
	UINT32 SFG_SFG_MID_DUMMY_3_S_R;
	UINT32 SFG_SFG_DATA_AFTER_DEN_S_R;
	UINT32 SFG_SFG_INSERT_SUBPIXEL_0_S_R;
	UINT32 SFG_SFG_INSERT_SUBPIXEL_1_S_R;
	UINT32 SFG_SFG_INSERT_SUBPIXEL_2_S_R;
	UINT32 SFG_SFG_INSERT_SUBPIXEL_3_S_R;
	UINT32 SFG_SFG_CTRL_10_S_R;
	UINT32 SFG_SFG_LAST_EXT_PIXEL_LAST_FLIP_S_R;
	UINT32 SFG_SFG_DEBUG_S_R;
	UINT32 SFG_SFG_DATA_CAPTURE_VH_S_R;
	UINT32 SFG_SFG_DATA_CAPTURE_SRC_S_R;
	UINT32 SFG_SFG_DATA_CAPTURE_READ_DATA_S_R;
	UINT32 SFG_SFG_LAST_SEG_0_S_R;
	UINT32 SFG_SFG_LAST_SEG_1_S_R;
	UINT32 SFG_SFG_DRD_CTRL_0_S_R;
	UINT32 SFG_SFG_DRD_CTRL_1_S_R;
	UINT32 SFG_SFG_DRD_CTRL_2_S_R;
	UINT32 SFG_SFG_DRD_CTRL_6_S_R;
	UINT32 SFG_SFG_DRD_CTRL_7_S_R;
	UINT32 SFG_SFG_DRD_CTRL_8_S_R;
	UINT32 SFG_SFG_DRD_CTRL_12_S_R;
	UINT32 SFG_SFG_DRD_CTRL_13_S_R;
	UINT32 SFG_SFG_DRD_CTRL_14_S_R;
	UINT32 SFG_SFG_DRD_CTRL_18_S_R;
	UINT32 SFG_SFG_DRD_CTRL_19_S_R;
	UINT32 SFG_SFG_DRD_CTRL_20_S_R;
	UINT32 SFG_SFG_DRD_CTRL_3_S_R;
	UINT32 SFG_SFG_DRD_CTRL_4_S_R;
	UINT32 SFG_SFG_DRD_CTRL_5_S_R;
	UINT32 SFG_SFG_DRD_CTRL_9_S_R;
	UINT32 SFG_SFG_DRD_CTRL_10_S_R;
	UINT32 SFG_SFG_DRD_CTRL_11_S_R;
	UINT32 SFG_SFG_DRD_CTRL_15_S_R;
	UINT32 SFG_SFG_DRD_CTRL_16_S_R;
	UINT32 SFG_SFG_DRD_CTRL_17_S_R;
	UINT32 SFG_SFG_DRD_CTRL_21_S_R;
	UINT32 SFG_SFG_DRD_CTRL_22_S_R;
	UINT32 SFG_SFG_DRD_CTRL_23_S_R;
	UINT32 SFG_SFG_SWAP_CTRL1_S_R;
	UINT32 SFG_SFG_SWAP_CTRL2_S_R;
	UINT32 SFG_SFG1_DUM_DATA_LINE_0_S_R;
	UINT32 SFG_SFG1_DUM_DATA_LINE_1_S_R;
	UINT32 SFG_SFG1_DUM_DATA_LINE_2_S_R;
	UINT32 SFG_SFG1_DUM_DATA_LINE_3_S_R;

	//interface common
	UINT32 PIF_LVDS_CTRL3_S_R;
	UINT32 PIF_LVDS_CTRL0_S_R;
	UINT32 PIF_LVDS_PAIR_SELECT_CTRL_0_REG_S_R;
	UINT32 PIF_LVDS_PAIR_SELECT_CTRL_1_REG_S_R;
	UINT32 PIF_LVDS_PAIR_SELECT_CTRL_2_REG_S_R;
	UINT32 PIF_MLVDS_CTRL0_S_R;
	UINT32 PIF_MLVDS_RESET_PUL_CTRL_S_R;
	UINT32 PIF_MLVDS_CTRL1_S_R;
	UINT32 PIF_MLVDS_CTRL2_S_R;
	UINT32 PIF_MLVDS_CTRL3_S_R;
	UINT32 PIF_MLVDS_CTRL4_S_R;
	UINT32 PIF_MLVDS_MULTI_RESET_PULSE_CTRL_S_R;

	//local dimming
	UINT32 LDSPI_LD_SPI_H_TOTAL_S_R;
	UINT32 LDSPI_LD_SPI_V_TOTAL_S_R;
	UINT32 LDSPI_LD_SPI_REPRODUCE_S_R;

	//pinmux lvdsphy
	UINT32 PINMUX_LVDSPHY_LVDS_0_S_R;					 
	UINT32 PINMUX_LVDSPHY_LVDS_1_S_R;					 
	UINT32 PINMUX_LVDSPHY_LVDS_2_S_R;					 
	UINT32 PINMUX_LVDSPHY_LVDS_3_S_R;					 
	UINT32 PINMUX_LVDSPHY_LVDS_4_S_R;					 
	UINT32 PINMUX_LVDSPHY_LVDS_5_S_R;					 
	UINT32 PINMUX_LVDSPHY_PIN_MUX_LVDS_S_R; 			 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_4_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_5_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_6_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_7_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_8_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_9_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_11_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_12_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_13_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_14_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_15_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_16_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_4_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_5_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_6_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_7_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_8_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_9_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_11_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_12_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_13_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_14_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_15_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_16_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_10_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_17_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_10_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_17_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_18_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_0_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_2_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_1_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_3_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_18_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_19_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_21_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_19_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_21_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_2_2_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_0_27_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_2_3_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_3_2_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_2_4_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_2_5_S_R;  
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_22_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_23_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_24_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_25_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_26_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_27_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_28_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_29_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_30_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_31_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_32_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_33_S_R; 
	UINT32 PINMUX_LVDSPHY_LVDSEPIVBY1_PHY_CTRL_1_34_S_R; 
} VBE_DISP_SUSPEND_RESUME_T;

typedef struct {
	UINT32 EPI_EPI_PACKET_CTR1_0_0_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_1_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_2_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_3_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_4_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_5_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_6_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_7_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_8_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_9_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_10_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_11_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_12_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_13_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_14_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_15_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_16_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_17_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_18_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_19_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_20_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_21_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_22_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_0_23_S_R;
	UINT32 EPI_EPI_PACKET_CTRL_S_R;
	UINT32 EPI_EPI_CLOCK_CTRL0_S_R;
	UINT32 EPI_EPI_CLOCK_CTRL1_S_R;
	UINT32 EPI_EPI_PORT_OPTION_CTRL_S_R;
	UINT32 EPI_EPI_CMPI_FRONT_S_R;
	UINT32 EPI_EPI_DUMMY_EN_0_S_R;
	UINT32 EPI_EPI_DUMMY_SEL_0_S_R;
	UINT32 EPI_EPI_DUMMY_SEL_1_S_R;
	UINT32 EPI_EPI_DUMMY_COLOR_0_S_R;
	UINT32 EPI_EPI_DUMMY_COLOR_1_S_R;
	UINT32 EPI_EPI_DUMMY_COLOR_2_S_R;
	UINT32 EPI_EPI_DUMMY_COLOR_3_S_R;
	UINT32 EPI_EPI_CRC_CTRL_0_S_R;
	UINT32 EPI_EPI_CRC_CTRL_1_S_R;
	UINT32 EPI_EPI_CRC_CTRL_2_S_R;
	UINT32 EPI_EPI_DATA_SRC_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_INV_DBUF_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_INV_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_INV_TABLE_1_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_INV_TABLE_2_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_INV_TABLE_3_S_R;
	UINT32 EPI_EPI_PACKET_CTR1_INV_TABLE_4_S_R;
	UINT32 EPI_EPI_CMPI_RLC_S_R;
	UINT32 EPI_EPI_SCR_TCON_RST_S_R;
	UINT32 EPI_EPI_SCR8_CTRL_S_R;
	UINT32 EPI_EPI_SCR8_INI_VAL_S_R;
	UINT32 EPI_EPI_SCR10_CTRL_S_R;
	UINT32 EPI_EPI_SCR10_INI_VAL_S_R;
	UINT32 EPI_EPI_SCR8CM_CTRL_S_R;
	UINT32 EPI_EPI_SCR8CM_INI_VAL_S_R;
	UINT32 EPI_EPI_SCR10CM_CTRL_S_R;
	UINT32 EPI_EPI_SCR10CM_INI_VAL_S_R;
	UINT32 EPI_EPI_CMPI_PG_CTRL_S_R;
	UINT32 EPI_EPI_CMPI_PG_CMD_ST_S_R;
	UINT32 EPI_EPI_CMPI_PG_CMD_CMD1_S_R;
	UINT32 EPI_EPI_CMPI_PG_CMD_CMD2_S_R;
	UINT32 EPI_EPI_CMPI_PG_CMD_CMD3_S_R;
	UINT32 EPI_EPI_CMPI_PG_START_S_R;
	UINT32 EPI_EPI_CMPI_PG_DATA0_S_R;
	UINT32 EPI_EPI_CMPI_PG_DATA1_S_R;
	UINT32 EPI_EPI_CMPI_PG_DATA2_S_R;
	UINT32 EPI_EPI_CMPI_PG_DATA3_S_R;
	UINT32 EPI_EPI_CMPI_PG_DATA4_S_R;
	UINT32 EPI_EPI_CMPI_PG_DATA5_S_R;
	UINT32 EPI_EPI_CMPI_PG_DATA6_S_R;
	UINT32 EPI_EPI_CMPI_PG_DATA7_S_R;
	UINT32 EPI_EPI_CMPI_PG_DATA8_S_R;
	UINT32 EPI_EPI_CMPI_PG_DATA9_S_R;
	UINT32 EPI_EPI_CMPI_PG_END_S_R;
	UINT32 EPI_EPI_LS_PORT_EN_S_R;
	UINT32 EPI_EPI_HS_PORT_EN_S_R;
	UINT32 EPI_EPI_DATA_PORT_EN_S_R;
	UINT32 EPI_EPI_DEN_FALL_LOCA_S_R;
	UINT32 EPI_EPI_SOE_CONTROL_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE0_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE0_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE0_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE0_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE1_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE1_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE1_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE1_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE2_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE2_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE2_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE2_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE3_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE3_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE3_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE3_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE4_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE4_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE4_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE4_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE5_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE5_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE5_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE5_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE6_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE6_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE6_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE6_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE7_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE7_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE7_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE7_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE8_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE8_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE8_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE8_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE9_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE9_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE9_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE9_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE10_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE10_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE10_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE10_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE11_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE11_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE11_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE11_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE12_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE12_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE12_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE12_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE13_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE13_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE13_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE13_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE14_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE14_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE14_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE14_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE15_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE15_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE15_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE15_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE16_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE16_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE16_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE16_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE17_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE17_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE17_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE17_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE18_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE18_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE18_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE18_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE19_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE19_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE19_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE19_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE20_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE20_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE20_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE20_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE21_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE21_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE21_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE21_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE22_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE22_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE22_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE22_S_R;
	UINT32 EPI_EPI_SOE_LINE0_LANE23_S_R;
	UINT32 EPI_EPI_SOE_LINE1_LANE23_S_R;
	UINT32 EPI_EPI_SOE_LINE2_LANE23_S_R;
	UINT32 EPI_EPI_SOE_LINE3_LANE23_S_R;
	UINT32 EPI_EPI_LANE_DST_MUX0_S_R;
	UINT32 EPI_EPI_LANE_DST_MUX1_S_R;
	UINT32 EPI_EPI_LANE_DST_MUX2_S_R;
	UINT32 EPI_EPI_LANE_DST_MUX3_S_R;
	UINT32 EPI_EPI_LANE_DST_MUX4_S_R;
	UINT32 EPI_EPI_LANE_DST_MUX5_S_R;
	UINT32 EPI_EPI_LANE_CST_MUX0_S_R;
	UINT32 EPI_EPI_LANE_CST_MUX1_S_R;
	UINT32 EPI_EPI_LANE_CST_MUX2_S_R;
	UINT32 EPI_EPI_LANE_CST_MUX3_S_R;
	UINT32 EPI_EPI_LANE_CST_MUX4_S_R;
	UINT32 EPI_EPI_LANE_CST_MUX5_S_R;
	UINT32 EPI_EPI_LANE_CTR1_MUX0_S_R;
	UINT32 EPI_EPI_LANE_CTR1_MUX1_S_R;
	UINT32 EPI_EPI_LANE_CTR1_MUX2_S_R;
	UINT32 EPI_EPI_LANE_CTR1_MUX3_S_R;
	UINT32 EPI_EPI_LANE_CTR1_MUX4_S_R;
	UINT32 EPI_EPI_LANE_CTR1_MUX5_S_R;
	UINT32 EPI_EPI_LANE_CTR2_MUX0_S_R;
	UINT32 EPI_EPI_LANE_CTR2_MUX1_S_R;
	UINT32 EPI_EPI_LANE_CTR2_MUX2_S_R;
	UINT32 EPI_EPI_LANE_CTR2_MUX3_S_R;
	UINT32 EPI_EPI_LANE_CTR2_MUX4_S_R;
	UINT32 EPI_EPI_LANE_CTR2_MUX5_S_R;
	UINT32 EPI_EPI_LANE_CTR3_MUX0_S_R;
	UINT32 EPI_EPI_LANE_CTR3_MUX1_S_R;
	UINT32 EPI_EPI_LANE_CTR3_MUX2_S_R;
	UINT32 EPI_EPI_LANE_CTR3_MUX3_S_R;
	UINT32 EPI_EPI_LANE_CTR3_MUX4_S_R;
	UINT32 EPI_EPI_LANE_CTR3_MUX5_S_R;
	UINT32 EPI_EPI_TCON_MUX_S_R;
	UINT32 EPI_EPI_TCON_MUX1_S_R;
	UINT32 EPI_EPI_TCON_MUX2_S_R;
	UINT32 EPI_EPI_TCON_MUX3_S_R;
	UINT32 EPI_EPI_DUMMY_REG_S_R;
	UINT32 EPI_EPI_LANE_DST_DATA_S_R;
	UINT32 EPI_EPI_LANE_CST_DATA_S_R;
	UINT32 EPI_EPI_LANE0_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE0_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE1_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE1_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE2_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE2_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE3_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE3_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE4_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE4_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE5_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE5_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE6_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE6_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE7_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE7_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE8_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE8_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE9_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE9_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE10_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE10_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE11_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE11_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE12_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE12_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE13_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE13_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE14_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE14_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE15_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE15_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE16_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE16_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE17_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE17_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE18_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE18_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE19_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE19_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE20_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE20_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE21_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE21_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE22_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE22_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE23_CTR1_EDATA_S_R;
	UINT32 EPI_EPI_LANE23_CTR1_ODATA_S_R;
	UINT32 EPI_EPI_LANE0_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE0_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE1_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE1_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE2_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE2_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE3_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE3_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE4_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE4_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE5_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE5_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE6_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE6_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE7_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE7_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE8_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE8_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE9_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE9_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE10_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE10_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE11_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE11_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE12_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE12_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE13_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE13_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE14_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE14_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE15_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE15_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE16_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE16_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE17_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE17_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE18_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE18_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE19_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE19_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE20_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE20_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE21_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE21_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE22_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE22_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE23_CTR2_EDATA_S_R;
	UINT32 EPI_EPI_LANE23_CTR2_ODATA_S_R;
	UINT32 EPI_EPI_LANE0_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE0_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE1_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE1_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE2_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE2_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE3_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE3_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE4_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE4_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE5_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE5_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE6_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE6_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE7_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE7_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE8_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE8_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE9_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE9_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE10_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE10_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE11_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE11_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE12_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE12_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE13_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE13_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE14_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE14_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE15_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE15_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE16_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE16_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE17_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE17_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE18_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE18_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE19_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE19_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE20_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE20_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE21_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE21_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE22_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE22_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_LANE23_CTR3_EDATA_S_R;
	UINT32 EPI_EPI_LANE23_CTR3_ODATA_S_R;
	UINT32 EPI_EPI_TCON_IP_EN_S_R;
	UINT32 EPI_EPI_TCON_CTRL_S_R;
	UINT32 EPI_EPI_DOUBLE_BUFFER_CTRL1_S_R;
	UINT32 EPI_EPI_DOUBLE_BUFFER_CTRL2_S_R;
	UINT32 EPI_EPI_DOUBLE_BUFFER_CTRL3_S_R;
	UINT32 EPI_EPI_DOUBLE_BUFFER_CTRL4_S_R;
	UINT32 EPI_EPI_DOUBLE_BUFFER_CTRL5_S_R;
	UINT32 EPI_EPI_DOUBLE_BUFFER_CTRL6_S_R;
	UINT32 EPI_EPI_DOUBLE_BUFFER_CTRL7_S_R;
	UINT32 EPI_EPI_DOUBLE_BUFFER_CTRL8_S_R;
	UINT32 EPI_EPI_TCON0_HSE_S_R;
	UINT32 EPI_EPI_TCON0_VSE_S_R;
	UINT32 EPI_EPI_TCON0_CTRL_S_R;
	UINT32 EPI_EPI_TCON0_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON0_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON0_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON0_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON1_HSE_S_R;
	UINT32 EPI_EPI_TCON1_VSE_S_R;
	UINT32 EPI_EPI_TCON1_CTRL_S_R;
	UINT32 EPI_EPI_TCON1_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON1_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON1_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON1_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON2_HSE_S_R;
	UINT32 EPI_EPI_TCON2_VSE_S_R;
	UINT32 EPI_EPI_TCON2_CTRL_S_R;
	UINT32 EPI_EPI_TCON2_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON2_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON2_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON2_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON3_HSE_S_R;
	UINT32 EPI_EPI_TCON3_VSE_S_R;
	UINT32 EPI_EPI_TCON3_CTRL_S_R;
	UINT32 EPI_EPI_TCON3_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON3_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON3_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON3_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON4_HSE_S_R;
	UINT32 EPI_EPI_TCON4_VSE_S_R;
	UINT32 EPI_EPI_TCON4_CTRL_S_R;
	UINT32 EPI_EPI_TCON4_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON4_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON4_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON4_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON5_HSE_S_R;
	UINT32 EPI_EPI_TCON5_VSE_S_R;
	UINT32 EPI_EPI_TCON5_CTRL_S_R;
	UINT32 EPI_EPI_TCON5_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON5_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON5_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON5_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON6_HSE_S_R;
	UINT32 EPI_EPI_TCON6_VSE_S_R;
	UINT32 EPI_EPI_TCON6_CTRL_S_R;
	UINT32 EPI_EPI_TCON6_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON6_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON6_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON6_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON7_HSE_S_R;
	UINT32 EPI_EPI_TCON7_VSE_S_R;
	UINT32 EPI_EPI_TCON7_CTRL_S_R;
	UINT32 EPI_EPI_TCON7_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON7_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON7_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON7_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON8_HSE_S_R;
	UINT32 EPI_EPI_TCON8_VSE_S_R;
	UINT32 EPI_EPI_TCON8_CTRL_S_R;
	UINT32 EPI_EPI_TCON8_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON8_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON8_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON8_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON9_HSE_S_R;
	UINT32 EPI_EPI_TCON9_VSE_S_R;
	UINT32 EPI_EPI_TCON9_CTRL_S_R;
	UINT32 EPI_EPI_TCON9_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON9_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON9_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON9_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON10_HSE_S_R;
	UINT32 EPI_EPI_TCON10_VSE_S_R;
	UINT32 EPI_EPI_TCON10_CTRL_S_R;
	UINT32 EPI_EPI_TCON10_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON10_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON10_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON10_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON11_HSE_S_R;
	UINT32 EPI_EPI_TCON11_VSE_S_R;
	UINT32 EPI_EPI_TCON11_CTRL_S_R;
	UINT32 EPI_EPI_TCON11_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON11_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON11_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON11_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON12_HSE_S_R;
	UINT32 EPI_EPI_TCON12_VSE_S_R;
	UINT32 EPI_EPI_TCON12_CTRL_S_R;
	UINT32 EPI_EPI_TCON12_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON12_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON12_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON12_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON13_HSE_S_R;
	UINT32 EPI_EPI_TCON13_VSE_S_R;
	UINT32 EPI_EPI_TCON13_CTRL_S_R;
	UINT32 EPI_EPI_TCON13_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON13_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON13_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON13_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON14_HSE_S_R;
	UINT32 EPI_EPI_TCON14_VSE_S_R;
	UINT32 EPI_EPI_TCON14_CTRL_S_R;
	UINT32 EPI_EPI_TCON14_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON14_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON14_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON14_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON15_HSE_S_R;
	UINT32 EPI_EPI_TCON15_VSE_S_R;
	UINT32 EPI_EPI_TCON15_CTRL_S_R;
	UINT32 EPI_EPI_TCON15_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON15_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON15_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON15_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON16_HSE_S_R;
	UINT32 EPI_EPI_TCON16_VSE_S_R;
	UINT32 EPI_EPI_TCON16_CTRL_S_R;
	UINT32 EPI_EPI_TCON16_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON16_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON16_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON16_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON17_HSE_S_R;
	UINT32 EPI_EPI_TCON17_VSE_S_R;
	UINT32 EPI_EPI_TCON17_CTRL_S_R;
	UINT32 EPI_EPI_TCON17_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON17_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON17_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON17_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON18_HSE_S_R;
	UINT32 EPI_EPI_TCON18_VSE_S_R;
	UINT32 EPI_EPI_TCON18_CTRL_S_R;
	UINT32 EPI_EPI_TCON18_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON18_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON18_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON18_H_OFFSET_SHIFT_S_R;
	UINT32 EPI_EPI_TCON19_HSE_S_R;
	UINT32 EPI_EPI_TCON19_VSE_S_R;
	UINT32 EPI_EPI_TCON19_CTRL_S_R;
	UINT32 EPI_EPI_TCON19_ACROSS_LINE_CONTROL3_S_R;
	UINT32 EPI_EPI_TCON19_ACROSS_FRAME_CONTROL_S_R;
	UINT32 EPI_EPI_TCON19_FRAME_HL_CONTROL_S_R;
	UINT32 EPI_EPI_TCON19_H_OFFSET_SHIFT_S_R;
}VBE_DISP_PANEL_EPI_SUSPEND_RESUME_T;

typedef struct {
	UINT32 TCON_TCON_CTRL_S_R;
	UINT32 TCON_TCON0_HSE_S_R;
	UINT32 TCON_TCON0_VSE_S_R;
	UINT32 TCON_TCON0_CTRL_S_R;
	UINT32 TCON_TCON0_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON0_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON0_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON0_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON1_HSE_S_R;
	UINT32 TCON_TCON1_VSE_S_R;
	UINT32 TCON_TCON1_CTRL_S_R;
	UINT32 TCON_TCON1_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON1_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON1_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON1_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON2_HSE_S_R;
	UINT32 TCON_TCON2_VSE_S_R;
	UINT32 TCON_TCON2_CTRL_S_R;
	UINT32 TCON_TCON2_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON2_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON2_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON2_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON3_HSE_S_R;
	UINT32 TCON_TCON3_VSE_S_R;
	UINT32 TCON_TCON3_CTRL_S_R;
	UINT32 TCON_TCON3_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON3_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON3_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON3_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON4_HSE_S_R;
	UINT32 TCON_TCON4_VSE_S_R;
	UINT32 TCON_TCON4_CTRL_S_R;
	UINT32 TCON_TCON4_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON4_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON4_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON4_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON5_HSE_S_R;
	UINT32 TCON_TCON5_VSE_S_R;
	UINT32 TCON_TCON5_CTRL_S_R;
	UINT32 TCON_TCON5_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON5_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON5_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON5_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON6_HSE_S_R;
	UINT32 TCON_TCON6_VSE_S_R;
	UINT32 TCON_TCON6_CTRL_S_R;
	UINT32 TCON_TCON6_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON6_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON6_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON6_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON7_HSE_S_R;
	UINT32 TCON_TCON7_VSE_S_R;
	UINT32 TCON_TCON7_CTRL_S_R;
	UINT32 TCON_TCON7_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON7_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON7_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON7_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON8_HSE_S_R;
	UINT32 TCON_TCON8_VSE_S_R;
	UINT32 TCON_TCON8_CTRL_S_R;
	UINT32 TCON_TCON8_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON8_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON8_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON8_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON9_HSE_S_R;
	UINT32 TCON_TCON9_VSE_S_R;
	UINT32 TCON_TCON9_CTRL_S_R;
	UINT32 TCON_TCON9_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON9_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON9_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON9_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON10_HSE_S_R;
	UINT32 TCON_TCON10_VSE_S_R;
	UINT32 TCON_TCON10_CTRL_S_R;
	UINT32 TCON_TCON10_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON10_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON10_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON10_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON11_HSE_S_R;
	UINT32 TCON_TCON11_VSE_S_R;
	UINT32 TCON_TCON11_CTRL_S_R;
	UINT32 TCON_TCON11_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON11_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON11_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON11_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON12_HSE_S_R;
	UINT32 TCON_TCON12_VSE_S_R;
	UINT32 TCON_TCON12_CTRL_S_R;
	UINT32 TCON_TCON12_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON12_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON12_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON12_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON13_HSE_S_R;
	UINT32 TCON_TCON13_VSE_S_R;
	UINT32 TCON_TCON13_CTRL_S_R;
	UINT32 TCON_TCON13_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON13_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON13_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON13_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON14_HSE_S_R;
	UINT32 TCON_TCON14_VSE_S_R;
	UINT32 TCON_TCON14_CTRL_S_R;
	UINT32 TCON_TCON14_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON14_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON14_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON14_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON0_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON0_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON1_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON1_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON2_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON2_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON3_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON3_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON4_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON4_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON5_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON5_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON6_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON6_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON7_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON7_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON8_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON8_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON9_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON9_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON10_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON10_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON11_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON11_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON12_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON12_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON13_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON13_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON14_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON14_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON_IP_EN_S_R;
	UINT32 TCON_TCON15_HSE_S_R;
	UINT32 TCON_TCON15_VSE_S_R;
	UINT32 TCON_TCON15_CTRL_S_R;
	UINT32 TCON_TCON15_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON15_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON15_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON15_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON16_HSE_S_R;
	UINT32 TCON_TCON16_VSE_S_R;
	UINT32 TCON_TCON16_CTRL_S_R;
	UINT32 TCON_TCON16_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON16_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON16_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON16_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON17_HSE_S_R;
	UINT32 TCON_TCON17_VSE_S_R;
	UINT32 TCON_TCON17_CTRL_S_R;
	UINT32 TCON_TCON17_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON17_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON17_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON17_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON18_HSE_S_R;
	UINT32 TCON_TCON18_VSE_S_R;
	UINT32 TCON_TCON18_CTRL_S_R;
	UINT32 TCON_TCON18_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON18_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON18_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON18_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON19_HSE_S_R;
	UINT32 TCON_TCON19_VSE_S_R;
	UINT32 TCON_TCON19_CTRL_S_R;
	UINT32 TCON_TCON19_ACROSS_LINE_CONTROL3_S_R;
	UINT32 TCON_TCON19_ACROSS_FRAME_CONTROL_S_R;
	UINT32 TCON_TCON19_FRAME_HL_CONTROL_S_R;
	UINT32 TCON_TCON19_H_OFFSET_SHIFT_S_R;
	UINT32 TCON_TCON15_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON15_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON16_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON16_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON17_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON17_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON18_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON18_NO_SSCG_SE_S_R;
	UINT32 TCON_TCON19_NO_SSCG_CONTROL_S_R;
	UINT32 TCON_TCON19_NO_SSCG_SE_S_R;
}VBE_DISP_PANEL_TCON_SUSPEND_RESUME_T;
#endif

unsigned char Get_PANEL_BL_type(void);
void Set_PANEL_BL_type(unsigned char type);
unsigned char Get_PANEL_LED_Bar_type(void);
void Set_PANEL_LED_Bar_type(unsigned char type);
unsigned char Get_PANEL_EPI_TYPE(void);
void Set_PANEL_EPI_TYPE(unsigned char type);
unsigned char Get_PANEL_INCH(void);
void Set_PANEL_INCH(unsigned char inch);
unsigned char Get_PANEL_MAKER(void);
void Set_PANEL_MAKER(unsigned char maker);
unsigned int Get_DISP_OSD_Width(void);
void Set_DISP_OSD_Width(unsigned int width);
unsigned int Get_DISP_OSD_Height(void);
void Set_DISP_OSD_Height(unsigned int height);
void Disp_Enable_isForceFreeRun(BOOLEAN isForceFreeRun);
BOOLEAN Disp_Get_isForceFreeRun(void);
void Disp_Set_framerate(unsigned char framerate);
unsigned char Disp_Get_framerate(void);
void modestate_set_fll_running_flag(unsigned char bEnable);
unsigned char modestate_get_fll_running_flag(void);
unsigned char vbe_disp_get_adaptivestream_fs_mode(void);
void scaler_disp_smooth_variable_setting(void);
void scaler_disp_smooth_variable_settingByDisp(unsigned char _channel);
void vbe_disp_first_resume(void);
void vbe_disp_resume(void);
void vbe_disp_tcon_on(void);
void vbe_disp_tcon_off(void);
void vbe_disp_tcon_verifyOnOff(char *bOnOff);
unsigned char vbe_disp_tcon_lock_self_check(void);
char vbe_disp_tcon_readStatus(void);
unsigned char vbe_disp_always_check_tcon(void);
void vbe_disp_vby1_init_flow(void);
void vbe_disp_orbit_position_update(unsigned char tableIdx);
void vbe_disp_set_orbit(UINT8 bEnable);
unsigned char vbe_disp_get_orbit(void);
unsigned char vbe_disp_decide_PQ_power_saveing(void);
unsigned char vbe_disp_decide_memc_mux_bypass(void);
void vbe_disp_set_dynamic_memc_bypass_flag(unsigned char bOnOff);
unsigned char vbe_disp_get_dynamic_memc_bypass_flag(void);
void vbe_disp_game_mode_memc_bypass(unsigned char b_gameMode_onOff);
void vbe_disp_pwm_frequency_update(bool bEnableDB);
void vbe_disp_debug_framerate_change_msg(void);

/*declaration for VSC use*/
int HAL_VBE_AVE_Initialize(void);
int HAL_VBE_AVE_Open(void);
int HAL_VBE_AVE_Connect(VBE_AVE_INPUT_INDEX AVEInput);
int HAL_VBE_AVE_Disconnect(void);
void Scaler_disp_setting(unsigned char display);
void HAL_VBE_DISP_SetFrameRate(BOOLEAN isForceFreeRun,UINT8 frameRates);
void HAL_VBE_DISP_TCON_Initialize(void);
void HAL_VBE_DISP_TCON_Uninitialize(void);
void HAL_VBE_DISP_TCON_EnableColorTemp(bool bOnOff);
void HAL_VBE_DISP_TCON_EnableDGA(bool bOnOff);
void HAL_VBE_DISP_TCON_EnableDither(bool bOnOff);
void HAL_VBE_DISP_TCON_SetDitherMode(DISP_TCON_DITHER_T mode);
void HAL_VBE_DISP_TCON_SetGammaTable(UINT32 *pRedGammaTable, UINT32 *pGreenGammaTable, UINT32 *pBlueGammaTable);
void HAL_VBE_DISP_TCON_EnableTCon(bool bOnOff);
void HAL_VBE_DISP_TCON_H_Reverse(UINT8 u8Mode);
void HAL_VBE_DISP_TCON_SetClock(bool bOnOff);
void HAL_VBE_DISP_TCON_WriteRegister(UINT32 u32Address, UINT32 u32Data);
void HAL_VBE_DISP_TCON_ReadRegister(UINT32 u32Address, UINT32 *pData);
void HAL_VBE_DISP_TCON_SetLvdsFormat(HAL_VBE_DISP_TCON_LVDS_TYPE_T type);
void HAL_VBE_DISP_TCON_Debug(void);
void HAL_VBE_DISP_OLED_SetOrbit(BOOLEAN bEnable);
void HAL_VBE_DISP_SetBOEMode(UINT8 *pFwData, UINT32 size);
void HAL_VBE_DISP_GetBOEVersion(DISP_BOE_VERSION_T *pstRomVer, DISP_BOE_VERSION_T *pstFwVer);
void HAL_VBE_DISP_SetMLEMode(VBE_DISP_MLE_MODE_T index);
void HAL_VBE_DISP_SetInnerPattern(UINT8 bOnOff, VBE_DISP_INNER_PTG_BLOCK_T block, VBE_DISP_INNER_PTG_TYPE_T type);
void HAL_VBE_DISP_GetPanelSize (DISP_PANEL_SIZE_T *panel_size);
void HAL_VBE_SetDGA4CH (UINT32 *pRedGammaTable, UINT32 *pGreenGammaTable, UINT32 *pBlueGammaTable, UINT32 *pWhiteGammaTable, UINT16 nTableSize);


extern int create_timer(unsigned char id, unsigned int interval, unsigned char mode);
extern int rtk_timer_control(unsigned char id, unsigned int cmd);

#endif
