KBUILD_CPPFLAGS += -I ./
obj-$(CONFIG_RTK_KDRV_THERMAL) += rtk_thermal.o
obj-$(CONFIG_RTK_KDRV_THERMAL_SENSOR) += rtk_thermal_sensor.o rtk_monitor.o
obj-$(CONFIG_RTK_KDRV_THERMAL_GOV_RTK_THERMAL_THROTTLE)   += rtk_thermal_throttle.o