#Copyright (C) 2007-2013 Realtek Semiconductor Corporation.
obj-$(CONFIG_RTK_KDRV_DISEQC)  += rtk_diseqc_core.o rtk_diseqc_data_buff.o
#obj-$(CONFIG_RTK_KDRV_DISEQC)  +=  rtk_diseqc_data_buff.o
obj-$(CONFIG_RTK_KDRV_DISEQC_CHARDEV) += rtk_diseqc_dev.o
