#
# Makefile for the Realtek adcsource drivers.
#

obj-y := core/crypto_spu.o core/secure_flash.o core/hdmi.o \
  core/bigdigits.o core/crypto.o core/hmac.o core/hdcp2_rcp_api.o core/sha2.o \
  rx/hdcp2_interface.o rx/hdcp2_messages.o rx/hdcp2_session.o rx/spu_main.o \
  tx/test_hdcptx.o tx/HDCPTX22.o tx/HDMI_HDCP_API.o
