# Makefile for the Realtek scaler VIP drivers.
#
#obj-y := scalerColor.o color.o dcc.o di_ma.o film.o icm.o intra.o nr.o custom_sharpness.o xc.o peaking.o ultrazoom.o gibi_od.o pq_misc_table.o pq_adaptive.o localdimming.o
obj-y := ultrazoom.o di_ma.o scalerColor.o dcc.o color.o film.o icm.o intra.o nr.o custom_sharpness.o xc.o peaking.o gibi_od.o pq_misc_table.o pq_adaptive.o localdimming.o vip_panel_default.o viptable.o scalerColor_tv006.o localcontrast.o memc_mux.o pq_3dlut_table.o pq_rpc.o still_logo_detect.o tc_hdr.o tc_math.o tc_OEOTF_convert.o hdr_table.o

